### ISSUE TITLE
Issue when two displays connected together

### ISSUE THREAD

**Issue by odonnellc08** [hzeller/rpi-rgb-led-matrix#10]
Hi hzeller

I followed a tutorial from Adafruit (https://learn.adafruit.com/16x32-rgb-display-with-raspberry-pi-part-2/software) to connect two LED displays together using your code. I am using a Raspberry Pi to run the displays. When I connect one display to the Pi, everything works find. I can display anything on it and there is no issue. I tested both displays like this and they both worked excellent. However, when I connect the two together and run the necessary adjustments to your code I run into a problem. When I try run something, only the 8th and 14th row on the display that is connected directly to the Pi work, the rest remain blank. I can tell the image is being sent to the display, as the LED's on those two rows change color, turn on, off. 

Have you encountered a problem like this before? Do you have any tips on how it can be fixed?

Regards, 
C

**Comment by mutax** [comment]
are you sure you connected the displays in the correct order and that the connecting cable has no shorts? I have connected 2 displays as well and everything works.
What do you mean by 'adjustments' to the code - I just use -c2 as command line parameter and everysthing works as expected.

**Comment by hzeller** [comment]
I think the Adafruit tutorial is a bit behind and describes an ancient version. It is always better to go by the current README.md.

Closing now, as the original issue probably resolved already.
