### ISSUE TITLE
Read config from USB stick and auto running script

### ISSUE THREAD

**Issue by folny** [hzeller/rpi-rgb-led-matrix#100]
Hi hzeller

I think it would be great to do something like reading configuration and GIF files from USB stick and run the script immediately when you turn on Raspberry Pi to avoid entering commands via the keyboard it would be possible to do something like that ?.

**Comment by hzeller** [comment]
Sure, I usually run that in such a configuration. Just write an Linux init script for your Pi (or put it in `/etc/rc.local`). Don't forget to give absolute paths to your images.
