### ISSUE TITLE
Random artifacts in video appear periodically 

### ISSUE THREAD

**Issue by jabulonboaz** [hzeller/rpi-rgb-led-matrix#1005]
When i play back any video or any vid.stream i get artifacts appearing in every video that appear for a millisecond then disappear and appear again randomly within a video say around every 4 seconds. Pls see pics - two showingthe issu, one normal. What causes these and how can i get read of them pls?
I am using a p3b+ with an Adafruit RGB matrix bonnet, four 64x64 P2.5 panels in series and a 5A 10A PSU. 
![20200315_041219](https://user-images.githubusercontent.com/30203930/76695912-d5f80300-667c-11ea-84ee-03dbbc468e33.jpg)
![20200315_040913](https://user-images.githubusercontent.com/30203930/76695914-ddb7a780-667c-11ea-81b1-4e2be47e75c3.jpg)
![20200315_041154](https://user-images.githubusercontent.com/30203930/76695917-eb6d2d00-667c-11ea-9886-d25f1251d358.jpg)
![20200315_053933](https://user-images.githubusercontent.com/30203930/76696113-b0b8c400-667f-11ea-949b-07737869a104.jpg)

**Comment by hzeller** [comment]
if it is regularly, it sounds like the symptom of one-wire connection not disabled
https://github.com/hzeller/rpi-rgb-led-matrix#troubleshooting

If that is not the reason, try slowing down gpio with the `--led-slowdown-gpio=2` (or even higher) option.

Finally, sometimes glitches can happen if the power cabeling is too noisy. Make sure to have power wires individually connected to the power supply, have them thick, potentially add a capacitor etc.

But from the described symptom it sounds like one-wire connection to me.

**Comment by hzeller** [comment]
Also, have you a monitor connected to the Pi ? Running a graphical UI also is known to mess with the timing of the outputs. I recommend to always run the Raspberry Pi headless.

For a slim raspberry Pi operating system I recommend DietPi ( https://dietpi.com/ )

**Comment by jabulonboaz** [comment]
> Also, have you a monitor connected to the Pi ? Running a graphical UI also is known to mess with the timing of the outputs. I recommend to always run the Raspberry Pi headless.
> 
> For a slim raspberry Pi operating system I recommend DietPi ( https://dietpi.com/ )

Hello thanks for the fast response and this amazing work you have done. 
I am afraid non of the above, 1 wire is disabled (i just checked again both in config.txt and raspi-config GUI) and also no monitor conected, i have installed the lite distribution you recommended on the instructions. 
All my wiring is fine is like you recommend but i have not used a capacitor, how many farad and do i put it in parallel with VCC and GNG right? 
Pls also see the additional picture that shows my CLI maybe i missed something there ? 
Any suggestion is welcomed.

**Comment by jabulonboaz** [comment]
Fixed thank u! It was the gpio slowdown! I put it to =2 and the issue is gone. Thanks HZeller.

**Comment by hzeller** [comment]
Raspbian Lite is good, but from the feedbck I get from users dietpi seems to be better w.r.t. not randomly generating flicker reasons.

Next thing on the commandline I'd try is `--led-slowdown-gpio=2` (or 3) and see if that makes a difference. The fact that 'further away' from the connection looks garbled indicates that the matrix might be too slow for the Pi sending data.

(As for power supply: I'd probably put in the order of 3300μF on each panel if that turns out to be an issue)

**Comment by jabulonboaz** [comment]
> Raspbian Lite is good, but from the feedbck I get from users dietpi seems to be better w.r.t. not randomly generating flicker reasons.
> 
> Next thing on the commandline I'd try is `--led-slowdown-gpio=2` (or 3) and see if that makes a difference. The fact that 'further away' from the connection looks garbled indicates that the matrix might be too slow for the Pi sending data.
> 
> (As for power supply: I'd probably put in the order of 3300μF on each panel if that turns out to be an issue)

Thanks for everything it was the gpio slowdown i put exactly what u said and its working perfectly now.
