### ISSUE TITLE
Make transformers available from Python

### ISSUE THREAD

**Issue by hzeller** [hzeller/rpi-rgb-led-matrix#101]
Transformers should be accessible by name from Python.

**Comment by bentwire** [comment]
I'm new to Cpython, so I'm not sure, is this a pretty straight forward process?  From what I see in the core and graphics python bindings it looks simple enough...

**Comment by daker** [comment]
👍  for this

**Comment by yarikoptic** [comment]
+100 on this one ;)
I would really appreciate if someone has implemented this since I would like to script display from Python but need to establish a chain of transformers (e.g. https://github.com/hzeller/rpi-rgb-led-matrix/pull/113 ;-) ) for my 2x2 display.

**Comment by Saij** [comment]
If I'll get my testing box up and running again I'll implement it ^.^
(But first get my box back again from my girlfriend -.-)

**Comment by daker** [comment]
@Saij We will be grateful for that :+1:

**Comment by delectatronics** [comment]
Hi Saij
Do you have an estimate when you believe the transformers will be available from Python?  I am trying to have a baseball scoreboard operational using Python 2.7 in about 3 weeks.
I appreciate your time and I am not pushing at all - just trying to work out if I need to go in a different direction.
Cheers

**Comment by Saij** [comment]
Sorry just got back from a convention ^.^
Will give my best to get it running soon ^.^ But can't promise anything yet

**Comment by delectatronics** [comment]
No probs at all – I appreciate all of your voluntary efforts

**Comment by serverfire** [comment]
@Saij this should open , many need transformer for python , thank you

**Comment by hzeller** [comment]
I am working towards it
