### ISSUE TITLE
Rss Scrolling, im having trouble

### ISSUE THREAD

**Issue by breakingbk** [hzeller/rpi-rgb-led-matrix#1016]
Hello Mr Zeller, 

Huge thanks for this amazing work, please may you assist me in a problem im having.

I've downloaded a python script which scrolls news from rss feeds. 

The code is here that i am using, i see you have helped on this one a few times in the past :)
https://gist.github.com/chubbyemu/4ca0c68878c6d978d067da4a36bcc71d

Only been using linux a couple of weeks so im fairly new, i did a pip install of feedparser for python.

I am able to confirm that feedparser can be imported in python, and shows it comes from '/home/pi/.local/lib/python2.7/site-packages/feedparser.pyc'> within python, im guessing that the pip install has placed it in the wrong directory or i have made some other silly error somewhere. 

I am getting an error which says File "rssparse.py", line 7, in <module>
 import feedparser
ImportError: No module named feedparser

If you could help, it would be so appreciated and thanks again.

Chris

**Comment by hzeller** [comment]
I myself am more a C++ person, but there is probably someone out here that can chime in and help setting up the Python environment that it works for you.

You mentioned that you confirmed that feedparser can be imported into Python. But then you wrote a script that couldn't import it. What was different ?

**Comment by breakingbk** [comment]
Hello, 

Thank you for the response, i used chmod 755 and it looks as though the script will run, it also populates the directory with ppm's which are relevant to the rss feeds i wanted 

![image1](https://user-images.githubusercontent.com/37982510/77253727-0d097e00-6c54-11ea-9ed0-d94c09b9361f.jpeg)
![image0](https://user-images.githubusercontent.com/37982510/77253730-14308c00-6c54-11ea-9a56-7977b28209ad.jpeg)

**Comment by hzeller** [comment]
do you have the right path to the demo binary ? See the error output.

**Comment by breakingbk** [comment]
Do you have an idea of what would be creating this error reporting?

**Comment by breakingbk** [comment]
I shall try that now

**Comment by breakingbk** [comment]
is it the line 95 i should be changing?

os.system("sudo ./led-matrix -r 16 -c 3 -t 60 -m 25 -D 1" +disp) 

I have tried changing it to a the path of exaples-api-use and it didnt work 

Sorry for the noobness :)

**Comment by hzeller** [comment]
The program is called `examples-api-use/demo`.

Also, you want a fully qualified absolute path (e.g. `/home/pi/rpi-rgb-led-matrix/examples-api-use/demo` ... really depending on where you checked it out)

**Comment by breakingbk** [comment]
Cheers for helping me, 

im still having errors 

![image0](https://user-images.githubusercontent.com/37982510/77254717-c9fed900-6c5a-11ea-9e69-a05646e5cf52.jpeg)

![image1(1)](https://user-images.githubusercontent.com/37982510/77254722-ce2af680-6c5a-11ea-87be-6c4e9d38786c.jpeg)

**Comment by breakingbk** [comment]
apologies for the orientation of the photos lol :/

**Comment by breakingbk** [comment]
Nothing is ever simple in IT is it :)

**Comment by hzeller** [comment]
You have a dot-slash in front of your path, not a slash.
The `.` is the current directory, so you are trying to find something relative to your current directory ... and there is no home/pi/... in your directory, so of course os.system() will not find it.

If it starts with slash, this is the absolute path.

**Comment by breakingbk** [comment]
Thanks, i am getting there now i think i just need to change the options now.... :)

**Comment by breakingbk** [comment]
We've done it!!!! 

![image0(1)](https://user-images.githubusercontent.com/37982510/77255382-e3a21f80-6c5e-11ea-9224-7470150a41f3.jpeg)

You are so so kind, honestly i am so happy with this project, it is absolutely amazing, if i can contribute in any way please let me know, via a donation or anything. 

Thanks so much!

**Comment by breakingbk** [comment]
just need to play around with fonts and sizing and speeds etc...

**Comment by hzeller** [comment]
If you just want to output text, you might consider using the [text-scrolling utility](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/utils#text-scroller) directly instead of the detour of creating a PPM first, then run the demo.
There you have options such as background color or an outline around your font.

And the very best thing of course it to *not* invoke the external program with `os.system()` in the first place, but do everything in Python using the provided [rpi-rgb-led-matrix Python binding](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/bindings/python). There are some examples that get you started with outputting text, like the [samples/runtext.py](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/bindings/python/samples/runtext.py).

**Comment by breakingbk** [comment]
Thanks, i shall definately have a look at doing that. Lots to learn! :) This project has really inspired me, cheers!
