### ISSUE TITLE
Converting from uint_32 to uint_64 for Compute Module Chain 5 and 6

### ISSUE THREAD

**Issue by punyanagari** [hzeller/rpi-rgb-led-matrix#1035]
I am trying to make changes from errors in compiling but not able to solve the problem.

https://github.com/punyanagari/rpi-rgb-led-matrix

--led-gpio-mapping="compute-module"

**Comment by punyanagari** [comment]
I am getting closer to solve this.
I don't have any error now but the output is not as expected
I connected 1st RGB on GPIO 7,8,9 and 2nd RGB on 32,33,34

Here is the command:

` sudo ./demo -D3 --led-multiplexing=4 --led-rows=16 --led-gpio-mapping=compute-module`

Image: First half is correct next half is wrong showing blue colour only
![WhatsApp Image 2020-04-12 at 20 51 58](https://user-images.githubusercontent.com/59508143/79072598-8e0ddf80-7cff-11ea-8b21-883295fb9cbf.jpeg)

What else do I need to change to uint64_t

Please advice @hzeller

**Comment by salazarhog** [comment]
Closing this issue now
Successful in getting 6 parallel chains from Compute Module 3 +
Also automated the Initialization of GPIO's > 31 so that it won't affect the refresh rate when they are not used

Let me know if I should send a pull request

**Comment by punyanagari** [comment]
Closing this issue now
Successful in getting 6 parallel chains from Compute Module 3 +
Also automated the Initialization of GPIO's > 31 so that it won't affect the refresh rate when they are not used

Let me know if I should send a pull request

**Comment by hzeller** [comment]
Yes, please send a pull request!

**Comment by punyanagari** [comment]
Done
