### ISSUE TITLE
no output with "led-image-viewer"; other commands do output an image.

### ISSUE THREAD

**Issue by cpf3xf** [hzeller/rpi-rgb-led-matrix#1039]
hi there,
first of all, thanks for this great code!
i am new to this and really enjoy playing with my LED matrix.
i've done some testing with your code and the examples and all the demos work fine.
so now i wanted to start playing with PNG pictures using the led-image-viewer tool.
i am running ot form the CLI, no GUI on my raspi 3 b+ with adafruit HAT and a 64x32 led panel.
using this command:

sudo ./led-image-viewer /media/usb/test.png --led-no-hardware-pulse --led-rows=32 --led-cols=64 --led-multiplexing=0 

Getting the feedback:
Size: 64x32. Hardware gpio mapping: regular
Loading 1 files...
Loading took 0.103s; now: Display.

But not output on the LED matrix. Using the same parameters, demo output works absolutely fine.

Any chance you know this issue?
Thanks a lot for helping me out! :)

**Comment by hzeller** [comment]
Look at the output message, it says `Hardware gpio mapping: regular`.
So you need to switch it to the hat: `--led-gpio-mapping=adafruit-hat`
