### ISSUE TITLE
https://github.com/gege13007/Led-panel-display/blob/master/README.md

### ISSUE THREAD

**Issue by gege13007** [hzeller/rpi-rgb-led-matrix#1053]
Hi Haener Z. and thanks for this work.
I'm working on a new project of RGB-Panel-Display wich allows to write direct rich text, effects, and images directly in a text message (like a small html balise language).
Can I import your rgbmatrix lib directory on my repository, or just link to yours ?
Thanks.
https://github.com/gege13007/Led-panel-display

**Comment by hzeller** [comment]
Sure, simplest would be if you add it as a submodule:

https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#integrating-in-your-own-application

Make sure your application has the GPL license as required to link with this library.
