### ISSUE TITLE
Getting the r,g,b from a pixel (x,y) in Frame Canvas

### ISSUE THREAD

**Issue by albucristian642** [hzeller/rpi-rgb-led-matrix#1058]
Hi there, firstly I wanna thank you and all the contributors for this awesome library.  
I am trying to obtain an implementation where I have different threads as owners of different part of the screen. It works fine, but I encountered a problem when I want to display animations ( frameCounter > 1). In led-image-viewer the frames are buffered in the stream but for the whole matrix. My solution is to replace with SetPixel() only the area in the active frame that I am interested in. But I cannot find a GetPixel(x,y) for a FrameCanvas. 

Could someone give me an idea how I could do that?
Thank you in advance!

**Comment by hzeller** [comment]
There is no get pixel as the pixel-data is converted to the preprocessed linearilized (8bit -> 11 bit) and bitplane representation needed to push out the GPIO, but it is unnecessarily hard to convert that back.

So if you need to remember pixels you said, I suggest to implement a [`Canvas`](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/include/canvas.h#L32) interface that delegates to some underlying canvas (e.g. FrameCanvas) but also remembers the pixel colors. That way, you cam provide a `GetPixel(x, y`) functionality. All graphics functions take a Canvas interface, so all your program should be compatible with that.
