### ISSUE TITLE
Clarification of PWM bits

### ISSUE THREAD

**Issue by daveythacher** [hzeller/rpi-rgb-led-matrix#1062]
When the PWM bits are set to 11 does that give 2^33 colors? This seems impossible to me give the 25MHz clock and column depth. Based on my understanding of the could it would suggest 11^3 colors. As the bits really represent a counter/mask/index.

**Comment by hzeller** [comment]
Yes, 2^33 linear colors indeed.
You need about 10-12 bits linear resolution per channel to properly approximate the logarithmic response of the eye. After the gamma curve application, this boils down to 256^3, 16.7M colors.
The PWM uses binary code modulation to get this resolution: so each channel only has to be clocked out 11 times, but with doubling output enable times.
