### ISSUE TITLE
Clarification if this use NEON instructions 

### ISSUE THREAD

**Issue by daveythacher** [hzeller/rpi-rgb-led-matrix#1063]
Does this code generate/use ARM NEON instructions for compatible processors?

**Comment by hzeller** [comment]
All C++ codes is just using basic integer stuff; if the compiler generates NEON instructions, I don't know, but that should be compilable everywhere.
Of course, it is tied to the Raspberry Pi processor as it uses that particular GPIO subsystem and timing registers etc.
