### ISSUE TITLE
Function request if possible

### ISSUE THREAD

**Issue by rijotech** [hzeller/rpi-rgb-led-matrix#1075]
Hi, Mr Zeller. 
I was wondering if possible to add images transitions option to led-image-viewer in the future 
 for example `sudo led-image-viewer -C -f -w5 -t8  *.gif -transition name`.
Also there is a way to auto play all mp4 videos in sequence from a folder?

Thanks for this amazing library, this is my latest project.

[![LED Screen prototype](https://i.ytimg.com/vi/ivzQ7Pf2-dA/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAboK5g2IzJEc32v5CT9MgPdDxySg)](https://www.youtube.com/watch?v=ivzQ7Pf2-dA "Everything Is AWESOME")

**Comment by xuniuer** [comment]
I guess you could write a shell script to do that.
for gif in `ls *.gif`
do
  sudo led-image-viewer -C -f -w5 -t8 $gif -transition name # as you presented
  sleep 1 # Need to have a delay?
done

The above will play all gif files. If you want to have a loop, an outer loop could be added.

**Comment by rijotech** [comment]
I already have a script but the problem is there is no option for a transition yet.

**Comment by xuniuer** [comment]
Please refer to link: https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality
