### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by wyliew19** [hzeller/rpi-rgb-led-matrix#1080]
Whenever I try to compile, I'm given multiple errors. I'm not familiar with C++ and can barely make out what any code is doing.
![image](https://user-images.githubusercontent.com/61804733/84333691-78c9fb80-ab5e-11ea-8b05-ca505f4f77ff.jpg)

**Comment by hzeller** [comment]
Interesting, there was a header technically needed to be included for `size_t` but apparently it worked before. Can you try again after a `git pull` if this fixes it ?

**Comment by hzeller** [comment]
(reopening until verified working)

**Comment by wyliew19** [comment]
Started working after using std::size_t
