### ISSUE TITLE
Rpi0w can't power on with active controller hat?

### ISSUE THREAD

**Issue by cluelessperson** [hzeller/rpi-rgb-led-matrix#1093]
My Computer usb read "overcurrent protection" on only powering the rpi + active board.  The panels have a separate power supply.

![IMG_20200627_152315](https://user-images.githubusercontent.com/5635253/85933591-9e107680-b88d-11ea-8fe3-c2cfcae837a4.jpg)

**Comment by hzeller** [comment]
You probably want to ask the people where you got the board from.

**Comment by hzeller** [comment]
also, this looks odd, did you plug in the board the wrong way ? Usually the the boards are done in a way that the pi is underneath.
