### ISSUE TITLE
Displaying animated gifs

### ISSUE THREAD

**Issue by mike-charles** [hzeller/rpi-rgb-led-matrix#11]
Is there any way with this code, or another that you know of, to display animated GIFs on the LED matrix?

**Comment by hobbzey** [comment]
I also have to agree that this functionality would be GREATLY appreciated!

**Comment by rogerguess** [comment]
Agree, this is the #1 thing I hope to see added. Looking at https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/demo-main.cc#L211 makes me wonder if it could be modified to loop through a directory of PPMs. Assuming the gif were broken down into individual images. Does this seem a reasonable approach? I am not a c++ dev, but think I could figure something out in c# that split a GIF into PPMs.

**Comment by mike-charles** [comment]
Sounds like it would work...

Boy I wish there was a pure Python package I could use for this...

**Comment by hzeller** [comment]
Guys, before you consider some complicated looping through PPMs, which is somewhat involved, why not add the handful of lines of code that you need to read a gif ?
I didn't add it, because I didn't want to add more dependencies to this code (which is why I wrote the PPM reading by hand as well, not using a library).

But looks like popular demand wants me to add it :/
I'll have a look once I have it working properly with the newer RPis.

@mike-charles I think adafruit wrote a Python wrapper for my code.

**Comment by rogerguess** [comment]
I have something very basic working with the python wrapper:

http://youtu.be/-p3MXTT7wiw

https://github.com/rogerguess/rpi-rgb-led-matrix/commit/ec18bc2816d553532c96a509e739435ec7925c36

sudo python matrixGIF.py <file name of gif>

It's a ways off though. I have one gif it works well with, but I believe that is because the gif was created in such a way that every pixel is updated on each frame. I think something needs to be done where an image is created an overwritten. That image would be given to SetImage() rather than each frame of the gif.

It also seems to reverse colors with some gifs. Note that I have a gif size matching the size of my matrix (32x64). A dimension specific google search would likely turn up plenty of test examples:

https://www.google.com/search?q=a&biw=1920&bih=1019&tbm=isch&source=lnt&tbs=isz:ex,iszw:64,iszh:32#q=a&tbs=isz:ex,iszw:64,iszh:32,itp:animated&tbm=isch

Should this be possible with the Python wrapper, or would more need to be added to the API?

I for one, would still love to see this natively supported by your code.

**Comment by hzeller** [comment]
I pushed a first version of an image viewer. For it to compile, you need the imagemagick dev libraries:

     sudo aptitude install libmagick++-dev
     make led-image-viewer

I does seem to work with many gifs, but some still look funny - turns out the 'frame disposal methods' in GIFs can be nasty. Anyway, first version. Would be cool if you could try it out.

**Comment by rogerguess** [comment]
Well, level shifting gets me again. It looks it would work perfectly if I were not directly wiring to it:

http://youtu.be/1OrMYGhfXXs

I get the feeling that everything I need to get a HAT working with your latest code is in this checkin:

https://github.com/adafruit/rpi-rgb-led-matrix/commit/10fd63b65e8abda7a9ae32e596e2fc14d4be234c

... still reading, now quite understanding it yet.

Thanks

**Comment by hzeller** [comment]
Can you try as well the new ouput GPIOs for output_enable (now GPIO 27, pin 13 on RPi-header) and clock (now GPIO 11, pin 23 on RPi header) ? To pins to re-wire on your setup.

I have a suspicion that a pull-up on the traditional outputs for this (pin 3 and 5 on RPi header) might influence the electrical output. So the new suggested way is to use these instead (the old ones are still working as you can see, but I essentially deprecated them).

Maybe this fixes it for your Panel.

**Comment by rogerguess** [comment]
Sure, will give it a try. Do I need a parameter to tell the code or change/recompile anything?

**Comment by hzeller** [comment]
No, works out of the box.

**Comment by rogerguess** [comment]
Oh, that is how it is wired already. I followed the readme that you updated here:

https://github.com/hzeller/rpi-rgb-led-matrix

OE from the panel is in GPIO 27 and CLK is in GPIO 11

**Comment by hzeller** [comment]
Ok then.
So next steps would be to keep your cables short to the first panel (< 5cm), go through a level shifter or use the level shifter on the Adafruit HAT (which means you might need to patch the code to work with their pinout).

**Comment by rogerguess** [comment]
patched! Works great! I even left it running all night just to see.

Thank you!

**Comment by hzeller** [comment]
FYI, I changed from ImageMagick to GraphicsMagick library (a little bit faster and at least one less bug I noticed).

I changed the README, but here is essentially what you need to do before compiling from head:
```
sudo aptitude install libgraphicsmagick++1-dev
```

**Comment by makifbuz** [comment]
Dear Henner,
Do you think add read all images in a folder sample function? If you did it
would awesome. Or you can light me up how can I do that where should I
start.

p.s. I think your code require to understand the highest level knowledge
and experience c++ programming. I am the beginner. I hardly undersand.
Thanks.

2015-03-05 22:09 GMT+02:00 Henner Zeller <notifications@github.com>:

**Comment by hzeller** [comment]
When would the images transition ? One after another with some configurable time between them ?
I could think of something like "Run for X seconds, whatever comes last, the X seconds or a full run of the animation (so if the animation fits in 5.2 times in the X seconds, it will run 6 full times)"

That way, it would work for regular, static images, as well as for animations.

**Comment by makifbuz** [comment]
i would like to run after another between specified time delay. it could be
still image or gif animation. My idea is changing the filename with
"image001.gif" to "image002.gif" after the last gif frame showed and recall
the load image function and display the second animation and so on.
7 Mar 2015 01:35 tarihinde "Henner Zeller" <notifications@github.com> yazdı:

**Comment by hzeller** [comment]
Well, renaming files is hard for people to understand. I would just make it that you can give it a list of files
  ./led-image-viewer file1.gif file2.gif file3.gif

... or of course, you can put it in a directory
  ./led-image-viewer directory/*

Reloading files while things are being displayed is probably not a good idea as the Raspberry Pi is quite slow (you see how long it already takes to load and preprocess a regular image). Also, as I said, it is confusing.

If you want to dynamically changing the content over time, then you are better off by actually writing the code directly.

**Comment by makifbuz** [comment]
infact rpi2's speed is enough for me. i won't show a movie by merging gifs.
i will try to do some modifications and i would like to help me out.

p.s. do you think enlarge every parallel displays by daisy chaining to make
heighter displays like "LargeCanvas64x64" option? so we could drive not
only wider panels.
7 Mar 2015 01:55 tarihinde "Henner Zeller" <notifications@github.com> yazdı:

**Comment by hzeller** [comment]
> p.s. do you think enlarge every parallel displays by daisy chaining to make
> heighter displays like "LargeCanvas64x64" option? so we could drive not
> only wider panels.

Sure, you can do the same pixel-remapping tricks.

**Comment by hzeller** [comment]
Image viewer is now there for a while and looks like this is what was needed.
Closing this now. Please re-open if you have further issues.

**Comment by ClanHost** [comment]
Yes, I did it like this

```
                        DOWNLOADIMAGE(IMGFILENAME)
                        frame = Image.open(IMGFILENAME)
                        frameNo = 0
                        #size = 16, 96
                        while True:
                            offscreen_canvas.Clear()
                            try:
                                frame.seek(frameNo)
                            except EOFError:
                                break
                            frameNo += 1
                            time.sleep(0.1)
                            xframe = frame.convert('RGB')
                            #xframe.thumbnail(size, Image.ANTIALIAS)
                            offscreen_canvas.SetImage(xframe, 0, 0)
                            offscreen_canvas = self.matrix.SwapOnVSync(offscreen_canvas)
```

**Comment by Simon-Ince** [comment]
I got this working, I've posted my .py in a Gist here if it helps anyone: https://gist.github.com/Simon-Ince/910c440eb34bb722afa90853ecfb1d85

It needs some tweaking, gifs have timings for each of their frames and I haven't taken this into consideration.
