### ISSUE TITLE
Any advice on how to remove this flicker?

### ISSUE THREAD

**Issue by jerkwagon** [hzeller/rpi-rgb-led-matrix#1104]
Hi everyone, I have read over the troubleshooting parts and still can not seem to fix this flicker. 

Here is the P5 32x64 panel i am using [Link to panel](https://www.aliexpress.com/item/32841046668.html?spm=a2g0s.9042311.0.0.5fdc4c4dNWDqwl)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45178188/87858844-bc462100-c8e5-11ea-9d37-b057d2bff050.gif)

I am using a Pi3 with raspian lattest version and updates.  I think i will try to install the lite version, as this noise isnt going to suffice for my project.   I also have a nano laying around i could try as well

Looking for any input, thanks in advance

side note , is there anywhere i can get general community support for LED panels , discord or forum?  not much on reddit..

**Comment by hzeller** [comment]
You didn't describe how you connected the panels, did you use the standard wiring, or some Adafruit HAT ? If you used the hat, did you do the PWM modification ? If not, you absolutely want to do that.

The glitches seen there are mostl likely due to
   * Not using PWM (hence the first question)
   * Pi to fast for panels. Adjust the slowdown gpio value.
   * Power supply has trouble. Add capacitors and make sure ot have short wiring.

**Comment by hzeller** [comment]
As for forum, I think @marcmerlin was interested in setting up something like that, but I don't have time for that. For now, the bugtacker is a perfectly good place.

**Comment by jerkwagon** [comment]
> You didn't describe how you connected the panels, did you use the standard wiring, or some Adafruit HAT ? If you used the hat, did you do the PWM modification ? If not, you absolutely want to do that.
> 
> The glitches seen there are mostl likely due to
> 
> * Not using PWM (hence the first question)
> * Pi to fast for panels. Adjust the slowdown gpio value.
> * Power supply has trouble. Add capacitors and make sure ot have short wiring.

sorry about that, here is a photo of my wiring, 
<img width="878" alt="Screen Shot 2020-07-18 at 11 17 47 AM" src="https://user-images.githubusercontent.com/45178188/87859244-7b034080-c8e8-11ea-9679-fde24042e1c1.png">

no adafruit hat,

GPI slowdown didnt really change much

i noticed gpio slowdown is best a 0 or 2,  on the volume mixer demo i dont get that much noise, its very noticeable on the video player.  

my goal is to run 3x2 matrice of 32x64 matrix boards to make  video frame of sorts. 


one thing i have not done is ground the Ground pins, since my

**Comment by jerkwagon** [comment]
turns out i was missing my ground. issue fixed. 

@hzeller  thanks for your time i really appriciate it!

**Comment by marcmerlin** [comment]
@hzeller  I just asked Louis if he can help with his existing web board.

**Comment by hzeller** [comment]
Glad you got it working @jerkwagon .

In particular I like the progress of debuging, with one comment ending in a dangling
```
one thing i have not done is ground the Ground pins, since my...
```

... and the next continues with
```
Turns out i was missing my ground. issue fixed.
```

:)
