### ISSUE TITLE
using std::cout with led-matrix library

### ISSUE THREAD

**Issue by SethSenpai** [hzeller/rpi-rgb-led-matrix#1119]
Hey there,

I noticed that running the library, even with the showfps flag disabled, will prevent you from directly outputting anything to console. Any strings send to console will only show up after the program has closed. Is there a flag or option that I missed that would prevent this behaviour from happening?

Thank you!

**Comment by hzeller** [comment]
mmh, I don't see an immediate reason why it shouldn't work. Did you add `<< std::endl` to the end of your messages to make sure they are flushed ?

**Comment by SethSenpai** [comment]
I did not, thank you that solved it!

You learn something new every day :)
