### ISSUE TITLE
Problems with 1/8 Scan and out of order rows

### ISSUE THREAD

**Issue by James2k2** [hzeller/rpi-rgb-led-matrix#1121]
I've been trying to get my 32x32 panels to work and no matter what I do, I can't get the row orders to align correctly.

Setting multiplexing option 1 gives me the best image but as can be seen from the photo below the middle 2 sets of 8 rows should be swapped with the top and bottom 8 rows.
![IMG_20200815_203621](https://user-images.githubusercontent.com/69733295/90320703-604dd700-df3b-11ea-8d18-b0266eac8818.jpg)

**Comment by hzeller** [comment]
mmh, so if there is none of the 16 multiplexing options work, we'd need to add a new one, possibly a kind of StripMultiplexMapping but with flipped second row. Let me have a look.

**Comment by James2k2** [comment]
16 multiplexing options? Apologies I can only access 10 of them.

If it helps I compiled using the Adafruit guide, I'm assuming it's out of date? I'll also have a look around. Thank you!

**Comment by hzeller** [comment]
Please use this particular library here directly https://github.com/hzeller/rpi-rgb-led-matrix and follow the instructions in the README. The Adafruit people are using my library, but are always a little bit behind in syncing them.

Make sure to set the `--led-gpio-mapping=adafruit-hat`

**Comment by James2k2** [comment]
Recompiled and I've tried all 16 now, no dice unfortunately. Option 1 still gives me the best result so far. If it helps, I've attached a few photos of the panels I've got. Thank you again! 
![IMG_20200815_220331](https://user-images.githubusercontent.com/69733295/90321651-9000dd00-df43-11ea-9217-0d4c45dcce24.jpg)
![IMG_20200815_220415](https://user-images.githubusercontent.com/69733295/90321654-955e2780-df43-11ea-9f35-5573f64510f1.jpg)
![IMG_20200815_220426](https://user-images.githubusercontent.com/69733295/90321656-97c08180-df43-11ea-9503-491ea5c7661d.jpg)

**Comment by hzeller** [comment]
Can you do a fresh `git pull` and recompile, testing if the option 17 I just added works ?
It flips the way the parts are addressed:
![mux-1](https://user-images.githubusercontent.com/140937/90321898-d3872700-df02-11ea-9e52-d16ba8ce5a1b.png)

new one
![mux-17](https://user-images.githubusercontent.com/140937/90321900-d97d0800-df02-11ea-91cf-9c9f63c243ac.png)

**Comment by hzeller** [comment]
Oh, and just realized there was a typo. Now it is what it should be
![mux-17](https://user-images.githubusercontent.com/140937/90321927-1c3ee000-df03-11ea-9133-3239472d3c4f.png)

(count was off by one)

**Comment by James2k2** [comment]
Well sir, you have done a stirling job! Thank you very much. Here's a screenshot. 
![IMG_20200815_223836](https://user-images.githubusercontent.com/69733295/90322135-4f579280-df48-11ea-9602-c76c53d8d50e.jpg)

**Comment by hzeller** [comment]
Yay, have fun with your LED panels!

**Comment by James2k2** [comment]
OK, you're going to hate me now! The order seems to be swapped again when I add a second panel. These panels are very confusing. Also, please do just tell me if these panels are too problematic to fix! 
![IMG_20200815_230514](https://user-images.githubusercontent.com/69733295/90322446-0e617d00-df4c-11ea-8a05-b006a69bc61e.jpg)

**Comment by hzeller** [comment]
What are the parameters you are passing ? Did you use `--led-chain=2` ?
It should be something like
  `--led-cols=32 --led-rows=32 --led-chain=2 --led-multiplexing=17`

**Comment by James2k2** [comment]
You know what, it's late and I've completely missed that parameter! I do apologise. Yes it works perfectly! Now to try and get Adafruit Framebuffer code to accept the extra mode you added. Thank you again for your patience and doing my stupidity checks!

**Comment by hzeller** [comment]
I think the rpi-fb-matrix just uses this project as sub-module.
So you probably just have to

```
cd rpi-rgb-led-matrix
git checkout master
git pull
```

**Comment by hzeller** [comment]
mmh, they use a deprecated transformer that doesn't exist anymore, so that code won't compile.

So it is probably easier to just hack this in: In your rpi-fb-matrix/ directory, edit `rpi-rgb-led-matrix/lib/multiplex-transformers.cc` and modify line 74; replace the `<`
```
    const bool is_top_stripe = (within_panel_y % (panel_rows_/2)) < panel_rows_/4;
```
with `>=`
```
    const bool is_top_stripe = (within_panel_y % (panel_rows_/2)) >= panel_rows_/4;
```

.. then use `--led-multiplexing=1`

**Comment by James2k2** [comment]
Well you're a fountain of knowledge. Thank you very much! I had attempted to look through your examples to see if I could modify their code to use a newer transformer but it wasn't presenting itself to me at this moment.

**Comment by hzeller** [comment]
Essentially what needs to be done is to implement a [`PixelMapper`](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/include/pixel-mapper.h) instead of a tranformer. It should be somewhat straight-forward; both map pixels from source to destination essentially.

The PixelMapper requires a little less brain-twisting (but it means that the old transformer has to be un-brain-twisted).
