### ISSUE TITLE
Help me ,I have 2 panels of 32*64

### ISSUE THREAD

**Issue by 6010110254** [hzeller/rpi-rgb-led-matrix#1123]
and i am using adafruit-hat with the Pi4 when running  on rpi-rgb-led-matrix/examples-api-use  
sudo ./demo -D 4 runtext.ppm 
output design here . red 2 rows [scroll]
![117596016_3416096268441421_4604090276562882682_n](https://user-images.githubusercontent.com/47842161/90523489-25e07600-e197-11ea-997c-fef6db5b73ae.jpg)
![117649998_756564971823217_8534796477707536965_n](https://user-images.githubusercontent.com/47842161/90523499-27aa3980-e197-11ea-9073-7fd6b3dd416b.jpg)
![117843095_304785864075660_2913968660539137334_n](https://user-images.githubusercontent.com/47842161/90523502-28db6680-e197-11ea-8e2a-1fcb75f219ce.jpg)

where sholud i fix it?

**Comment by hzeller** [comment]
Did you systematically go through the options such as `--led-row-addr-type`	and`--led-multiplexing`  ? Since you are using the Pi4, you probably also need the `--led-slowdown-gpio` option.

Please read and follow the []README](https://github.com/hzeller/rpi-rgb-led-matrix) first and follow all instructions there systematically.

**Comment by 6010110254** [comment]
I've tried it
sudo ./demo --led-cols=32 --led-rows=32 --led-chain=2 --led-row-addr-type=2 --led-multiplexing=1 --led-slowdown-gpio=4 --led-pixel-mapper=U-mapper -D 1 runtext.ppm

But results like this
![117893325_4263943110347370_6945973279489608015_n](https://user-images.githubusercontent.com/47842161/90542966-2422ac80-e1af-11ea-96e3-7b2356cf8a2c.jpg)
![117968908_1772525052901332_4403236609278559245_n](https://user-images.githubusercontent.com/47842161/90542975-25ec7000-e1af-11ea-8cee-019da91d90dd.jpg)
![117710580_305555733888256_48081458124281330_n](https://user-images.githubusercontent.com/47842161/90542978-271d9d00-e1af-11ea-97d2-4468052a43c0.jpg)

Help me thank you very much

**Comment by hzeller** [comment]
Why are you using u-mapper, when you only have one panel provided ?
The panel is 64 columsn wide, so `--led-cols=64` is probably more appropriate.
Did you go through all four row-addr-types, two led-panel types and 17 led-multiplexing ?

If so, your panel probably is not yet supported and you need to hunt down a datasheet for it.

**Comment by 6010110254** [comment]
I have tried to fix it. --led-row-addr-type 2 The only option to see results and --led-multiplexing has tried all 10 values and it seems to see the results. But still not clear
![118094628_1203118716727903_9110927636813576577_n](https://user-images.githubusercontent.com/47842161/90548953-f726c780-e1b7-11ea-9947-2ea2e957315a.jpg)
![117663116_630692510898795_5803092312411909978_n](https://user-images.githubusercontent.com/47842161/90548957-f8f08b00-e1b7-11ea-9c98-da34a46babc5.jpg)
![117646420_608078969873340_6705383490963761635_n](https://user-images.githubusercontent.com/47842161/90548958-fa21b800-e1b7-11ea-8b0e-c34b5a006b4f.jpg)

Please take a look at this LED p5.
https://www.igetled.com/product/94/p5-fullcolor-%E0%B9%83%E0%B8%99%E0%B8%A3%E0%B9%88%E0%B8%A1

Thank you very much, sorry for wasting your time.

**Comment by hzeller** [comment]
Do you have a picture of the input connector on the matrix ?
I suspect that this is an entirely different panel (or you plugged in the input on the output :) ).

**Comment by hzeller** [comment]
If you only see 10 values for led multiplexing, you're using an ancient version of this library. did you check out the Adafruit fork ?
I'd use this one here

**Comment by daveythacher** [comment]
--led-gpio-mapping=adafruit-hat

**Comment by 6010110254** [comment]
I have removed and reloaded the version, but still the same, tried multi 0-17 and I fixed the adafruit-hat.
But I power the 5v LED through the adafruit-hat board, don't know if that's right.
![118215909_2607334269483852_7528256340576349089_n](https://user-images.githubusercontent.com/47842161/90592629-3c76e380-e210-11ea-8436-58207dbef596.jpg)
![117897642_349414329796506_7914795350908607401_n](https://user-images.githubusercontent.com/47842161/90592634-3ed93d80-e210-11ea-90b2-b43e7d120c1f.jpg)
![117980428_406015030375156_8527621701681002469_n](https://user-images.githubusercontent.com/47842161/90592638-3f71d400-e210-11ea-8dfb-8bf4e54f119d.jpg)
![118144588_775448879858119_2512418427961745121_n](https://user-images.githubusercontent.com/47842161/90592640-40a30100-e210-11ea-8c83-d41e45fc48ea.jpg)
![118195554_330839704723007_6627024833169054671_n](https://user-images.githubusercontent.com/47842161/90592642-41d42e00-e210-11ea-9457-ca0a7bd7d2d0.jpg)

**Comment by 6010110254** [comment]
![118215909_2607334269483852_7528256340576349089_n](https://user-images.githubusercontent.com/47842161/90593143-6d0b4d00-e211-11ea-84ba-0b67cadaf12c.jpg)
![Uploading 117897642_349414329796506_7914795350908607401_n.jpg…]()

**Comment by 6010110254** [comment]
After I connected to a switching 5V, the results were quite dramatic, but still not clear.
![117725661_755671568554734_7665601866905667017_n](https://user-images.githubusercontent.com/47842161/90620185-51696c00-e23c-11ea-9cb0-b44998b447c0.jpg)
![117765934_299327827821740_8205495291471649343_n](https://user-images.githubusercontent.com/47842161/90620194-54645c80-e23c-11ea-8ca1-03a73a66d2ca.jpg)
![117767770_320009642449274_7423414784802846855_n](https://user-images.githubusercontent.com/47842161/90620199-562e2000-e23c-11ea-86f7-33c7a233ead2.jpg)
![117909424_304106470697411_1368468587549610939_n](https://user-images.githubusercontent.com/47842161/90620202-575f4d00-e23c-11ea-824b-4bdb399591a5.jpg)

**Comment by 6010110254** [comment]
I feel the led rows in the middle are not showing.
Why

**Comment by 6010110254** [comment]
![117725643_305533044101434_7749985857352567147_n](https://user-images.githubusercontent.com/47842161/90642392-82599900-e25c-11ea-83b2-44b54a613be5.jpg)
 thanks very much

**Comment by daveythacher** [comment]
This can be closed
