### ISSUE TITLE
Issue with 16x32 panel

### ISSUE THREAD

**Issue by manuel1507** [hzeller/rpi-rgb-led-matrix#1124]
Hi, first of all congratulations for this excellent work! I'm trying to work with the library and a bunch of 16x32 LED panels purchased on Aliexpress (P10). My HW setup: Raspberry PI 3 B + Adafruit HAT and DietPi (OS) and one panel for now. I made some steps forward, but I got stucked here
![hello_world](https://user-images.githubusercontent.com/42934442/90578434-969d8780-e1c3-11ea-8ab3-c68acb6a639f.png)

played around for a few hours with all different settings, but only minor progress. The picture shows my best effort with the runtext python sample :-) 
Any idea what I'm doing wrong here?

thanks a lot!

**Comment by daveythacher** [comment]
Good info, but I would need more information like how many panels and your command. So lets start here:

~/rpi-rgb-led-matrix/examples-api-use/demo --led-rows=16 --led-cols=32 --led-chain=1 --led-parallel=1 --led-show-refresh --led-slowdown-gpio=2 --led-pwm-bits=3 --led-pwm-lsb-nanoseconds=300 -D4 --led-gpio-mapping=adafruit-hat

For this first pass I am ignoring a few things: Multiplex, mapping, addr_type, driver special case, etc.

**Comment by manuel1507** [comment]
Thank you David for the support. I followed your suggestion and I can
appreciate some improvements on the performance, but still rows from 5->8
and 13->16 are not working and string is not formatted well. Attached a
picture
. Any further support is highly appreciated.
Cheers
Manuel

Il giorno mer 19 ago 2020 alle 04:58 David Thacher <notifications@github.com>
ha scritto:

**Comment by 6010110254** [comment]
i'm just like you, the text isn't as clear as some lines don't.

**Comment by 6010110254** [comment]
![117666715_2850855538534050_9215814792537352602_n](https://user-images.githubusercontent.com/47842161/90624543-529d9780-e242-11ea-90ad-cdf1bdb57bef.jpg)

**Comment by 6010110254** [comment]
![117813879_2961116934115135_8631780441468237685_n](https://user-images.githubusercontent.com/47842161/90638033-f8f39800-e256-11ea-89eb-06e8bff306a2.jpg)
thank you complete

**Comment by daveythacher** [comment]
This can be closed.

**Comment by daveythacher** [comment]
@manuel1507 How many address pins do you have?

**Comment by manuel1507** [comment]
ABC

Il giorno mer 19 ago 2020 alle 16:19 David Thacher <notifications@github.com>
ha scritto:

**Comment by daveythacher** [comment]
@manuel1507 What command?

**Comment by manuel1507** [comment]
Not sure I got your question..I was trying both demo and python sample.
Result is the same. Maybe some soldering issue...I get two black lines

Il giorno mer 19 ago 2020 alle 17:34 David Thacher <notifications@github.com>
ha scritto:

**Comment by manuel1507** [comment]
ok, it has to be some soldering issue. I removed now the HAT and tried the
regular wiring and I managed to get rid out of the black lines, but the
final result is far from being perfect.
See LINK https://youtu.be/jgTPr2ocd_U

If I remove all GND it gets slightly better, but this is not a solution.

Any hint?

This is the command: ./demo --led-rows=16 --led-cols=32 --led-chain=1
--led-parallel=1 --led-show-refresh --led-slowdown-gpio=2 --led-pwm-bits=3
--led-pwm-lsb-nanoseconds=300 -D1 runtext16.ppm --led-gpio-mapping=regular

Il giorno mer 19 ago 2020 alle ore 17:34 David Thacher <
notifications@github.com> ha scritto:

**Comment by daveythacher** [comment]
Lets keep with this command:
./demo --led-rows=16 --led-cols=32 --led-chain=1
--led-parallel=1 --led-show-refresh --led-slowdown-gpio=2 --led-pwm-bits=3
--led-pwm-lsb-nanoseconds=300 -D1 runtext16.ppm --led-gpio-mapping=adafruit-hat

Lets add this to it now:
--led-row-addr-type=3

If this turns on all the display rows that will be progress. At this point we are just trying to explain why some rows are not turning on. It could use a weird multiplex scheme which we can probably work at with different command.

Do you have a picture of the panel back side? Or a list of IC numbers used on your board?

**Comment by daveythacher** [comment]
> If I remove all GND it gets slightly better, but this is not a solution.

That is really strange. We can try slowing it down, but I am not sure exactly what that gets. However if you are using certain wire lengths at high speed or in noisy environment it could help. Most of the panels buffer the input signals, so long as the wires are short it should not matter a lot. These panels likely have 4 grounds. Ground loops could be a problem.

Ways to slow it down. Increase one or more of the following --led-slowdown-gpio, --led-pwm-bits, --led-pwm-lsb-nanoseconds (not very effective). You could also increase the columns and maybe mess around with the rows. (But I am not sure I recommend messing with these right now.)

Moving to --led-slowdown-gpio=4 and --led-pwm-bits=8 will seriously drag down the FPS. To drag the multiplex you could try increasing the pwm-bits to 11.

**Comment by manuel1507** [comment]
Here the picture



Il giorno gio 20 ago 2020 alle 17:03 David Thacher <notifications@github.com>
ha scritto:

**Comment by daveythacher** [comment]
There is no picture

**Comment by manuel1507** [comment]
Il giorno gio 20 ago 2020 alle 21:50 David Thacher <notifications@github.com>
ha scritto:

**Comment by daveythacher** [comment]
I am not able to see the chips in that picture. Have you tried increasing --led-pwm-lsb-nanoseconds? Did you follow the hook up in here: https://github.com/hzeller/rpi-rgb-led-matrix/blob/90a890ab440f70e85ba7da9c6085c97c3fd67fd2/lib/hardware-mapping.c#L30?

**Comment by daveythacher** [comment]
I am curious what is on Q1 and Q2. I think I know what is on U1 and U2. I would guess both are the same. I am not really interested with UR1-4, UG1-4, UB1-4. I think I know that those are, but it could be helpful to know just to be sure. They should all be the same also.

**Comment by daveythacher** [comment]
In a deleted comment I mentioned changing the address type. I also mentioned ground loops due to your ground comment. However I am not sure if those made sense per say. However I would be interested in tracking down your panel then checking wiring.

I find it hard to believe that board has soldering issue. You would be able to tell with visual inspection more than likely or with volt meter. You only soldered on the through hole connectors, which should not cause too much issue.

**Comment by manuel1507** [comment]
> In a deleted comment I mentioned changing the address type. I also mentioned ground loops due to your ground comment. However I am not sure if those made sense per say. However I would be interested in tracking down your panel then checking wiring.
> 
> I find it hard to believe that board has soldering issue. You would be able to tell with visual inspection more than likely or with volt meter. You only soldered on the through hole connectors, which should not cause too much issue.

**Comment by manuel1507** [comment]
Hi David,
just to make clear. I was following two paths:
1) RPi4 + Adafruit HAT
2) RPi + breadboard wiring schema and "regular" mapping

Different problems both ways:
1) ./demo --led-rows=16 --led-cols=32 --led-chain=1 --led-parallel=1 --led-show-refresh --led-slowdown-gpio=2 --led-pwm-bits=3 --led-pwm-lsb-nanoseconds=300 -D4

BLACK ROWS (tried already addr option and slow down; I even played around with multiplexing):

![D4](https://user-images.githubusercontent.com/42934442/90836800-a1d1ee00-e350-11ea-8fdd-95dbdaef66d3.jpeg)

2) Looks much better but it's FLICKERING:

https://youtu.be/BwoGrMfBKcg

I believed I managed to read the chip: Q1 and Q2 are ICN2012. All the others are shift registers from ChipOne.

**Comment by manuel1507** [comment]
Habemus Led control. 

![747C28F4-645B-4C32-9169-463DE0F106C5](https://user-images.githubusercontent.com/42934442/91606128-d443a280-e971-11ea-8357-88743e77e7fd.png)
![Uploading AC574E34-137B-464A-A33F-89B78BEDD536.jpeg…]()


A little re-wiring and different power adapter and voila.

Thank you David for the all the support and patience. We can close this one.

**Comment by daveythacher** [comment]
What changes did you make?

**Comment by manuel1507** [comment]
When I was using the wires and the breadboard the problem was the power
supply. I put the capacitor in parallel and that solved the issue.

With the Adafruit HAT the issue were two pins not soldered correctly on the
flat cable. Solved.

Thanks again for all your support, I will now play around with the library
and a few applications I had in mind.

Cheers


Il giorno ven 28 ago 2020 alle 21:39 David Thacher <notifications@github.com>
ha scritto:
