### ISSUE TITLE
difficulty making a first easy sketch by myself with c++

### ISSUE THREAD

**Issue by carmonkeylab** [hzeller/rpi-rgb-led-matrix#1157]
hi guys, as the title suggests, I am having trouble creating the sketch by myself. do i need to compile the sketch, if so, how would i do that. where would i need to create the sketch. can i put it wherever i want or am i supposed to put it somewhere designated. also, if possible, can someone send basic code that just fills the screen a solid color with comments on most, if not all lines so i can properly understand what each command would do. thanks for the help in advance. i am using a rpi 4

**Comment by carmonkeylab** [comment]
forgot to state that i am using a raspberry pi 4

**Comment by daveythacher** [comment]
https://github.com/hzeller/rpi-rgb-led-matrix/blob/97ec43d07f3f85431db4d4a29836fd6a412b0c68/examples-api-use/demo-main.cc#L1063-L1064

https://github.com/hzeller/rpi-rgb-led-matrix/blob/97ec43d07f3f85431db4d4a29836fd6a412b0c68/examples-api-use/demo-main.cc#L1066-L1068

https://github.com/hzeller/rpi-rgb-led-matrix/blob/97ec43d07f3f85431db4d4a29836fd6a412b0c68/examples-api-use/demo-main.cc#L1071-L1075

https://github.com/hzeller/rpi-rgb-led-matrix/blob/97ec43d07f3f85431db4d4a29836fd6a412b0c68/examples-api-use/demo-main.cc#L1102-L1104

https://github.com/hzeller/rpi-rgb-led-matrix/blob/97ec43d07f3f85431db4d4a29836fd6a412b0c68/examples-api-use/demo-main.cc#L89

https://github.com/hzeller/rpi-rgb-led-matrix/blob/97ec43d07f3f85431db4d4a29836fd6a412b0c68/examples-api-use/demo-main.cc#L60

https://github.com/hzeller/rpi-rgb-led-matrix/blob/97ec43d07f3f85431db4d4a29836fd6a412b0c68/examples-api-use/demo-main.cc#L82-L83

https://github.com/hzeller/rpi-rgb-led-matrix/blob/97ec43d07f3f85431db4d4a29836fd6a412b0c68/examples-api-use/demo-main.cc#L1186

**Comment by carmonkeylab** [comment]
>do i need to compile the sketch, if so, how would i do that. where would i need to create the sketch. can i put it wherever i want or am i supposed to put it somewhere designated.

**Comment by carmonkeylab** [comment]
can you pls answer these 2 questions
