### ISSUE TITLE
G1 not working on Raspberry Pi 1 Rev 1

### ISSUE THREAD

**Issue by tazfriend** [hzeller/rpi-rgb-led-matrix#118]
On a Rapsberry Pi A/B PCB Rev 1 (September 2012 or earlier), pin 13 of the GPIO connector is connected to GPIO 21 not GPIO 27. Could one change this with a compile flag.

**Comment by hzeller** [comment]
If you define RGB_CLASSIC_PINOUT and ONLY_SINGLE_CHAIN then output-enable and clock will be on P1-03 and P1-05

See this:
https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/framebuffer-internal.h#L121

.. for wiring.

**Comment by davemaster** [comment]
Greetings,

Try replacing RGB cables.

2016-02-22 15:37 GMT-05:00 Henner Zeller <notifications@github.com>:

> If you define RGB_CLASSIC_PINOUT and ONLY_SINGLE_CHAIN then output-enable
> and clock will be on P1-03 and P1-05
>
> See this:
>
> https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/framebuffer-internal.h#L121
>
> .. for wiring.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hzeller/rpi-rgb-led-matrix/issues/118#issuecomment-187372729>
> .
>



-- 
David Elias Flores Escalante
TeleTracking SAC

**Comment by hzeller** [comment]
Did it work @tazfriend ?

**Comment by crazyduck** [comment]
Dirty workaround for RPi1rev1, as PIN13 is GPIO27(RPi1) replace in 
https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/framebuffer-internal.h#L210

unsigned int p2_b2          : 1;  // 21 P1-40 (only on A+/B+/Pi2)

with

unsigned int p0_g1          : 1;  // 21 P1-40 (only on A+/B+/Pi2)

**Comment by hzeller** [comment]
No response by @tazfriend - but anyway, whoever stumbles over this, the suggstion above (setting RGB_CLASSIC_PINOUT and ONLY_SINGLE_CHAIN) should work. Closing now.
