### ISSUE TITLE
Not working with CM4 

### ISSUE THREAD

**Issue by arahasya** [hzeller/rpi-rgb-led-matrix#1212]
Hi

I have made a custom PCB using CM4. I get this output with --led-show-refresh

infHz

The library is not initializing. How to add support?

**Comment by hzeller** [comment]
CM4 was not yet detected as it was a new version of the Pi. Added support for it, can you check if it works now after a fresh `git pull` ?

**Comment by arahasya** [comment]
Yes. Working now. Thanks!
