### ISSUE TITLE
How to vary speed of rolling text?

### ISSUE THREAD

**Issue by jax200** [hzeller/rpi-rgb-led-matrix#1214]
Not clear if there is this option.

**Comment by hzeller** [comment]
If you look at the options, there is `-s` which controls that.
https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/utils#text-scroller

**Comment by jax200** [comment]
Thx.  Right there in front of my nose!  I was referring to the other help menu that shows -s "extra spacing".

**Comment by jax200** [comment]
also...

pi@raspberrypi:~/rpi-rgb-led-matrix $ make text-scroller
make: *** No rule to make target 'text-scroller'.  Stop.

**Comment by hzeller** [comment]
Well, did you go to the `utils/` directory first ?
