### ISSUE TITLE
Help me , Display not show

### ISSUE THREAD

**Issue by 6010110254** [hzeller/rpi-rgb-led-matrix#1222]
Help me
Several days ago I was able to show led-image-viewer, today I can't show it again, same code.
![Screenshot (316)](https://user-images.githubusercontent.com/47842161/103440909-3f80e680-4c7c-11eb-99a3-496c49593a98.png)

![135512015_871491597017328_6037411910578203780_n](https://user-images.githubusercontent.com/47842161/103440920-4e679900-4c7c-11eb-8fea-958758075b6b.jpg)

I don't know
Why
Thanks

**Comment by davemaster** [comment]
... previous picture?

possible cause:
1. Power supply fault
2. data cable fault
3. rpi - rgb panel pcb of cable fault
4. command line is not the same as you believe, or you update hzeller library 

check them up

**Comment by jaygarcia** [comment]
What Panels are you using? What is the connector type?

**Comment by 6010110254** [comment]
Sorry for saying late
Now I can show it, I don't know why.
