### ISSUE TITLE
Lag when it comes to displaying logos with "blurred edges" vs logos that are just "all pixels"? 

### ISSUE THREAD

**Issue by justinodunn** [hzeller/rpi-rgb-led-matrix#1250]
Hey all! So I'm working on a stock ticker with 6 daisy chained 64x32 LED matrix panels with the RPI 4, and how it works is that basically it takes a whole bunch of different stock prices with their different logos and generates a very wide scrolling image to display. 

Right now, I'm getting some issues with performance though, sometimes I'd get lag / stuttering with the scrolling animation, which I noticed in particular when it starts displaying logos that have "blurred edges" to them, hence some of the LED pixels end up being half lit to make up those blurred edges. However, when logos that are fully just pixelated come out, they seem to lag less. Please look at the images below to see what I'm referring to:

This is a logo that is "fully pixelated" (No LED pixels are semi lit. Notice how the color is 100% on this logo):
![Screen Shot 2021-02-14 at 12 10 07 AM](https://user-images.githubusercontent.com/13812089/107854879-ec44ab00-6e59-11eb-9b1f-61c01b1a020c.png)

This is a logo that has "blurred edges" (Some LED pixels are semi lit to display those blurred edges. Notice how the edges have some transparency to them. These logos seem to cause lag issues):
![Screen Shot 2021-02-14 at 12 10 50 AM](https://user-images.githubusercontent.com/13812089/107854891-01213e80-6e5a-11eb-87b7-5d47d5c41e68.png)

Any ideas how to fix this? Thank you.

**Comment by hzeller** [comment]
The LED matrix code should not have any issue with blurred images or not.

I can only assume that your code that assembles it might need more resources to render these.

(Unrelated: I notice that the stock prices are written in an antialiased font. I'd suggest to use a bitmap font here, because you really want a crisp display of these.)

**Comment by justinodunn** [comment]
Thanks for the quick response Mr. Zeller! So you don't think blurred images should affect the lag issue that much, and that it's rather something else that's causing this? Are there any flags I can use to perhaps better increase performance? I'm currently using a GPIO slowdown of 4, rows=32, col=64, chain=6, and GPIO mapping=adafruit-hat. 

Could you also please elaborate more on needing more resources to render? Sorry I didn't write the code for this, a friend made this for me.

Thank you.

**Comment by hzeller** [comment]
Connecting a single chain of 6x 64 columns long panels is somewhat long, this will not give you a good refresh rate and I'd not recommend such many pixels on one chain to start with.

Make this [three chains](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/adapter/README.md) with two panels chained each and to physically arrange them in one row you can [use the VMapper (there is an example with one row)](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#v-mapper-and-vmapperz-vertical-arrangement)  - that way it presents to your application as the usual 384x32 pixel canvas.

While you use the `adafruit-hat`, you will get brightness glitches unless you do the [Adafruit-hat PWM hardware mod](https://github.com/hzeller/rpi-rgb-led-matrix#improving-flicker) and then run it with `adafruit-hat-pwm`.

Other than that, use the usual recommendations found in the [troubleshooting section](https://github.com/hzeller/rpi-rgb-led-matrix#troubleshooting), make sure to have the [isolcpus setting](https://github.com/hzeller/rpi-rgb-led-matrix#cpu-use), don't do resource-intensive stuff on the system (e.g. don't run a UI, don't have other intensive background processes running, preprocess stuff you can (e.g. if you need to scale down an image, like the logos, do it once in the beginning an then use that later),  strongly prefer C++ to Python). It is also noticeable that network traffic can cause glitches, as apparently inside the Pi this interferes with the GPIO output.

Using an antialiased font could also result in more resource usage as it it much more expensive to scale it to the proper size. Also given that it is more 'ugly', changing this to use a bitmap font is probably a good start (There is bitmap text drawing [in the graphics API of this library](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/include/graphics.h#L109-L118)).

**Comment by justinodunn** [comment]
Sounds good, thank you for the response! I will look more into this and experiment around. Will close this for now thanks!
