### ISSUE TITLE
Using led-image-viewer to go through folder of animated GIFs

### ISSUE THREAD

**Issue by tbakker123** [hzeller/rpi-rgb-led-matrix#126]
First of all I have to say, great piece of software. My panel from Aliexpress worked pretty much plug&play. 

I'd like my panel to go through a folder of animated GIFs but have not been able to achieve this. I've tried to use Python subprocesses to call the shell command for each gif in a folder, with a few seconds in between. I have been unable to simulate the "ctrl-c" SIGINT command in my Python script to properly reset the matrix panel. Therefore I end up overwriting gifs on top of each other, which makes the panel display a scrambled mess of pixels.  

This is the code I tried:
```
path = '/home/pi/gifs/'
fileslist = [f for f in listdir(path) if isfile(join(path, f))]

for i in range(len(fileslist)):
 bash = 'sudo /home/pi/rpi-rgb-led-matrix/led-image-viewer ' + fileslist[i]
 gifloop = subprocess.Popen(bash, shell=True)
 time.sleep(2)
 os.kill(gifloop.pid, signal.SIGINT)
```
I also tried different kinds of terminating the subprocess, such as gifloop.kill(), gifloop.terminate(). All to no avail. 

Has anyone been able to achieve this? What was your solution? Thanks in advance.

EDIT: This just came to my mind, my GIFs have infinte looping enabled, will try GIF with fixed number of loops when I get home.

EDIT2: Well, that didn't work unfortunately.

EDIT3: After hours of messing with Python script (I am a beginner after all), I dove into the led-image-viewer.cc file itself and edited line 137, changed the for loop end conditions to i < 3* frames.size(), to make the gif loop 3 times then quit. I can now cycle my GIF with the following script:

```
#/usr/bin/python

import subprocess
from os.path import isfile, join
from os import listdir, getpid, kill, system
import time
import signal


try:
	path = '/home/pi/gifs/'
	fileslist = [f for f in listdir(path) if isfile(join(path, f))]
	print 'Number of files: ', len(fileslist)
	print fileslist
	
	while True:
		for i in range (len(fileslist)):
			bash = 'sudo /home/pi/rpi-rgb-led-matrix/led-image-viewer -b 10 /home/pi/gifs/' + fileslist[i]
			print bash
			gifloop = subprocess.Popen([bash], shell=True)
			stdoutdata, stderrdata = gifloop.communicate()

		
except KeyboardInterrupt:
	kill(getpid(), signal.SIGINT)
	print "gifloop got ctrl-c"
```

**Comment by hzeller** [comment]
I would suggest to really do that in the led-image-viewer itself. If someone wants to implement something like that, please send a pull request.
