### ISSUE TITLE
Minor flickering problem after 20 minutes

### ISSUE THREAD

**Issue by rijotech** [hzeller/rpi-rgb-led-matrix#1261]
Hi Mr. Zeller. 
I'm facing a minor issue with a screen, I'm running 8 P2.5 128x64 LED modules, I have also added 8 capacitor 25v 3300uf, I noticed that when the screen is off for a few hours and I turn it on there is no static or flickering but after 10 to 20 minutes I notice some flickering on the left upper last two modules also depending on the color of the video the flickering gets more intense.
I'm running this command 
`sudo video-viewer -f -F video.mp4 --led-rows=64 --led-cols=128 --led-chain=4 --led-parallel=2 --led-pixel-mapper=V-mapper --led-slowdown-gpio=5  --led-pwm-lsb-nanoseconds=200 --led-panel-type=FM6126A --led-scan-mode=0 --led-pwm-bits=9 --led-limit-refresh=90 --led-pwm-dither-bits=1`
So far I replaced those two modules, power supply, shorted the power cables with no luck. 

Can you please provide me with some solutions?

https://user-images.githubusercontent.com/17016357/109404102-dee6f080-7930-11eb-8d76-266ababb48c9.mp4

**Comment by davemaster** [comment]
try reduce --led-slowdown-gpio=(2-4) also  --led-pwm-lsb-nanoseconds=(200-350); in this last, there is a way to try the better values for this, using refresh rates values (make them visible)

**Comment by rijotech** [comment]
@davemaster I have tried all that and --led-slowdown-gpio=(2-4) will just make it worst, I don't think this is a command-related problem but I could be wrong, I will try using capacitor 25v 4700uf or 35v 3300uf to see if that makes any difference.

**Comment by rijotech** [comment]
Well, the capacitor 25v 4700uf didn't work if any I got even more static, I'll try using ground and power bars next.

**Comment by davemaster** [comment]
Did You try with another RGB LED panels?

**Comment by rijotech** [comment]
@davemaster Yep shorted the cables, change the power supply, grounded the raspberry pi, swap capacitors, disable crontab, disabled all running services, disabled audio on boot.txt dtparam=audio=off, applied isolcpus=3 on /boot/cmdline.txt and still I can't get rid of the flickering.

**Comment by rijotech** [comment]
I just fixed it finally.

**Comment by hzeller** [comment]
What was the issue ?

**Comment by rijotech** [comment]
The data cable was too long I purchased different cables ![image](https://user-images.githubusercontent.com/17016357/110838873-f7c89d80-8270-11eb-9218-e887a826979d.jpeg)
