### ISSUE TITLE
How to install python binding in a pipenv?

### ISSUE THREAD

**Issue by azflin** [hzeller/rpi-rgb-led-matrix#1265]
Question in title.  I am able to install the python binding on my base python using:
```bash
git clone https://github.com/hzeller/rpi-rgb-led-matrix.git
cd rpi-rgb-led-matrix
make build-python PYTHON=$(which python3)
sudo make install-python PYTHON=$(which python3)
```
 How would I do it for an isolated pipenv environment?

**Comment by macaquedev** [comment]
you activate your pipenv, run:
`which python`
in isolation to check that "python" points to the pipenv python, and then you run the last 2 commands. It's really that simple

**Comment by azflin** [comment]
@macaquedev Thanks! It works. I thought I had tried that previously.
