### ISSUE TITLE
2 more parallel chains with Compute Module

### ISSUE THREAD

**Issue by currentlysober** [hzeller/rpi-rgb-led-matrix#127]
Dear Henner,

according to our conversation, I was trying to run 2 more chains (4th and 5th) using Compute Module. The new CMv3 is going to be released soon so once we get prepared, we will be able to show nice images on 5 chains.
I decided to use as following:
chain no.4
gpio30 -> R1
gpio31 -> R2
gpio32 -> G1
gpio33 -> G2
gpio34 -> B1
gpio35 -> B2
chain no.5
gpio38 -> R1
gpio39 -> R2
gpio40 -> G1
gpio41 -> G2
gpio42 -> B1
gpio43 -> B2
(gpio 36 and 37 I left for uart)

I was not able to upload files here and I didn't want to copy 4 big files into this message, so I uploaded them into my repository:
https://github.com/currentlysober/led_temp_files
I provided changes and marked them with 'change' comments.
To make long story short, the result does not work as it should. Here is the photo of 3th and 4th row. I print RR GG BB:

![fullsizerender](https://cloud.githubusercontent.com/assets/13116908/14461425/c5ce6970-00c2-11e6-9ba9-2de52daeb630.jpg)

as you can see, 3th row works correctly - this is the row from your lib. But the new row no.4 works partially - only one color is visible. Moreover, on 5th row there's nothing at all. 
Could you please consider this interesting issue and give some idea what the reason might be? Maybe some other members can participate in solving it? Then you would copy the files and put into your library to have complete source code.

Thank you in advance.
Regards
Daniel

**Comment by hzeller** [comment]
You are going beyond the 32 bits, so you need to change the gpio operations to do 64 bits.

**Comment by currentlysober** [comment]
Hi!
The problem is that your library is too complicated for me :P Of course I tried, I have put changes and here I uploaded:
https://github.com/currentlysober/led_temp_files
but still there is no result. I am sure I missed many places but when I changed more uint32-s into 64, I couldn't see anything on the screen (even in chains 1-3). 
Moreover, I had an error:
static void rgb_matrix::internal::Framebuffer::InitGPIO(rgb_matrix::GPIO*, int): Assertion `result == b.raw' failed.
So I changed into
assert(result == (uint32_t)b.raw);
Could you please take a look and give some advice? I'll be grateful. Then we can merge it into official library. Thanks!
