### ISSUE TITLE
Yet another black bar issue 64x64 panel from Adafruit (http://adafru.it/4732)

### ISSUE THREAD

**Issue by s3rdl** [hzeller/rpi-rgb-led-matrix#1279]
As described in the following issue: #961 #926 #895 #1189 I tried all mentioned hardware modifications on the Bonnet and the PiHAT. Even those shown on Adafruit website. I do have both boards twice, so I can depict different stages of the hardware mods.
I tried every combination of wiring and command prompt, but have no success.
This is, how I start the prog at the moment:
 `sudo ./demo -D0 --led-cols=256 --led-rows=64 --led-gpio-mapping=adafruit-hat-pwm --led-multiplexing=1 --led-limit-refresh=400 --led-show-refresh --led-pwm-dither-bits=1 --led-slowdown-gpio=4`

Used hardware: 
Pi 4 - 4GB - running raspbian buster lite (as lite as possible)
Adafruit RGB Matrix HAT + RTC for RPi (http://adafru.it/2345)
Adafruit RGB Matrix Bonnet (http://adafru.it/3211)
4x Adafruit 64x64 RGB LED Matrix - 3mm Pitch (http://adafru.it/4732) chained together

The following pictures shows the mods on the boards and the result on the LED-Matrix.

Bonnet front/back:
![Bonnet_Front_MOD](https://user-images.githubusercontent.com/25957772/111999468-4dc4fd00-8b1d-11eb-9f83-eec8522d635d.png)
![Bonnet_Back_MOD](https://user-images.githubusercontent.com/25957772/111999497-54ec0b00-8b1d-11eb-8190-823b16cedf01.png)

PiHAT front/back:
![PiHAT_Front_MOD](https://user-images.githubusercontent.com/25957772/111999591-6cc38f00-8b1d-11eb-9243-80b18ad9c2f8.png)
![PiHAT_Back_MOD](https://user-images.githubusercontent.com/25957772/111999636-764cf700-8b1d-11eb-992f-4197d8837f25.png)

And the Matrix:
![Matrix_output](https://user-images.githubusercontent.com/25957772/111999692-806ef580-8b1d-11eb-9418-55f548d06918.png)

I can run static and scrolling text without any hassle, but only in the first and the third section of the panel where no black bars are.
Using larger fonts, or setting margin for text, affects in the described black bars.

Using one panel with a D1 mini ESP8266 showing a picture, all LEDs running.

Sorry to open yet another topic regarding this issue, but I have no clue anymore.
I'd appreciate any help, or hint to solve this.

Thanks in advanced

**Comment by s3rdl** [comment]
OK. I found it.
In my case the E-line is on PIN8 instead of PIN4, so I soldered back PIN4 and cut the line to PIN8 and routed it to GPIO24.
Now everything works.
Cheers.

**Comment by Sploitastik** [comment]
I can confirm this works for DCHY-P2-644-1515-VP panels!
