### ISSUE TITLE
128x64 panel using ICN2038S chip

### ISSUE THREAD

**Issue by WernerFettke** [hzeller/rpi-rgb-led-matrix#1296]
Hi, 

I purchased some 128x64 panels from led-card.com (https://www.led-card.com/p2-fullcolor-led-indoor-module.html), the panels are P2 and from what I can see they using the following chip ICN2038S.

I've tried setting the panels up with the Adafruit hat, as well as the ElectroDragon Pi shields version 1 and 2, the best I can get it to display is as per the image below, it almost looks like the mapping is out, I've tried various mapping options, row address types, etc etc, but still no luck.

The panels have no E or D pins (I've also tried setting up the various cards as if there was an E pin), but no luck.

![9f302e7f-8f53-4dba-96a5-8d9b8b03808a](https://user-images.githubusercontent.com/53822201/116290911-46d08080-a794-11eb-9897-e9f5857b5d5d.jpg)

I also chatted to the guys at led-card.com and they suggest rotating the imageby 45 degrees, but this option is not available under the rotation options, the value needs to be in 90 degree increments.

The attached image is what I get when I run the wiring directly off the Pi, I used the Smiley Face wiring option, without using the E or D pins as there are no E / D pins on the Hub 75 connector.

![IMG_1711](https://user-images.githubusercontent.com/53822201/116291488-edb51c80-a794-11eb-9bf6-473c09792647.jpg)

Any assistance would really be appreciated as I've purchased 12 of these panels and would really like to get them working on my Pi.  (I've tried on a Pi2 / 3 and 4), also tried using different builds as suggested.

I'm not sure if it will help, but when running the rotating square demo, I get the video below:

https://user-images.githubusercontent.com/53822201/116292239-c579ed80-a795-11eb-86c4-9360d2a82b61.mov

Many Thanks in advance.

Regards

Werner

**Comment by hzeller** [comment]
Did you go through all `--led-multiplexing` and `--led-row-addr-type` settings ? The fact that there are only three address pins A, B, C indicates that these options are very relevant. Maybe they have a special mapping ?
Did you get a datasheet for the Matrix and their pixel-mapping, maybe you need to add a new one.

**Comment by WernerFettke** [comment]
Many thanks for getting back to me so quickly ! I have asked the guys at led-card.com for datasheet, but unfortunately they have not responded as yet. All I can see under the specifications of the panels is the following, which I know does not help much.


Pixel pitch | 2mm
-- | --
Module Size | 256X128 mm
Model Pixel | 128X64Pixels
lattice density | 250000 dots/square meter
Pixel form | 1R1G1B SMD1515
Best viewing distance | 1m~20 m
Max power consumption | 2000W/square meter
Ave power consumption | 600W/square meter
Max power per module | 25W
warranty | 1 year
Drive mode( Optional) | Constant current 1/32scan
Control system | DVI card+Full color control card
Pixel type | Real pixel
refresh frequency | >=400HZ
Horizontal View Angel | > 110 degree
Working Environment | Temp:-20Celsius degree-+60Celsius degreeHumidity : 10%-90%
Working voltage | DC 5V
Lifetime | >=100000 hours
Gray scale | 12 bit/ 1 color
Color display | manual adjust
Brightness | >600 cd/square meter
Blind spot rate | <0.00001
Waterproof Class | IP43
Software | Support window series system

In terms of trying the multiplexing and row address options, I have been through them all, even going as far as setting the row address option and then trying each multiplexing options, then trying the next row address and going through the multiplexing options again, until I have been through all the row address and multiplexing options.

As soon as I hear back from them I will send you an updated.

Thanks for the great software, and for being so pro-active when it comes to resolving issies.

Regards

Werner

**Comment by WernerFettke** [comment]
Just to provide some more feedback, if I try the various -led-row-addr-type options, The panel only displays something when I use options 0 and 4.
Option 0 gives the output as per my original post, and option 4 results in the attached image.
![IMG_1713](https://user-images.githubusercontent.com/53822201/116298811-34a71000-a79d-11eb-984c-61765afaa799.jpg)

**Comment by WernerFettke** [comment]
Hi, Apparently they don't really have anything, however I've been able to find the following, apparently the panels I'm using are using the ICN2038S chip, I could only find the following:

![1877788707131379c0b4685d9d36495818b9ece6](https://user-images.githubusercontent.com/53822201/116304486-e85ece80-a7a2-11eb-9a5f-f89736b9b2d7.jpg)
![cec3296139fc919643eb3a242fd86a556dab9ba6](https://user-images.githubusercontent.com/53822201/116304491-e98ffb80-a7a2-11eb-94d6-6a04386a3dcb.jpg)

I was also able to find some info on the non S version ICN2038, however I believe the S version is the replacement for the non S version:

![c5b24363efc67422e4232ce8ad259077f5ac15cf](https://user-images.githubusercontent.com/53822201/116304636-147a4f80-a7a3-11eb-9ca1-83ce0cc06a52.jpg)
![cd0db0a8de589c54497caa175c54314e5cdbb1e4](https://user-images.githubusercontent.com/53822201/116304643-15ab7c80-a7a3-11eb-9bbb-59dcd360f0fc.jpg)

**Comment by WernerFettke** [comment]
Hi, After playing with the ABC pins and the settings, I was able to get the panel to work as intended, the settings I used was: sudo ./demo -D 1 runtext.ppm --led-no-hardware-pulse  --led-slowdown-gpio=2 --led-rows=64 --led-cols=128 --led-multiplexing=0 --led-row-addr-type=3

Thank you for your help and awesome software !!!

**Comment by Overboard-code** [comment]
I have the 128x64 1/32 panel and an ElectroDragon  Can you tell me what you did on the driver board?  Did you jumper 4 or 8 to E?

**Comment by WernerFettke** [comment]
Hi,

For the panels I was using I did't need to do anything on the ElectroDragon card,  my issue was resolved by using row-address-type option 3.... have you tried running the demo with the same options I used in the previous post where I got it to work ?

**Comment by Overboard-code** [comment]
My board does have an E pin  
![image](https://user-images.githubusercontent.com/53097137/165563183-f84ea20b-ae3c-4877-852a-12ebf99b9530.png)

So I had to use the jumpers  Different.  no standards yet  It's still early days I guess
