### ISSUE TITLE
Not really an issue, need help

### ISSUE THREAD

**Issue by spannt** [hzeller/rpi-rgb-led-matrix#1304]
Hello, not sure where else to put this. I'm building a stargate, using 32X32 panels, a raspberry pi 3 b+ with a led matrix hat. For some reason no matter how much I try, I can't get the audio to sync with the video. I'm using video-viewer. If anyone has any suggestions, that would be awesome. I'm using dietpi 64bit version. 

![PXL_20210511_215518646](https://user-images.githubusercontent.com/42418198/117889888-4818a780-b282-11eb-915d-058510c5709d.jpg)
![PXL_20210511_215525384](https://user-images.githubusercontent.com/42418198/117889988-654d7600-b282-11eb-8bed-3228eb61cb4e.jpg)
![IMG_20210511_180049](https://user-images.githubusercontent.com/42418198/117890338-fcb2c900-b282-11eb-9aed-fe9660181052.jpg)

**Comment by spannt** [comment]
Yeah I know that, the sound is separate in a mp3. The sound is dead on to the video when played on another raspberry pi. Could it be the video isn't running as fast as it should? Thats the issue I'm having.

**Comment by spannt** [comment]
Here's how I'm running the video

$MATRIXDIR/video-viewer -F --led-scan-mode=1 --led-rows=32 --led-cols=32 --led-chain=31 --led-gpio-mapping=adafruit-hat-pwm --led-slowdown-gpio=3 --led-multiplexing=1 ./abydos_dial.mp4>/dev/null 2>&1 &

**Comment by hzeller** [comment]
yes, the video decoding uses a lot of resources and might play frames back slower than they should, in prticular if the video needs to be scaled down a lot by the video-viewer.

For minimum overhead at runtime, I suggest to create a stream-file from the video, and then play that back with the image- viewer. The output file will be huge, but it means there is no overhead at runtme except reading it from disk. There is something in the [examples section of the video-viewer](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/utils#examples-2) that shows how to do that.

**Comment by hzeller** [comment]
One thing I noticed: your chain of 31 panels is somewhat long and you might experience lower refresh rate than pleasent.
(I'd consider running three parallel chains and map the video accordingly)

If you see low refresh rate (using `--led-show-refresh`), you can play around with `--led-pwm-bits` and `--led-pwm-dither-bits` to see if you can optimize a bit the refresh.

**Comment by spannt** [comment]
Thank you, I will start with the images and go from there. BTW I'm a member of the The Repilica Prop Forum, I have been sharing your github with everyone. They keep asking for me to share my code, so I send them here.  :)

**Comment by spannt** [comment]
I got it, :) Thanks for your help

[https://youtu.be/fGfVdd5qGIg]

**Comment by hzeller** [comment]
Yay! Have fun with your Stargate :star: :door:
