### ISSUE TITLE
MATRIX SCRAMBLES AFTER 3 SECONDS

### ISSUE THREAD

**Issue by perrySeoul** [hzeller/rpi-rgb-led-matrix#1339]
Good morning. Thank you, I really appreciate your work. I have been using the rgb-led-matrix clock for about two years. The SD card became corrupted after updating raspbian last week. I did not write down or save the settings I was using for the clock. I am using a Raspberry Pi Zero W. I put raspbian on a new SD card, downloaded the rgb-led-matrix. When I run the clock example or any example the matrix is stable for 3 seconds then scrambles.

This is the settings I am using now.

`sudo ./clock -f ../fonts/7x13.bdf --led-chain=2 --led-rgb-sequence=BGR -d "%A" -d "%H:%M:%S"'

Here are pictures of the back of the matrix, and the issue.
![IMG_0348](https://user-images.githubusercontent.com/90905032/133867386-f3e02a93-02f4-4ffe-8f05-5199ab819cd2.jpg)

![IMG_0355 copy](https://user-images.githubusercontent.com/90905032/133867402-92f80e64-3d7c-4780-a68e-3b64a7a20c02.jpg)

![IMG_0349 copy](https://user-images.githubusercontent.com/90905032/133867410-f85b9968-c260-467e-bced-986587570147.jpg)

![IMG_0350](https://user-images.githubusercontent.com/90905032/133867424-3caea590-3069-4255-ae82-e775816c1dca.jpg)

![IMG_0353](https://user-images.githubusercontent.com/90905032/133867435-d6d3e8a3-5ad0-4db7-99c0-a076d954e4cb.jpg)

Thank you for your help.
Perry

**Comment by hzeller** [comment]
Did you check the [troubleshooting section](https://github.com/hzeller/rpi-rgb-led-matrix#troubleshooting) ?
Sudden scrambling is consitent with what one would observe if one-wire protocol is enabled.

**Comment by perrySeoul** [comment]
Thank you for your help. I’m sorry for wasting your time with this issue.
This is why I hesitated to ask for help. I knew this was something I should
have resolved on my own. I did many google searches, I did read the
troubleshooting guide.

I missed the solution to resolve the issue.

Thank you for your time and help.

Perry

**Comment by hzeller** [comment]
cool, sounds like it is working now. Have fun with your LED panel.
