### ISSUE TITLE
image viewer

### ISSUE THREAD

**Issue by Dan7766** [hzeller/rpi-rgb-led-matrix#134]
Tried to install the image viewer after the main program and get the below:

NOTE: selecting "libgraphicsmagick++1-dev" instead of the virtual package libgraphicsmagick++-dev"

After this it will not compile the image viewer as i think its looking for files that are not there due to the above Note: downloading the wrong package..

Well done on this by the way, just learning this rite now but having fun....Thanks.

**Comment by hzeller** [comment]
This is a normal message of the package manager, so that should be fine.

What is the compilation error you get ?

**Comment by Dan7766** [comment]
If its normal perhaps im doing something wrong..
Attached a pic of the files that were not found during libgraphicsmagick install. the rest installed ok. And when trying to compile.
Im sure you will probably laugh at what vie missed or done wrong but hopefully you can see why it wont work for me.

![led image viewer](https://cloud.githubusercontent.com/assets/19208663/15075408/8ff6d624-13e7-11e6-9c95-9756065bba49.jpg)

**Comment by hzeller** [comment]
It looks like it didn't find packages on the debian servers. Did you do 
  `sudo apt-get update`
before the `sudo apt-get install` ?

**Comment by Dan7766** [comment]
Thank you very much, that worked and the image viewer compiled and works like a charm..
Im guessing i should have known to do that....Looks like i have a lot of reading to do..

Thanks again

**Comment by hzeller** [comment]
Don't worry, I have now updated the README to include that line in the description so it is harder to forget.
