### ISSUE TITLE
Horizontal white/pink lines displayed across matrix instead of text

### ISSUE THREAD

**Issue by naveenfarey** [hzeller/rpi-rgb-led-matrix#1345]
Hardware

- Raspberry Pi Zero WH
- Adafruit Bonnet
- 1 x Adafruit RGB LED Matrix (64x32 2.5mm Pitch)

OS
- Raspbian Lite

ISSUE
- Horizontal white/pink lines are displayed across the screen instead of hello world text when using runtext.py. Issue also occurs with other examples.  Command I'm running is,

sudo python3 runtext.py --led-gpio-mapping=adafruit-hat --led-cols=64  --led-rows=32
Same issue occurs with python2.7

dtparam=audio=on has been altered to dtparam=audio=off in /boot/config.txt

![photo](https://user-images.githubusercontent.com/44567342/136980360-587c858a-fdfe-4042-a395-398428c19e14.jpeg)

**Comment by naveenfarey** [comment]
Apologies for the delayed response @hzeller. Yes, I did try both options ('FM6126A', 'FM6127').

I also did away with using Python and tried the examples-api-use/demo however it's displaying the same results. Is it possible that the led matrix board is faulty?
`
sudo examples-api-use/demo -D0 --led-gpio-mapping=adafruit-hat --led-rows=32 --led-cols=64 --led-row-addr-type=0`

**Comment by naveenfarey** [comment]
Photo of current setup @hzeller 

![led_matrix](https://user-images.githubusercontent.com/44567342/141956255-a2d0c2ab-fd83-486c-8e76-8ea3af46fda8.jpg)

![pi_zero](https://user-images.githubusercontent.com/44567342/141956277-99db5d11-e960-4bf6-9b92-0e33032e359c.jpg)

**Comment by anandrajgupta** [comment]
is your bonnet GPIOs soldered properly?

**Comment by naveenfarey** [comment]
@anandrajgupta sorry I'm confused why would it need to be soldered? I'm using the adafruit hat/bonnet and the pi has pre soldered pins, the hat/bonnet just slips on.

**Comment by naveenfarey** [comment]
I'm assuming you're referring to the step where it mentions,

> If you're using a 64x64 RGB matrix and either a Bonnet or a Rev C HAT, use your soldering iron to melt a blob of solder on the bottom solder jumper so the middle pad is 'shorted' to 8. (This is compatible with 64x64 matrices in the Adafruit store. For 64x64 matrices from other sources, you might need to use 16 instead, check the datasheet.)

@anandrajgupta would that need to be done even though I don't have a 64x64 display matrix? or it needs to be done because I have a bonnet?

**Comment by naveenfarey** [comment]
Issue due to faulty adafruit bonnet
