### ISSUE TITLE
I have a problem with running the linux terminal command for exiting the image-display process (with python) for a 64x64 LED-Matrix

### ISSUE THREAD

**Issue by real-oskar** [hzeller/rpi-rgb-led-matrix#1347]
I have wrote a python programm that displays a picture on my rgb matrix (64x64). That works completly fine, but if i want to exit/close the task (displaying the image) with a terminal command, it wont work. I dont know if its something with Python or a bug  with the command/process.

```
...
os.system("sudo /home/pi/rpi-rgb-led-matrix/utils/led-image-viewer --led-rows=64 --led-cols=64 coverWeb.png") #worked fine
os.system("kill -SIGINT") #or os.system("exit(-1)") and so on didnt work either
...
```

**Comment by hzeller** [comment]
I wouldn't do a system() call and then do a harsh kill.
If you want to show an image from Python, why not do it directly from there using the Python API ?

**Comment by OskarGER05** [comment]
I didn't know how to fill in the right python Version in the Installation command.😅
Thats why i tried to avoid the api...

**Comment by OskarGER05** [comment]
`make build-python PYTHON=$(which python3)`
how do i put my python version in here?

**Comment by OskarGER05** [comment]
Can you tell me please? I am new to Linux...

**Comment by hzeller** [comment]
the commandline will execute `which python3` and will find where it is, so this should work as expected if you have python3 installed.

**Comment by OskarGER05** [comment]
Thank you very much👍😅
