### ISSUE TITLE
No rule to make target 'led-image-viewer'

### ISSUE THREAD

**Issue by luchadorman** [hzeller/rpi-rgb-led-matrix#135]
When I run this,
` sudo apt-get update &&
 sudo apt-get install libgraphicsmagick++-dev libwebp-dev &&
 make led-image-viewer`

It ends with make: ***No rule to make target 'led-image-viewer'. Stop.

I'm realllllllly trying to get this running to put on my graduation cap tomorrow and would love some help!

**Comment by hzeller** [comment]
In which directory are you in ?
You compile this at the toplevel directory,

**Comment by luchadorman** [comment]
I am in ~/rpi-rgb-led-matrix-master

Is that correct?

**Comment by hzeller** [comment]
Yes, that is perfect. If it doesn't work, then you have the wrong repository :)
Make sure to get things here: https://github.com/hzeller/rpi-rgb-led-matrix

**Comment by luchadorman** [comment]
Is there anyway for me to check the repository? I was following that documentation during installation.

**Comment by luchadorman** [comment]
I am very low level on skills for a project such as this.

**Comment by hzeller** [comment]
If you checked out this repository, you're good and it should work. If you got the repository from somewhere else (e.g. Adafruit), it won't work.

**Comment by luchadorman** [comment]
I did follow [this adafruit tutorial](https://learn.adafruit.com/adafruit-rgb-matrix-plus-real-time-clock-hat-for-raspberry-pi/driving-matrices) 

Do you know what I would need to do differently to run this one instead?

**Comment by hzeller** [comment]
Do not follow the Adafruit tutorial. They point to their fork of this tutorial, which is ancient and does not have the image viewer for instance.

You are filing issues for this repository, so you should as well check out this library:
https://github.com/hzeller/rpi-rgb-led-matrix.git

Then follow the README. If you have an Adafruit HAT, look in the section "If you have an Adafruit HAT" what to edit in the Makefile to make it work with that hardware.

**Comment by luchadorman** [comment]
Ok! I will do that and check the adafruit hat section.

Thank you for your help, I will comment here if I have anymore issues!

**Comment by luchadorman** [comment]
I just cleared out my previous files and redid it with your repository and still received the same message. I've attached a picture below.

![img_3326](https://cloud.githubusercontent.com/assets/17821814/15090487/31d3d9ba-13de-11e6-8874-df3e51285563.JPG)

**Comment by luchadorman** [comment]
I ran `wget https://github.com/hzeller/rpi-rgb-led-matrix/archive/master.zip`

then `unzip master.zip`

then `cd rpi-rgb-led-matrix-master/ && make`

then tried a couple of demos that ran,

and finally ` sudo apt-get update &&
 sudo apt-get install libgraphicsmagick++-dev libwebp-dev &&
 make led-image-viewer`

**Comment by luchadorman** [comment]
I've resolved this problem, i cloned the git instead of using wget and everything now works.

**Comment by Skid32** [comment]
Can you help me wen i run a demo i just get this 
![screenshot 7](https://cloud.githubusercontent.com/assets/21077832/17730765/a5da7738-646a-11e6-9a67-0a6136225524.png)

**Comment by vic-cortes** [comment]
Hello, I've been doing the steps that you already mention. I clone the most recent repository from [GitHub](https://github.com/hzeller/rpi-rgb-led-matrix) and followed the steps. However I still have the message `***No rule to make target 'led-image-viewer'. Stop.` 
Is there another way to install the led-image-viewer? 

Thanks in advance

**Comment by hzeller** [comment]
Are you in the `utils/` directory ?

**Comment by vic-cortes** [comment]
I was in the `rpi-rgb-led-matrix/` directory, but I changed it to `utils/` directory and everything worked fine. Thank a lot.

**Comment by 8bignic8** [comment]
> unzip master.zip

That worked thanks :)!
