### ISSUE TITLE
How to compile multiplex-mappers.cc

### ISSUE THREAD

**Issue by FrancoRosa** [hzeller/rpi-rgb-led-matrix#1351]
Hello!
I am trying to create a new multiplex option, to match a 16x16 P10 RGB.
Please send me the command required to compile. I already tried this:
`/rpi-rgb-led-matrix/lib $ gcc multiplex-mappers.cc -o multiplex-mappers.o`
Then I got a long error that starts with
```
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/8/../../../arm-linux-gnueabihf/crt1.o: in function `_start':
(.text+0x34): undefined reference to `main'
...
```

**Comment by cPabz** [comment]
@FrancoRosa to recompile the new multiplex option you need to rebuild the library.
In the root folder of this repo.

### For Python 2
```
sudo apt-get update && sudo apt-get install python2.7-dev python-pillow -y
make build-python
sudo make install-python 
```

### For Python 3
```
sudo apt-get update && sudo apt-get install python3-dev python3-pillow -y
make build-python PYTHON=$(command -v python3)
sudo make install-python PYTHON=$(command -v python3) 
```


 [Reference](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/bindings/python#building)

**Comment by FrancoRosa** [comment]
@cPabz Thank you for your reply. I was using an old version of the repo, that's why I did not find the instructions any information about this.
Just to help someone else, I paste the link below.
https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/bindings/python
