### ISSUE TITLE
Coral Dev Board

### ISSUE THREAD

**Issue by SotirisKar** [hzeller/rpi-rgb-led-matrix#1386]
More of a question than an issue.
I run the code with raspberry pi 4 and it worked great. Now I wanna try this with a coral dev board that I own.
I'm getting an error "non-existent Revision: Could not determine Pi model". Is it possible for me to modify the code and run with coral? Would this be a pain?

**Comment by hzeller** [comment]
Any other board than the Raspberry Pi will not have a compatible GPIO, so you have to read the datasheet of the SoC of your board, and re-implement essentially all of gpio.cc, which right now is very specific to the Raspberry Pi.

Depending on how much you usually do datasheet reading and low-level implement things, this process can be somewhere between _fun_ and _pain_ :)
