### ISSUE TITLE
My Clock is Wrong

### ISSUE THREAD

**Issue by SnowyDevelop** [hzeller/rpi-rgb-led-matrix#1393]
I have tried the clock sample but it shows summer time not winter time ,how can i change it?

**Comment by hzeller** [comment]
The clock sample just outputs the system time.
If you type `date` on your command line, does it show the correct time ?
You can fix timezone issues using `sudo raspi-config`

**Comment by SnowyDevelop** [comment]
Thank you for your quick answer. It works now!
