### ISSUE TITLE
When Running Command text-example show unreadable Text 

### ISSUE THREAD

**Issue by b4m84** [hzeller/rpi-rgb-led-matrix#1396]
Dear @hzeller , i have question when running this command :
#sudo ./text-example -f ../fonts/5x8.bdf  --led-no-hardware-pulse

in P10 display show unreadable Text like =
![foto](https://user-images.githubusercontent.com/45556901/151102944-b9f0067e-b254-4b30-a00d-9e7c688059f6.jpg)

and this is my wiring configuration =
![Capture](https://user-images.githubusercontent.com/45556901/151103056-676a10de-6b9e-4fa2-b942-09392fad3a60.PNG)

Maybe any solution for this ? i have change font , it's same show unreadable text.

Note: When i run demo =
#sudo ./demo -D0 --led-no-hardware-pulse  
it's running and show like this =
![fotodemo](https://user-images.githubusercontent.com/45556901/151103381-bbc8e9be-89c2-48a1-91b0-925a20e4d4aa.jpg)

Thanks
Bambang

**Comment by hzeller** [comment]
Looks like you need to choose a [`--led-multiplexing`](https://github.com/hzeller/rpi-rgb-led-matrix#types-of-displays) that fits your display.

**Comment by b4m84** [comment]
Thanks @hzeller it's work when i set --led-multiplexing=8
sudo ./text-example -f ../fonts/6x13.bdf  --led-no-hardware-pulse --led-multiplexing=8
![fototest](https://user-images.githubusercontent.com/45556901/151105036-16940f31-8ce8-48ae-bb6a-113ad0702964.jpg)

thanks for your support
