### ISSUE TITLE
Raspberry Pi 2

### ISSUE THREAD

**Issue by helgevh** [hzeller/rpi-rgb-led-matrix#14]
Hi,
I have successfully used your program on my Raspberry Pi Model B. 
Now I have tried to use it on my new Raspberry Pi 2 Model B. I am able to compile the code but the RGB Matrix is staying black when I run the program. I guess the new hardware of the Rapsberry Pi 2 needs some code fixing. Do you have some hints, where to start?

Regards 
Helge

**Comment by hzeller** [comment]
On 14 February 2015 at 08:14, helgevh <notifications@github.com> wrote:

> Hi,
> I have successfully used your program on my Raspberry Pi Model B.
> Now I have tried to use it on my new Raspberry Pi 2 Model B. I am able to
> compile the code but the RGB Matrix is staying black when I run the
> program. I guess the new hardware of the Rapsberry Pi 2 needs some code
> fixing. Do you have some hints, where to start?
>

I don't have a Raspberry Pi 2 yet, so I don't know what is wrong; as soon
as mine arrives, I'll dig into it. Until then - if you find out something,
let me know :)

-h

**Comment by hzeller** [comment]
On 14 February 2015 at 08:36, Henner Zeller <h.zeller@acm.org> wrote:
> On 14 February 2015 at 08:14, helgevh <notifications@github.com> wrote:
>>
>> Hi,
>> I have successfully used your program on my Raspberry Pi Model B.
>> Now I have tried to use it on my new Raspberry Pi 2 Model B. I am able to
>> compile the code but the RGB Matrix is staying black when I run the program.
>> I guess the new hardware of the Rapsberry Pi 2 needs some code fixing. Do
>> you have some hints, where to start?
>
>
> I don't have a Raspberry Pi 2 yet, so I don't know what is wrong; as soon as
> mine arrives, I'll dig into it. Until then - if you find out something, let
> me know :)

Looks like adafruit cloned my repository and they did something to
make it work with the Pi 2
https://github.com/adafruit/rpi-rgb-led-matrix/commits/master

-h

>
> -h
>

**Comment by helgevh** [comment]
Thanks for the hint. I've tested the adafruit version but I am not able to build it. I think tomorrow I will have a closer look at it.

Helge

**Comment by perl5577** [comment]
need python-2.7-dev and other package for image
Not work for me :(

**Comment by helgevh** [comment]
Same here. Matrix is staying black.

**Comment by hzeller** [comment]
On 15 February 2015 at 10:25, helgevh <notifications@github.com> wrote:

> Same here. Matrix is staying black.
>
Interesting. I'll try to get a new Raspberry Pi to see...

**Comment by perl5577** [comment]
work with HAT adafruit :(
https://www.youtube.com/watch?v=EvcBqRSVU7U

probleme converter 3.3V > 5V ?

**Comment by hzeller** [comment]
On 15 February 2015 at 16:01, perl5577 <notifications@github.com> wrote:

> work with HAT adafruit :(
> https://www.youtube.com/watch?v=EvcBqRSVU7U
>
> probleme converter 3.3V > 5V ?
>

no, the RGB panels work with 3.3V signal level; the 5V converter is just
there to give an extra margin.

**Comment by perl5577** [comment]
why work with HAT adafruit ? 
Only difference between direct connexion and HAT is converter level .

**Comment by hzeller** [comment]
>
> why work with HAT adafruit ?
> Only difference between direct connexion and HAT is converter level .
>

Well, don't ask me, it is Adafruits product :)
I guess it makes it simpler to get things running right away with an easy
plug-and-play board.

They might have changed as well some GPIO pins to work with their hat, so
you might want to look out for that as well when you use that code.

**Comment by hzeller** [comment]
RPi 2 is on the way, I'll look at it as soon as I get it.

**Comment by helgevh** [comment]
They have added a "#ifdef ADAFRUIT_RGBMATRIX_HAT" section in several files, so you can select between Adafruit hat and the old pinout. The changes aren't mentioned in the readme file.

changed files
lib directrory:
framebuffer.cc
framebuffer-internal.h
Makefile
root directory:
Makefile
makefile

**Comment by perl5577** [comment]
More simple 
in ./lib/Makefile  comment line DEFINES+=-DADAFRUIT_RGBMATRIX_HAT
in ./Makefile remove -DADAFRUIT_RGBMATRIX_HAT  for cible .o

**Comment by helgevh** [comment]
Is it working for you? I have already removed both entries and recompiled the files. Now I see some flickering on the RGB matrix. But the test images are still not working.

**Comment by perl5577** [comment]
is it  working for me,  I use both  32x64 . ( -L )
I have reduce flickering  , I load 100% one core .

http://monero.crypto-pool.fr/videos/IMG_1146.MOV
http://monero.crypto-pool.fr/videos/IMG_1148.MOV

**Comment by helgevh** [comment]
Nice work. Especially the flames are looking great. Are you using pixel-pusher? https://github.com/hzeller/rpi-matrix-pixelpusher
