### ISSUE TITLE
Outdoor waterproof cabinet/frame?

### ISSUE THREAD

**Issue by halwebguy** [hzeller/rpi-rgb-led-matrix#140]
This is a slightly off-topic question, in that it's not the electronics or software I'm asking about.  I have 6 of the outdoor/waterproof panels below:

![2016-05-15 10 54 59](https://cloud.githubusercontent.com/assets/2458237/15274901/fb60fa3e-1a8b-11e6-968e-d66d852e74c5.jpg)

I can't figure out how to safely encase the 6x1 array for outdoor use.  Do I need to get sheet metal and bend it / drill holes accordingly?  Seems like a bigger job for me than the software I wrote (and will contribute back) and the wiring!

Any ideas?  

Thanks,
Hal

**Comment by hzeller** [comment]
I suspect this is something specific you need to figure out for this particular type of LED panel (the manufacturer probably has some recommended set-up ?)

Possibly it is enough to have a metal frame that is just the crossings of bars to have proper inside/outside separation.

Please update this if you find some solution, but for now I'll close this bug (just going through the list of still relevant bugs).
