### ISSUE TITLE
Several rows not turning on 32x32

### ISSUE THREAD

**Issue by Niek09** [hzeller/rpi-rgb-led-matrix#1425]
So I"m trying to connect a 32x32 HUB75B (don't know what the B indicates) to an electrodragon bonnet. This bonnet already came with the fixed version, as there was a problem with it in February.

The raspberry pi is running DietPi with sound turned off. My command line input is:
sudo ./demo --led-cols=32 --led-rows=32 --led-slowdown-gpio=4 -D 4 

The LED Matrix is 32x32 with 1:16 scan rate. At least that is what the supplier said.

So basically what happens is that there are 8 rows on, then 4 rows off, 4 rows slightly on and that repeats. I already tried some multiplexing options, but this didn't work. Does anyone know a solution for this?

So I basically found out it gets send to the same place with the pixel mover:
https://user-images.githubusercontent.com/103577163/163388961-798f23e2-8217-49a1-ae6f-db8f13e31356.mp4

![PXL_20220413_101724186 MP](https://user-images.githubusercontent.com/103577163/163176411-dcb9bfbc-907d-4936-8ce4-7489b258f2e5.jpg)
![PXL_20220413_101806089](https://user-images.githubusercontent.com/103577163/163176420-68de930c-703b-45b0-a6e2-4c8724bff8d0.jpg)

Please don't mind the cables, there will be 6 panels parallel, but they all have this problem.

**Comment by ZoyshM** [comment]
Have you tried to change the --led-row-addr-type flag?

**Comment by Niek09** [comment]
The problem was the electrodragon bonnet. I got a new one and the issue was resolved.
