### ISSUE TITLE
64x64 RGB LED-Matrix not working properly (Split Image)

### ISSUE THREAD

**Issue by jan424242** [hzeller/rpi-rgb-led-matrix#1435]
Hey, I have a Project for School and my 64x64 RGG LED-Matrix is not working properly (image)
We are using a Adafruit HAT with RTC

The command is: sudo ./demo -D 0 --led-rows=64 --led-cols=64 --led-gpio-mapping=adafruit-hat
Does anyone have similar problems? I need help asap, thanks :D

![image](https://user-images.githubusercontent.com/106308151/170456982-492e778d-f17a-4bc1-8fd4-06263964e1e7.png)
![20220526_111210](https://user-images.githubusercontent.com/106308151/170457526-ea01b664-f1c2-4410-af84-3087683ee625.jpg)

**Comment by hzeller** [comment]
Did you do the necessary hardware mod on the HAT that is described in the README? https://github.com/hzeller/rpi-rgb-led-matrix#64x64-with-e-line-on-adafruit-hatbonnet

**Comment by jan424242** [comment]
Yes, I have a newer version of the "HAT" than described in the "Readme" file. With this HAT, you have to put a dot between E and 8 next to the HUB75 connector. (you can see it on the Image)

**Comment by kaerka** [comment]
I have the same panels, and same hat, and am having the same issue.  I've nearly exhausted all options - it seems like maybe either the code or the hat just can't handle ABCDE/64x64 panels, or perhaps an issue with the 1/32 scan rate?

Mine shows a nearly identical set of black bars across it, along with flicker - but only when on the 64x64 smaller LED panels.

I have:
- tested the panels with other setups, including the matrixportal m4 and pimoroni i75 - the panels work and don't have this issue.  (Those, however, don't have enough memory to run what I want, however.)
- tested dropping from 8 panels to 4, then to 2, then to 1 - same issue even on a single panel.  
- swapped from older adafruit hat to newer version with the E pin mod, but without the audio pin mod (yet)
- reflowed all of my solder, checked continuity and solder points.
- swapped to a dedicated power supply (a 300w x 5v - 60a psu)
- retested the same hat/pi4/code with 2 x 16x32 older panels (no issues there)
- tested with different IDC cables - no change

My setup is (at the moment, it changes as I test different things):
- pi4, 8gb (no OC, disabled 1-wire, enabled I2C and SPI), wifi connected
- Raspbian 10 (buster)
- Commit ID: f88355e46faafb9de7f1e59dd258ab36c7e7b097

Anyway - on my setup, I'm not sure where to go with further troubleshooting - but am willing to help test and post photos/videos of results.

**Comment by kaerka** [comment]
Here are a few photos of mine, and also my command line for those.  Ignore the panel on the right and below, those have different code running on them.

$ sudo ./demo -D 0 -m 100 --led-gpio-mapping=adafruit-hat --led-slowdown-gpio=4 --led-brightness=50 --led-chain=4 --led-rows=64 --led-cols=64 --led-multiplexing=0 --led-pixel-mapper="U-mapper:1" --led-row-addr-type=0

![IMG_2524](https://user-images.githubusercontent.com/1696060/185811765-0324ddcc-aeb4-47e9-870c-a4e60e23e894.jpg)

$ sudo ./demo -D 9 -m 150 --led-gpio-mapping=adafruit-hat --led-slowdown-gpio=4 --led-brightness=50 --led-chain=4 --led-rows=64 --led-cols=64 --led-multiplexing=0 --led-pixel-mapper="U-mapper:1" --led-row-addr-type=0
![IMG_2523](https://user-images.githubusercontent.com/1696060/185811798-2a9b0a18-98ab-4420-bdf2-deef9aa28487.jpg)

**Comment by kaerka** [comment]
I reflowed my E pin behind the connector, and then also did the jumper for the pins #4 to #18; and then recompiled for that.  The reflow of my E pin seems to have been the fix for me - now it's working excellently!  I just love your code - thanks and awesome!
![IMG_2535](https://user-images.githubusercontent.com/1696060/185814567-b4db1105-f0e0-4307-9467-06b00f77c9cf.jpg)
![IMG_2533](https://user-images.githubusercontent.com/1696060/185814584-eaaca36c-10fa-4c66-9fee-46641ae1446b.jpg)

**Comment by ignaciogaticarojas** [comment]
Hi ! @kaerka could you please share images of your hardware mod on the hat?

Thanks!

**Comment by kaerka** [comment]
Sure - I had to reflow the solder on the DE pin behind the hub75 connector several times before it worked correctly, and then I added the jumper between pins 4 and 18, and recompiled for the quality option.

I'm still doing other things to improve the rate that I can push it, but it's pretty stable now.

This is the pins you have to short for a 64x64 panel to get those lines to go away, assuming that is the issue.

![image](https://user-images.githubusercontent.com/1696060/188527908-0e40792e-89dc-4200-b575-41fc3038e5b5.jpeg)

These are the pins for higher quality display output (it mainly reduces a little bit of flicker and artifacts).  My jumper wire is atrocious, but it is working.
![image](https://user-images.githubusercontent.com/1696060/188527990-11715ef1-18a2-45dc-8dbb-9ae5d27bdb31.jpeg)

And here is a picture of the overall 8 x 64x64 panel setup.  I also upgraded my power supply, though at a different step.  The 5v x 15a PSU I had was not enough, once I got it all working.
Ignore the couple extra 32x32 panels, they're on separate controllers.
Front:
![image](https://user-images.githubusercontent.com/1696060/188528417-7fb63d06-e1ca-44e6-ba12-46ce6258cdad.jpeg)

Back:
![image](https://user-images.githubusercontent.com/1696060/188528482-e2108777-81cf-4c4d-af5a-3c7fba094012.jpeg)

Better macro focus of the overall hat on a pi4:
![image](https://user-images.githubusercontent.com/1696060/188528523-d4d246c5-89ee-446f-8db6-e1a56187a2be.jpeg)

**Comment by ignaciogaticarojas** [comment]
Hi @kaerka that is awesome, can you please explain me what do you mean by "reflow" the DE pin, does this mean removing it?
Thanks a lot and congrats on such a nice display

**Comment by kaerka** [comment]
Thanks!  Most of the thanks really goes to the developers of the rgb-matrix code and adafruit - most of this is beyond me, and I'm using it as a fast-paced python learning experience.

Reflowing the solder is to basically re-heat it, such that it resettles and provides a better connection.  I'd have thought that my first attempt was good - it looked fine... but it didn't work.  It took a total of 4 times re-flowing to get it 100% correct, I think it was overlapping onto the 3rd contact a bit, and then later I could see a little line between the two contacts which were supposed to be jumped.  The little line between them indicated that they weren't really, even if the solder looked connected.

I did figure out that when trying to get it to re-flow - be patient, give it a a few min for the iron to heat up correctly and don't try to rush it.  And then, also be careful that you're only putting heat on the solder and pads, and not on the board itself.  

Last - in my case, this wasn't the only solder joint that I figured out that I'd done poorly.  I reflowed many of the gpio pins as well.  They don't look great, but all are showing good continuity on a multi-tester, so seem fine now.

**Comment by combs** [comment]
nice! Probably makes sense to close this issue out then?

**Comment by davemaster** [comment]
> Hi ! @kaerka could you please share images of your hardware mod on the hat?
> 
> Thanks!

I had a Electrodragon adapter, and was very easy to mod it, because is a build-in connector paths to do it. Pin E to pin 8, or pin E to pin 4. 

![ELECTRODRAGON-RGB-ACTIVE-RPI-ADAPTER MOD 0](https://github.com/hzeller/rpi-rgb-led-matrix/assets/1075807/374d872e-efa1-4261-b15d-6110f38db982)

In my case, I welded a 3-pin header for quick set or unset option

![ELECTRODRAGON-RGB-ACTIVE-RPI-ADAPTER MOD 1](https://github.com/hzeller/rpi-rgb-led-matrix/assets/1075807/9611d488-7138-4e82-9cc8-0cc9f25da31d)

Here, the final result, in picture:

![ELECTRODRAGON-RGB-ACTIVE-RPI-ADAPTER MOD 2](https://github.com/hzeller/rpi-rgb-led-matrix/assets/1075807/f023578c-1802-4c23-a9fd-5a4576375a6f)

Here a [video of my adventure today](https://www.youtube.com/watch?v=sBRi85QoGuY)... mission, acomplished.
