### ISSUE TITLE
Code not running in 64-bit Raspbian OS, any Solution?

### ISSUE THREAD

**Issue by anandrajgupta** [hzeller/rpi-rgb-led-matrix#1461]
Hello Mr. @hzeller,

Thank you.

I was wondering if this code can be run on a Raspberry Pi 3 having a 64-bit Raspbian OS?
Directly running fails, any possible solution will be appreciated.

Thank you once again...

**Comment by anandrajgupta** [comment]
As shown in the following picture, the compilation fails
![image](https://user-images.githubusercontent.com/19954301/189339098-d5e8ac21-43d4-4c93-aa4e-7acded5e01de.png)

**Comment by anandrajgupta** [comment]
Also, if i try to run the pre-compiled code then it says "no such file or directory" (using sudo ./executableFile)

Note: I am trying to run it in 64-bit OS in a hope to get better frame-rate!

**Comment by davemaster** [comment]
Greetings,
First, link or exact version of your 64-bit OS ?

**Comment by hzeller** [comment]
It looks like you maybe copied over the version from a 32bit compile, then of course the object files don't work there.

First, `make clean`, then make again.

**Comment by anandrajgupta** [comment]
Thank you very much, i will try...

**Comment by anandrajgupta** [comment]
Thank you so much.
`make clean` worked!
Now it is able to run on 64-bit OS also, but no improvement in frame rate with it!
Thank you again.
