### ISSUE TITLE
Split Image with HUB75E tried all options of hat/bonnets/electrodragon/active adapter

### ISSUE THREAD

**Issue by ignaciogaticarojas** [hzeller/rpi-rgb-led-matrix#1462]
Hi im having a matrix displaying image with a blan link in the middle because of hub75 E-Line.

Im curious why since i tried all options with the active adapter that this repository suggest @hzeller
Also  tried adafruit options and electrodragon. Doing the modifications and conections asked for each them.

 And i still have that blank line with all of them. Is there anyone in the community that could help with some advice? Thanks a lot 

Im running it with 

--led-cols=64 --led-slowdown-gpio=2 --led-gpio-mapping=adafruit-hat --led-brightness=85 --led-panel-type=FM6126A 

![image](https://user-images.githubusercontent.com/99695299/189450218-95f43166-fddf-4863-89c4-1fe76508bf8e.jpeg)
![image](https://user-images.githubusercontent.com/99695299/189450240-7ab366b8-d8ec-44fa-9bbb-a81a7dacf7cd.jpeg)

![image](https://user-images.githubusercontent.com/99695299/189452583-97f12940-d6ad-4cca-9879-b6bc9d717208.jpeg)

![298754090_1777039889305932_2307719804239271376_n](https://user-images.githubusercontent.com/99695299/189453048-bf0042c7-e617-4e4b-aa2d-ce0bbcae9a6b.jpg)
![304725628_1097318011211252_2972815615827972831_n](https://user-images.githubusercontent.com/99695299/189453050-7c180f9f-7a2f-4cde-b623-5a21c2569236.jpg)

**Comment by hzeller** [comment]
looks like you have 40 pixel rows. Did you add `--led-rows=40` ?

**Comment by ignaciogaticarojas** [comment]
That worked! @hzeller thank you again!

**Comment by hzeller** [comment]
yay!
