### ISSUE TITLE
i cant figure out how the c++ api works

### ISSUE THREAD

**Issue by hannescam** [hzeller/rpi-rgb-led-matrix#1466]
please help with printing text from the c++ api

**Comment by hzeller** [comment]
Did you go through the examples ? What part is problematic ?

**Comment by hannescam** [comment]
yes i figured it out and  made something work based of the clock example compile on the pi with g++ clock.txt -o test.o -Wall -O3 -g -Wextra -Wno-unused-parameter -I. -c && g++ test.o -o test -L ../lib/ -l rgbmatrix -lrt -lm -lpthread:
[clock.txt](https://github.com/hzeller/rpi-rgb-led-matrix/files/9631891/clock.txt)
