### ISSUE TITLE
explain the c++ code

### ISSUE THREAD

**Issue by bagumondigi** [hzeller/rpi-rgb-led-matrix#147]
I'm trying to see how SetPixel and Fill function work in framebuffer.cc. However, there are some points I can not understand.
In function Fill i don't know what these code use for:
```c++
    for (int row = 0; row < double_rows_; ++row) {
      IoBits *row_data = ValueAt(row, 0, b);
      for (int col = 0; col < columns_; ++col) {
        (row_data++)->raw = plane_bits.raw;
      }
    }
```
and why in SetPixel function don't have them, instead
```c++
bits += columns_;
```
Why we increase 'bits' ? 
thanks for reading

**Comment by hzeller** [comment]
Not sure what your particular question is. Here are some thoughts that might help you

  * Incrementing a pointer in C means shifting to the next element it points to
  * In Fill(), you want to set all pixels.
  * Each bitplane for a particular pixel is columns_ apart
