### ISSUE TITLE
Word Wrap Auto

### ISSUE THREAD

**Issue by Holychris56** [hzeller/rpi-rgb-led-matrix#1485]
Hello! Is there a way to do auto word wrap on an LED screen, instead of trying to find out what is the best font/size/offsets?

I am using the python library.

Thanks!

**Comment by anandrajgupta** [comment]
the drawText function returns how much pixels are used in writing the word

**Comment by Holychris56** [comment]
How does that allow me to have an auto wrap? I'm running a 64x32 led matrix. I would like to write "hello world" and when it get cuts off, it writes the following world to the next line.

**Comment by anandrajgupta** [comment]
you will have to make your logic to achieve that, using the feature mentioned above

**Comment by Holychris56** [comment]
ahhh ok. I thought there was already code written to do this. Didn't want to re-invent the wheel haha!
