### ISSUE TITLE
green turns into blue

### ISSUE THREAD

**Issue by Holychris56** [hzeller/rpi-rgb-led-matrix#1486]
Hello, I am using the adafruit hat with my raspberry pi 3B. I connected the hat, however, when I'm trying to use green color, it turns it to blue. Not sure why

**Comment by anandrajgupta** [comment]
--led-rgb-sequence

**Comment by Holychris56** [comment]
what command option do I set for that?

**Comment by Holychris56** [comment]
--led-rgb-sequence ??

**Comment by hzeller** [comment]
Is there a problem in the documentation of this flag ?

**Comment by anandrajgupta** [comment]
> what command option do I set for that?

"RBG"
