### ISSUE TITLE
`IsRaspberryPi2()` robustness

### ISSUE THREAD

**Issue by jroelofs** [hzeller/rpi-rgb-led-matrix#149]
I noticed a comment in `IsRaspberryPi2()`:

```
static bool IsRaspberryPi2() {
  // TODO: there must be a better, more robust way. Can we ask the processor ?
```

There _is_ a more robust way: Inspect the `Revision` field in `/proc/cpuinfo`. Docs on the meaning of that field are here: http://elinux.org/RPi_HardwareHistory

**Comment by hzeller** [comment]
Thanks, I'll take that into consideration in the next update (looks like it needs some thorough testing with various Pi's in the field).
