### ISSUE TITLE
Help for correct wiring

### ISSUE THREAD

**Issue by Schopfkuss** [hzeller/rpi-rgb-led-matrix#1495]
EDIT:

Seems like (though double/triple testing) my first wiring was faulty.
I just rewired everything and now it works.

Important lesson for me:
- Although Pin 12 is labeld "GND", wire it like it would be "D" (=> GPIO 22).
- Also PIN 15 indeed is OE.

------------
I got myself one of these 64x64 Matrix: https://seengreat.com/productinfo/865747.html.
I connect it directly to the GPIOs of a raspberry 3b.
The HUB75 connector seems to be different than shown in the wiring diagram section of the readme.md:

[board](https://imgur.com/a/naWvYVF)

Please notice there is no D and the two [R2]-connections, though the wiring diagram on the sellers page is assuming there is a "D":
[https://seengreat.com/rgbmatrixp3_64x64#2.2](https://seengreat.com/rgbmatrixp3_64x64#2.2)

Wiring it like 
- my E AS GND
- my 2nd GND As D
- my 2nd [R2] AS OE

will work for half of my screen (where 1/4 is black, 2/4 works, 3/4 is black, 4/4 works)

Also:

If you look into the images you'll notice the connections are doubled, once pre soldered with connectors and once plain. Do they expect me to solder connectors on the 2nd half of the board by myself? Or did I just used the wrong wiring diagram?

**Comment by combs** [comment]
glad you got it working! Probably makes sense to close this issue out then?
