### ISSUE TITLE
Undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by Solaerts** [hzeller/rpi-rgb-led-matrix#1535]
Hey, so I try to code RGB matrix panel of 64x32 with a Raspberry PI 2, I installed all files needed and when I want to lunch the code runtext.py with Thonny I get this error message: 
ImportError: /home/pi/rpi-rgb-led-matrix/bindings/python/rgbmatrix/core.so: undefined symbol: _Py_ZeroStruct
I really don't know what it means and when I try to run a code i made, Thonny say that he could'nt find the rgbmatrix package. I really don't know what I do wrong if someone can help me it would be great.

**Comment by hzeller** [comment]
Did you compile and install the Python according to the [docs](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/bindings/python) ?

**Comment by Solaerts** [comment]
Yeah i think so, I was just about to restant the process from the begining.

**Comment by Solaerts** [comment]
Yeah i think so, I was just about to restant the process from the begining.

**Comment by combs** [comment]
nice! Probably makes sense to close this issue out then?
