### ISSUE TITLE
Run text rotation

### ISSUE THREAD

**Issue by Solaerts** [hzeller/rpi-rgb-led-matrix#1537]
I have 2 matrix of 64x32 and I have connected them in parallel to have one matrix of 64x64. I was scrolling a text from right to left but I want to to scroll from up to down. How do I do that pls ? I am using a raspberry pi 2 and I am coding in python with Thonny.

**Comment by anandrajgupta** [comment]
"VerticalDrawText" function

https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/led-matrix-c.cc

**Comment by hzeller** [comment]
Ah, good point, I forgot that `DrawVerticalText()` was available.
