### ISSUE TITLE
Replaced faulty panel and new issue now

### ISSUE THREAD

**Issue by bierbarrel** [hzeller/rpi-rgb-led-matrix#1538]
I had a yellow block on one of my 4 panels. Troubleshot down to bad panel. Where ever I moved the panel in the array the yellow block stayed on the new panel. I ordered a new panel. It uses the same chipset. On the new panel I get green when Im supposed to have blue. Is there a way to adjust the panel to get it to color match the other panels? Or do I need to get another board?

thx

**Comment by anandrajgupta** [comment]
--led-rgb-sequence

**Comment by ledvinap** [comment]
@anandrajgupta : That applies to all panels, but only one has different RGB mapping in this case.

@bierbarrel : You can place new panel last and swap RGB wires ...

**Comment by bierbarrel** [comment]
are you talking about swapping wires in the ribbon cable?

**Comment by bierbarrel** [comment]
![PXL_20230426_123555837](https://user-images.githubusercontent.com/75229947/234577478-2d9eb30e-421e-4d9c-9be4-256c1f0fefa2.jpg)

I have the screen separator lines set to red but the bad panel shows blue

**Comment by ledvinap** [comment]
@bierbarrel : Some options are:
- separate and swap wires before crimping PFL
- cut RGB wires and solder them in correct order 
- use (a lot of) premade jumper wires (hole-pin to display or pin-pin between 2 cables)

It is possible to do it in software (https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/framebuffer.cc#L337), but it is non-trivial to do in in clean way and `Framebuffer::Fill()` won't work correctly.

**Comment by bierbarrel** [comment]
Thx petr.. I'll give that a shot. I can make up a ribbon cable. I will just have to figure out the RGB lines.

**Comment by bierbarrel** [comment]
Up and running....thx guys!
![PXL_20230429_145226995](https://user-images.githubusercontent.com/75229947/235309585-c2bd6472-d7c4-4ca3-9fb2-90eac6725bb7.jpg)
![PXL_20230429_145233560](https://user-images.githubusercontent.com/75229947/235309588-ea983987-adca-4062-80d8-8e9c9747a87e.jpg)

**Comment by bierbarrel** [comment]
Ill make a ribbon cable later...

**Comment by combs** [comment]
nice! Probably makes sense to close this issue out then?
