### ISSUE TITLE
CIE1931 profile

### ISSUE THREAD

**Issue by HollyAssasin** [hzeller/rpi-rgb-led-matrix#1540]
Hello, could someone please point me the file/section where the RGB is getting converted to the CIE1931 profile.
Much appreciated.

**Comment by hzeller** [comment]
https://github.com/hzeller/rpi-rgb-led-matrix/blob/6e53ad187113ac2856c314dd563ce17c08bfb240/lib/framebuffer.cc#L625-L644 maps the incoming color using a look-up table that is pre-computed here
https://github.com/hzeller/rpi-rgb-led-matrix/blob/6e53ad187113ac2856c314dd563ce17c08bfb240/lib/framebuffer.cc#L591-L609

**Comment by HollyAssasin** [comment]
Thank you for such a quick answer!
