### ISSUE TITLE
Trouble seeing correctly simple-square sample on 96x96 display 

### ISSUE THREAD

**Issue by ignaciogaticarojas** [hzeller/rpi-rgb-led-matrix#1548]
Hello ,

Im having trouble finding a way to make simple-square sample work well on a 96x96 screen display made out two 96x48 matrix 
 16208 chipset panels using the U-Mapper. Running it with : sudo python3 simple-square.py --led-cols=96 --led-slowdown-gpio=3 --led-gpio-mapping=adafruit-hat  --led-rows=48 --led-chain=2 --led-pixel-mapper=U-mapper  --led-parallel=1 --led-brightness=70

I tried different mappers and all giving me abstract shapes.

Please let me know what would be an option to fix this 

here is an image of the output.

![photo_2023-05-21 22 16 55](https://github.com/hzeller/rpi-rgb-led-matrix/assets/99695299/22dac75f-1017-40b7-b775-6b1efb6b64d9)

**Comment by hzeller** [comment]
did you also go through all `--led-row-addr-type` ?

**Comment by ignaciogaticarojas** [comment]
--led-row-addr-type=3 made it thank you again @hzeller
