### ISSUE TITLE
Why the led is turned off when i connect to UGreen soundcard

### ISSUE THREAD

**Issue by ghost** [hzeller/rpi-rgb-led-matrix#1549]
I am using led to send audio... accepting it in another side via solar cell
why when connect Ugreen sound card to the led .. the lighten for a moment and then closes fast

if you don't the answer send the aux of the UGREN soundcard please

Thanks and regards

**Comment by hzeller** [comment]
Make sure to disable [all Raspberry Pi hardware sounds](https://github.com/hzeller/rpi-rgb-led-matrix#bad-interaction-with-sound) to not interfere with the GPIO outputs of the LED output. External USB sound cards should still work.
