### ISSUE TITLE
Matrix having issues displaying 

### ISSUE THREAD

**Issue by np2446** [hzeller/rpi-rgb-led-matrix#1553]
Hello, I am having issue with my matrix. It seems to fire up errant pixels and can't clearly display things. When I run a test script that just turns the screen red, green, then blue it does it fine. But when any motion is introduced, it messes stuff up. I've attached  videos [here](https://imgur.com/a/OAIcYyh) of the issue.

**Comment by hzeller** [comment]
what GPIO slowdown did you use ?

**Comment by np2446** [comment]
I wasn't using a GPIO slowdown. Didn't know that was necessary. Will implement one and let you know results.

**Comment by np2446** [comment]
That fixed it! set gpis-slowdown to 2. Thank you very much!
