### ISSUE TITLE
Another 80x40 P4 indoor acting weird

### ISSUE THREAD

**Issue by lukee7** [hzeller/rpi-rgb-led-matrix#1573]
Hi!

I think I found another P4 80x40 that is somehow acting weird.

After fiddling around with all the ideas in #986 and #49 and #1499 I finally gave up.
Main problem is: I don't know know anything about the panel. Got it bundled with some NovaStar receiver card that (to my understanding) would need a NovaStar processor and/or some Windows-only Software.

I did

```
./text-example --led-gpio-mapping=adafruit-hat --led-cols=80  --led-rows=40 -f ../fonts/6x10.bdf
1 2 3 4 5 6
```

![IMG_20230723_231135045_HDR](https://github.com/hzeller/rpi-rgb-led-matrix/assets/2269341/d1f81bc0-6930-47be-802f-ce39339dd0c0)

Adding `a e i o u` in 2nd and 3rd (2nd line appeared mixed into 123456 text; 3rd line appeared below the numbers) line
![IMG_20230723_231114190_HDR](https://github.com/hzeller/rpi-rgb-led-matrix/assets/2269341/951f32be-4723-4b9f-b517-d668333ca377)

Also the demo 0:
`./demo --led-gpio-mapping=adafruit-hat --led-cols=80  --led-rows=40 -D 0
`
![IMG_20230723_231316367_HDR](https://github.com/hzeller/rpi-rgb-led-matrix/assets/2269341/d9bc0716-b91d-4f93-93f0-0853eddc207c)

I appreciate any help - really clueless how to solve the puzzle ^^

thanks,
lukas

**Comment by anandrajgupta** [comment]
led-multiplexing?

**Comment by lukee7** [comment]
> led-multiplexing?

Tried 0-18, but it didn't get better 🤷‍♂️

**Comment by lukee7** [comment]
It's supposed to be this module: https://www.qzxrled.com/outdoor-3d-p4-led-module-led-video-wall

But there's no useful information on their website. I asked for a datasheet right now.

**Comment by lukee7** [comment]
![IMG_20230728_115503062~2](https://github.com/hzeller/rpi-rgb-led-matrix/assets/2269341/9e22a290-dd7c-4aa6-ad06-33a4c0bde81b)

There's a lot of those on the board. Reads "DP51250" (211307 in second line).

**Comment by lukee7** [comment]
Well...I gave up. The "pixel mover" example did not help in understanding what's going on.
I ordered a 64x32 panel at Amazon and everything just works out-of-the-box
