### ISSUE TITLE
64x64 ABCDE - black horizontal bar problem

### ISSUE THREAD

**Issue by olablt** [hzeller/rpi-rgb-led-matrix#1580]
Testing chain with 3 LED panels:

`sudo ./clock -f ../fonts/10x20.bdf -d "%H:%M:%S" --led-brightness 50 --led-cols 64 --led-rows 64 --led-chain 3 -y 25 -x 50 --led-slowdown-gpio=4`

Result:

![Pasted image 20230817154928](https://github.com/hzeller/rpi-rgb-led-matrix/assets/674574/8fc02d76-66ac-47c3-9c1a-16ff84cc518c)

I am using passive adapter https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/adapter/passive-3 and modified as per instructions:

https://github.com/hzeller/rpi-rgb-led-matrix/issues/360#issuecomment-321104348
![Pasted image 20230816151500](https://github.com/hzeller/rpi-rgb-led-matrix/assets/674574/1dd2dba4-3258-4c2f-9737-bf4ec4a63ca2)

Back of my panels:

![Pasted image 20230816155458](https://github.com/hzeller/rpi-rgb-led-matrix/assets/674574/e9f434a6-30ca-4d42-98f4-5b56dcb5cf72)

What could be the problem?

**Comment by Feuerflamme** [comment]
i have the same problem

**Comment by olablt** [comment]
soldered active board, problem gone
