### ISSUE TITLE
trouble accessing the Makefile

### ISSUE THREAD

**Issue by jonathankrier** [hzeller/rpi-rgb-led-matrix#160]
Hi, 
   Noob question here, but i'm having issues accessing the Makefile to address some flickering on my LED Display.  I've already soldered the connections, but want to access the Makefile to remove the #.

let me walk you through the pathology of my problem, as i suspect i'm not approaching this problem correctly:

- accessing the root terminal inputting the following command: 
$ cd rpi-rgb-led-matrix-master
$ ./lib/Makefile
bash: ./lib/Makefile: Permission denied

I've tried to change permissions using chmod by inputting the following command while in the "rpi-rgb-led-matrix-master" directory.  using the following command: 
$ chmod 744 Makefile
$ ./lib/Makefile
bash: ./lib/Makefile: Permission denied

I'm quite confused and have spent a few hours trying to trouble shoot online to figure out how to fix this problem.  any help?

Hardware: 
Rpi 3
adafruit rgb matrix hat

Distro: 
Raspbian-lite

Thank you!

**Comment by hzeller** [comment]
If you type `./lib/Makefile`, you try to execute the file.
Which is not what you want. You want to edit it, so use an editor, such as `nano ./lib/Makefile`.

**Comment by jonathankrier** [comment]
Thank you!
