### ISSUE TITLE
Led-image-viewer wont open any image format

### ISSUE THREAD

**Issue by Hiendsen** [hzeller/rpi-rgb-led-matrix#1606]
Installed everything step-by-step and the demos work perfectly fine but when I try to use `sudo ./led-image-viewer` it outputs the following. I've tried multiple image formats with a different image every time. 
```
Size: 64x32. Hardware gpio mapping: regular
Loading 1 files...
Opening file: No such file or directory
home/(insert user here)/Downloads/45908.jpg skipped: Unable to open (Magick: Unable to open file (home/(insert user here)/Downloads/45908.jgp) reported by magick/blob.c:3061 (OpenBlob))
No image could be loaded.
```
I have not the slightest idea what the issue might actually be. Three extra things to point out: Using the regular GPIO mapping (jump cables) on an old Raspberry Pi Model B Rev 2.0, controlling the Pi via RealVNC Viewer and video-viewer also refused to open the file (tested it because I saw someone else have a similar problem with a .gif file and the image viewer refused to work while video viewer opened the file)

**Comment by MOVE1904** [comment]
> home/(insert user here)/Downloads/45908.jpg skipped: Unable to open (Magick: Unable to open file (home/(insert user here)/Downloads/45908.jgp) reported by magick/blob.c:3061 (OpenBlob))
> No image could be loaded.

Did You see the "(insert user here)"?

**Comment by Hiendsen** [comment]
> > home/(insert user here)/Downloads/45908.jpg skipped: Unable to open (Magick: Unable to open file (home/(insert user here)/Downloads/45908.jgp) reported by magick/blob.c:3061 (OpenBlob))
> > No image could be loaded.
> 
> Did You see the "(insert user here)"?

Apologies please ignore everything I said as I am incomprehensibly stupid. It didn't even have to do with root access to images which was the issue, it was literally that I was missing a "/" to the very beginning of the path to the files I was trying to open. But I'll just say this for anyone else if they're having problems, aside from checking your directory is perfect also try this post https://github.com/hzeller/rpi-rgb-led-matrix/issues/1458 which mentions --led-no-drop-privs and chmod a+r myimagefile.png which change the access of files because the led-image-viewer drops any privileges upon initializing
