### ISSUE TITLE
Overflow of uint8 in demo-main.cc

### ISSUE THREAD

**Issue by jpasqua** [hzeller/rpi-rgb-led-matrix#161]
In the drawBarRow method of the VolumeBars class, loop variable x can overflow for wide panel configurations. The y parameter to the method can overflow for tall configurations. I tested with a width of 256 pixels.

    for (uint8_t x=bar*barWidth_; x<(bar+1)*barWidth_; ++x) {

Changes these to int (or uint16_t) fixes the problem for widths and heights that are attainable with this HW.

**Comment by hzeller** [comment]
Thanks, fixed!
