### ISSUE TITLE
Can't use other devices in parallel

### ISSUE THREAD

**Issue by SThiviyan** [hzeller/rpi-rgb-led-matrix#1610]
Hey there, 

I want to build an alarm clock with the matrix display, but want it to be controlled by a rotary encoder. I programmed a library that would be able to receive inputs from that rotary encoder. But when I use that library in tandem with the rpi-rgb-led-matrix library, the rotary encode doesn't work anymore because the gpio pins (26, 21, 20), don't return any values.

I'm using a waveshare 64x32 panel with the standard pin configuration. Not using any hats or anything.

**Comment by hzeller** [comment]
The RPI led matrix takes over control over the GPIO, but it provides a way for you to read inputs; check out the example at 

https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/examples-api-use/input-example.cc
