### ISSUE TITLE
Issue with Displaying Pixel Propperly

### ISSUE THREAD

**Issue by glappa** [hzeller/rpi-rgb-led-matrix#1624]
Im using this Matrix Pannel with the panel type 'S3800467M05334 : 
https://de.aliexpress.com/item/1005005720691780.html?spm=a2g0o.order_list.order_list_main.28.42f65c5flfYDDz&gatewayAdapt=glo2deu
on a Raspberry Pi 4, with a Adafruit Bonnet: 
https://www.amazon.de/dp/B07DNBLXV2?psc=1&ref=ppx_yo2ov_dt_b_product_details

https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/f2fbff09-71d6-41e7-b118-e8b23512d851

https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/f3882031-486a-433a-8517-2a0c90344f5a

https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/99adc201-6f3e-49b3-bfd3-e4d9856552e9

Command used on the Raspberry PI 4
"sudo ./demo -D 7 --led-rows=64 --led-cols=64 --led-gpio-mapping=adafruit-hat --led-slowdown-gpio=5"

**Comment by glappa** [comment]
i also tried it without the "--led-panel-type=S3800467M05334" Parameter and the Matrix still just shows a few Pixels instead of the Demo

**Comment by Nam0** [comment]
Could you send a picture of the back of your LED Panel?

**Comment by davemaster** [comment]
Greetings, 

You wanna be helped? First, take many pictures to your panel, specially to: HUB-75 LED INPUT, code of the RGB PANEL.
Second, use the command :

Command used on the Raspberry PI 4
"sudo ./demo -D 7 --led-rows=64 --led-cols=64 --led-gpio-mapping=adafruit-hat --led-slowdown-gpio=5"

and record a video of the result. 


Best regards

**Comment by glappa** [comment]
Hello @davemaster.
thank you for your reply!
here are some picture of the back of my matrix!
![IMG-20240321-WA0003](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/332b6458-ea35-4a4d-b43e-f1e32e0b434f)
![IMG-20240321-WA0004](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/8e3fa8c5-e7c3-4110-b98b-33405fe41b2a)
![IMG-20240321-WA0005](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/98e3a159-7d20-469c-a802-2ade1f5ed94f)
![IMG-20240321-WA0006](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/3e31af79-1398-4574-a63c-d0cb9919c614)
![IMG-20240321-WA0007](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/40c943dc-28e0-4ef2-a51e-ccd1e338b701)
![IMG-20240321-WA0008](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/7e0a69eb-a4d8-4bb5-a557-f90fc5e3880d)
![IMG-20240321-WA0009](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/6679e4e9-3d11-456a-bfac-2dbb077ac2bb)

as well as a video with the command you provided!

https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/ec809e73-d953-4486-85d2-882faef5d0d8


https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/edf3e228-e31c-4a25-ba5b-3875730ac5c7

hope this can help!

**Comment by Nam0** [comment]
Hi Glappa,
Thanks for all of the pictures and videos, it looks like it might be an issue with how your E Line is set up, I was running a similar setup, slightly different board but same Hub 75 configuration. Could you try and solder a jumper from Pin 4 (OE) to Pin 18 on the RPI Bonnet board and run it again? If you want to double check before soldering it you should be able to steadily hold a wire on the two contacts and it should get reflected instantly on the board.

**Comment by glappa** [comment]
Hello @Nam0,
Did you mean it like this?
![IMG-20240324-WA0005](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/dee4e80a-5196-4861-9e4a-4a531333ba55)

![IMG-20240324-WA0006](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/53e2325c-556d-4539-8614-876dba1a4fb4)

![IMG-20240324-WA0007](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/2b2815b5-d967-4add-8ae7-5c82766fdcec)

Same Result:
https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/fb277d97-d044-4857-a07c-1e36440d6b20

**Comment by Nam0** [comment]
Gotcha, and just to double check you have the E and 8 pins on the underside of the bonnet board bridged correct?

**Comment by glappa** [comment]
this is the backside of the Bonnet:
![WhatsApp Bild 2024-03-24 um 19 09 59_045dc8f7](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/1f387825-251a-4581-87d1-67c9fbce8c5f)

![WhatsApp Bild 2024-03-24 um 19 09 59_ab5f25a9](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/c995ba3e-a07b-44f0-bcc0-24b120e6f3ac)

![WhatsApp Bild 2024-03-24 um 19 09 59_bda917a1](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/aab5cfd0-6f9f-474b-94c9-d5da0325a02a)

**Comment by Nam0** [comment]
Ah I see you don't have the E line pin soldered up, you will need to go thru and bridge the connector from E to 8 for these two pins
![image](https://github.com/hzeller/rpi-rgb-led-matrix/assets/17018473/2224e968-b756-49ba-8400-8260971651c1)

**Comment by glappa** [comment]
like this @Nam0 ?
![WhatsApp Bild 2024-03-24 um 19 23 02_f726c726](https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/0dd71a06-ad4c-4209-ae9a-3ee4dd01f373)

**Comment by glappa** [comment]
Thank you very much @Nam0 IT WORKS!
https://github.com/hzeller/rpi-rgb-led-matrix/assets/119673858/3f06e4a6-fef0-4d0d-955b-ebf8f63dc98a

**Comment by glappa** [comment]
marked as closed
