### ISSUE TITLE
display on P3 32x64

### ISSUE THREAD

**Issue by lucas-pouchot** [hzeller/rpi-rgb-led-matrix#163]
Hi, can we use your soft to display something on led panel P3 32*64 ?

running : `./led-matrix -D 1 -r 32 -c 2  runtext.ppm`
I got : 
![img_20160628_100749 1](https://cloud.githubusercontent.com/assets/6933800/16408640/00898ff2-3d1a-11e6-8a00-ec2f6cbd7861.jpg)

and with : 
`(while :; do date +%T ; sleep 0.2 ; done) | sudo ./text-example -f fonts/8x13B.bdf -y8 -c2 -C0,0,255`

I got : 
![img_20160628_100700 1](https://cloud.githubusercontent.com/assets/6933800/16408691/382fd43e-3d1a-11e6-8acd-bdaf6c8f4b02.jpg)

Lines 8 to 15 are displayed on the lines 0 to 7 and lines 24 to 31 are displayed on the lines 16 to 23.

I'm using a Raspberry Pi 3 and the new wiring schema.

Thanks.

**Comment by currentlysober** [comment]
I think you need to write transformer. Or try at first with different row=X values..?

**Comment by bagumondigi** [comment]
I used P5 32*64 and it worked fine ! Try this
`sudo ./led-matrix -r 32 -c 2 -D 1 runtext.ppm`
instead
`./led-matrix -D 1 -r 32 -c 2 runtext.ppm`

**Comment by hzeller** [comment]
This looks like your `D` address line does not make it through. Can you check that connection ?

**Comment by lucas-pouchot** [comment]
Oh, thanks, I used my wiring for the 16x32 panel and I forgot the `D`
Shame on me :D
