### ISSUE TITLE
Lines goes on raspberry pi 2 Jessie

### ISSUE THREAD

**Issue by atiroir** [hzeller/rpi-rgb-led-matrix#164]
Hi
I'v already make work the matrix before 

but today i don't know what is wrong (I have check many times the wires)

I made a video to show you [https://youtu.be/OI8Il_5AFuk](https://youtu.be/OI8Il_5AFuk
)
Someone else could help me ?

Basile

**Comment by hzeller** [comment]
is this a new Raspbian install? This could be due to the sound modules they activate by default recently. Can you remove these (described in the Troubleshooting section) and report back?

**Comment by atiroir** [comment]
Thank you for your quick answer. I'v tried the instructions  described in the roubleshooting section it 'i sworking now. Thank you gain
