### ISSUE TITLE
Chain 4 RGB LED Matrix (64x32) for display

### ISSUE THREAD

**Issue by mandarp22** [hzeller/rpi-rgb-led-matrix#1642]
Hello Everyone,
I am trying to chain 4 RGB LED Matrix displays in attached format to create a display of 128x32.
I want to display big text or numbers on display as part of my project , so I need to use these 4 displays to make one giant display.
I have Adafruit HAT and Raspberry PI4

I tried to use several samplebase.py options but not able to figure out on how to make them chain to use as single display.

Can you please help?
![intended_display_use](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/aa9c8440-01dd-42ac-abce-1982b3a75260)
![led_display_config_back](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/8cf02573-1319-4140-8f9d-4e5b03083880)
![led_display_config_front](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/f48b2084-5473-47f7-8a82-73a20cfcc416)

**Comment by davemaster** [comment]
![321049821-f48b2084-5473-47f7-8a82-73a20cfcc416](https://github.com/hzeller/rpi-rgb-led-matrix/assets/1075807/5991ccbc-0593-4b49-8fcf-7b6d63fe75e4)
Greetings. This is the way I get worked, but with 3x2 arrangement. U must use the U-MAPPER, I don't know if that feature is still used in the latest version of rpi-rgb-led-matrix, but You must have Rpi 3-Rpi4 for this.

./demo --led-chain=4 --led-pixel-mapper="U-mapper"

in this link, an example -> [example u-mapper](https://github.com/hzeller/rpi-rgb-led-matrix/tree/a3eea997a9254b83ab2de97ae80d83588f696387/examples-api-use#remapping-coordinates)

**Comment by mandarp22** [comment]
Thank you Dave. That worked perfectly.
Thank you for your help and response

**Comment by davemaster** [comment]
You're Welcome, I'm glad your problem is gone... God bless You

**Comment by mandarp22** [comment]
![IMG_6040](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/52c0d554-0f67-4e39-b3a2-5fd1669acec1)

Thanks Again @davemaster

**Comment by mandarp22** [comment]
I got new outdoor LED's and I am using same setting but I am getting output as below

./demo -D0 --led-slowdown-gpio=4 --led-chain=4 --led-pixel-mapper="U-mapper"

https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/10310a4a-be0f-4b49-b0b2-02a02adff16c

**Comment by mandarp22** [comment]
I am using same setup 4 -   64 x32 P5 LED Outdoor panels
![led-back1](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/379f4ec7-2db3-4900-be84-32b1e3a43c5d)
![led-back2](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/cf7b5b3a-0885-4c04-b053-f2e56587019a)
![Led_number1](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/c794ccfa-5583-4455-89f3-e3699b237b7d)
![Led_number2](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/eb976647-7bf1-45cf-b23d-0d3d98a73072)

**Comment by mandarp22** [comment]
Old Indoor LEDs were fine with code, as picture above I was able to display score correctly.

However with same setup for these LEDs. I am getting below.

I also tried setup changing row=64 and cols=128 , but still same

![Uploading score_new_led1.jpg…]()

**Comment by mandarp22** [comment]
![score_new_led2](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/b2222b2f-7678-4602-8895-42b0f1c23250)

**Comment by mandarp22** [comment]
![score_new_led1](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166573021/a7163ec3-de00-42c9-a384-edf8e9dc3e41)

**Comment by mandarp22** [comment]
Thank you for help in advance

**Comment by mandarp22** [comment]
actually i was able to fix issue by setting --led-multiplexing =1

**Comment by davemaster** [comment]
> actually i was able to fix issue by setting --led-multiplexing =1

Share Your success with a picture, better with a Video. Best regards
