### ISSUE TITLE
QiangLi P6 48x24 working not correct

### ISSUE THREAD

**Issue by Rpsl** [hzeller/rpi-rgb-led-matrix#1649]
Hello. 

I have a QiangLi P6 Outdoor matrix, 48x24 diodes. I connected it according to the instructions in [wiring.md](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/wiring.md), but it doesn't work properly.

The label on the matrix says it is ‘sm16208sj + rul5158c’, also on the matrix I see not typical HUB75 pins.

- When I try to run with `./demo -D 4 --led-gpio-mapping=regular`, every odd line lights up. 
- When I try to run with `./pixel-mover --led-gpio-mapping=regular`, I see a couple of pixels with (0,0) and zero pixels with (0,1).

I don't understand if this is a wiring problem or a multiplexer problem. If it is a multiplexer problem, how can I determine the correct positioning?

Can anyone help me with this?

![IMG_4230](https://github.com/hzeller/rpi-rgb-led-matrix/assets/265634/39a6c874-46b1-43e8-87f3-2c614dfbde78)
![IMG_4248](https://github.com/hzeller/rpi-rgb-led-matrix/assets/265634/be6b4485-5dc0-4136-a2ba-e43cf4aec813)
![IMG_4236](https://github.com/hzeller/rpi-rgb-led-matrix/assets/265634/adf91985-1325-48a0-8b04-5f1262f79d0e)

<img width="584" alt="screenshot-2024-04-23-20-58-d078229d32" src="https://github.com/hzeller/rpi-rgb-led-matrix/assets/265634/ffd83741-a7aa-4654-88eb-61af9e1e69f0">

![IMG_4247](https://github.com/hzeller/rpi-rgb-led-matrix/assets/265634/f9ac27ea-2d16-4296-afc3-62a502da96e2)

**Comment by davemaster** [comment]
Greetings,

You forgotten to use in your command these:

--led-rows=<rows>        : Panel rows. Typically 8, 16, 32 or 64. (Default: 32).
--led-cols=<cols>        : Panel columns. Typically 32 or 64. (Default: 32).
--led-multiplexing         : panel scan, test from 1 to 14 (i think)

[view this](https://github.com/hzeller/rpi-rgb-led-matrix?tab=readme-ov-file#types-of-displays)

**Comment by davemaster** [comment]
> @davemaster thanks. i used all possible combination of `--led-multiplexing` and `--led-row-addr-type`. also i used `rows` and `cols` options.
> 
> i not wrote that in issue but i test it.

what exactly you wrote?

**Comment by Rpsl** [comment]
> what exactly you wrote?

```
./demo -D 4 --led-gpio-mapping=regular --led-cols=48 --led-rows=24 
   --led-multiplexing=0..18 # i try all options
   --led-row-addr-type=0..4 # i try all options
```

**Comment by Rpsl** [comment]
> And, a PICTURE at least of the value of multiplexing that better works ?

Values of `--led-multiplexing` don't give any changes. At some multiplexing values every second line is filled in the matrix, at others it does not lighting matrix.

this is how it looks: 
![IMG_4247](https://github.com/hzeller/rpi-rgb-led-matrix/assets/265634/7a08fe67-474c-4d21-95a9-1e0c0d709ca9)

ps.
- It's work only with `--led-row-addr-type=0`, with other options matrix not lighting.
- I check it with matrix on another chip and my setup work correct.
- I check it with several other matrix (QiangLi P6 `sm16208sj + rul5158c`) and that problem repeated.

**Comment by Rpsl** [comment]
just bought new panels with another chipset and they work perfect
