### ISSUE TITLE
Is it possible to rotate the whole canvas of the matrix?

### ISSUE THREAD

**Issue by KayLerch** [hzeller/rpi-rgb-led-matrix#165]
Hi there,

due to some physical limitations I have to place my LED panel like it is rotated by 90 degrees. Is there a simple solution on rotating the canvas of the matrix before displaying text / images? 

Thanks for any help.
Kay

**Comment by hzeller** [comment]
Yes, you can use a `RotateTransformer`, see `include/transformer.h`.

The `led-matrix` demo has an example, you can give the rotation with the `-R` option. So `-R90` will rotate the output.
