### ISSUE TITLE
Matrix Displaying 2 rows after every 2 rows

### ISSUE THREAD

**Issue by JAM-200** [hzeller/rpi-rgb-led-matrix#1656]
![WIN_20240522_23_25_19_Pro](https://github.com/hzeller/rpi-rgb-led-matrix/assets/170599615/bb9014fa-5e4b-437e-b2d6-5e7edffc55eb)
 ive tried with another pannel and they both do this so the panel is working, I've also tried all the demos and a python print text and they all do this same thing. i am using a raspberry pi zero

Led Board
https://www.amazon.ca/gp/product/B0B5N5HPKX/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1

**Comment by davemaster** [comment]
Rows issue. PLEASE, always share your command, and picture of your wiring or hat.

Best regards

PD. try many values of --led-multiplexing= 1... 18 to find you panel type

**Comment by getgotbois** [comment]
Hi sorry for not showing the command or the wiring, I tried all the different multiplexing options and the default looks the best still.
![IMG_1736](https://github.com/hzeller/rpi-rgb-led-matrix/assets/80500606/8640946c-4ae5-4802-a5bc-48b96bd031d9)
![IMG_1737](https://github.com/hzeller/rpi-rgb-led-matrix/assets/80500606/50fc8494-9e33-418e-88b7-a19b42942238)

**Comment by getgotbois** [comment]
Oh and the panel power is connected to a wall power extender usb, and the pi is connected to a battery bank (my usbs under my desk shorted out from a speaker project not too long ago)

**Comment by davemaster** [comment]
Sadly, in each multiplexing try You doesn't post the RGB Panel output... it can tell a lot; at least that with better results
try to use in your command:

$ sudo ./demo -D 0 --led-rows=32 --led-cols=32 --led-multiplexing=**_1-1x_** --led-gpio-mapping=adafruit-hat-pwm

some panels manufacturer use x2 32x32 panels together... 

Also, put some pictures of those panels works fine

**Comment by JAM-200** [comment]
after playing around with jumper pins to connect it I'm just gonna guess its a hardware issue with the hat, thanks for your help though

**Comment by davemaster** [comment]
Here my solution, just in this days I was trying to probe my own 64x64 p3 screen, and it doesn't worked with my adapter (electrodragon). But thanks GOD, it was possible with a little mod, build-in with the adapter:

details [here in my video](https://www.youtube.com/watch?v=sBRi85QoGuY)
