### ISSUE TITLE
Rpi3 Shaking,flickering, jitter

### ISSUE THREAD

**Issue by jdbuendia** [hzeller/rpi-rgb-led-matrix#168]

**Comment by jdbuendia** [comment]
Hi, I'm getting a jittery and a upper shadow that not had in the rpi2.

https://www.youtube.com/watch?v=CJf2wXflyRw
https://www.youtube.com/watch?v=7nezryJceOM

The sound is turned off, and the system has no workload.
in rpi 2 it does not occur. Which may be due?

**Comment by hzeller** [comment]
The RPi3 is a little faster than the RPi-2, and some displays have trouble dealing with the signal speed. Can you try to set the `DEFINES+=-DRGB_SLOWDOWN_GPIO=1` in `lib/Makefile` to 2 from 1 to see what happens ?

**Comment by jdbuendia** [comment]
Hi hzeller, that was, I changed the line to -DRGB_SLOWDOWN_GPIO = 2, and it does not flicker.
Congratulations, this library is a great job.

https://www.youtube.com/watch?v=mGfwIM7u2pw

**Comment by bagumondigi** [comment]
hi, @jdbuendia how can you show terminal to LED display in your video ? can you guide me ? Thanks you :)

**Comment by jdbuendia** [comment]
hello, take a look this https://github.com/adafruit/rpi-fb-matrix

**Comment by chrisoutwright** [comment]
I changed my Pi 3 to boot to command line instead of Desktop and the flicker is much lower, also I enabled internet sharing on eth0 for wlan0 hotspot before, I disconnected eth0 and also flicker is lower. Just moving the mouse produced noticeable flicker so better not to have periphery on.
