### ISSUE TITLE
[Q&A] Is /dev/mem a security risk?

### ISSUE THREAD

**Issue by bluelasers** [hzeller/rpi-rgb-led-matrix#1680]
I was under the impression that using /dev/mem was to be avoided. Adding this into a library seems kind of dangerous to me. Correct me if I am wrong: There should be kernel module which manages the access to the hardware registers on behalf of the user space library?

**Comment by hzeller** [comment]
the GPIO area is memory mapped, and that is the only way to access it performantly.

The security aspect is handled by dropping privileges as soon as the hardware is initialized.
