### ISSUE TITLE
Problem turning off audio in /boot.congig.txt - Pi 4 Model B 

### ISSUE THREAD

**Issue by ElBertrando** [hzeller/rpi-rgb-led-matrix#1683]
I have a Pi 4 Model B running Debian 12. Upon installing the software for the Adafruit Matirx Hat + RTC and testing some the examples in the subdirectory examples-api-use, I find that I need to turn off the sound module:
![sndLoaded](https://github.com/user-attachments/assets/6420d457-253d-435e-afbb-394cdf3f92f6)
However when I go to edit the parameter in `/boot/config.txt`, it says the file has moved to` /boot/firmware.txt`
![bootCfg](https://github.com/user-attachments/assets/d59d96aa-2326-4ea1-a1de-7aa57cfb684b)
When I edit that file, it has no effect on the example code -- it seems does not recognize it:
![bootFrmCfg](https://github.com/user-attachments/assets/cda1a47f-2eb1-4a46-ac74-1337807f3466)
I have the same code running fine on a raspberry pi 4 model B running raspbian Buster.
I have rebooted the pi several times and yet the I still get the error mesage when running the example code...

**Comment by davemaster** [comment]
use: 

sudo raspi-config, and do from there

**Comment by ElBertrando** [comment]
I tried rapsi-config to avail but was able to turn it off with a combination of turning it off in ` /boot/firmware.txt` and adding the line `blacklist snd_bcm2835` by : `cd /etc/modprobe.d`    then ---> `sudo nano alsa-blacklist.conf` 

I can close issue now.. thx
