### ISSUE TITLE
really silly question for noob :(

### ISSUE THREAD

**Issue by fragmation** [hzeller/rpi-rgb-led-matrix#1690]
im really sorry, but not know how to install on raspberry pi zero 2w :( any help please (im so lost)

**Comment by hzeller** [comment]
Mostly, checking out things, then type 'make':

```
git clone https://github.com/hzeller/rpi-rgb-led-matrix
cd rpi-rgb-led-matrix
make
```

In  the utils/ directory, there are a few utilities that you might want to play with. They also include description of some additional dependencies you might need:

https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/utils
