### ISSUE TITLE
Need help with audio modules

### ISSUE THREAD

**Issue by vsumpi** [hzeller/rpi-rgb-led-matrix#1692]
Hi, my project needs audio not High-definition but a loudspeaker or buzzer with a low/high frequency. Do you have any board or USB recommendations? I will need an amp too for 4-amp 2-watt speakers. the panel occupies almost the whole GPIO output so my only choice for a Rpi4 is USB.

**Comment by davemaster** [comment]
in your command, you can use --led-hardware-no-pulse, then you have no need to disable the sound in your Raspberry Pi 3 from the boot. I use the sound, a speaker with amp plugged in the audio of my [Rpi 3, and works great](https://youtu.be/DsmSmaUgFRw)

**Comment by vsumpi** [comment]
> amp plugged in the audio
Is it a 3.5mm jack or USB?

**Comment by davemaster** [comment]
It is the 3.5mm jack in a RPi 3 B+

**Comment by vsumpi** [comment]
Thanks.

**Comment by davemaster** [comment]
This was the usb sound card

Modelo: USB Sound Card Adapter 7.1 Channel
![imagen](https://github.com/user-attachments/assets/2e684b5b-6b14-4a6b-bc11-eb4b94628f59)
