### ISSUE TITLE
RPI5 support

### ISSUE THREAD

**Issue by VitekOpach** [hzeller/rpi-rgb-led-matrix#1694]
Hello, I would like to know if there will be RPI5 support any time soon?

**Comment by hzeller** [comment]
As soon as there is time, yes. I did some initial investigation how to get the GPIO to work with the Pi5 (in the context of #1603) and it looks like it will be somewhat slower, so more work is needed. For now, I recommend a Pi4.

**Comment by bitslip6** [comment]
I took some time and created a separate implementation that supports pi5 with GPU rendering support available here: https://github.com/bitslip6/rpi-gpu-hub75-matrix

@hzeller perhaps you could port into this library?
