### ISSUE TITLE
Add sound to video-viewer to work with external usb sound adapter

### ISSUE THREAD

**Issue by CyrusKell** [hzeller/rpi-rgb-led-matrix#1706]
It would be nice for the video-viewer util to be able to play and decode audio with an external USB sound adapter. Also, it would be helpful if the audio could be decoded and saved as a stream to play it back with led-image-viewer.

**Comment by marcmerlin** [comment]
since this is not something that is ultimately a bug or on the roadmap for the current code, I'm going to close this, but you can re-open if you have a pull request to attach
