### ISSUE TITLE
glitch on P5 panel (32x64)

### ISSUE THREAD

**Issue by Stalker-moment** [hzeller/rpi-rgb-led-matrix#1708]
hello please help me, i have a glitch on my P5 panel (32x64), 2 chain length. how to solve this glitch?
i use classic configuration on raspberry pi 3B for this case because my panel does not have pin E. Is there any hardware/code solution to eliminate this glitch effect? ​​thanks and sorry for my poor English

https://github.com/user-attachments/assets/f604a68b-2aa3-4502-8d27-aff27531db39

**Comment by bitslip6** [comment]
Looks like a signal issue. Try gpio slowdown command line option. could be your cables are too long.

**Comment by marcmerlin** [comment]
You can also use different ribbon cables, but ultimately there is a ribbon length issue. gpio slowdown will help, to a point.
Please re-open if appropriate, but otherwise not much more help we can give, it's really looking like a hardware issue.
