### ISSUE TITLE
display for 4x3 matrix panel

### ISSUE THREAD

**Issue by dhiksha10** [hzeller/rpi-rgb-led-matrix#1712]
I am experiencing issues while using a 4x3 matrix display connected to a single Adafruit HAT. The display shows two different colors inconsistently. Additionally, when I attempt to increase the panel number to 12,(i.e --led-chain=12) there is no display output at all.

Adafruit HAT Model: regular
Matrix Display Model: P10 (32x16)
Wiring Details: Daisy chaining
Command : sudo python3 runtext.py  --led-cols=32  --led-rows=16  --led-chain=8  --led-no-hardware-pulse=LED_NO_HARDWAREPULSE  --text="Dhiksha" --led-multiplexing=3  --led-slowdown-gpio=2  --led-row-addr-type=2  --led-parallel=3  --led-pixel-mapper=U-mapper
Power Supply Specifications: 5V 40 A
Screenshots:
![dc (1)](https://github.com/user-attachments/assets/81f56169-fcfa-4c99-bf6f-0c3db5dea53e)

Environment
Operating System: Raspberry Pi 3 
Library Version: RGB Matrix Library 
Python Version: Python 3.7

Please let me know if there are any troubleshooting steps or modifications I can try to resolve these issues.

**Comment by davemaster** [comment]
Greetings, 

40 A is too short for almost x10 panels, each 7-10A, get an 80A power supply, or another 40A

**Comment by board707** [comment]
@davemaster 
Each these panels eats about 4A at full white brightness, so the 40A power supply seems to be way to enough for 4x3 screen with a few letters on it

**Comment by bitslip6** [comment]
Isn't the ada fruit hat only 1 port?  Why you have parallel set to 3?

**Comment by marcmerlin** [comment]
I think you got multiple suggestions, there is no issue with the code or anything to fix that I can see.
Basically make sure you have enough power and for that many panels, use the electrodragon active 3 board with 3 channels, not a single channel adafruit board.
