### ISSUE TITLE
Can only get yellow/red flickering lights.

### ISSUE THREAD

**Issue by StevenJansen** [hzeller/rpi-rgb-led-matrix#1718]
I've been trying for hours to get my LED matrix to work on my Raspberry Pi 4, without success. I had checked the pins 3 times, and following the wiring.md file. When I run one of the demo's, regardless of which one, this is all I get:

![WhatsApp Image 2024-10-16 at 12 46 30](https://github.com/user-attachments/assets/af01d046-dce0-498c-ab4d-74696c447093)

I am very new to LEDs and matrixes. I did disable 1wire in the raspi-config, blocked the onboard audio and added the isolcpus=3 to my boot/firmware/cmdline.txt.

Does anybody got any clues/suggestions that I can try, I'm all out of ideas.

**Comment by hzeller** [comment]
Did you also connect GND ?
