### ISSUE TITLE
How to invert Display in Python lib?

### ISSUE THREAD

**Issue by jppw** [hzeller/rpi-rgb-led-matrix#173]
Hello,

so i need to invert the signals for my 64x16 monochrom display.

It generely act a bit weird but i worked around that.

My problem is, i want to use the Python Libs, but how can i invert it?

In the mainlibs i can toggle it in the Makefile.

**Comment by hzeller** [comment]
The python library ust uses the C++ library, so if you re-compile the python-lib after you have changed and compiled the library, you get whatever you choose in the Makefile on the C side.
