### ISSUE TITLE
How to easily configure my display?

### ISSUE THREAD

**Issue by Dowanproject** [hzeller/rpi-rgb-led-matrix#1740]
Hello! I am using 128X64 Led matrix in 2X3 format and it works well. But I would like to control this display remotely. There are programs like Jinx, but they are very tricky and difficult to set up. I was wondering if there was another way.
(Please understand that there may be some awkwardness in the English translation.)

**Comment by marcmerlin** [comment]
this is not an issue, please use https://rpi-rgb-led-matrix.discourse.group/
