### ISSUE TITLE
Problem with P2-1515-128X64-32S-S2 Matrix

### ISSUE THREAD

**Issue by ASMediaDev** [hzeller/rpi-rgb-led-matrix#1742]
Hi,

I got a P2-1515-128X64-32S-S2 Matrix but it seems that only half of the rows is being adressed.

This is my command:
sudo ./demo -D 0 --led-cols=128 --led-rows=64 --led-row-addr-type=0 --led-brightness=100

Which gives me this output:

https://github.com/user-attachments/assets/b521cea3-d9bd-4edc-a9ab-a4fa3b4eedf7

Here's a picture of the back of the panel:

![WhatsApp Image 2024-12-13 at 07 33 48](https://github.com/user-attachments/assets/500456f4-5981-439a-9ac2-4fb345878f57)

The panel did work with another library with an esp32 so the panel itself should be good.

Happy to get your advice, thanks!

**Comment by marcmerlin** [comment]
you are likely using an electrodragon board or other board where you did not assign the 5th address bit (E) which usually needs to be wired to pin 8.
It'd be great if it were wired so by default but apparently not all panels wire the E address the same
