### ISSUE TITLE
Setting custom brightness doesn't work

### ISSUE THREAD

**Issue by marcinzdunek** [hzeller/rpi-rgb-led-matrix#187]
Hello,
I am trying to set custom brightness of pure white text with function canvas->SetBrightness.
All values below 90 generate whole black board. Value 90 sets the same brightness as 100.
I am not using EXPERIMENTAL_HIGH_BRIGHTNESS define.
What is wrong here?

**Comment by hzeller** [comment]
For brightness adjustment to work, you need to have PWM enabled. So it only works if you have `SetPWMBits()` (or the `-p` flag) to something larger than 1.

**Comment by hzeller** [comment]
Haven't hard back. Closing this now as I assume this was the problem you were seeing.
