### ISSUE TITLE
OSH Park board -- is that a full assembly or just a board ready for soldering?

### ISSUE THREAD

**Issue by yarikoptic** [hzeller/rpi-rgb-led-matrix#191]
Sorry for a naive question: the board from OSH Park, is that just the board itself, so I would need to purchase/solder all components  or it comes "fully assembled" as on e.g. https://github.com/hzeller/rpi-rgb-led-matrix/raw/master/img/three-parallel-panels-soic.jpg ?
just thought to buy more and chain/arrange display of 12 32x32s  (into 2x6 arrangement) but I am afraid then adafruit HAT wouldn't be sufficient and I would better have at least two 6 panel chains.

**Comment by maddogs** [comment]
The board you'd get from OSH Park is just the board. You'd need to buy the level shifters, caps and sockets and solder them all on.

**Comment by hzeller** [comment]
12 on a single chain is indeed pushing it, so having the parallel chains is nicer.

OshPark just creates the PCB from the plans, you have to indeed solder it up  yourself.

**Comment by yarikoptic** [comment]
Just for lazy like me, if there was a complete recipe "buy this board from here and these components from there" it would be quite useful

**Comment by hzeller** [comment]
Currently, I don't have enough resources in my spare time to prepare a kit, but anyone in your local hacker space would be able to help here.
