### ISSUE TITLE
Adafruit rgb-matrix, half screen shows blue

### ISSUE THREAD

**Issue by djdollar** [hzeller/rpi-rgb-led-matrix#194]
Im having problems with the Adafruit rgb-matrix + raspberry 3 and the 32x32 led matrix.

Half screen(last 16 ros of leds) just shows a static blue while the other half works
![img_1440](https://cloud.githubusercontent.com/assets/21034323/17659337/1802a406-62d2-11e6-92c7-46bf7515efae.JPG)

Any ideas of what i could do?

**Comment by djdollar** [comment]
if i change some of the settings from:
![fullsizerender 31](https://cloud.githubusercontent.com/assets/21034323/17664275/39795a1e-62f3-11e6-8f15-7eb782bb830f.jpg)

to:
![fullsizerender 32](https://cloud.githubusercontent.com/assets/21034323/17664286/4992025c-62f3-11e6-9afb-d009f1ab03d3.jpg)

i get this result instead:
![16 rgbmatrix](https://cloud.githubusercontent.com/assets/21034323/17664298/55b0c730-62f3-11e6-97cb-cf7aaf6ce0ce.jpg)

any ideas?

**Comment by Skid32** [comment]
i sorta have that problom i looks like this 
![img_0193 1](https://cloud.githubusercontent.com/assets/21077832/17765130/2f02bb1a-6524-11e6-957f-b3bdf7c12092.JPG)

**Comment by hzeller** [comment]
Check the cables and that the connectors are properly soldered without shorts.
