### ISSUE TITLE
I Cant Run Demos

### ISSUE THREAD

**Issue by Skid32** [hzeller/rpi-rgb-led-matrix#195]
Wen I Try To Run A Demo I Just Get This 
![screenshot 7](https://cloud.githubusercontent.com/assets/21077832/17732130/a72e5f86-6470-11e6-8e07-0ee0f62f2f96.png)

**Comment by hzeller** [comment]
This is how it is supposed to look. If you don't see anything on your matrix, it is not connected correctly. Double check your wiring and check out the 'Troubleshooting' section of the README.

**Comment by Skid32** [comment]
i can get it to run with the adafruit version

**Comment by hzeller** [comment]
Note, the Adafruit version has modified the pinout.
If you are using the Adafruit HAT for instance then this won't work until you do the things mentioned in the relevant section in the README.

**Comment by Skid32** [comment]
i fix it sorry for my typeing

**Comment by Skid32** [comment]
thank you
