### ISSUE TITLE
Help Me Led Is PooP

### ISSUE THREAD

**Issue by Skid32** [hzeller/rpi-rgb-led-matrix#197]
So Wen I Display An Image on My LED RGB Matrix 32X32 It looks Like This
![img_0193 1](https://cloud.githubusercontent.com/assets/21077832/17748102/27636718-64b8-11e6-8650-9d6e601c64ab.JPG)
So As You Can Se The Top Is Broken And The Botom Is Fine So If You Can Help That Would Be Nice

Ps. I Am Very Bad At Spelling Since I Have Dyslexia
Thank You

**Comment by RcArtSolutions** [comment]
To locate this failure, you must know two facts.

1. To display a white pixel, the panel must mix all three colors. Your panel show only a mix of red and blue, __green is missing__.
2. Your panel has two _RGB buses_, one for the first top 16 rows (x1) an the other for the last (bottom) 16 rows (x2).

So, we can say: Check the connection of G1 ;-) The also the [Wiring Diagram](https://github.com/hzeller/rpi-rgb-led-matrix#wiring-diagram).


You write top and bottom, but you photo show a difference between left and right... In case of an orientation-problem (top and bottom reversed) you must check also the connection of G2.
