### ISSUE TITLE
outdoor led

### ISSUE THREAD

**Issue by serverfire** [hzeller/rpi-rgb-led-matrix#212]
First of all thank you for great work you have done , you should put a button for donation to this project .

I have problem with python code , i have edited this line of code [led-matrix.cc#L170](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/led-matrix.cc#L170)

To use my transporter by default and replace it with Null , 

 It work with c++ demo but won't change how python code work and won't transformer it .

Any idea where should put my transformer for python 

Thank you in advance

**Comment by hzeller** [comment]
The Python code uses the other constructor, so you have to change the corresponding SetTransformer(NULL) in line 183.

**Comment by serverfire** [comment]
@hzeller i'm sure is not calling that function , did not worked , also put a fprintf to make sure . 
maybe @Saij can tell me which file i should edit to set default transformer for python

**Comment by serverfire** [comment]
@hzeller 

I have founded a way with last code to make the python to use my transformer but some how there is problem . as you can see in this screen shots it look bad .

graphics.py 

![2](https://cloud.githubusercontent.com/assets/132761/18472928/70e584a8-79cf-11e6-8864-6b2e3c7bef02.png)

simple-square.py

![3](https://cloud.githubusercontent.com/assets/132761/18472929/70e57e36-79cf-11e6-9245-79cd74ec7d78.png)

run-text,py

![1](https://cloud.githubusercontent.com/assets/132761/18472930/70e9b640-79cf-11e6-8ca0-36d2f96609ab.png)


any idea what should i do ?

**Comment by hzeller** [comment]
You didn't mention how you use the transformer ?

**Comment by hzeller** [comment]
Maybe your Pi is just too fast for your Matrix ?
In `lib/Makefile`, try commenting out the define for `RGB_SLOWDOWN_GPIO` and set it to 2 or maybe 3.
```
DEFINES+=-DRGB_SLOWDOWN_GPIO=2
```
then, in the Python directory, 'make clean' and then install again.

**Comment by serverfire** [comment]
i have set DRGB_SLOWDOWN_GPIO=3 already and have done make clean too . in led-matrix.cc i have put ApplyStaticTransformer(RotateTransformer(180)); in RGBMatrix::RGBMatrix(GPIO *io, int rows, int chained_displays,
                     int parallel_displays)

also in RGBMatrix::RGBMatrix(GPIO *io, const Options &options)

**Comment by serverfire** [comment]
I can give you ssh access to rpi and access to ip cam if it is possible for you to take a look , i will pay for your time :)
