### ISSUE TITLE
DrawText not working on rc.local boot?

### ISSUE THREAD

**Issue by tehmooo** [hzeller/rpi-rgb-led-matrix#221]
Bit of a weird one... Written a python script to turn the LED panel into a clock, and it all works well and great when i run it from terminal - but if i add it to rc.local and boot it with the pi the DrawText stuff doesn't appear. I get lines from DrawLine and I can fill sections and manually setPixels... but DrawText isn't appearing. Any ideas?

**Comment by BennoG** [comment]
something with the fonts that can not be found ?
just my 2c
Benno

**Comment by hzeller** [comment]
Make sure that you set an absolute path the font, because your binary runs in some working directory depending on where the rc.local started it.

**Comment by tehmooo** [comment]
Aha! That's the problem, brilliant. Thanks for the help!
