### ISSUE TITLE
Use of GPIO pins for other purposes with Active-3 attached

### ISSUE THREAD

**Issue by easleyjs** [hzeller/rpi-rgb-led-matrix#224]
Hi,

I was wondering if it's possible to use some of the GPIO pins for additional things (I2C, etc) with an Active-3 attached, and using it to push LED Matrices.

Thanks,

Josh

**Comment by hzeller** [comment]
Yes, if you don't use full parallel=3, then you can use the non-used GPIO pins. e.g. if parallel=2, then SDA/SCL for i2c is free.
