### ISSUE TITLE
Interference/Static when powering external circuit

### ISSUE THREAD

**Issue by jhchong92** [hzeller/rpi-rgb-led-matrix#230]
Hi, I have an external circuit that triggers a 12V siren and a 12V strobe light when an input is received. However, when both of them are powered, my panel shows some static/interference. I tried tweaking the commands but not much help. Separating the power supply for the external circuit and the panel (previously it was connected on the same supply with a power extension), improved it a little.

Is magnetic interference the real cause here? The external circuit draws only 0.5A. Or is it the fact that I am using the 3.3V GPIO outputs to the panel, which might cause interference as mentioned #124 
### External circuit not running

![20161007_161908](https://cloud.githubusercontent.com/assets/16560316/19184274/e8814b40-8cae-11e6-9916-68734924bcf8.jpg)
### External circuit running

![20161007_161855](https://cloud.githubusercontent.com/assets/16560316/19184273/e87d369a-8cae-11e6-91e4-66d5591c8b6d.jpg)

**Comment by hzeller** [comment]
This can have all kinds of reasons, which you only can figure out by measuring the power and line glitches with an oscilloscope and then implement the appropriate measures to work around that.
