### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dennys78** [hzeller/rpi-rgb-led-matrix#231]
hi

when I "make led-image-viewer" command I receive this message :

/usr/bin/ld: warning: libjpeg.so.8, needed by /usr/lib/libGraphicsMagick.so, may conflict with libjpeg.so.62

Apparently led-image-viewer works but any GIF is show on the panel

please help me

**Comment by hzeller** [comment]
This is only a warning, so things should work fine.

Your sentence is not quite clear: you tried and show images such as PNG or JPEG but then GIF didn't work ?

**Comment by dennys78** [comment]
It does not work any images... my procedure is this:
# git clone https://github.com/hzeller/rpi-rgb-led-matrix.git
edit Makefile and correct in /lib HARDWARE_DESC?=adafruit-hat 
uncomment DEFINES+=-DADAFRUIT_RGBMATRIX_HAT_PWM
# cd ..
# make (compile but not appare executable led-matrix) 
# cd utils 
# make led-image-viewer
when lunch  #./led-image-viewer -c1  pesci.gif  
appear :
Load images...
Display.
But nothing on the panel :( :( :(

**Comment by hzeller** [comment]
Did you confirm that the regular demos work with your Adafruit PWM hardware modification ?

**Comment by dennys78** [comment]
no don't work

**Comment by hzeller** [comment]
Then you first need to make sure that that is working. The README has a lot of information regarding troubleshooting the Adafruit modifications.
For instance, did you disable the sound system ?

**Comment by dennys78** [comment]
I will try with this command :

./led-image-viewer --led-no-hardware-pulse -C -c1 pesci.gif

but nothing

**Comment by dennys78** [comment]
It's possible send me a version correctly compiled for raspberry pi 3 ??!? Or use another system?!!

**Comment by hzeller** [comment]
This has nothing to do with the Raspberry Pi 3 - the library compiles fine there and works. You have something in your electrical set-up that is not working. Maybe the bridge you had to solder to use the HAT PWM setting is not working properly.
You need to systematically rule out the mistakes.

**Comment by hzeller** [comment]
Haven't heard anything, I presume you figured it out.

**Comment by dennys78** [comment]
Great the bridge not working properly!!! Now all ok. Thank for the support!!!!!
