### ISSUE TITLE
Problem with 1-wire protocol

### ISSUE THREAD

**Issue by haubuchon** [hzeller/rpi-rgb-led-matrix#236]
My panel (16X32) was working great until one day where it started showing this problem:
- works great for 2 to 10 seconds
- starts displaying random patterns

After trying everything in the troubleshooting section, I finally remembered I recently enable the 1-wire module. I tried to disable it and reboot. After that everything is back to normal.

Any idea why ? Should I use different pins ?
Note that no 1w sensors are used or connected. Only the kernel option is turned on.

RPI 3. external 5v power supply for the panel.

Thank !

**Comment by hzeller** [comment]
You probably have to disable the kernel module for the 1w connect, if it is bound to a particular GPIO. Even if no sensor is connected - after all, the kernel will 'ask' on the 1w-bus if something is there.

You either have to move the 1w GPIO to one that is not used by the led-matrix, or you have to move the led-matrix GPIO that conflicts with your 1w GPIO somewhere else (lib/hardware-mapping.c ... don't forget to then re-wire the led matrix).
