### ISSUE TITLE
Pixel rows 17-32 no red ; rpi3 + Adafruit HAT + a 64x32 panel

### ISSUE THREAD

**Issue by LucasVos** [hzeller/rpi-rgb-led-matrix#241]
Thanx for the great library! 

I have a Raspberry Pi3 with Adafruit HAT and a 64x32 panel. I used a recent copy of the master branche (couple of days old), and build with the "HARDWARE_DESC=adafruit-hat make".

Everything works fine. Except the lower 17-32 lines aren't displaying any red.

Example: When running the demo D11 , i see full board of green, full board of blue, but only the first 16 lines of red.. 

- i switched the panels already and used another cable

Other suggestions to look for?

**Comment by hzeller** [comment]
So sounds like your panel either has a broken red line or the HAT has some solder issue with that line.
