### ISSUE TITLE
2x 64x32 panels flipped

### ISSUE THREAD

**Issue by GumboBeans** [hzeller/rpi-rgb-led-matrix#245]
Hi, 

I have 2 64x32 panels, which seems to be working, however, the image is not shown correctly, i'm sure i am missing an cli argument somewhere, but i cant figure it out, hopefully someone here can help me. 
Its looks to me like the "U" arrangement of the panels is the wrong way around, but i have the boards wired up correctly from what i can see. 

Board: Raspberry Pi Zero
Command: sudo ./demo -L --led-rows=32 --led-chain=4 -D0

Many thanks for a great project :)

Picture below is the D0 example. 
![nbb9f7p](https://cloud.githubusercontent.com/assets/5621958/20607947/ac61df58-b274-11e6-8332-566a67474292.png)

**Comment by hzeller** [comment]
Why don't you just fold the panels the other way around ?

**Comment by GumboBeans** [comment]
Yeah... i now feel like an idiot. Sorry for wasting your time, Flipping the panels worked.
