### ISSUE TITLE
No pwm_lsb_nanoseconds in Python

### ISSUE THREAD

**Issue by xboomx** [hzeller/rpi-rgb-led-matrix#246]
Am I missing something? I couldn't find a way to control pwm_lsb_nanoseconds parameter with Python. Is there any way of reducing ghosting when using Python?

**Comment by hzeller** [comment]
Not all flag configuration options are available in Python (like the pwm nanoseconds), but I am happy to apply a pull request that provides the options struct in the Python wrapper.

For now, you have to change the setting statically in lib/Makefile and recompile the library and Python wrapper.

**Comment by xboomx** [comment]
Thank you! You're the best :)

**Comment by hzeller** [comment]
In the latest commit https://github.com/hzeller/rpi-rgb-led-matrix/commit/e2ffd91644eb9ca36b57921c07106be1ef0d0f63 there are now a couple of options available in Python, including `--led-pwm-lsb-nanoseconds`
