### ISSUE TITLE
How to replace the running ppm file without killing the process

### ISSUE THREAD

**Issue by RamyashreeGR** [hzeller/rpi-rgb-led-matrix#256]
hi
i want to dynamically update or replace the ppm files, without  killing the running process, is their any way to do that.
 

Thank you
Ramya

**Comment by hzeller** [comment]
Just write a little server that accepts new images via a network socket.

**Comment by ejrua** [comment]
Hi, very thank, do you have an example for it case?

**Comment by ejrua** [comment]
Hi, very thank, do you have an example for it case?
