### ISSUE TITLE
Thank You note

### ISSUE THREAD

**Issue by genvagula** [hzeller/rpi-rgb-led-matrix#257]
Just wanted to thank you Sir for this tutorial, detailed readme and the  'work you've done for us to send stuff from Raspberry to LED matrix displays. Was very useful for me to start with the prototyping.

You may check out my first prototype trial here:
https://www.youtube.com/watch?v=YJ_skJ6TtJk

Think i will be back sometimes in the future with some questions :)

Regards,
Gen

**Comment by hzeller** [comment]
Cool! Have fun with your LED matrix display!
