### ISSUE TITLE
have trouble using flaschenvnc

### ISSUE THREAD

**Issue by trhtr** [hzeller/rpi-rgb-led-matrix#258]
hi everyone, i have watched clip https://www.youtube.com/watch?v=s3pGp_Vf4Pk and i like it, but when i use flaschenvnc, i have an error as picture in below link: 

https://cloud.githubusercontent.com/assets/24630115/21291307/2c6086c4-c50c-11e6-9c5e-a4079ebc2a5b.PNG

can you help me?
Thanks for watching !

**Comment by hzeller** [comment]
Maybe you should ask on a Python related list. Looks like you want to install the twisted module.

Also, if at all, this is a question for the flaschenvnc repository not here.

(You really should not post screenshots but actually copy/pasteable text of your output).
