### ISSUE TITLE
artifacts while scrolling text

### ISSUE THREAD

**Issue by genvagula** [hzeller/rpi-rgb-led-matrix#259]
Was curios if you would have any idea where this artifacts may come from ? Where I should start looking for issues ?

Clip:
http://files.genvagula.com/3CBR

**Comment by hzeller** [comment]
you mean the random dots that sometimes show up at the edge of the display ? This is an hardware issue in some LED panels that can't deal with too fast pulses and which shows with very strong contrasts such as text. Look for 'ghosting' in the README to try fix it with `--led-pwm-lsb-nanoseconds`

**Comment by genvagula** [comment]
Thnx. I'll try.
