### ISSUE TITLE
wiring multiple chains

### ISSUE THREAD

**Issue by roykolak** [hzeller/rpi-rgb-led-matrix#262]
I have connected R1, G1, B1, R2, G2, B2 to my first and second chains (two chains with two 64x64 panels). 

Question about GND, strobe, clock, OE-, A, B, C, D. It seems like ALL chains need to be wired with these connections. Is that correct? Can I just splice the one wire from the pi to both chains?

**Comment by hzeller** [comment]
Yes, GND, strobe, cock, OE-, A, B, C, D (and possiblye E if you have a 64x64) need to be wired to all panels. You can do that with wires, but I'd suggest to solder up an adapter to simplify things
https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/adapter/active-3

**Comment by roykolak** [comment]
gotcha, just wanted to confirm. Thanks!
