### ISSUE TITLE
Color Mixed

### ISSUE THREAD

**Issue by akardes5** [hzeller/rpi-rgb-led-matrix#267]
Hi,

The project is very nice. I did the same. But the colors are mixed.

Red -> Blue
Green -> Red
Blue -> Green

For example;
A red color image appears blue.
How can I fix?

Thank you.

**Comment by hzeller** [comment]
You probably have a panel that has swapped inputs. Just wire up the R1, G1, B1 and R2, G2, B2 differently so that it matches your panel.

**Comment by akardes5** [comment]
Do you know the Adafruit Hub75 R1 G1 B1?

Thank you.

**Comment by hzeller** [comment]
if you are using the HAT, then better remap it in software. look in lib/hardware-mapping.c and change the p0_r1 etc to point to the gpio it should be.

**Comment by akardes5** [comment]
I think this will solve the problem. Thank you so much.

**Comment by prunella2017** [comment]
@akardes5 , hey, did the hub75 work for you? Thanks!.

**Comment by hzeller** [comment]
There is now an option `--led-rgb-sequence` that allows to choose the order on the command line without changes to the code.
(added in https://github.com/hzeller/rpi-rgb-led-matrix/commit/efe8a77f1958c342f97a3ac7f7d0601e02c30b6a )
