### ISSUE TITLE
Processor affinity not working?

### ISSUE THREAD

**Issue by tigertone** [hzeller/rpi-rgb-led-matrix#269]
With isolcpus=3 set in /boot/cmdline.txt on a pi3, the process doesn't seem to be locked to the 3rd core ( when I run 'taskset -c -p 1136', it returns: current affinity list: 0-2 (does this mean it's actively avoiding the 3rd core?). This is when using the led-image-viewer function.

Thanks

**Comment by hzeller** [comment]
With `isolcpus=3` you tell the kernel to actively avoid scheduling something on CPU 3 unless it is requesting to run there. Probably that is what taskset is returning ?

rpi-rgb-led-matrix is explicitly requesting core 3 for the matrix update, and no specific affinity for everything else.
So if you go in `top` and press `1` (to show the individual CPU percentages) and `H` (to show individual threads), you see that there is one rpi-rgb-led-matrix thread that is hogging the Cpu3 - this is the update thread for the matrix. The others are using whatever is there 0-2.

Not sure if taskset is picking that up properly.
