### ISSUE TITLE
Show a specific area on the led display

### ISSUE THREAD

**Issue by akardes5** [hzeller/rpi-rgb-led-matrix#272]
Hello there,

I did the project. It was a very nice work thanks. In the project; The LED panel gives the same view as the screen. What should I do to show a specific area on the screen?

Thank you.

**Comment by hzeller** [comment]
The LED matrix is just a canvas, it shows whatever pixels you choose to set.

In particular, it does not mirror your screen, you actively have to implement something that takes the image from the screen and sends it to the matrix. So if you have implemented such a mechanism, you have full control which area you show.
