### ISSUE TITLE
Get Pixel Colour

### ISSUE THREAD

**Issue by Kaktuar** [hzeller/rpi-rgb-led-matrix#273]
I'm looking to find a way of getting the colour of a specific pixel on the matrix e.g **int GetPixel(int x, int y);**

What would be the best way to approach this?

**Comment by hzeller** [comment]
Write a wrapper canvas, that delegates to the underlying RGBMatrix canvas, but also stores the color you set at a particular position. With that, you can then implement a GetPixel() function, as you have stored the color locally.

It is not very easy to get the color out of the original canvas, as it is deconstructed and prepared in memory for the display activity. So having storing it in its original form as described above is the best.
