### ISSUE TITLE
Multiple pixel lit

### ISSUE THREAD

**Issue by agoesssss** [hzeller/rpi-rgb-led-matrix#278]
Hi there, is there anyone ever experienced multiple vertical pixel lit when trying to SetPixel single pixel. I'm trying to turn on single pixel but I always got 4 vertical pixel lines. 

Can anyone address this issue? 

Thank you

**Comment by agoesssss** [comment]
![image](https://cloud.githubusercontent.com/assets/25609263/22688681/e9ca92f6-ed5f-11e6-816e-7761607cd777.png)

That is what I got when doing SetPixel(0, 0, 255, 255, 255);

**Comment by hzeller** [comment]
This is interesting, does that happen on any pixel, eg. if you choose one in row 2, does it go from row 2 to 6 ?

This might be a slightly different panel control. CS sounds suspicious (this abbreviation usually means 'Chip Select', used to tell a subsystem that whatever data it gets is supposed for it).
It can be detrimental if that is floating (i.e. not connected). Try to set that to 5V in one experiment and to GND in another (I expect the panel to not show anything in one or the other experiment).

Can you take a good readable picture of the connector on the back of the panel and post here ?

It could also be a different issue in which it does multiplexing a bit differently, which we have to find out.

**Comment by agoesssss** [comment]
I guess that's nothing to do with the chip select that I also suspect earlier, because when I tried to pulse that CS then my system freeze and nothing happened when I set to ground, and then I realized that CS is shorted to the ground. I guess there's issues with multiplexing

these is what I got when doing
matrix_->SetPixel(0, 0, 255, 0, 0);
matrix_->SetPixel(1, 1, 0, 255, 255);
matrix_->SetPixel(2, 2, 0, 0, 255);
![image](https://cloud.githubusercontent.com/assets/25609263/22722093/3e85272a-ede7-11e6-8e71-12246354cca5.png)

matrix_->SetPixel(1, 0, 255, 0, 0);
matrix_->SetPixel(2, 0, 0, 255, 255);
matrix_->SetPixel(3, 0, 0, 0, 255);
![image](https://cloud.githubusercontent.com/assets/25609263/22722128/870da94a-ede7-11e6-97a6-2f470ea6ee79.png)

matrix_->SetPixel(0, 1, 255, 0, 0);
matrix_->SetPixel(0, 2, 0, 255, 255);
matrix_->SetPixel(0, 3, 0, 0, 255);
![capture](https://cloud.githubusercontent.com/assets/25609263/22722180/e53873d8-ede7-11e6-93d1-b11d81db29bf.JPG)

Also attached below the pinout
![capture](https://cloud.githubusercontent.com/assets/25609263/22722205/060c189e-ede8-11e6-9d28-99375639e551.JPG)

Thank you for your support

**Comment by agoesssss** [comment]
Attached below the video while doing sweep test using the option "--led-rows=16 --led-chain=2"

`for( int sweepY = 0; sweepY < 16; sweepY = sweepY + 1 ){
  for( int sweepX = 0; sweepX < 64; sweepX = sweepX + 1 ){
    matrix_->SetPixel(sweepX, sweepY, 255, 255, 255);
    usleep(10000);
  }
}
`
[VID_20170208_091053.zip](https://github.com/hzeller/rpi-rgb-led-matrix/files/759647/VID_20170208_091053.zip)

**Comment by agoesssss** [comment]
This is the product website http://www.qiangliled.com/products-63.html

**Comment by Arvindace** [comment]
Did we figure out a solution to this problem. I am using the same panel and facing the same issue. please help. thanks!

**Comment by vapiper** [comment]
Hello Henner!
I bought the same matrix and got the same result as described above.
![img_2221](https://user-images.githubusercontent.com/34489252/34873564-a24122ae-f7a6-11e7-9c96-128b8552345c.JPG)
I had LED screen controller Onbon BX-5Q1+. The matrix is working correctly with this controller. Here is a chart from HUB75 of the controller (2 matriсes 32x16 in 1 chain, CH0..CH5 color bits):
![2018-01-11_18-43-56](https://user-images.githubusercontent.com/34489252/34873941-028d495c-f7a8-11e7-958e-adc2bda699ae.png)

And here is the chart from Rpi+Adafruit Hat (rows=16, chain=1):
![2018-01-12_13-28-54](https://user-images.githubusercontent.com/34489252/34874161-f17b6f44-f7a8-11e7-8f5c-bd6a908dbe4d.png)

The pin CS is connected to GND  inside the matrix ( When I applied +5V I got a short circuit).
If I understand correctly, in the matrix multeplexing chip is missing and rows are selected directly by the lines A, B, C, D.
This weekend I will try to make changes in methods `Framebuffer::InitGPIO` and ` Framebuffer::DumpToMatrix`.

**Comment by vapiper** [comment]
My assumption was correct! Now matrix Qiangli X10 is working properly.
This is a graph after making changes to the code were made:
![2018-01-12_17-12-47](https://user-images.githubusercontent.com/34489252/34905447-d47e949a-f869-11e7-9a6d-3f761f3042c1.png)

**Comment by hzeller** [comment]
So looks like @vapiper has fixed this one with the #509 pull request resulting in commit https://github.com/hzeller/rpi-rgb-led-matrix/commit/b6892aa85666c21e7e9a9392285a278f795755e5
