### ISSUE TITLE
Trouble in Installation of Supplementary Fonts

### ISSUE THREAD

**Issue by Acqua-Alta** [hzeller/rpi-rgb-led-matrix#279]
Hi, I'm troubled with installation of supplementary font, although I read "rpi-rgb-led-matrix/fonts/README".

Firstly, I can't find the directory of "submission".
Should I execute "mkdir submission", and continue to following command?

```
cd submission/
make
su
mv -b *.pcf.gz /usr/lib/X11/fonts/misc/
cd /usr/lib/X11/fonts/misc/
mkfontdir
xset fp rehash
```

**Comment by hzeller** [comment]
the README in that directory is referring to the use of these fonts in your system. But you don't need that for the matrix.

**Comment by Acqua-Alta** [comment]
OK, so I'll just skip this process.
Then, how to use the supplementary fonts?
I downloaded the supplementary packages from "http://www.cl.cam.ac.uk/~mgk25/download/ucs-fonts-asian.tar.gz".
Then I unpacked at the directory of "rpi-rgb-matrix/fonts".
And I executed 
```
sudo ./text-example -f ../fonts/12x13ja.bdf
```
But nothing indicated on the led matrix.

**Comment by Acqua-Alta** [comment]
Sorry, I succeeded.
I just need to type texts on command line.

**Comment by Acqua-Alta** [comment]
Then would you tell me how to indicate characters with scrolling in python using supplementary fonts?

**Comment by hzeller** [comment]
Just look at the code of the runtext.py example, there the font is chosen. Look for `LoadFont`.

**Comment by Acqua-Alta** [comment]
I've done it!!
I greatly appreciate for your quick reply and precise pointing out, and of course, for your program!

```
sudo nano runtext.py
```

Before
```
...   
   def run(self):
        offscreen_canvas = self.matrix.CreateFrameCanvas()
        font = graphics.Font()
        font.LoadFont("../../fonts/7x13.bdf")
...
```

After
```
...
    def run(self):
        offscreen_canvas = self.matrix.CreateFrameCanvas()
        font = graphics.Font()
        font.LoadFont("../../fonts/12x13ja.bdf")
...
```

And it work out as I hope!

**Comment by Acqua-Alta** [comment]
Sorry, can I ask one more question?
This program designates the encode of font file, 'utf-8'.
Suppose that I use .bdf file encoded not  'utf-8' but 'shift-jis' or 'JIS X 0208', where should be changed?
I wish I could find .bdf file encoded with utf-8, but I can only find .ttf or encoded by 'JIS' file.

**Comment by hzeller** [comment]
1) You could manually recode the codepoints from JIS to UTF-8 (you need to change the ENCODING from the JIS encoding to whatever the codepoint would be in UTF-8). This can be tedious though, but I suspect that font-editors can provide that feature as well - load the BDF file and write it out with UTF-8 encoding.

2) Look at the code. `graphics.DrawText()` gets the y-coordinate as 4th parameter. So if you call DrawText() multiple times with different y-coordinates, you get multiple lines of text.

**Comment by Acqua-Alta** [comment]
Solved : 
1. I changed encoding of .bdf file with FontForge in ubuntu, from Shift-JIS to UTF-8 (ISO 10646-1)

Solved : 
2. I understood your description and now I can display strings in two rows.

Thank you.



But may I ask one more question?
Although I feel really sorry about asking you again and again.

That's following:

The font files which you suggested for Chinese, Japanese, Korean worked well.
But, some of kanji fonts was terrible.
Concretely to say, part of kanji as simple as alphabet, was well displayed.
But complex kanji were the state of being crashed.
So I decided to use alter kanji fonts, shinonome font.
In  http://openlab.ring.gr.jp/efont/dist/shinonome/
shinonome0.9.11p1... includes the font.

I'll show figure as sample. (shinmk14.bdf)

This is default.
![default](https://cloud.githubusercontent.com/assets/19947593/23067318/1661ff5c-f562-11e6-879b-0a08f3edcc3b.PNG)

It worked such as this.
![disp](https://cloud.githubusercontent.com/assets/19947593/23067325/1c9a1c6a-f562-11e6-9916-49ff5d329a6f.png)

Another sample
![default](https://cloud.githubusercontent.com/assets/19947593/23067954/dc2afaa2-f564-11e6-96b0-295e859aabb7.png)

So, then I shifted for few bits.

Then, it worked well.
![shifted-](https://cloud.githubusercontent.com/assets/19947593/23067432/9fe78eb8-f562-11e6-881f-522cdec91913.png)

![shifted](https://cloud.githubusercontent.com/assets/19947593/23068056/623038d8-f565-11e6-9141-d94d8dc2fea6.PNG)

However, when I tried to display two characters sequently, it worked as following.
![default](https://cloud.githubusercontent.com/assets/19947593/23067518/115a8622-f563-11e6-87fe-f14dd57a5cb5.PNG)

What causes this odd phenomenon?

Where should I change?


Additionaly, I thought I could solve this problem if I just shift bits about all characters anyway.

But, some of fonts didn't require to be shifted such as the following character.

![default](https://cloud.githubusercontent.com/assets/19947593/23068073/76451ece-f565-11e6-8bb3-c30ed0a89b2e.PNG)


![default](https://cloud.githubusercontent.com/assets/19947593/23068083/7dc2f70c-f565-11e6-8718-5b4c72a991b7.PNG)


How should I handle these difference?
