### ISSUE TITLE
Cairo anyone?

### ISSUE THREAD

**Issue by VolkerGoeschl** [hzeller/rpi-rgb-led-matrix#281]
Has anyone successfully used cairo (or any other lib thats a bit more exhaustive then the nicely self-contained graphics.h) and is willing to share her/his knowledge?
I´m not sure how much work I would need to put into getting cairo to draw on Henners nice canvas, so I thought I could ask here first.
Greetings
Volker

**Comment by hzeller** [comment]
I am not aware that anyone tried, that, but I think it would be very worthwhile thing to do. I suspect that Cairo already has a way to add a simple new framebuffer backend, so maybe it would actually not be too hard.

**Comment by hzeller** [comment]
Did you get around writing a cairo backend ?
