### ISSUE TITLE
32x32 led matrix dual display

### ISSUE THREAD

**Issue by Abhigyanabhijeet** [hzeller/rpi-rgb-led-matrix#287]
Hello Again,

I am using these led matrix plates and the problem with them is 1st and 9th line is internally connected so even if i write a sentence in first row it gets copied in the next row. As you can observe in picture "A W E" is repeated twice but I coded just for one row.
![image](https://cloud.githubusercontent.com/assets/13011818/22991295/cb13f95a-f3e1-11e6-841f-4c9b81e5b3fa.png)

Is there any library change which can fix this? Thanks for responding to previous post so quickly.  

Thank you 
Abhijeet

**Comment by hzeller** [comment]
* Do you have a picture of your Hub75 connector on your matrix ?
 * What command line parameters do you give the programs you run ?
 * do you know the multiplexing of your matrix from its documentation?

**Comment by Abhigyanabhijeet** [comment]
Yes sir!
I just acquired all data , here it is: 
A) image of Hub 75 

![led_matrix_socket2](https://cloud.githubusercontent.com/assets/13011818/23094480/d1f4e4d8-f61f-11e6-8548-308bc155d14a.png) 

In place of "CLK" its printed "S". "LAT" is replaced bu "L" and "GND" at bottom right is replaced by "Dg"

B) command line is exactly this ->  $ sudo ./demo -D 1 runtext.ppm

C) No documentation was provided by seller. But we have "Q6A-SL(M4)(1X2)192X192H" Board name mentioned

**Comment by Abhigyanabhijeet** [comment]
Board Name is "q6d8v5"

**Comment by hzeller** [comment]
Sounds like you might have a 1:8 multiplexing in a way that the second and forth stripe is just the longer part of the rest.
Try `--led-rows=16 --led-chain=2` and observe how things look.
