### ISSUE TITLE
Wrong color.

### ISSUE THREAD

**Issue by nutthakun** [hzeller/rpi-rgb-led-matrix#289]
Hi i use 32x64 led panel connect 2 parallel by jumper wire. In parallel2 color is wrong at row 1-16 but 17-32 is work. 
help me please. 

https://goo.gl/photos/57s8pkximVGq3wJn7
https://goo.gl/photos/vPFoAtwydmAHxVYj8

Thank you.

**Comment by nutthakun** [comment]
I use raspi 2 and raspi 3 it same problem.

**Comment by hzeller** [comment]
This symptom looks like you might need 3.3V -> 5V logic level converter.

**Comment by nutthakun** [comment]
Thank you for answer.
Use this for all gpio of row2 or use R1 G1 B1 only ?
http://112.124.9.237/images/0E92A13C47924EE889EDABC0336B64F5.jpg

**Comment by hzeller** [comment]
You need it for all data lines. I usually use 74HCT245.
See https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/adapter/active-3
