### ISSUE TITLE
Active-RPi-3xHub75-Adapter

### ISSUE THREAD

**Issue by GnuPP** [hzeller/rpi-rgb-led-matrix#29]
Hi,
I want to buy your adapter but I expect the board will be delivered without the IC etc.
So can you tell me which components are needed?

Thanks

**Comment by hzeller** [comment]
Yes, OshPark just sends the bare board.
As components, you need 
  4x 74hct245 in a 20-TSSOP  package
  4x 100nF ceramic capacitor
  1x 40pin (2x20) female connector to connect to the RPi
  3x16pin (2x8) male IDC box connector
