### ISSUE TITLE
Are LED Matrices required?

### ISSUE THREAD

**Issue by codyohlsen** [hzeller/rpi-rgb-led-matrix#290]
Why can't I still use this library with several strips stacked together into a matrix?

**Comment by ahlynsky** [comment]
Yes I also have this question.  I'm trying to use a logic converter to step the 3.7v up to 5v, and run a single APA102 50 LED strand.  Has anyone else tried this?

**Comment by hzeller** [comment]
This library is not for LED strips, but for the Hub75 LED matrices.
Programmable LED strips are an entirely different thing and can be dealt with e.g. https://github.com/hzeller/spixels
