### ISSUE TITLE
RGB order is swapped

### ISSUE THREAD

**Issue by HakanL** [hzeller/rpi-rgb-led-matrix#291]
I have some P6 32x32 panels (Aliexpress) and I was able to create a Transformer to support the layout, but Red and Blue are swapped. I did a quick hack in framebuffer.cc and it works, but I think it would be better to have an option to specify the RGB order on the command line (like --led-rgb-order RGB or GRB, etc).

**Comment by hzeller** [comment]
There is now an option `--led-rgb-sequence` that allows to choose the order.
(added in https://github.com/hzeller/rpi-rgb-led-matrix/commit/efe8a77f1958c342f97a3ac7f7d0601e02c30b6a )
