### ISSUE TITLE
[question] audio with matrix

### ISSUE THREAD

**Issue by aycgit** [hzeller/rpi-rgb-led-matrix#294]
i am thinking of buying a rgb matrix to use with this  api but in the readme is stated that it doesn't work with audio, is there a way to find out if it works before buying it? i checked lsmod and bcm2835 is in there. Does it always not work if that is enabled? i really want to use my pi as sound system and as matrix system. thanks in advance

**Comment by hzeller** [comment]
It won't work with the internal audio unless you tolerate more flickering and disable hardware pulse generation (not recommended). But what you can do is to add a $5 usb external audio adapter, which will work. It also is much  better audio quality than the RPi built-in audio anyway.
