### ISSUE TITLE
16x32 LED Bottom Half Blank

### ISSUE THREAD

**Issue by LordHoratio** [hzeller/rpi-rgb-led-matrix#295]
When I run the demos with the setting for 16 rows, only the top half displays. Interestingly,  when I tried the 8 row setting it only displayed the top 4 rows. Also, I tried messing with gpio slowdown which had no effect. I troubleshooted all address pins and they all work fine.

**Comment by LordHoratio** [comment]
It might be a multiplexing issue, but I lack the expertise to fix it.

**Comment by cobr4a** [comment]
check wiring of the "D" pinout of the HUB75 to 22 pin on Rasp GPIO.
