### ISSUE TITLE
Formatting broken in wiring.md

### ISSUE THREAD

**Issue by Mezgrman** [hzeller/rpi-rgb-led-matrix#297]
The wiring table is broken, rendered as a code block and just a mess of text and emoji. Makes it more or less impossible to see what's going on.

**Comment by hzeller** [comment]
Looks like github is in the process of messing up their markdown implementation. I'll contact them.

**Comment by Mezgrman** [comment]
Probably. I noticed that if I paste the code into an external Markdown viewer, it looks normal.

**Comment by hzeller** [comment]
Fixed in https://github.com/hzeller/rpi-rgb-led-matrix/commit/10d120782e0e8af44b2be524dfa8d3d0ee365972
