### ISSUE TITLE
Problem of Accessing  32x32Panel 1:8 scan rate 

### ISSUE THREAD

**Issue by alexdisoza007** [hzeller/rpi-rgb-led-matrix#299]
Dear Henner,

I am facing the problem of accessing 32x32Panel , I gone through issue #66. I made change in transformer.cc and transformer.h, I written class like this:
In **transformer.cc**

`class CrazyChineseTransformer::TransformCanvas : public Canvas {
	public:
		TransformCanvas(): delegatee_(NULL) {}
		void SetDelegatee(Canvas* delegatee);
		virtual void Clear();
		virtual void Fill(uint8_t red, uint8_t green, uint8_t blue);
		virtual int width() const;
		virtual int height() const;
		virtual void SetPixel(int x, int y, uint8_t red, uint8_t green, uint8_t blue);
	private:
		Canvas *delegatee_;
	};
	void CrazyChineseTransformer::TransformCanvas::SetDelegatee(Canvas* delegatee) {
		delegatee_ = delegatee;
	}
       void CrazyChineseTransformer::TransformCanvas::Clear() {
		delegatee_->Clear();
	}
	void CrazyChineseTransformer::TransformCanvas::Fill(uint8_t red, uint8_t green, uint8_t blue) {
		delegatee_->Fill(red, green, blue);
	}
	int CrazyChineseTransformer::TransformCanvas::width() const {
		return delegatee_->width()/2;
	}
	int CrazyChineseTransformer::TransformCanvas::height() const {
		return delegatee_->height()*2;
	}
	void CrazyChineseTransformer::TransformCanvas::SetPixel(int x, int y, uint8_t red, uint8_t green, uint8_t blue) {
		int new_x = 0;
		int new_y = 0;
		new_x = ((x / 32) * 64) + (x % 32);
		if ((y & 8) == 0) {
			new_x += 32;
		}
		new_y = ((y / 16) * 8) + (y % 8);
		delegatee_->SetPixel(new_x, new_y, red, green, blue);
	}
	CrazyChineseTransformer::CrazyChineseTransformer() 
		: canvas_(new TransformCanvas()) {}

	CrazyChineseTransformer::~CrazyChineseTransformer() {
		delete canvas_;
	}
	Canvas *CrazyChineseTransformer::Transform(Canvas *output) {
		assert(output != NULL);

		canvas_->SetDelegatee(output);
		return canvas_;
	}
`
**Transformer.h** 

`class CrazyChineseTransformer : public CanvasTransformer {
	public:
		CrazyChineseTransformer();
		virtual ~CrazyChineseTransformer();

		virtual Canvas *Transform(Canvas *output);
		void AddTransformer(CanvasTransformer *transformer);
		void DeleteTransformers();

	private:
		class TransformCanvas;

		TransformCanvas *const canvas_;
	};`
I am calling this class in **demo-main** like
`RGBMatrix *matrix = CreateMatrixFromOptions(matrix_options, runtime_opt);
  if (matrix == NULL)
    return 1;
//*********************************************************************************//
	CrazyChineseTransformer *transformer = new CrazyChineseTransformer();
	matrix->SetTransformer(transformer);
	
//******************************************************************************
  if (large_display) {
    // Mapping the coordinates of a 32x128 display mapped to a square of 64x64.
    // Or any other U-arrangement.
    matrix->ApplyStaticTransformer(UArrangementTransformer(
                                     matrix_options.parallel));
  }

  if (rotation > 0) {
    matrix->ApplyStaticTransformer(RotateTransformer(rotation));
  }

  printf("Size: %dx%d. Hardware gpio mapping: %s\n",
         matrix->width(), matrix->height(), matrix_options.hardware_mapping);

  Canvas *canvas = matrix;`

I am passing arguments like this  `sudo ./demo -D 1 -r16 runtext.ppm`  I am little bit confusing in this, Could you please help me and give me some tips, information, how to program 32x32 panels with 1:8 scan rate? I will be really grateful. This how my Ledmatrix is running https://www.youtube.com/watch?v=thPB6ORebg0](url)

![Uploading IMG_20170405_175327.jpg…]()
![Uploading IMG_20170405_175343.jpg…]()

Thanks, 
Alex

**Comment by possenhalter** [comment]
@alexdisoza007 I succeeded in getting [this](https://www.aliexpress.com/item/192x192mm-p6-led-panel-indoor-full-color-SMD-led-modules-32x32-pixel-1-16-scan-led/32537649016.html?spm=2114.13010608.0.0.vNArVX) 32x32 1:8 panel to work with the library.

I'm currently using the [Go binding](https://github.com/mcuadros/go-rpi-rgb-led-matrix), but I think this could be useful for you anyway.

I had to set the following parameters:

```go
rows       = flag.Int("led-rows", 32, "number of rows supported")
parallel   = flag.Int("led-parallel", 1, "number of daisy-chained panels")
chain      = flag.Int("led-chain", 2, "number of displays daisy-chained")
```
and use this transformation logic (I think it's same as yours):
```c
tx = x;
if ( y % 16 < 8 ) {
    tx = x + 32;
}
```
Hope it will help,
Zoltan

**Comment by hzeller** [comment]
Please check out the new option `--led-multiplexing` https://github.com/hzeller/rpi-rgb-led-matrix#multiplexing
It does the mapping built into the library (and can also be used from Python.)
(You need to do a fresh checkout and compile, this just went in).
