### ISSUE TITLE
Active-3 adapter & Secondary I2c - Yes?

### ISSUE THREAD

**Issue by Timelord0** [hzeller/rpi-rgb-led-matrix#312]
First off, this project is absolutely awesome, and it has inspired me to take up learning C++ (among other things).  Thank you so much for providing this.  Someday I do hope my code is worth sharing with others as well. :)

As for the question: I see no reason why it would not work, but would the secondary I2C bus (pin 28 & 29) still be able to be used with the Active-3 board?

**Comment by hzeller** [comment]
If you only use one chain, then Pin 28 & 29 are not used, so you can do that.
