### ISSUE TITLE
LED not turning on at all

### ISSUE THREAD

**Issue by navinjethani** [hzeller/rpi-rgb-led-matrix#315]
Hello Everybody

I am working on a fun project using LED Matrix

Issue:
LED are NOT turning ON at all with this library/code for me.
I have tried examples-api-use and python also.
Both of them are NOT turning the LED.

The experimental python code listed on Adafruit is working ALL the time.
I see the three rectangles with proper colors

https://learn.adafruit.com/connecting-a-16x32-rgb-led-matrix-panel-to-a-raspberry-pi/experimental-python-code

Debugging:
a. Verified that experimental python code is working (ensures that the connections are done properly)
b. Verified that on board audion is turned OFF
dtparam=audio=off in /boot/config.txt
c. Able to compile the code without any issues

Any help would be highly appreciated

**Comment by hzeller** [comment]
Please read the Readme of _this_ library and make sure to have the right wiring. Or, if you have an Adafruit Hat, use the right option to switch to that wiring.
