### ISSUE TITLE
it's limited

### ISSUE THREAD

**Issue by beikimajid** [hzeller/rpi-rgb-led-matrix#316]
Hi hzeller,
I noticed that your Program only supports the boards have this property:
Scan_Multiplexing = (2 / ROWS_of_panel)
for example 16x32 1/8 scan , 32x64 1/16 scan , 32x32 1/16 scan , 64x64 1/32 scan   Which are in Group indoor Panel.
Are you going to do to complete the program to support **outdoor** panel for example 32x64 1/8 scan, 16x32 1/4 scan,16x32 1/2 scan without external Pixel Mapping?

Thank you very much

**Comment by hzeller** [comment]
Outdoor panels are working the same and you an use them directly with this library without change. You just need to do a different Pixel mapping that you then can plug into the static transformer function (see the section in the Readme about it or various people who have done that for their outdoor panels).

It is on my TODO list to integrate these outdoor pixel mappings directly in this library, but I only really can do that once I have access to such panels myself to experiment with. As usual with open source software, having enough spare time and funds to acquire the needed hardware are the limiting factor :)
