### ISSUE TITLE
.bdf font not working

### ISSUE THREAD

**Issue by Anrban** [hzeller/rpi-rgb-led-matrix#323]

**Comment by Anrban** [comment]
Hi,
i generated .bdf font of sizr 32x32 using fontforge. This file works fine with rpi-rgb-led-matrix but when i add it to flaschen-taschen there is no display. can i know what may be the possible cause and its remedy

**Comment by hzeller** [comment]
There was a recent fix in how fonts are parsed in rpi-rgb-led-matrix that fixed some issue with certain BDF files. So if you use the text library in FlaschenTaschen, you need to do that there.

So technically this is a bug in FlaschenTaschen, not in this library that does it right, so I am closing it here. Please open a bug in the FlaschenTaschen repo.
