### ISSUE TITLE
make build-python compilation error

### ISSUE THREAD

**Issue by DO7LZ** [hzeller/rpi-rgb-led-matrix#324]
Hi,

first of all, I would like to thank Henner Zeller for serving this piece of delicious code for accessing the RGBMatrix panels via the Raspberry Pi. But trying to compile the code for python will result in some error on my machine.

`make build-python
make -C ./lib
make[1]: Entering directory '/home/pi/rgbmatrix/rpi-rgb-led-matrix/lib'
make[1]: Leaving directory '/home/pi/rgbmatrix/rpi-rgb-led-matrix/lib'
make -C python build
make[1]: Entering directory '/home/pi/rgbmatrix/rpi-rgb-led-matrix/python'
make -C ../lib
make[2]: Entering directory '/home/pi/rgbmatrix/rpi-rgb-led-matrix/lib'
make[2]: Leaving directory '/home/pi/rgbmatrix/rpi-rgb-led-matrix/lib'
python setup.py build --build-lib .
running build
running build_py
running build_ext
building 'core' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../include -I/usr/include/python2.7 -c rgbmatrix/core.cpp -o build/temp.linux-armv7l-2.7/rgbmatrix/core.o -O3 -Wall
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/include/python2.7/Python.h:58:0,
                 from rgbmatrix/core.cpp:4:
/usr/include/python2.7/pyport.h:510:1: warning: null character(s) ignored
`

then there will come up about 1000 lines of other stuff (faded out regarding readability reasons) and at the end

`In file included from /usr/include/python2.7/Python.h:58:0,
                 from rgbmatrix/core.cpp:4:
/usr/include/python2.7/pyport.h:458:1: error: expected declaration before ‘}’ token
 }
 ^
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
Makefile:67: recipe for target 'build-python' failed
make[1]: *** [build-python] Error 1
make[1]: Leaving directory '/home/pi/rgbmatrix/rpi-rgb-led-matrix/python'
Makefile:33: recipe for target 'build-python' failed
make: *** [build-python] Error 2
`

The packages python-pil and python2.7-dev were installed. And the audio interface was disabled by blacklisting and changing the appropriate line on /boot/config.txt.

Raspbian was set up on this Raspberry Pi 3 yesterday and is up to date. The panels are connected via the Adafruit hat. The demo works. In the /lib/Makefile the following changes were made:

`HARDWARE_DESC?=adafruit-hat-pwm` 

and 

`HARDWARE_DESC=adafruit-hat-pwm`

As I am no expert on compiling source code with only some python skills, could you please help me?

Kind regards
Matthias

**Comment by hzeller** [comment]
you need to look at the place where it fails. For instance, in line 458 in pyport.h in your system, there is some issue which you need to pinpoint and fix. I suspect there is an issue with a type that for some reason is not defined on your system. Some detective work needed :) Good thing is: when done, you've reached next Ninja level in compilig stuff which helps next time.
