### ISSUE TITLE
How to / where to set library to make 16x32 by default 

### ISSUE THREAD

**Issue by SparkyXI** [hzeller/rpi-rgb-led-matrix#326]
Hello friends -

Looking to find out how to make 16x32 as the default (i.e., not having to set that flag [`at--led-rows=16`] with every command). There are obvious options per the readme relating to `DEFINES+=-DLSB_PWM_NANOSECONDS` or `DEFINES+=-DDISABLE_HARDWARE_PULSES`... anything like this for default number of rows?

Have tried `DEFINES+=-DLED_ROWS=16` to no avail...

**Comment by hzeller** [comment]
It is even simpler, you can do that directly in your code.

When you set-up your options before creating the matrix, you can set-up the defaults you need

```
RGBMatrix::Options matrix_options;
matrix_options.rows = 16;              // <- set the options you want as default.
matrix_options.chain_length = 1;
matrix_options.parallel = 1;
if (!ParseOptionsFromFlags(&argc, &argv, &matrix_options, &runtime_opt)) {
    return usage(argv[0]);
}
// ...
```
