### ISSUE TITLE
Active 3 PCB through-hole capacitor pads

### ISSUE THREAD

**Issue by depili** [hzeller/rpi-rgb-led-matrix#334]
Speaking of the active 3 PCB, on simple improvement would be to increase the size of the solder pads for the through-hole filter capacitor on power input. Currently the pads on the underside of the board are smaller than is usual for through-hole stuff. As the pads are still usable as-is this should be considered as a low priority improvement.

**Comment by hzeller** [comment]
Ok, done :)
