### ISSUE TITLE
P10 1/2 scan multiple pixel lit

### ISSUE THREAD

**Issue by beikimajid** [hzeller/rpi-rgb-led-matrix#336]
Hi
I have P10 16x32 1/2 scan.When i run pixel-test give me this result :
I send (0,0)  then  (7,0) (7,1) (7,4) (7,5) together lit.
I send (1,0)  then  (6,0) (6,1) (6,4) (6,5) together lit.
.
.
I send (7,0)  then  (0,0) (0,1) (0,4) (0,5) together lit.
I send (8,0)  then  (0,2) (0,3) (0,6) (0,7) together lit.

I use this pixel-mapping for 1/4 scan & it work (just 1 pixel lit):
int new_x = 0;
int new_y = 0;
if (y < 4 || (y > 7 && y < 12)) {
new_x = (x * -1) + (24 * ((x / 8) + 1)) - 17;
new_y = y;
} else {
new_x = x + (8 * ((x / 8) + 1));
new_y = y - 4;
}

I'm confused why several light goes on together in 1/2 scan.Can you help me to write transformer for 1/2 scan?

Thanks a lot

**Comment by beikimajid** [comment]
Who does not idea?

**Comment by hzeller** [comment]
You did not adhere to the rule of bug reporting: add all relevant information :)

You have not really specified your panel (size ?). How does the connector on the back look like (Does it only have A, no B, C ? Because 1:2 scan would be something like this). Did you figure out the pixel mapping by going through all available pixels one by one ?

**Comment by beikimajid** [comment]
Hi
As I said I use P10 16x32 1/2 scan.This is my module:
R1   G1
B2   GND
R2   G2   
B2   GND
A    B
NC  GND
CLK  LAT
OE GND

I've used the same module with 1/4 scan and it's OK.
But with 1/2 scan I can not figure out the pixel mapping by going through all available pixels one by one because as example when I send (0,0)  then (7,0) (7,1) (7,4) (7,5) together lit.

**Comment by beikimajid** [comment]
Does anyone have an idea?

**Comment by hzeller** [comment]
It is not clear why you want to use 1/2 scan (which would mean you would only use address `A`).

If multiple rows are lit, maybe you got a different kind of panel, that does some internal address advancing ?
