### ISSUE TITLE
Led-Image-Viewer update is not supporting .png .gif

### ISSUE THREAD

**Issue by primanator** [hzeller/rpi-rgb-led-matrix#339]
With the recent update the led-image-viewer gives "*** not a usable image format" when trying to display any .png or .gif.
Before update everything was running ok, checked it by downloading and compiling the december repository version.

I`m running RPi3 and 32x32 matrix.

**Comment by hzeller** [comment]
This is odd. Can you give a command line you are using, an example image and the version numbers of the graphics-magic libraries ?
Is there any other error message that is shown ?

**Comment by hzeller** [comment]
I've now added more diagnostic output, maybe it helps to figure out what is happening in your case.
I suppose you recompiled everything from scratch, with a nice `make clean` in the toplevel directory and then a `make` in the utils directory just in case there is something funny with the linking ?

**Comment by hzeller** [comment]
If it still doesn't work - do you see anything in the diagnostic output ?

**Comment by hzeller** [comment]
No response. Assuming it started working.
