### ISSUE TITLE
Define include paths for Matrix library in Geany?

### ISSUE THREAD

**Issue by jboyoli** [hzeller/rpi-rgb-led-matrix#340]
Hi.

I am able to compile and run my own projects using the makefile options as per your documentation but as I want to do more complex C code I would like to use Geany, Geany compile my code without errors (as long as I enter the full path to the library when using #includes    but it won't build the project as it has issues with dependencies. Is there a way in geany to define the library locations? or do you recomend any other C/C++ IDE to use in Rpi to use your wonderful MAtrix library?  

Thanks in advance.

**Comment by hzeller** [comment]
I don't know Geany, so you probably have to check their documentation. Maybe someone subscribing to the issue notifications know ?

Usually using external projects is just a matter of adding `-I` include paths for your includes and `-L` paths for linking. A typical example with standard Makefiles is shown in the [examples and API use page](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#integrating-in-your-own-application).

As for IDE, I usually just use emacs in Tramp mode, in which I can edit files on my 'big' machine and then saving will just store them remotely on the headless Raspberry Pi (as running a graphical UI is a bad idea as the Pi is so slow; also in particular you don't want it when you run the Matrix). When I call the emacs compile command, it also executes the make remotely, so very seamless integration.
