### ISSUE TITLE
Future consideration: Asus tinkerboard support?

### ISSUE THREAD

**Issue by depili** [hzeller/rpi-rgb-led-matrix#343]
Asus tinkerboard is a faster rpi-clone with the same form factor and gpio-header pinout as the pi. It would be quite attractive alternative for driving larger displays due to having about twice the raw computing power and twice the memory compared to the pi.

I haven't dug into the details about the access GPIO and how hard it would be to port the library to the tinkerboard, but maybe sometime...

https://www.asus.com/uk/Single-Board-Computer/Tinker-Board/

**Comment by hzeller** [comment]
These boards that claim to be 'compatible' are really not. They just provide a shallow layer to have GPIO access work from user space, but they are entirely different underneath.
This library uses the features of the Raspberry Pi.
