### ISSUE TITLE
Active3 adapter and 64x64 panel

### ISSUE THREAD

**Issue by chrisoutwright** [hzeller/rpi-rgb-led-matrix#344]
So far I got the components soldered on the board _(74HCT245D instead of 74HCT245, I wonder what the differences are)_  and the panel is working fine with chain=2.

I do have some questions, which arose during the process:

- How important are the 4x 100nF capacitors , as I am not sure if I broke one in my first SMD soldering attempt. The panels themselves are powered separately with caps on.

- I took extra care not to expose the logic shifters to excessive temperature when soldering, but still I had to fix a bridge now and then, will this be a problem lifespan-wise by dint of having exceeded temperature?

- As I used before an Adafruit HAT, I wonder also if there is still an equivalent of a "pwm-
 antiflicker" only for _gpio-mapping=regular_, or is it implemented automatically?

- Will a 4x 32x32 panels setup have the same refresh rate as one 64x64 panel?

Thanks for clearifying!

**Comment by hzeller** [comment]
* the 100nF capacitors are to provide a stable voltage to the HCT245 when they switch. But even if you break one, you're probably fine.
 * If after soldering the chips still work, you're probably fine. Yes they age faster if they get a lot of temperature, but with normal soldering and repairing you probably won't notice muche.
 * The `regular` hardware mapping already does the right thing with antiflicker.
 * The difference is, that 4x32x32 you can operate as two parallel chains of 2, while the 64x64 will only be on one chain, so it will be slower. You can test that, if you just give the options you would give to the program and output the refresh rate even with no board connected.
