### ISSUE TITLE
Glitches on the matrix

### ISSUE THREAD

**Issue by tychop** [hzeller/rpi-rgb-led-matrix#348]
Has anybody got some tips to solve these glitches?

![out](https://user-images.githubusercontent.com/80199/27917552-9a2110ae-626c-11e7-8527-d1f8a057109c.gif)

My power supply is 5v, 10Amps

And the command I ran was: `sudo ./demo --led-rows=32 --led-chain=2 --led-slowdown-gpio=3 --led-pwm-lsb-nanoseconds=1500 --led-slowdown-gpio=3 --led-no-hardware-pulse -D1 runtext16.ppm `

I think I tried most of the command parameters, but I keep seeing the glitches....

**Comment by maddogs** [comment]
Do you have anything that could be interfering in the background such as PiGPIO or 1 wire sensor

**Comment by hzeller** [comment]
Please read the troubleshooting section. This looks like you haven't disabled the 1 wire sensor. Also, do not use PiGPIO.

**Comment by tychop** [comment]
No, nothing.. Even the sound is turned off in /boot/config.txt.

**Comment by tychop** [comment]
@hzeller I understand it's not an issue with the library... Where do you think I should ask this question?

**Comment by hzeller** [comment]
The glitches you show look like the 1-wire sensor.
Also make sure to run Raspbian Lite as the regular Raspbian packs all kinds of things on there that might interfere with your GPIO.

**Comment by tychop** [comment]
Thnx!, I'll go and get the raspbian light. That sounds like it could help.

**Comment by tychop** [comment]
Awesome. Installed the lite version and all is peachy with just the nr of rows & chain.
👍🏻
