### ISSUE TITLE
led-image-viewer does nothing

### ISSUE THREAD

**Issue by felixmc** [hzeller/rpi-rgb-led-matrix#35]
I have a raspberry pi version 1 running latest Raspbian and a 32x32 LED matrix. All the "led-matrix" demos work as expected. I have the "libgraphicsmagick++1-dev" installed and "led-image-viewer" builds without any issues.

However, whenever I try to run "led-image-viewer", nothing happens on the LED matrix (stays completely off the whole time). I tried running it with a variety of images with different formats and dimensions. This is the output of running the command (which seems normal):  
![command screenshot](https://photos-4.dropbox.com/t/2/AABmoXMS2Shi97tPnHGX40evkC3GMouAUk2n-ao7VCxGTQ/12/10719862/png/32x32/1/1434952800/0/2/Screenshot%202015-06-21%2022.06.33.png/CPakjgUgASACIAMgBCAFIAYgBygBKAIoBw/zz4s_V4Hu17JO_5VA6_wj_U-sUK8GZ_4-GWZPaaVwBU?size=1280x960&size_mode=2)

Any ideas on why it might not work or what steps I can take to further debug this?

**Comment by hzeller** [comment]
I don't see the output, looks like the image does not exist. Can you just copy/paste the terminal output ?

**Comment by felixmc** [comment]
Sorry, not sure what happened to the image, here's a direct Dropbox link to it: https://www.dropbox.com/s/rqs3capnglcwabu/Screenshot%202015-06-21%2022.06.33.png?dl=0

**Comment by hzeller** [comment]
Do you have a fresh checkout of the repository ? There was a brief phase when the image viewer code didn't work. Could you try with a fresh pull ?

**Comment by felixmc** [comment]
pulled down again and rebuilt led-image-viewer and everything worked on the first try :)
