### ISSUE TITLE
Ideas on dynamic char spacing with DrawText()

### ISSUE THREAD

**Issue by chrisoutwright** [hzeller/rpi-rgb-led-matrix#357]
I am not sure if the method DrawText() is already using a kind of dynamic spacing (apart from the fixed max width of the font itself) depending on adjacent letters. 

A quick look at the 10x20.bdf file, does reveal a fixed type, and that individual spacing would better be found in another bdf file. But none-the-less I try to use this bdf file as starting font.

The idea is also to implement a typewriter effect with DrawText, so that this work could serve another purpose if space fixing is achieved alot easier with the font file itself.

Notice, in this code, I have added font.width() as a attribute call, which needed some code additions to lib files.

Would there be an easier method instead of using DrawText() for every "single character" string with a lookup spacing table like this? :

	float letw(char value) {
		switch (value) {
			case 'L': return 2;
			case 'l': return 2;
			case 'r': return 2;
			case 'i': return 2;
		case '|': return 1.4;
		case ':': return 1.8;
		case '\'': return 1.5;
			default: return 2;
		}
	}

Well, ideally, the lookup would be a 'matrix' to account for different spacings of letters before and after the middle letter in question, but this would surely be a big table. This version averages the changed width on both sides equally, as seen next.

And for the main loop, asserting `pch` is a string for a single row and `go` its index counter:

			int pchlen = strlen(pch);
			for (int go=0; go<pchlen;go++) {
					
					char theval[2] = {0};
					theval[0] = pch[go];

					if (letw(pch[go-1])!=2 && letw(pch[go])==2) 
						{xlan = xlan+(font.width()*(letw(pch[go-1])/2));
					}

					rgb_matrix::DrawText(offscreen_canvas, font, x + xlan, y + font.baseline(), color, theval);
							
					if ((letw(pch[go+1])==2) && (letw(pch[go])==2) && (go != pchlen-1)) {
						xlan = xlan+(font.width()*(letw(pch[go])/2));
					}
					if ((letw(pch[go+1])!=2) && (go != pchlen-1)) {
						xlan = xlan+(font.width()*(letw(pch[go+1])/2));
					}
					
					
				}

It does work in my case but seems like a lot of overhead work,
Printing every Char on each turn seems btw. as a nice way to implement a typewriter effect on the panel.
Not sure if this code so far makes sense for it right now in terms of readability or make of use.

**Comment by hzeller** [comment]
You might want to use the `font.DrawGlyph()` method directly if you are essentially going through the characters character by character (essentially have a look at how [DrawText() is implemented](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/graphics.cc#L28)).

Note that your string-processing is assuming ASCII text, while we are doing UTF-8 here; so you need to use the UTF-8 character iterator to be correct.

Most of the fonts in the fonts directory are fixed width, but for instance the `helvR12.bdf` is a proportional font with varying distance.

**Comment by chrisoutwright** [comment]
I've must have overlooked the implementation of DrawText(), when I searched for it with the search function of github. Thank you for the link, this makes it all much clearer. I will try to use DrawGlyph for my case.
Just another question, as pointed out prior. Would you implement a typewriter effect in a similar way like I tried to implement or would you do it altogether differently?

**Comment by chrisoutwright** [comment]
Is this what you mean by UTF-8 Iterator?
`char um1[30];
	std::string um2 =u8"ES@K@IST@U@FÜNF";
	strncpy(um1,um2.c_str(),30);
	
    char* whole[] = {um1,"ZEHN@ZWANZIG"}; `

Some special characters like "1 over 4" are displayed but not letters with diaeresis  like ü, also when I use escape characters, it does not work in my case. 
Am I misunderstanding something seriously?

**Comment by hzeller** [comment]
You need to properly encode your character as UTF-8. The byte-sequence for codepoint 0xDC is 0xC3 0x9C. Values above 0x7F become a multi-byte sequence ([Read about UTF-8 encoding on wikipedia](https://en.wikipedia.org/wiki/UTF-8)).

It probably works in Python because Python does the right thing on encoding strings internally UTF-8. If you write code with your editor, make sure set your editor to UTF-8 (some really old installations still use Latin1 for instance) or give your string literals the right byte sequence "\u00DC" (if you give u8"..." you still need the text be properly encoded).
(also make sure, if you haven't already, that your locale does UTF-8 by default, e.g. en_US.UTF-8 or de_DE.UTF-8; this is the LC_ALL environment variable).

Don't use wchars, they make life miserable. They are a sad legacy from early Windows implementations...

The UTF-8 iterator is going through a byte string and extract the codepoints [lib/utf8-internal.h](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/utf8-internal.h). It is used internally to the DrawText() function, so I thought you had seen it.

**Comment by chrisoutwright** [comment]
Thank you very much for your reply.
At first sight I also thought it could work with \xC3\x9C. Then after testing nearly everything, including testing wide chars, I found my error:

for (int go=0; go<pchlen;go++) {
				
				char theval[2] = {0};
				theval[0] = pch[go];

				if (letw(pch[go-1])!=2 && letw(pch[go])==2 && (go!=0)) 
					{xlan = xlan+(font.width()*(letw(pch[go-1])/2));
				}
				
				rgb_matrix::DrawText(offscreen_canvas, font, x + xlan, y + font.baseline(), color, theval);
				
				
							
				
				
				if ((letw(pch[go+1])==2) && (letw(pch[go])==2) && (go != pchlen-1)) {
					xlan = xlan+(font.width()*(letw(pch[go])/2));
				}
				if ((letw(pch[go+1])!=2) && (go != pchlen-1)) {
					xlan = xlan+(font.width()*(letw(pch[go+1])/2));
				}
		
			}

So reading in every singly character to the DrawText method will naturally destroy any two byte sequence of chars in this way, no matter how they came in!!

I found this when I changed the first row umlaut and the other rows were changed as well, this is sort of segmentation fault maybe. At least I can work at a workaround, maybe use drawglyph. Any ideas how to read in single characters with drawtext or drawglyph which works with umlaut?

**Comment by hzeller** [comment]
> Any ideas how to read in single characters with drawtext or drawglyph which works with umlaut?

As I said, use the iterator  I mention above. It goes through your character sequence and extracts the codepoints one after another.

**Comment by chrisoutwright** [comment]
Thanks again, I will have a try with the iterator for this matter. Just a single question about the character length. A string like "Olé" will be always counted as length=4 with char type right (not accounting '\0')? 

Could an iterator be modified to express the true length or would I then need the _(in Linux world)_ unloved and unneded wide chars methods like cwslen()?

It would help with the final resolution of the whole matter. Thank you

**Comment by hzeller** [comment]
As with regular `strlen()`, which walks each character until you reach `\0`, the equivalent for UTF-8 would be to use the iterator to go through all characters and count them. So this is what you would do if you needed the length of the string (but you don't really in your application as you can just go from left to right). There are also libraries to determine the stringlength of a UTF-8 string (but I encourage you to write the one-liner `while()` loop with the provided `utf8_next_codepoint()` as exercise.

Wide characters are universally unloved not only in the Linux world. They only make sense if they are 32 bit wide and thus only really useful in applications that need direct access to particular characters (i.e. using an index).

The problem with wchar is, that it typically is 16 bit, so it still can't represent all of Unicode (it only worked early 90ies when there were so few chracters defined). So even with that you wouldn't be able to represent a string. You can, by storing a string of uint32_t, but that is somewhat memory inefficient. The beauty of UTF-8 is, that it is compact and still will work typically with old school string operations, as it as well doesn't contain any NUL characters (so e.g. `strcpy()` will just work, or iterating to `\0` if you are only interested in the bytes). Unless you go full 32 bit, don't use wchar's they are a thing of the past and generally painful.

The main problem is, that you attempt to solve your problem by assuming you can index characters, which you can't as UTF-8 is a run-length encoded format. There are two ways to solve this: you either convert everything into a uint32 array with codepoints first (which uses more memory), or you rewrite your code in a way that you only stream through the characters one by one (better solution).

**Comment by chrisoutwright** [comment]
I got take a closer look at the method `uint32_t utf8_next_codepoint()`.
As I could infer with the letter Ü (0xc3,0x9c) it combines (c3 fulfilling the first multibyte if condition) it combines it to 0xDC. The iterator `uint32_t cp = *it++;` is in fact already looking at the possible next byte of the multibyte of the utf8_text. 
My single letter method was failing because the second part of Ü (0x9c) was simply not saved in char `theval[2] = {0}; theval[0] = pch[go];`, which I needed to pass along single letters. 
So I would have to make sure the whole multibyte is passed along, and I would be fine.

Thanks for the help so far. This topic can now be closed due to near success. ;-)

**Comment by chrisoutwright** [comment]
Just to demonstrate what I described above, the code for the simulated word clock would look like this, using the bad wchar_t fix

Used file to load:

`ES@K@IST@U@FÜNF
ZEHN@ZWANZIG
DREIVIERTEL
NACH@T@VOR@AUS
HALB@G@SECHS@E
ZWEI@S@AM@NULL
H@ELF@FÜNF@VIER
DR@EÜ@N@S@IEBEN
L@ACHT@E@ZWÖLF
ZEH@N@EUN@M@UHR`

`
// This code is public domain
// (but note, that the led-matrix library this depends on is GPL v2)

#include "led-matrix.h"
#include "graphics.h"
#include <iostream>
#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#include <sys/time.h>
#include <ctime>
#include <stdlib.h>
#include <fstream>
#include <locale>
#include <boost/locale/encoding_utf.hpp>
#include <cwchar>



// These methods are for the bad fix to count umlaute with correct length
using boost::locale::conv::utf_to_utf;

std::wstring utf8_to_wstring(const std::string& str)
{
    return utf_to_utf<wchar_t>(str.c_str(), str.c_str() + str.size());
}

std::string wstring_to_utf8(const std::wstring& str)
{
    return utf_to_utf<char>(str.c_str(), str.c_str() + str.size());
}






using namespace rgb_matrix;

static int usage(const char* progname)
{
    fprintf(stderr, "usage: %s [options]\n", progname);
    fprintf(stderr, "Reads text from stdin and displays it. "
                    "Empty string: clear screen\n");
    fprintf(stderr, "Options:\n");
    rgb_matrix::PrintMatrixFlags(stderr);
    fprintf(stderr,
        "\t-f <font-file>    : Use given font.\n"
        "\t-b <brightness>   : Sets brightness percent. Default: 100.\n"
        "\t-x <x-origin>     : X-Origin of displaying text (Default: 0)\n"
        "\t-y <y-origin>     : Y-Origin of displaying text (Default: 0)\n"
        "\t-C <r,g,b>        : Color. Default 255,255,0\n");
    return 1;
}

static bool parseColor(Color* c, const char* str)
{
    return sscanf(str, "%hhu,%hhu,%hhu", &c->r, &c->g, &c->b) == 3;
}

char* time_o()
{
    time_t timer;
    //   char buffer[26];
    char buffer2[26];
    struct tm* tm_info;

    time(&timer);
    tm_info = localtime(&timer);

    //  strftime(buffer, 1024, "%Y-%m-%d", tm_info);
    //   strftime(buffer2, 26, "%H:%M:%S", tm_info);
    strftime(buffer2, 26, "%M", tm_info);

    return buffer2;
}

//For later use, spacing table, when letter-by-letter is fixed

float letw(char value)
{
    switch (value) {
    case 'L':
        return 2;
    case 'l':
        return 2;
    case 'r':
        return 2;
    case 'i':
        return 2;
    case '|':
        return 1.4;
    case ':':
        return 1.8;
    case '\'':
        return 1.5;
    case 'B':
        return 2;
    default:
        return 2;
    }
}


//Definitions for counters
char mb[20];
int mb2 = 0;




int main(int argc, char* argv[])
{
    RGBMatrix* canvas = rgb_matrix::CreateMatrixFromFlags(&argc, &argv);

    char temp2[26];
    char bufferwc[40];
    wchar_t* buffer;
    std::wstring tempwc;
    
	
	//Reading in the clock text overlay

    FILE* myfile = fopen(
        "/home/pi/new-rgb/rpi-rgb-led-matrix-master/examples-api-use/love.txt",
        "r");
    if (!myfile) {
        fprintf(stderr, "%s", "Could not open file \"love.txt\".\n");
        return 1;
    }

    Color black(0, 0, 0);

    Color color(255, 255, 0);
    Color color0(255, 255, 0);
    Color color1(255, 255, 0);
    Color color2(255, 255, 0);
    Color color3(255, 255, 0);
    Color color4(255, 255, 0);

    const char* bdf_font_file = NULL;
    int x_orig = 0;
    int y_orig = -1;
    int brightness = 100;

    // Colors q-1,w-2,e-3,r-4
    int opt;
    while ((opt = getopt(argc, argv, "x:y:f:C:b:q:w:e:r:")) != -1) {
        switch (opt) {
        case 'b':
            brightness = atoi(optarg);
            break;
        case 'x':
            x_orig = atoi(optarg);
            break;
        case 'y':
            y_orig = atoi(optarg);
            break;
        case 'f':
            bdf_font_file = strdup(optarg);
            break;
        case 'C':
            if (!parseColor(&color, optarg)) {
                fprintf(stderr, "Invalid color spec.\n");
                return usage(argv[0]);
            }
            break;
        case 'q':
            if (!parseColor(&color1, optarg)) {
                fprintf(stderr, "Invalid color spec.\n");
                return usage(argv[0]);
            }
            break;
        case 'w':
            if (!parseColor(&color2, optarg)) {
                fprintf(stderr, "Invalid color spec.\n");
                return usage(argv[0]);
            }
            break;
        case 'e':
            if (!parseColor(&color3, optarg)) {
                fprintf(stderr, "Invalid color spec.\n");
                return usage(argv[0]);
            }
            break;
        case 'r':
            if (!parseColor(&color4, optarg)) {
                fprintf(stderr, "Invalid color spec.\n");
                return usage(argv[0]);
            }
            break;

        default:
            return usage(argv[0]);
        }
    }

    if (bdf_font_file == NULL) {
        fprintf(stderr, "Need to specify BDF font-file with -f\n");
        return usage(argv[0]);
    }

    if (canvas == NULL)
        return 1;

    /*
 * Load font. This needs to be a filename with a bdf bitmap font.
 */
    rgb_matrix::Font font;
    if (!font.LoadFont(bdf_font_file)) {
        fprintf(stderr, "Couldn't load font '%s'\n", bdf_font_file);
        return usage(argv[0]);
    }

    if (brightness < 1 || brightness > 100) {
        fprintf(stderr, "Brightness is outside usable range.\n");
        return 1;
    }

    canvas->SetBrightness(brightness);

    bool all_extreme_colors = brightness == 100;
    all_extreme_colors &= color.r == 0 || color.r == 255;
    all_extreme_colors &= color.g == 0 || color.g == 255;
    all_extreme_colors &= color.b == 0 || color.b == 255;
    if (all_extreme_colors)
        canvas->SetPWMBits(1);
	
	
	
	//Some further definitions
	
    const int x = x_orig;
    int y = y_orig;
    
    
    color0 = color;
    int xlan = 0;
	
    
    wchar_t* pchwc;
    
    int a = 0;
    int minu = 0;
    strncpy(temp2, time_o(), 26);
    std::string line;
    FrameCanvas* offscreen_canvas = canvas->CreateFrameCanvas();

    while (a < 10) {
        while (fgets(bufferwc, sizeof(bufferwc), myfile)) {
			
			
			/* All further methods work with wide char till DrawText(), 
				before it I convert it back to UTF-8 */
				
			// Therefore lets convert catched lines to wide chars
			
            tempwc = utf8_to_wstring(bufferwc);
            wchar_t temp[wcslen(tempwc.c_str())];
            wcscpy(temp, tempwc.c_str());

            const size_t last = wcslen(temp);
            if (last > 0)
                temp[last - 1] = '\0'; // remove newline.

			
			
			
			// Stuff for row spacing and placing text to rows or clearing Matrix
			
            if ((y + font.height() > canvas->height())) {
                offscreen_canvas->Clear();

                y = y_orig;
            }

            if (y < y_orig + font.height()) {
				
				
				// Catch the first row to initiate update for time string!
                strncpy(temp2, time_o(), 2);
                //	int minu;
                minu = atoi(temp2);
            }
			
			
			// New part to catch seperators to group row line to words!
			
			/* The switches are a test instead of ifs, to change colors 
			of single words in specific rows to active or black! */

            int wort = 0;

            for (pchwc = wcstok(temp, L"@", &buffer); pchwc != NULL; wort++) {

                switch (a) {

                case 0:
                    switch (wort) {
                    case 0:
                        color = color1;
                        break;
                    case 1:
                        color = color4;
                        break;
                    case 2:
                        color = color1;
                        break;
                    case 3:
                        color = color1;
                        break;
                    case 4:
                        color = color1;
                        break;
                    }
                    break;

                case 1:
                    switch (wort) {
                    case 0:
                        color = color1;
                        break;
                    case 1:
                        color = color4;
                        break;
                    case 2:
                        color = color1;
                        break;
                    case 3:
                        color = color1;
                        break;
                    case 4:
                        color = color1;
                        break;
                    }
                    break;

                case 2:
                    switch (wort) {
                    case 0:
                        color = color1;
                        break;
                    case 1:
                        color = color4;
                        break;
                    case 2:
                        color = color1;
                        break;
                    case 3:
                        color = color1;
                        break;
                    case 4:
                        color = color1;
                        break;
                    }
                    break;
                case 3:
                    switch (wort) {
                    case 0:
                        color = color1;
                        break;
                    case 1:
                        color = color4;
                        break;
                    case 2:
                        color = color1;
                        break;
                    case 3:
                        color = color1;
                        break;
                    case 4:
                        color = color1;
                        break;
                    }
                    break;

                case 4:
                    switch (wort) {
                    case 0:
                        color = color1;
                        break;
                    case 1:
                        color = color4;
                        break;
                    case 2:
                        color = color1;
                        break;
                    case 3:
                        color = color1;
                        break;
                    case 4:
                        color = color1;
                        break;
                    }
                    break;

                case 5:
                    switch (wort) {
                    case 0:
                        color = color1;
                        break;
                    case 1:
                        color = color4;
                        break;
                    case 2:
                        color = color1;
                        break;
                    case 3:
                        color = color1;
                        break;
                    case 4:
                        color = color1;
                        break;
                    }
                    break;

                case 6:
                    switch (wort) {
                    case 0:
                        color = color1;
                        break;
                    case 1:
                        color = color4;
                        break;
                    case 2:
                        color = color1;
                        break;
                    case 3:
                        color = color1;
                        break;
                    case 4:
                        color = color1;
                        break;
                    }
                    break;

                case 7:
                    switch (wort) {
                    case 0:
                        color = color1;
                        break;
                    case 1:
                        color = color4;
                        break;
                    case 2:
                        color = color1;
                        break;
                    case 3:
                        color = color1;
                        break;
                    case 4:
                        color = color1;
                        break;
                    }
                    break;

                case 8:
                    switch (wort) {
                    case 0:
                        color = color1;
                        break;
                    case 1:
                        color = color4;
                        break;
                    case 2:
                        color = color1;
                        break;
                    case 3:
                        color = color1;
                        break;
                    case 4:
                        color = color1;
                        break;
                    }
                    break;

                case 9:
                    switch (wort) {
                    case 0:
                        color = color1;
                        break;
                    case 1:
                        color = color4;
                        break;
                    case 2:
                        color = color1;
                        break;
                    case 3:
                        color = color1;
                        break;
                    case 4:
                        color = color1;
                        break;
                    }
                    break;
                }
				
				
				/* End of switch, huh, lets save the exact length of our word 
				and convert the characters to utf-8/char */
				
                int pchwclen = wcslen(pchwc);
                std::string lol = wstring_to_utf8(pchwc);
                // strncpy(pch, lol.c_str(),lol.length());

                rgb_matrix::DrawText(offscreen_canvas, font, x + xlan,
                    y + font.baseline(), color, lol.c_str());

                xlan = xlan + (pchwclen * font.width());
                pchwc = wcstok(NULL, L"@", &buffer);
            }
			
			
			/* Start of new row, repeat the former loop 
			and catch all words of the new row to print */
			
            xlan = 0;
            wort = 0;

            y += font.height();
			
			
			// This catcher will prevent the code to exit and do other stuff
            if (a == 9) {
                a = -1;
                offscreen_canvas = canvas->SwapOnVSync(offscreen_canvas);
                mb2++;
                sprintf(mb, "%d", mb2);
                rewind(myfile);
                sleep(10);
            }

            a = a + 1;
        }
    }

    // Finished. Shut down the RGB matrix.
    canvas->Clear();
    delete canvas;

    return 0;
}

`

**Comment by hzeller** [comment]
You made a very nice clock there!

**Comment by hzeller** [comment]
Very nice!

If you are exploring putting a frame around the LED panel, another look I tried is to hide the matrix behind an artist canvas. So it looks entirely white with the typical canvas structure, but then the LEDs shine through:

https://plus.google.com/u/0/+HennerZeller/posts/NgUcGo3YUTz

**Comment by bmclain** [comment]
@chrisoutwright you confirmed my fears that I'll need to manually scroll text myself character by character if I want dynamic coloring. Nice clock!
