### ISSUE TITLE
make error!

### ISSUE THREAD

**Issue by nguyenhuuhanhlam** [hzeller/rpi-rgb-led-matrix#363]
minimal-example.cc:8:24: fatal error: led-matrix.h: No such file or directory
 #include "led-matrix.h"
                        ^
compilation terminated.
<builtin>: recipe for target 'minimal-example' failed
make: *** [minimal-example] Error 1

**Comment by hzeller** [comment]
Thanks for the report.
Sorry about that, the makefile attempted to directly compile the binary but didn't have the include header path due to some simplification yesterday. This is fixed now, please do a `git pull` to get the latest version.
