### ISSUE TITLE
Active-RPi-3xHub75-Adapter This is hopefully a dumb question....

### ISSUE THREAD

**Issue by fusionfoto** [hzeller/rpi-rgb-led-matrix#374]
... So I wanted to make life easy on myself and try out this led matrix stuff as a fun project.

So I ordered the Active RPi Adapter boards from Oshpark and they look great.

However, they don't look like this board:
![image](https://user-images.githubusercontent.com/9053212/29290364-ccb7c520-810d-11e7-8b22-1c856f8f44a0.png)

They look like this:
![image](https://user-images.githubusercontent.com/9053212/29290381-d898891a-810d-11e7-90c7-e6f2e9ae46c7.png)

So I'm a little confused. Am I supposed to be acquiring and soldering on three ICs to these boards? I could have just breadboarded them if that's the case....  I definitely have to add headers in any case. 

These are multilayer PCBs, so its not obvious to me -- I haven't looked at the schematic to this level of detail.

thanks in advance!

**Comment by NetForces** [comment]
OSHPark is a PCB supplier not a complete solution supplier. So yes you will receive only the PCB (purple part) and will need to buy the buffers, connectors and passive (capacitors and resistor) and solder them.

**Comment by fusionfoto** [comment]
ok. thanks for the quick response!
