### ISSUE TITLE
using Tinker-Board instead of raspberry pi

### ISSUE THREAD

**Issue by beikimajid** [hzeller/rpi-rgb-led-matrix#375]
Hi
Can I use asus Tinker-Board instead of raspberry pi in this project?
Is Tinker-Board 40 pin compatible with raspberry pi to make no changes in PCB & software?

Link:
https://www.asus.com/us/Single-Board-Computer/Tinker-Board/

**Comment by hzeller** [comment]
The GPIO mapping is certainly entirely different, so it is very likely not working.

**Comment by beikimajid** [comment]
Do you know a board(except raspberry pi) have 2 slave spi device (cs0 cs1)  ? I change GPIO mapping&hardware&software and publish IT.

**Comment by hzeller** [comment]
There are certainly many SoCs, but they won't work with this matrix. This library uses specific features of the Raspberry Pi.
