### ISSUE TITLE
32x32 panel strange pixel mapping

### ISSUE THREAD

**Issue by vinchi9** [hzeller/rpi-rgb-led-matrix#376]
Hello,
I am using [this](https://www.digikey.cz/product-detail/en/mikroelektronika/MIKROE-2347/1471-1626-ND/6137614) 32x32 panel. After first connection the panel displayed everything very strangely. I tried multiple parameter configurations and I figured out, that the scan mode is 1:8, but the pixel mapping is odd. The panel is divided to 4 segments and some are badly placed and rotated. This is the input image: 
![a](https://user-images.githubusercontent.com/5941470/29431271-9fc5a064-8397-11e7-87f9-9df7415d9509.png)
I used this command:
`/led-image-viewer --led-rows=16  --led-chain=2 /home/pi/a.png -L`
And this is the result:
![panel](https://user-images.githubusercontent.com/5941470/29432097-935f8f08-839a-11e7-934a-3d529f8ff555.png)

How can I fix this?
Thank you

**Comment by vinchi9** [comment]
In the end I solved the problem by creating a remapping filter in ffmpeg and converting my media files. Thank you for creating this library.

**Comment by hzeller** [comment]
Cool. Yes, this is as well a way; the Transformer is essentially a remapping filter as well.
