### ISSUE TITLE
active-3 Red color wrong

### ISSUE THREAD

**Issue by beikimajid** [hzeller/rpi-rgb-led-matrix#382]
Hi
I test active-3 board for 1 module( 32x64  1/16 scan).Everything is ok but The red color does not appear in half of the module.
For example when i use [./demo -D 1 runtext.ppm], Letters in red appear in Upper half But not appear in Bottom half.
Actually that half of the RED "WORLD" text was cut off.
How can I solve this?

**Comment by hzeller** [comment]
Follow the red line, inputs and outputs. There must be some soldering issue.
