### ISSUE TITLE
Software runs but does not display on matrix on raspbian-stretch-lite.

### ISSUE THREAD

**Issue by HyperNerd** [hzeller/rpi-rgb-led-matrix#383]
Hello, as written up here: 
https://forums.adafruit.com/viewtopic.php?f=50&t=122103&p=611455#p611455

I was unable to get a display out on newest raspbian stretch lite but was able to get results in jessie-lite. Same gear, same install process. 

Unsure of what changes in the OS caused this breaking change, but wanted to let dev know.

**Comment by hzeller** [comment]
Did you update to the latest version ? This was fixed a couple of days ago.

**Comment by HyperNerd** [comment]
Ooh, ok. Wow, I think you resolved this just as I was bumping up against it. Thanks for the update.
