### ISSUE TITLE
Path not deep enough runtext.py (rpi-rgb-led-matrix/bindings/python/samples)

### ISSUE THREAD

**Issue by RobertFishcake** [hzeller/rpi-rgb-led-matrix#386]
When running runtext.py (with Python 3), I received an unable to load font error
Investigated, and it appears line 16 needs changing to go back 1 extra directory e.g:
font.LoadFont("../../../fonts/7x13.bdf")
Changed and it seems to work ok.
Hope this helps, excellent work BTW.

P.S Same problem occurs with any of the samples that use a file in another location (such as a font or an image etc.)...same fix works.

**Comment by hzeller** [comment]
Thanks for the report. Fixed.
