### ISSUE TITLE
Problem with Leeman 64x64 P3 from Aliexpress

### ISSUE THREAD

**Issue by 5oAwes0me** [hzeller/rpi-rgb-led-matrix#388]
Hello, 
i cant get my matrix to work. it is this one:
[https://de.aliexpress.com/item/P3-RGB-LED-MODULE-192MM-X-192MM-Indoor-SMD-LED-Panel-64x64-dots/32787250628.html](url)
 i would like to ask for some help. first i have to say im relatively new to programing. i wired up my matrix exactly as discribed. 
![pic1](https://user-images.githubusercontent.com/31445993/29828930-5e1982d4-8cde-11e7-8d32-f58371a9a1f3.jpg)
![pic4](https://user-images.githubusercontent.com/31445993/29828959-74f463a2-8cde-11e7-9383-bb8c8ba98e2e.jpg)
in the picture you can see the matrix connector. even tho its an 64x64 there is only A,B,C,D when i run 
`sudo examples-api-use/demo -D0 --led-rows=64 --led-chain=1 --led-parallel=1` 
the Terminal says 32x64 an the Display looks like: 
![pic2](https://user-images.githubusercontent.com/31445993/29828986-8d74219c-8cde-11e7-90b6-8e4f32a9e96d.jpg)
when i do 
`sudo examples-api-use/demo -D0 --led-rows=64 --led-chain=2 --led-parallel=1`
 it says 64x64 and looks like: 
![pic3](https://user-images.githubusercontent.com/31445993/29829010-9d7c5cee-8cde-11e7-8ccf-8825bbca3391.jpg)
i am 100% sure the wiring is correct and the Matrix is fully working.
but the thing is i only have one chain. i tried something with the Transformer but i barely understand how to use it. someone that has an idea how to get the screen propely to work?

thanks,
Jonas

**Comment by hzeller** [comment]
You also need to wire up the `E` line (pin 10 on the [Raspberry Pi wiring](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/wiring.md#wiring-diagram) to the pin labelled `E` on your Panel (which looks like Pin 8).
And then run with `--led-chain=2 --led-rows=64`.
