### ISSUE TITLE
Ignore complete black bitplanes

### ISSUE THREAD

**Issue by Saij** [hzeller/rpi-rgb-led-matrix#39]
Would it be better to ignore a full row in abitplane if the row doesn't set any data in the matrix?
It could possibly save some time the library doesn't have to spend on PWMing (when there is no data you won't need to toggle the row on and off)
Just clock it in, pull strobe and oe and don't PWM oe for long.
Or would the overhead more time consuming than the actual time you would wait for the PWM to finish?

**Comment by hzeller** [comment]
This would be too much overhead that wouldn't make much difference except in special cases.  Not worth the trouble.
Also, it would make the refresh-rate fluctuate a lot, which would not be a welcome artifact.

My plan is to reduce the processor time needed to clock-in things instead, using DMA.
