### ISSUE TITLE
Preloading multiple fonts

### ISSUE THREAD

**Issue by grene78** [hzeller/rpi-rgb-led-matrix#394]
I'm new to C++ development so I am hacking my way through this.  What I am trying to do is to create a dynamic scrolling message board that can show different messages with different effects.  One of the requirements is that each character of a message might be a different font.  It was far too slow to load them as I needed them so I started loading each of my fonts into a vector at startup and accessing them that way. 

ive got a "msgDisplay" class that loads all the supported fonts, and handles the IR buttons presses etc to facilitate adding and editing messages.  It's a monster, but its working well.  I've then got a msgplayer class that will be cycling through each message, showing the intro animation, play behavior, and exit animation for each.

The issue I am having now is that the "loadedFonts" are initialized in one class (msgDisplay) and passed to the player class which is a ThreadedCanvasManipulator.  When I stop the player (someone hits a button on the IR remote) I somewhat reproducibly get a **double free or corruption (out):** error.  

If I ditch the preloaded fonts vector, and just load up a single font, everything works great. (see comments referencing loadedFont vs code referencing the loadedFonts vector.  

hoping someone can point me in the right direction on my issue, and or point me in a better direction for how to pass these fonts around.

I should also mention the PlayerCanvas is a wrapper around FrameCanvas to store pixel data to be later retrieved by GetPixel() as discussed [here](https://github.com/hzeller/rpi-rgb-led-matrix/issues/131)

here is my player class:

`
```

#include "led-matrix.h"
#include "graphics.h"
#include <signal.h>
#include "threaded-canvas-manipulator.h"
#include "msgdisplay.h"
#include <string>

using namespace rgb_matrix;

extern volatile bool interrupt_received;

class MessagePlayer : public ThreadedCanvasManipulator {
public:
	MessagePlayer(RGBMatrix *m, std::vector<msg> *messageList, std::vector<Font*> loadedFonts)
		: ThreadedCanvasManipulator(m)
		, matrix_(m) {
		off_screen_canvas_ = m->CreateFrameCanvas();	
		messageList_ = messageList;
		loadedFonts_ = loadedFonts;		
		//loadedFont.LoadFont("/cousign/rpi-rgb-led-matrix-master/fonts/6x10.bdf");
	}
	
	void DrawFrame(msg *Message, PlayerCanvas *pc, int DrawXOffset = 0, int DrawYOffset = 0)
	{	
		if (!running())	{return;}		
		
		int currentFontIndex = 0;
		
		int currentX =  Message->horizontal_offset + DrawXOffset;	
		int currentY =  Message->vertical_offset + loadedFonts_[currentFontIndex]->baseline() + DrawYOffset;			
		//int currentY =  Message->vertical_offset + loadedFont.baseline() + DrawYOffset;			
		
		//draw background
		pc->SetBrightness(Message->bg_brightness);
		pc->Fill(Message->bg_color.r, Message->bg_color.g, Message->bg_color.b);
		
		//draw foreground
		pc->SetBrightness(Message->fg_brightness);
		for (int i = 0; i < Message->characters.size(); ++i)
		{
			char char2write[2] = { 0 };
			char2write[0] = Message->characters[i].character;
			
			currentFontIndex = Message->characters[i].font_index;
			
			std::cout << currentFontIndex;
			
			currentY =  Message->vertical_offset + loadedFonts_[currentFontIndex]->baseline() + DrawYOffset;	
			currentX += rgb_matrix::DrawText(pc,
				*loadedFonts_[currentFontIndex],
				currentX,
				currentY,
				Message->characters[i].fg_color,
				NULL,
				char2write);		
//			currentY =  Message->vertical_offset + loadedFont.baseline() + DrawYOffset;	
//			currentX += rgb_matrix::DrawText(pc,
//				loadedFont],
//				currentX,
//				currentY,
//				Message->characters[i].fg_color,
//				NULL,
//				char2write);				
		}
	}	
	
	void ScrollLeft(msg *Message, PlayerCanvas *pc, int StartX, int StopX, int StopTime, int loops)
	{
		if (StartX < StopX)
		{
			std::cout << "ScrollLeft() StartX is less than StopX" << std::endl;
			return;
		}
				
		for (int x = StartX; x > StopX; x--)
		{			
			DrawFrame(Message, pc, x, 0);
			if (!running())	{return;}
			off_screen_canvas_ = matrix_->SwapOnVSync(pc->delegatee_);
			usleep(20 * 1000);
		}
	}
	
	
	void Run() {

		PlayerCanvas player_canvas(off_screen_canvas_);
		
		//uint32_t continuum = 0;
		int offset = 0;
		int currentMessageIndex = 0;
		
		while (running() && !interrupt_received) {
							
				if (!running())	{break;}				
				player_canvas.Clear();			
				
				//play intro animation
				switch (messageList_->at(currentMessageIndex).StartAnimation)
				{
					case ANIMATION_NONE:
						break;
					case ANIMATION_SCROLL_LEFT:
					ScrollLeft(&messageList_->at(currentMessageIndex), 
						&player_canvas, 
						player_canvas.width() + 1, 
						0, 
						0, 
						1);
						break;
					case ANIMATION_SCROLL_RIGHT:
						break;
				}
				
	
				//play for loop iterations or number of seconds (stop when one or the other is met)			
				if (!running())	{break;}
				
				switch (messageList_->at(currentMessageIndex).PlayAnimation)
				{
				case ANIMATION_NONE:
					DrawFrame(&messageList_->at(currentMessageIndex), 
						&player_canvas, 
						0, 
						0);
					usleep(2000000);
					break;
				case ANIMATION_SCROLL_LEFT:					
					break;
				case ANIMATION_SCROLL_RIGHT:
					break;
				}				
				
				//play exit animation
				switch (messageList_->at(currentMessageIndex).StopAnimation)
				{
				case ANIMATION_NONE:
					break;
				case ANIMATION_SCROLL_LEFT:
					ScrollLeft(&messageList_->at(currentMessageIndex), 
						&player_canvas, 
						0, 
						(messageList_->at(currentMessageIndex).width() + messageList_->at(currentMessageIndex).horizontal_offset)* -1, 
						0, 
						1);
					break;
				case ANIMATION_SCROLL_RIGHT:
					break;
				}	
			
			currentMessageIndex++;
			if (currentMessageIndex > messageList_->size() - 1)
			{
				currentMessageIndex = 0;
			}
			
		}
	}

private:
	RGBMatrix *const matrix_;
	FrameCanvas *off_screen_canvas_;	
	std::vector<msg> *messageList_;
	std::vector<Font*> loadedFonts_;
	//Font loadedFont;
};

```
``
`

and the pertinent bits of my main();

```
msgDisplay* display = new msgDisplay();

ThreadedCanvasManipulator *player = NULL;
player = new MessagePlayer(display->canvas, &display->messageList, display->loadedFonts);		
player->Start();
	while (true)
	{
		//CHECK FOR IR BUTTON PRESSES
		if (ir_buttons_queue.size() > 0)
		{
			//pull ir command from queue
			IRButtonPressItem* ir_button = ir_buttons_queue.remove();
			std::cout << "IR COMMAND: " << ir_button->getMessage() << " Code: " << hex << "0x" << ir_button->getButton() << endl;
			
			display->button_push(ir_button->getButton());	
			
			if (display->currentMode == START_MENU_MODE)
			{
				display->currentMode = NORMAL_OPERATION;
				player->Stop();				
				display->show();
			}
		
			if (display->currentMode == PLAY_MODE)
			{
				player->WaitStopped();
				player->Start();
			}

			delete ir_button;			
		}		

	}

```

**Comment by hzeller** [comment]
If you run it in gdb or with valgrind, you might be able to pinpoint the place where the double free happens. You haven't shown the implementation of PlayerCanvas, this might contain the issue.

I don't think that preloading multiple fonts has anything to do with the issue at hand (as the bug entry suggests), it is just some regular issue somewhere in your code it seems.

Also, why do you pass the vector of the fonts as value not const reference ? This is unnecessarily inefficient; you could just keep these as reference (or, why not pass in the display directly into the MessagePlayer, so it can use whatever it needs?).

**Comment by grene78** [comment]
I think I may have passed the fonts in by value while I was busy barking up the wrong tree.  Having the preloaded fonts helped the code break, but were not the root cause.  I believe the root issue was double freeing something referenced by the PlayerCanvas.

I did end up changing the player to take a ref to the entire display class as you suggested, and it was a much smarter choice.  Still a long way to go, but things are working well as I build it out.  Thanks for the help!

**Comment by ClanHost** [comment]
This is how I pre-loaded my fonts

FONT = graphics.Font()
FONT.LoadFont("../../../fonts/10x20.bdf")

While True:
       graphics.DrawText(canvase, eval(FONT), LEFT, TOP, setcolor, MESSAGE)
