### ISSUE TITLE
Rotate whole matrix canvas with Python binding?

### ISSUE THREAD

**Issue by pstadler1990** [hzeller/rpi-rgb-led-matrix#398]
I saw the Transformer option in the demo example. Is there any chance to use that within the Python binding? Like rotating the canvas by 90 degrees?

**Comment by hzeller** [comment]
Mmh, since transformers are not supported on the Python side, you might need to add the transformer in the Python wrapper library, somewhere [after the matrix has been created](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/bindings/python/rgbmatrix/core.pyx#L180).

**Comment by FlorianLontsie** [comment]
Bonjour cordialement, s'il vous plaît, comment éditer canvas transformer ?
