### ISSUE TITLE
Active3 borad with 4 rows OR HUB75 Expansion

### ISSUE THREAD

**Issue by beikimajid** [hzeller/rpi-rgb-led-matrix#402]
Is it possible to design the Active3 borad that has 4 rows or more(4 parallel or more)     OR
Is it possible to design the HUB75 Expansion Which is mounted on the 40 PIN raspberry And give more Rows like [this link](https://sc01.alicdn.com/kf/HTB1zDAGKXXXXXa0XpXXq6xXFXXXs/202248796/HTB1zDAGKXXXXXa0XpXXq6xXFXXXs.jpg)?
In fact, I want to have a junction of HUB75 on PCB for each row.

**Comment by hzeller** [comment]
The GPIO pins of the Raspberry Pi are exhausted with 3 parallel display chains, but I have some ideas to do a few more with some tricks; haven't had time yet though to experiment with that idea.
