### ISSUE TITLE
Pi/Arduino alternative board?

### ISSUE THREAD

**Issue by stam32** [hzeller/rpi-rgb-led-matrix#415]
Hello,

Can somebody propose an alternative board other than the pi/Arduino that maybe can be used for professional purpose.
I am not sure about that, but I think that pi is not a wise choice to implement a professional solution of a 24/7 led matrix.

Thank you

**Comment by hzeller** [comment]
There are actually many people that use the Pi and this library in a professional setup (advertisement etc.), but of course you are limited by the number of displays to connect.

You always can go with the boards that are sold by the same people that sell you the LED panels. They often have HDMI input etc. and allow with more connectors for larger displays. However the downside is, that they often come with proprietary software without source and only running on Windows. Now that is something that you rally don't want in a professional set-up under any circumstances...
