### ISSUE TITLE
kBaseTimeNanos not bellow 100ns

### ISSUE THREAD

**Issue by Saij** [hzeller/rpi-rgb-led-matrix#42]
kBaseTimeNanos should not below 100ns.
I've set it to 50ns and my PI doesn't respond anymore.
100ns are ok.

**Comment by hzeller** [comment]
I think I tried 50ns and it somewhat worked, but at that point the pulses are so fast, that the colors are not  properly balanced anymore. Somewhere between 100 and 200ns seems to be fine.

Closing this now.
