### ISSUE TITLE
repeat pixel in panel P6 32x32 outdoor 1/8 scan rate

### ISSUE THREAD

**Issue by angelogoncalve** [hzeller/rpi-rgb-led-matrix#426]
Hello Dear Zeller. I hope you are fine. I have a panel P6 32x32 outdoor 1/8 scan rate which repeat a pixel for example (0,0) have a pixel in the same collumn but eidth rows above (9,0). I think I will need a transformer but I to do the translation in rows from each pixels but I do not have the wrigth transformer to do that. Can you give some ideas to do the rigth transformer for this panel from china? Thank you for your atention. Best Regards, Ângelo Gonçalves.

**Comment by angelogoncalve** [comment]
eigth* rows

**Comment by angelogoncalve** [comment]
Hello Dear Zeller. I hope you are fine. I have a panel P6 32x32 outdoor 1/8 scan rate which repeat a pixel for example (0,0) have a pixel in the same collumn but eigth rows above (9,0). I think I will need configure the matrix for rows=16 and chain= 2 and use a transformer to do the translation in rows from each pixels but I do not get the wrigth transformer to do that. Can you give some ideas to do the rigth transformer for this panel from china? See the link below:

https://ibb.co/mtCLia

How can I scroll text in a panel P6 16x32 indoor 1/8 scan rate? 

Thank you for your atention.

Best Regards,

Ângelo Gonçalves.

**Comment by angelogoncalve** [comment]
The picture that I saw in the panel for demo 0 is:

https://ibb.co/mCZNwv

**Comment by hzeller** [comment]
There is now a `--led-multiplexing` parameter which might already solve your problem. Can you try that ?
