### ISSUE TITLE
Lib : add area update

### ISSUE THREAD

**Issue by MaitreDede** [hzeller/rpi-rgb-led-matrix#428]
Hi,
When using as a lib, Instead of calling `led_canvas_set_pixel`, can you add a way to give an array ?
For example :
```
void led_canvas_set_area(int x, int y, int width, int height, const uint8_t* data);
```
with data as an array containing pixel data encoded as 1 byte for one color (aka RGB888) :
```
int index = (x * width + y) * 3;
uint8_t r = index;
uint8_t g = index +1;
uint8_t b = index + 2;
```

In my case, this will speed up things a lot, since I would reduce interop calls from 64x64 to 1 :smile: 
I think this may help for python too.

Maybe other common encodings can also be usefull, like RGBA888 (like RGB888, but with alpha transparency byte).

**Comment by hzeller** [comment]
There is no area call (It can't be done much faster in C/C++ than just calling `SetPixel()` in a loop, so it is left out of the 'official' API for simplicity reasons).

But if you are doing some interop calls, it might be worthwhile if you add an additional function for yourself that takes your area call and then internall calls the underlying `SetPixel()` in a loop. Then you call that function more efficiently if there is an overhead per call.

The [Python code is actually already using that](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/bindings/python/rgbmatrix/core.pyx#L36) if you call SetImage().
