### ISSUE TITLE
Led panel P8 16x32 - 1:4 multiplexing?

### ISSUE THREAD

**Issue by getvladimir4** [hzeller/rpi-rgb-led-matrix#430]
Hello Sirs,
I told you that I have correctly tested the panles led p10 16x32, p5 32x64 and everything was successful. But when testing the led panel p8 16x32 does not work it apparently requires a different scan. Could you help me how to solve?

P5 32x64 (ok)
https://www.youtube.com/watch?v=DA7VOTb2M0o
P8 16x32 (bad)
https://www.youtube.com/watch?v=zr0klS0OVoE

sudo ./demo -r 16 -c 1 -D 3
![image](https://user-images.githubusercontent.com/32687502/32811993-b136e0dc-c970-11e7-8ffb-cce2a94eb3f7.png)

![20171114_102953](https://user-images.githubusercontent.com/32687502/32795366-6c121abc-c939-11e7-8479-22e3e8e5930e.jpg)

P.d:. All the panels that I have are hub75

**Comment by angelogoncalve** [comment]
Dear Vladimir. First what is the scan rate for your panel 16x32? The hzeller library is prepare for indoor panels and for panels with 16x32 the scan rate is 1/8. Perhaps tour panel is outdoor and have a scan rate 1/4 or 1/2. You need build a correct transformer for your new scan rate. I think it is better speak with Zeller. He is expertise in this area. I am try to do that with a 32x32 panel with a scan rate 1/8 (see https://ibb.co/mCZNwv) but I did not fix yet and I need help too. He made prepare for 32x32 panel but with a scan rate 1/16. The scan rate should be a parameter to pass in the configuration of the options of the matrix that is wonderful if it is possible. Best Regards, Ângelo.

**Comment by angelogoncalve** [comment]
your*

**Comment by MikkelMiksen** [comment]
Does anyone a have fix yet? please

**Comment by marcmerlin** [comment]
@MikkelMiksen you replied to a bug closed in 2017.
If you need help with a panel, please post on discourse with full details on your panel, what you tried, what's working, what's not etc.  The more details you give, the more likely you are to get an answer.
