### ISSUE TITLE
16x32 1:8 scan rate transformer error

### ISSUE THREAD

**Issue by yigitbayol** [hzeller/rpi-rgb-led-matrix#437]
hello @hzeller,
I'm using your code and make a transformer for 1:8 scan rate P5 outdoor panel, but I have problem.

**Here what i did:**
1- I added this code to transformer.h

> class P5outdoorTransformer : public CanvasTransformer {
> public:
>   P5outdoorTransformer(int angle = 0);
>   virtual ~P5outdoorTransformer();
> 
>   void SetAngle(int angle);
>   inline int angle() { return angle_; }
> 
>   virtual Canvas *Transform(Canvas *output);
> 
> private:
>   // Transformer canvas to rotate the input canvas in 90° steps
>   class TransformCanvas;
> 
>   int angle_;
>   TransformCanvas *const canvas_;
> };

2- Also i added this code to transformer.cc

> class P5outdoorTransformer::TransformCanvas : public Canvas {
> public:
>   TransformCanvas(int angle);
> 
>   void SetDelegatee(Canvas* delegatee);
>   void SetAngle(int angle);
> 
>   virtual int width() const;
>   virtual int height() const;
>   virtual void SetPixel(int x, int y, uint8_t red, uint8_t green, uint8_t blue);
>   virtual void Clear();
>   virtual void Fill(uint8_t red, uint8_t green, uint8_t blue);
> 
> private:
>   Canvas *delegatee_;
>   int angle_;
> };
> 
> P5outdoorTransformer::TransformCanvas::TransformCanvas(int angle)
>   : delegatee_(NULL) {
>   SetAngle(angle);
> }
> 
> void P5outdoorTransformer::TransformCanvas::SetDelegatee(Canvas* delegatee) {
>   delegatee_ = delegatee;
> }
> 
> int P5outdoorTransformer::TransformCanvas::width() const {
>   return delegatee_->width() / 2;
> }
> 
> int P5outdoorTransformer::TransformCanvas::height() const {
>   return delegatee_->height() * 2;
> }
> 
> void P5outdoorTransformer::TransformCanvas::SetPixel(int x, int y, uint8_t red, uint8_t green, uint8_t blue) {
>   int odd8_block =(((y % 16) / 8) +1) % 2; //to know if the pixel is in an odd 8pixel row
>   int num_mod_x = (x / 64); //num of daisy chainned modules
>   int new_x = (x + 64*num_mod_x + 64*odd8_block); 
>   int new_y = (y % 8) + 8 *( y / 16);
>   delegatee_->SetPixel(new_x, new_y, red, green, blue);
> }

3- Finnaly i activate ApplyStaticTransformer from led-matrix.cc : 
> ApplyStaticTransformer(P5outdoorTransformer());

After these, i rebuild python and C codes : 

>  make -C lib clean all
   sudo make -C python clean
   make build-python
   sudo make install-python

when i try to run image-scroller.py, there was an error like this:

>  File "led_manager.py", line 4, in <module>
    from samplebase import SampleBase
  File "/home/eczane/core/bindings/python/samples/samplebase.py", line 7, in <module>
    from rgbmatrix import RGBMatrix, RGBMatrixOptions
  File "/usr/local/lib/python2.7/dist-packages/rgbmatrix/__init__.py", line 7, in <module>
    from .core import RGBMatrix, FrameCanvas, RGBMatrixOptions
ImportError: /usr/local/lib/python2.7/dist-packages/rgbmatrix/core.so: undefined symbol: _ZN10rgb_matrix20P5outdoorTransformerC1Ei

how can I solve this? I don't understand why.. 
If i disable ApplyStaticTransformer from led-matrix.cc, there is no error but also there is no transform.
Also i don't see any error while compiling.

Thanks.

**Comment by hzeller** [comment]
Can you try the new [`--led-multiplexing`](https://github.com/hzeller/rpi-rgb-led-matrix#multiplexing) ? It provides a couple of options to natively support 1:8 multiplexing. It also works from Python.
