### ISSUE TITLE
1/2 scan pixel mapping

### ISSUE THREAD

**Issue by beikimajid** [hzeller/rpi-rgb-led-matrix#438]
Hello hzeller, you've been asked for datasheet(p10 1/2 fullcolor) before in  #278

I find pixel mapping for 1/2 scan with HD2016(smart setting) and D10 controller.
Everything is OK in HD2016 and show text correctly.
Please help me to use this panel. You can see  #422 

https://user-images.githubusercontent.com/3895372/32982853-418814d0-cca0-11e7-8846-5375c9897492.png

**Comment by hzeller** [comment]
The library offers all the infrastructure for you to do the pixel mapping yourself. If you have a special case, then you have to do the coding yourself.
