### ISSUE TITLE
32:32 with 1:8 scan multiplexing problem

### ISSUE THREAD

**Issue by vitthalrm** [hzeller/rpi-rgb-led-matrix#441]
I have problem sudo ./demo -r 32 -c 2 -D 3 output like
![img_20171120_144008](https://user-images.githubusercontent.com/16988981/33010709-7e357af0-ce01-11e7-827b-f5bc7fb11845.jpg)

**Comment by lukasmalkmus** [comment]
Exact same issue here, but I was not able to get a proper transformer running.

**Comment by darknessii** [comment]
Try this ugly Transform Set, it works up to 8 Panel only on one Parallel output.


void UArrangementTransformer::TransformCanvas::SetPixel(
  int x, int y, uint8_t red, uint8_t green, uint8_t blue) {

int new_x = 0;
int new_y = 0;

if (y <= 7) {
  new_x = ((x / 16) * 32) + (x % 16);
  if ((y & 8) == 1) {
   new_x += 16;
  }
  new_y = ((y / 16) * 8) + (y % 8);
}else {
  if ((y >= 16) && (y <= 23)) {
    new_x = ((x / 16) * 32) + (x % 16);
    if ((y & 8) == 1) {
      new_x += 16;
    }
    new_y = ((y / 16) * 8) + (y % 8);
  }else {
    new_x = ((x / 16) * 32) + (x % 16);
    y -= 8;
    if ((y & 8) == 0) {
     new_x += 16;
    }
    new_y = ((y / 16) * 8) + (y % 8);
  }
}
delegatee_->SetPixel(new_x, new_y, red, green, blue);
}

**Comment by darknessii** [comment]
./demo -D 3 --led-rows=16 --led-chain=2

**Comment by hzeller** [comment]
Please check out the new option `--led-multiplexing` https://github.com/hzeller/rpi-rgb-led-matrix#multiplexing
It does the mapping built into the library (and can also be used from Python.)
(You need to do a fresh checkout and compile, this just went in).

**Comment by lukasmalkmus** [comment]
Can confirm. The new multiplexing options fixed my issue with the same display. I'm not talking in behalf of the issue author but I think this can be closed. @hzeller @angelogoncalve

**Comment by darknessii** [comment]
The --led-multiplexing option does not work for me. 

Only my Transfomset works fine. i did some optimisation.

void UArrangementTransformer::TransformCanvas::SetPixel(
  int x, int y, uint8_t red, uint8_t green, uint8_t blue) {

int new_x = 0;
int new_y = 0;

//Panel SMD3535 RGB OS-P6-32x32-8S
if ((y <= 7) || ((y >= 16) && (y <= 23)) || ((y >= 32) && (y <= 39)) || ((y >= 48) && (y <= 55))) {
  new_x = ((x / 16) * 32) + (x % 16);
  if ((y & 8) == 1) {
   new_x += 16;
  }
  new_y = ((y / 16) * 8) + (y % 8);
  }else {
	new_x = ((x / 16) * 32) + (x % 16);
	y -= 8;
	if ((y & 8) == 0) {
		new_x += 16;
	}
	new_y = ((y / 16) * 8) + (y % 8);
  }
delegatee_->SetPixel(new_x, new_y, red, green, blue);
}

sudo ./examples-api-use/demo -D 3 --led-rows=16 --led-chain=4 --led-parallel=2 --led-slowdown-gpio=2 --led-pwm-lsb-nanoseconds=80 --led-no-hardware-pulse

![img_20180214_222244](https://user-images.githubusercontent.com/32201125/36229415-64800520-11d7-11e8-9132-fc24bf25c0bc.jpg)



**Not working.....**

sudo ./examples-api-use/demo -D 3 --led-rows=16 --led-chain=4 --led-parallel=2 --led-slowdown-gpio=2 --led-pwm-lsb-nanoseconds=80 --led-no-hardware-pulse --led-multiplexing=0

![img_20180214_222218](https://user-images.githubusercontent.com/32201125/36229465-963f41b6-11d7-11e8-8c23-ef08eada3247.jpg)



sudo ./examples-api-use/demo -D 3 --led-rows=16 --led-chain=4 --led-parallel=2 --led-slowdown-gpio=2 --led-pwm-lsb-nanoseconds=80 --led-no-hardware-pulse --led-multiplexing=1

![img_20180214_222146](https://user-images.githubusercontent.com/32201125/36229490-af7e269c-11d7-11e8-8e74-386a3f391c21.jpg)



sudo ./examples-api-use/demo -D 3 --led-rows=16 --led-chain=4 --led-parallel=2 --led-slowdown-gpio=2 --led-pwm-lsb-nanoseconds=80 --led-no-hardware-pulse --led-multiplexing=2

![img_20180214_222054](https://user-images.githubusercontent.com/32201125/36229512-c22a93a2-11d7-11e8-9437-fab46669f86b.jpg)



sudo ./examples-api-use/demo -D 3 --led-rows=16 --led-chain=4 --led-parallel=2 --led-slowdown-gpio=2 --led-pwm-lsb-nanoseconds=80 --led-no-hardware-pulse --led-multiplexing=3

![img_20180214_222030](https://user-images.githubusercontent.com/32201125/36229540-e15786cc-11d7-11e8-8415-ff1a0da3aa6f.jpg)



sudo ./examples-api-use/demo -D 3 --led-rows=16 --led-chain=4 --led-parallel=2 --led-slowdown-gpio=2 --led-pwm-lsb-nanoseconds=80 --led-no-hardware-pulse --led-multiplexing=4

![img_20180214_221904](https://user-images.githubusercontent.com/32201125/36229558-f776474a-11d7-11e8-8ffd-06bde0ce8d2c.jpg)


Also the option  --led-row-addr-type  dose not work.

But thanks for the transform Set Option. this works fine.

**Comment by lukasmalkmus** [comment]
Hm. Have you tried something like `./demo --led-rows=32 --led-cols=32 --led-chain=2 --led-parallel=2 --led-multiplexing=1 -D3` Thats how it worked for me.

**Comment by darknessii** [comment]
Thank for the information, but it does not work with my panel.
it looks also funny...

./demo --led-rows=32 --led-cols=32 --led-chain=2 --led-parallel=2 --led-multiplexing=0 -D3
![img_20180214_232251](https://user-images.githubusercontent.com/32201125/36231929-318c6ce0-11e0-11e8-8b09-4a3cb9c8bbcb.jpg)


./demo --led-rows=32 --led-cols=32 --led-chain=2 --led-parallel=2 --led-multiplexing=1 -D3
![img_20180214_231624](https://user-images.githubusercontent.com/32201125/36231815-bc6fbf98-11df-11e8-8e2d-d1bea699cac2.jpg)
 
./demo --led-rows=32 --led-cols=32 --led-chain=2 --led-parallel=2 --led-multiplexing=2 -D3
![img_20180214_231958](https://user-images.githubusercontent.com/32201125/36231844-d7c9eb74-11df-11e8-9d7f-c5e70a28d2ea.jpg)

./demo --led-rows=32 --led-cols=32 --led-chain=2 --led-parallel=2 --led-multiplexing=3 -D3
![img_20180214_232115](https://user-images.githubusercontent.com/32201125/36231858-ea684ff0-11df-11e8-8449-5bb67ba78b26.jpg)

./demo --led-rows=32 --led-cols=32 --led-chain=2 --led-parallel=2 --led-multiplexing=4 -D3
![img_20180214_232028](https://user-images.githubusercontent.com/32201125/36231886-0428baf6-11e0-11e8-8040-5bfe72f353ff.jpg)

**Comment by darknessii** [comment]
The Option 2 looks like the best, but not in the right order.

./demo --led-rows=32 --led-cols=32 --led-chain=2 --led-parallel=2 --led-multiplexing=2 -D3

and has to be reorderd. But how? Looks like a puzzle.

![bild 2](https://user-images.githubusercontent.com/32201125/36232833-96e726e0-11e3-11e8-9a74-7bd99c98d017.png)

![bild 1](https://user-images.githubusercontent.com/32201125/36232840-9cf9d0e6-11e3-11e8-804b-2632c3e7ea22.png)

**Comment by hzeller** [comment]
This looks related to #445 ? Let's continue there to not have too many parallel threads open.
You seem to have found a pixel mapping for that, so it would be good if you could provide a pull request with your mapping in multiplex-transformers.cc.
