### ISSUE TITLE
LED PANEL 16X32 BAD SCANNING

### ISSUE THREAD

**Issue by getvladimir4** [hzeller/rpi-rgb-led-matrix#443]
### Hello masters!

I have the following problem for several weeks now. And the fact is that when executing the henner demos on the led panel 16x32 p8 I find it distorted as you can see the images and videos that I present below.
-------------------------------------------------------------------------------------------------------------------
*OK SCANNING in 16x32 P10
sudo ./demo -r 16 -c 1 -D 3
![20171117_171747 1](https://user-images.githubusercontent.com/32687502/33176756-30ee2006-d02e-11e7-9446-e384632fc237.jpg)
-------------------------------------------------------------------------------------------------------------------
*BAD SCANNING in 16x32 P8

sudo ./demo -r 16 -c 1 -D 3
![20171114_160343 1](https://user-images.githubusercontent.com/32687502/33176617-ac854f1a-d02d-11e7-8fee-ac38e1e71b0d.jpg)

sudo ./demo -r 16 -c 1 -D 1 runtext16.ppm
https://www.youtube.com/watch?v=zr0klS0OVoE

Apparently he has the following scan but I'm not sure about this.
![capture](https://user-images.githubusercontent.com/32687502/33177157-a8059182-d02f-11e7-96fa-47679e44da0a.PNG)

Any suggestions will help me a lot. Thank you so much.
Please, could you help me solve this problem? It's very urgent!

**Comment by hzeller** [comment]
You have to write yourself a transformer that maps the logical pixels to the physical ones.

Description in the [canvas.h](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/include/canvas.h#L51) header and in the [examples README](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#remapping-coordinates)

You can find a few [implementation examples here](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/transformer.cc).

**Comment by hzeller** [comment]
Please check out the new option `--led-multiplexing` https://github.com/hzeller/rpi-rgb-led-matrix#multiplexing
It does the mapping built into the library (and can also be used from Python.)
(You need to do a fresh checkout and compile, this just went in).on
