### ISSUE TITLE
3x16x24 HT1632C with Pi3

### ISSUE THREAD

**Issue by hebertpalomino** [hzeller/rpi-rgb-led-matrix#447]
Hey!

I realize this project is a bit old but I'm hoping you can help me out. The new matrix panels and Pis seem to be slightly different and I can't seem to get the panel to work.
The new panel looks like this:
https://www.dropbox.com/s/k51gqh3oxr7hfrt/1.jpg?dl=0

and Pi looks like this:
https://www.dropbox.com/s/sy505yafshkq9q1/2.jpg?dl=0

I've connected (Pi3 Diagram: https://openclipart.org/image/2400px/svg_to_png/280972/gpiopinsv3withpi.png)
vcc to 5v
ground to ground
Data to pin 19
Write to pin 23
sync to 24 (this is the one i couldn't find clock on matrix for)
cs0 to pin 26

I'd really appreciate any direction as this is driving me crazy :)

**Comment by hzeller** [comment]
Your panel looks like one of these ancient HUB12 panels. It should be possible to connect to this library, but you need to possibly change the polarity of the OutputEnable signal in the gpio code.
