### ISSUE TITLE
Real-time clock & Parallel3

### ISSUE THREAD

**Issue by beikimajid** [hzeller/rpi-rgb-led-matrix#451]
Hi
Can I use on same time with Parallel3 port &  RTC DS1307 (Connecting RTC DS1037, Pin 5 already occupied)?
I need RTC DS1307 & 3 parallel together.

What do you think of "raspberry Pi GPIO Triple Expand Board"?

![](https://statics3.seeedstudio.com/product/114990168%201_05.jpg)

**Comment by hzeller** [comment]
You should be able to connect a realtime clock to i2c but not while the panel is working - it needs all the IO pins. However, I suppose you can talk to the realtime clock at boot-up time, then switch on the panel.
