### ISSUE TITLE
Multiple Displays with different sizes Raspberry Pi 3

### ISSUE THREAD

**Issue by tibo2noix** [hzeller/rpi-rgb-led-matrix#454]
Hi,
First of all, thank you for this fantastic work you have done. I have already started with your tutorials and reached the step of displaying the rotating square, "hello world", etc. with the Adafruit HAT on 1 chain.

I will need for my project 3 different screens of different sizes to be driven ideally by one Raspberry Pi 3
- **screen 1:** 128 x 128Px (4 panels of 64x64 Px in square). 
- **screen 2:** 128 x 128Px (4 panels of 64x64 Px in square). 
I need to display different things on both screen 1 and 2, like a video on a side and text on the other.
- **screen 3:** 640 x 16 Px (20 panels of 32x16 Px, one after another):
Here will be displayed only scrolling text

My questions are the following:
1) Is it possible to combine different panel sizes or should I build all screens with the same panel sizes. Exemple: screen 1 with 8 panels of 64x32, same for screen 2 and screen 3 with 20 panels of 64x32. Like this we have only 64x32 panels.
2) Is it possible to display different things simultaneously on the 3 different screens with one Pi or do i need three Raspberry Pi ?
In theory, your 3 channels active board can drive 3 x 12 panels so I thought 2 chains for the 20 panels (screen 3) and 1 chain for the 2 different screens of 4 panels (screen 1 and 2).
3) If it isn't possible, an improvement could be to split it in 2, so two Raspberry Pi as well. Each Raspberry Pi would need to drive:
- **screen 1:**  128 x 128Px (4 panels of 64x64 Px in square). 
- **screen 2:** 320 x 16 Px (10 panels of 32x16 Px, one after another):

Hopefully this is clear enough. Thank you in advance for your help !

**Comment by hzeller** [comment]
So if you put things on three parallel chains, they need to have the same multiplexing. If you have a 64x64 panel, that has a 1:32 multiplexing, it won't be compatible with the 1:8 multiplexing of the 32x16.

I'd just go ahead and use different Pis to save the headache.
