### ISSUE TITLE
Adafruit RGB Matrix HAT + Raspberry Pi 3 Model B + P5 RGB Matrix 64x32

### ISSUE THREAD

**Issue by marcinguy** [hzeller/rpi-rgb-led-matrix#459]
Hi, 

I open this issue because I am little bit confused after reading the issues here, searching the Internet and reading docs on Adafruit website.

Having this setup of:

- Adafruit RGB Matrix HAT + RTC for Raspberry Pi - Mini Kit [ADA2345] (https://www.amazon.de/Adafruit-RGB-Matrix-HAT-Raspberry/dp/B00SK69C6E/ref=pd_bxgy_23_img_2?_encoding=UTF8&psc=1&refRID=GTRGSJCFJK7MMWQ5N4T9)

- P5 RGB Matrix (https://www.amazon.de/gp/product/B06XNJZN89/ref=oh_aui_detailpage_o01_s01?ie=UTF8&psc=1)

- Raspberry Pi 3 Model B (https://www.amazon.de/Raspberry-Pi-Model-ARM-Cortex-A53-Bluetooth/dp/B01CD5VC92/ref=pd_bxgy_23_img_3?_encoding=UTF8&psc=1&refRID=GTRGSJCFJK7MMWQ5N4T9)

Want to provide 5V 4A DC to HAT Board, take power from there to RGB Matrix and power RPI 3 seperately, by its own powersupply.

How do I set it up?

Wanted to follow the guide on:

https://learn.adafruit.com/adafruit-rgb-matrix-plus-real-time-clock-hat-for-raspberry-pi

They also mentioned it is possible to chain RGB Matrixes with the HAT

"You can even chain multiple matrices together for a longer display - we've only tested up to 32x128, the bigger the display the harder it is on the Pi so keep that in mind! "_

Wanted to use the forked Repo by Adafruit to drive the Matrixes:

https://github.com/adafruit/rpi-rgb-led-matrix

I am still waiting for my hardware, but want to know how to proceed when I get it. Which Tutorial should I follow and what software to use?

Anybody used the RGB Matrix in question:

https://www.amazon.de/gp/product/B06XNJZN89/ref=oh_aui_detailpage_o01_s01?ie=UTF8&psc=1

Anythink I should be aware of?

Thanks in Advance,

**Comment by hzeller** [comment]
Can you ask the Adafruit support directly with your power questions ? I just wrote this library that Adafruit then used for their HAT, but I don't know anything about their particular HAT.

If you use this library, then you should read the [README](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/README.md) and [wiring tutorial](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/wiring.md).
If you use the (somewhat outdated three year old) Adafruit fork of this library, use their tutorial. 

If you have multiple panels, I suggest to solder up the [parallel adapter](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/adapter/active-3) in this project.

**Comment by marcinguy** [comment]
Thank you for your response and explanation. BTW Great work on the lib!

**Comment by marcinguy** [comment]
My setup arrived. I assembled it and it works with your lib!

Had to use 

--led-slowdown-gpio=2

due to fast RPI 3 Model B

and used:

--led-rows=32 --led-chain=2

Wait still for 2nd 32x64 panel ... will try to hook it up as 32x128 or 64x64 ... so in total i will have 4 32x32 panels.

So with 32x128 I will change it to:

--led-rows=32 --led-chain=4

and

64x64

--led-rows=64 --led-chain=4

Correct?

**Comment by hzeller** [comment]
If you chain two of the 32x64 together, then you need `--led-rows=32 --led-chain=4`, correct.

If you want a 64x64, by 'bending' them over, you should use the [UArrangementTransformer](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#remapping-coordinates) in your code (or, if you use the demo, use the `-L` option).
