### ISSUE TITLE
Raspberry Pi 3 with Windows 10 IOT Core OS

### ISSUE THREAD

**Issue by DebaGracias** [hzeller/rpi-rgb-led-matrix#468]
Hi all,
I have Raspberry Pi 3 with Windows 10 IOT Core OS installed on it.I was not able to get this library working with the same.Is this library compatible with Rasp Pi running Windows 10 IOT Core?

Thanks,
Debasish.

**Comment by kbateam** [comment]
I think no.
This project based on linux OS

**Comment by angelogoncalve** [comment]
You can use this: https://www.hackster.io/highwave/32x32-chained-led-matrices-with-win-iot-core-on-rpi3-f1cb92
