### ISSUE TITLE
Can't get all pixels on 32x32

### ISSUE THREAD

**Issue by mblue002** [hzeller/rpi-rgb-led-matrix#469]
Hello,
I have two 32x32 panels and both seem to have the same pixel-mapping issue.
I am running a recent version of raspian-lite on a PI3 with the Adafruit hat.

One panel is directly from Adafruit, the other was ordered from a Chinese manufacturer (I got it through a thrid party). Adafruit says their display is 1/16 scan rate here: 
[https://www.adafruit.com/product/1484?gclid=Cj0KCQiAkNfSBRCSARIsAL-u3X9Kl7_vg9NxO76q1Ii72pxZEqKBP9NYQSLrGE9jRxoYOfVVG5TvnRAaApfGEALw_wcB](url)

The Chinese display is 1/4 scan rate.

Yet, the both exhibit the same behavior in that I only get rows 1,2,16,17 to show:

sudo ./examples-api-use/demo -D5 --led-rows=32 --led-gpio-mapping=adafruit-hat

![img_7020](https://user-images.githubusercontent.com/6225694/34786471-473dc90c-f602-11e7-9bf7-b22c49dba7ae.JPG) Just noticed that the picture is rotated 90degree. The top two rows are those at the edge of the display, on the left in the picture, and are slightly less bright.

The colors are correct.

I modified the demo-main.cc to include a test which just walks through all 32x32 pixels, one pixel at a time, and get the same results.

Thanks in advance,
Mike Davis

**Comment by hzeller** [comment]
Can you try the new `--led-multiplexing` option ? https://github.com/hzeller/rpi-rgb-led-matrix#multiplexing
It could also that you have one with an A/B line only, so you might need `--led-row-addr-type=1`
