### ISSUE TITLE
Issue with playing audio while running rpi-rgb-led-matrix

### ISSUE THREAD

**Issue by mzdunek92** [hzeller/rpi-rgb-led-matrix#470]
Hello,

I got your lib running on watchdog. I have excluded snd_bcm module. After reboot sometimes I am unable to play any .wav file with aplay (in background rpi-rgb is running). I got this error:

aplay: Device or resource is busy

Is any function in rpi-rgb-led-matrix even possible to cause this issue?

**Comment by hzeller** [comment]
usually, regular audio should work if you have an external sound card that is not using the Raspberry Pi PWM hardware. So if you have configured Alsa to only talk to some external USB sound-card, this should not intefered.

You can switch off hardware pulse generation with `--led-no-hardware-pulse` which makes the library not use that subsystem to test; but maybe something needs to be configured in your Alsa system to not mess with the Pi audio.
