### ISSUE TITLE
Buy panel hub75 P10 outdoor scan rate 1/4 16x32 pixels RGB Led

### ISSUE THREAD

**Issue by angelogoncalve** [hzeller/rpi-rgb-led-matrix#474]
Hello people. Where (the link from the manufacturer) can I buy a panel hub75 P10 outdoor scan rate 1/4 16x32 pixels RGB Led?

Thank you.

**Comment by hzeller** [comment]
On Aliexpress, you should be able to find lots of choices. I don't think that this forum can give any specific buying optons.

If you want to use them with this library, check out the description for multiplexing:
https://github.com/hzeller/rpi-rgb-led-matrix#multiplexing
