### ISSUE TITLE
Error working with Python 3

### ISSUE THREAD

**Issue by DebaGracias** [hzeller/rpi-rgb-led-matrix#479]
Hi All,
I am trying to run the runtext.py.I went through the steps documented in Readme file and followed the 1st step.
pi@RaspberryPiNoel ~/rpi-rgb-led-matrix/bindings/python $ sudo apt-get update && sudo apt-get install python3-dev python3-pillow -y
Hit http://mirrordirector.raspbian.org wheezy Release.gpg
Hit http://raspberrypi.collabora.com wheezy Release.gpg
Hit http://archive.raspberrypi.org wheezy Release.gpg
Hit http://raspberrypi.collabora.com wheezy Release
Hit http://mirrordirector.raspbian.org wheezy Release
Hit http://archive.raspberrypi.org wheezy Release
Hit http://raspberrypi.collabora.com wheezy/rpi armhf Packages
Hit http://mirrordirector.raspbian.org wheezy/main armhf Packages
Hit http://archive.raspberrypi.org wheezy/main armhf Packages
Hit http://mirrordirector.raspbian.org wheezy/contrib armhf Packages
Hit http://mirrordirector.raspbian.org wheezy/non-free armhf Packages
Hit http://mirrordirector.raspbian.org wheezy/rpi armhf Packages
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en_GB
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en
Ign http://archive.raspberrypi.org wheezy/main Translation-en_GB
Ign http://archive.raspberrypi.org wheezy/main Translation-en
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3-pillow

The I move forward to the 2nd step.When I execute the command I get the follo. error
pi@RaspberryPiNoel ~/rpi-rgb-led-matrix/bindings/python $ make build-python PYTHON3.2.3
make -C ../../lib
make[1]: Entering directory '/home/pi/rpi-rgb-led-matrix/lib'
make[1]: Leaving directory '/home/pi/rpi-rgb-led-matrix/lib'
python setup.py build --build-lib .
running build
running build_py
running build_ext
building 'core' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I../../include -I/usr/include/python2.7 -c rgbmatrix/core.cpp -o build/temp.linux-armv6l-2.7/rgbmatrix/core.o -O3 -Wall
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
rgbmatrix/core.cpp:4:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
Makefile:67: recipe for target 'build-python' failed
make: *** [build-python] Error 1

I am stuck at this point.Please help me on what to do next.

Thanks,
Debasish

**Comment by hzeller** [comment]
Why are you setting PYTHON3.2.3 in your make ? The documentation says to execute verbatimly

```
sudo make install-python PYTHON=$(which python3)
```
So, don't try to replace the `which` thing yourself, that is meant for the shell do do :)
