### ISSUE TITLE
Two 32x16 panels vertically

### ISSUE THREAD

**Issue by speedtek99** [hzeller/rpi-rgb-led-matrix#481]
Now that I figured out I had a bad pi, I am looking to stack my two 32x16 panels to make one 32x32 panel.  I'm using the adafruit hat - but cannot seem to get them to orient correctly. Searching I have found nothing on how to do this.  Any insights?

Thanks!

**Comment by hzeller** [comment]
Use the [UArrangementTransformer](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#remapping-coordinates).

**Comment by speedtek99** [comment]
Way easier than I thought, thanks!
