### ISSUE TITLE
DrawText with background not available in Python?

### ISSUE THREAD

**Issue by marwellit** [hzeller/rpi-rgb-led-matrix#487]
Hi

I've just installed a new sign with latest RGBMatrix download and when I try to use DrawText from Python (2.7) and specify background colour it complains that it only takes 6 arguments.....yet the C code documentation shows it with 8.

Everything is working fine otherwise 8-)

Is there something I'm doing wrong?

Many thanks
Dave

**Comment by hzeller** [comment]
It probably needs to be provided in the Python binding. If you need it, please send a pull request that adds it.
