### ISSUE TITLE
Issue with 64 x 32 RGB LED Panel - Bottom half not lighting up

### ISSUE THREAD

**Issue by adamwth** [hzeller/rpi-rgb-led-matrix#490]
Hi, I tried to display some of the demos and kept getting only one half of the 64 x 32 LED panel lit up. The problem is not with faulty LED lights on the other half because I was able to turn them on when I set --led-inverse. 

I tried to run the simple square demo with this command:  
sudo ./demo -D 3 ~~--led-cols=64~~
This was the result on a single 64 x 32 panel:
![simple square](https://user-images.githubusercontent.com/10760116/35473217-6d1658c0-03b7-11e8-8e8d-f3444cea143c.jpg)

(Apologies, I uploaded the wrong image previously. It was without --led-cols=64. The correct one when I entered sudo ./demo -D 3 --led-cols=64 is this:

![simple square with chain 2](https://user-images.githubusercontent.com/10760116/35474921-3f0579ac-03d0-11e8-9426-982019390f5c.jpg)

May I know what is the most likely problem for this? And how can I fix this?

Thanks in advance!

**Comment by hzeller** [comment]
Good question, this looks like they have some different kind of multiplexing going on inside.
Can you post a picture of the connector on the back ? Hopefully it has some silk-screen around that helps understand the inputs.
If you had a compiled version lying around and recently updated the code to get the `--led-cols` option, make sure to make clean everything before (there could be some mismatching struct sizes in the compiled binary).

How does the rotating square (`-D0`) look like ?

**Comment by adamwth** [comment]
(Back of my LED panel)
![64 x 32 led panel back](https://user-images.githubusercontent.com/10760116/35474956-ef8622a4-03d0-11e8-9145-9dc66e33f921.jpg)

(What happens when I ran rotating square -D0)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10760116/35475024-4dd4857a-03d2-11e8-8494-4e0f3f5ae508.gif)

Oh and I just cloned the repository today.

Thank you for replying!

**Comment by hzeller** [comment]
mmh, this looks strange. And apparently, there are no markings on the input port.
Could it be that this is a 1:32 multiplexing ? Do you have any documentation from the vendor ?
Can you try to also connect the 'E' line to either pin 4 or pin 8 (you have to try) to the panel and choose `--led-cols=64 --led-rows=64` and see if that makes a difference ? If so we might be able to get it to work.

**Comment by adamwth** [comment]
Ahh maybe it's because I got it from eBay.. The vendor didn't provide any documentation unfortunately.
What implications does 1:32 multiplexing have?

I'm not sure where the E pin is, is it the GND that is to the right of B2? If so, I tried connecting it to both pin 4 and 8, but the results didn't make a significant difference - one half is still not lighting up.

**Comment by hzeller** [comment]
Are you using logic level voltage converters to 5V logic level ? These are needed for most panels as they are 5V logic and the Pi only outputs 3.3V. You can temporary try to reduce the voltage on the panel to maybe 4V or so and see if that makes a difference.

What is strange is, that in the example above with `-D3`, it looks like some parts are displayed side-by-side, while with the `-D0` demo top/bottom is overlayd on top of each other but otherwise perfectly centered. This is puzzling. Both of these are with exactly the same options, right ?

(1:32 would mean that it is slower, but apparantly we don't have this here.)

**Comment by adamwth** [comment]
I am not using 5V logic converters as I don't currently have them on hand, but I will try sourcing them when I have the time! How do I reduce the voltage to 4V?

Yes, I ran both D3 D0 with the same option (--led-cols=64). I find it strange too, it seems like the logical levels for the LEDs in rows 17 - 32 are overflowing to those in rows 1-16.

**Comment by hzeller** [comment]
the the `-D0` looks like they are overflowing, while the `-D3` examples looks like they are streting every other pixel in the length.

If you have the LED panel on a bench power supply, you can reduce the voltage there (while you still operate your Raspberry Pi with an independent e.g. USB supply).

**Comment by adamwth** [comment]
Ah I don't have a bench power supply, but I will try to get the logic converters. I'll update here when I try them out.

**Comment by Ashish-Jog** [comment]
@adamwth Did you find any work around, I have an exact panel from Waveshare and bottom 16 rows (or exactly lower half) is not working.
