### ISSUE TITLE
Using this library with Apa102 White Led Matrix

### ISSUE THREAD

**Issue by stefanosky** [hzeller/rpi-rgb-led-matrix#491]
Hi
what a great project, do you know if this panel is compatible with you library functions?
It is a 16x16 matrix of White Led Apa102 chip
Thanks
![image](https://user-images.githubusercontent.com/22086710/35481604-25ee4302-0427-11e8-994c-c428d780131b.png)

**Comment by angelogoncalve** [comment]
See this issue https://github.com/hzeller/rpi-rgb-led-matrix/issues/136

**Comment by hzeller** [comment]
This won't work with the APA102, this is for low-level panels.
For APA102 matrix like the above, see another project of mine: http://spixels.org
