### ISSUE TITLE
Issue with 64 x 32 RGB LED Panel -- Interlaced display and top half always on

### ISSUE THREAD

**Issue by 594crab** [hzeller/rpi-rgb-led-matrix#492]
sudo ./demo -D 0
![-d0](https://user-images.githubusercontent.com/35894253/35483077-b12fb706-0478-11e8-994f-083f41b6d99e.jpg)
sudo ./demo -D 0 --led-cols=64
![-d0 --led-cols 64](https://user-images.githubusercontent.com/35894253/35483080-bd1c3b52-0478-11e8-8b39-8a03662c9df9.jpg)
sudo ./demo -D 3
![-d3](https://user-images.githubusercontent.com/35894253/35483082-c44aa21a-0478-11e8-8611-7e5e8b1e9a22.jpg)
sudo ./demo -D 0 --led-cols=64
![-d3 --led-cols 64](https://user-images.githubusercontent.com/35894253/35483083-c9cb7c32-0478-11e8-9b56-f7e7466caad2.jpg)

The pcb back:
![Uploading PCB-BACK.jpg…]()
The hub75 connector:
![Uploading HUB75.jpg…]()

I tried all the options of demo,the issue is not resolved.
I reduce the power supply from 5V to 4V,it is the same.
I was beated.

**Comment by 594crab** [comment]
row 1,3,5,7 and so on are on.And row 2,4,6,8 and so on are never on.

**Comment by hzeller** [comment]
double-check your address lines A, B, C, D. At least A is not properly connected.
If you continue to have issues make sure to first get logic level converters.

**Comment by 594crab** [comment]
u are right. A connect to 17 and G1 connect to 15.
thanks a lot.
