### ISSUE TITLE
I have problem

### ISSUE THREAD

**Issue by ffqqtv** [hzeller/rpi-rgb-led-matrix#499]
I want display a image type .jpg or .gif. One year ago, i used your library and i did good. But now, i can't do it. I was trying by follow your instruction, but i don't sucess. Please teach for me . Thank you so much.

**Comment by hzeller** [comment]
You didn't explain what the problem was.

**Comment by ffqqtv** [comment]
I am sorry. i want display an image or a dynamic image. But i don't look for way in to directory examples-api-use/ and is called 'demo'. Please help me. Thank you so much.
