### ISSUE TITLE
trying to call RunText class multiple times

### ISSUE THREAD

**Issue by GOBish** [hzeller/rpi-rgb-led-matrix#502]
Hi, thanks for the help in the past.

I am using the python scripts, basing off the runtext.py.

I am trying to loop the RunText(SampleBase) class a few times, so I can update what is being displayed.

So I am calling 
run_text = RunText()
in a loop in the Main function.

When I do this, however, the script runs fine the first time through the loop, but then I get an error
"Must run as root to be able to access /dev/mem
Prepend 'sudo' to the command.
Segmentation Fault.

I am running the script as sudo from the shell.

Thanks for the advice!

**Comment by hzeller** [comment]
You're creating the canvas multiple times, that can't work, as you are trying to access the same hardware resources multiple times.

What you should do instead is to create the matrix once, and then have the multiple texts you want to display write into the one canvas.
