### ISSUE TITLE
Weird multiplexing mode?

### ISSUE THREAD

**Issue by mansj** [hzeller/rpi-rgb-led-matrix#507]
I can't get any of the multiplexing modes to work right on my P10 16x32. 

See video: https://www.youtube.com/watch?v=ay-zYqXtmBA

This video ran `sudo ./examples-api-use/demo -D1 --led-gpio-mapping=adafruit-hat --led-cols=32 --led-rows=16  --led-brightness=40 examples-api-use/runtext16.ppm --led-multiplexing=3`

But all multiplexing modes look wrong in different ways. 

Any insight?

**Comment by hzeller** [comment]
mmh, this looks like a tradiional 1:8 multiplexing but with a 'reflected' second stripe.
What does the output with the flag `-D3 --led-cols=32 --led-rows=16` look like ?

**Comment by mansj** [comment]
Here's that mode with no other flags except adafruit-hat:

![img_2323](https://user-images.githubusercontent.com/592768/35961430-f6c53d80-0cad-11e8-956e-0d8c29a7d7ae.JPG)

**Comment by angelogoncalve** [comment]
Use sudo ./examples-api-use/demo -D1 --led-gpio-mapping=adafruit-hat --led-cols=32 --led-rows=16 --led-chain=1 --led-parallel=1 --led-brightness=100 examples-api-use/runtext16.ppm --led-multiplexing=1

**Comment by mansj** [comment]
No good unfortunately, @angelogoncalve : 
![img_4816](https://user-images.githubusercontent.com/592768/36020507-4b9d1776-0d83-11e8-8741-d8cb91c5dbe3.JPG)

**Comment by hzeller** [comment]
So looks like you need a transformer for this that maps 32x16 to 32x16 but with every other stripe of 4 going from the backwards. There is no standard transformer for this yet compiled-in, but it should be failry straight-forward for you to write.

Since this is not a multiplexing that reduces the number of lines, the standard multiplexing set-up doesn't work for that yet, but hopefully I can get some time on the weekend to prepare it in a way that it is easier to do.

**Comment by angelogoncalve** [comment]
Use sudo ./examples-api-use/demo -D1 --led-gpio-mapping=adafruit-hat --led-cols=16 --led-rows=8 --led-chain=2 --led-parallel=1 --led-brightness=100 examples-api-use/runtext16.ppm --led-multiplexing=1

**Comment by angelogoncalve** [comment]
or this way sudo ./examples-api-use/demo -D1 --led-gpio-mapping=adafruit-hat --led-cols=16 --led-rows=8 --led-chain=2 --led-parallel=1 --led-brightness=100 examples-api-use/runtext16.ppm --led-multiplexing=1

**Comment by angelogoncalve** [comment]
or use this way mode: --led-rows=16 --led-row-addr-type=2 --led-multiplexing=4

**Comment by angelogoncalve** [comment]
or this one: --led-rows=16 --led-row-addr-type=2 --led-multiplexing=0

**Comment by mansj** [comment]
Thanks, unfortunately during all this testing it seems that my (very cheap) LED panel has died, today I can't seem to get it to work at all, so most likely something burned out somewhere during my testing. I'll see if I can get a new one at the same price and try again.

**Comment by hzeller** [comment]
Alright. Once you're there, check out all the multiplexing options (another one has been added last week). If it doesn't work, just send a pull request with the binding needed for your panel.
