### ISSUE TITLE
Odroid C2 / 40Pins GPIO / ArmBian|DietPi

### ISSUE THREAD

**Issue by dma19** [hzeller/rpi-rgb-led-matrix#515]
Hello,

I used withtout problem on a RPI 3, 
but have performance problem with  multiple
( --led-chain=4 --led-rows=32 --led-parallel=2 p5 outdoor panel ).

So I buy, and install dietPi/armBian on odroid C2.
Compiled without problem.
But when I execute for example demo, my screen keep black.
I think GPIO's doesn't correctly with odroid C2, try also with wiringPi;

Can you help me?

Thanks!

**Comment by hzeller** [comment]
The odroid is not compatible with the Raspberry Pi, so this is expected.
