### ISSUE TITLE
unable to run python sample using RGBMatrix

### ISSUE THREAD

**Issue by Taprik** [hzeller/rpi-rgb-led-matrix#516]
the two sample
image-draw.py & image-viewer.py
display nothing. They seems to work as there is no errors and I can escape.
It's with : 
a recent PI3
the adafruit hat
the current raspbian image
python 2.7
the command is : sudo python image-draw.py --led-chain=4

The code of image.draw.py indicates that it needs rgbmatrix.so in the same folder. But the only rgbmatrix.so that I know is from the adafruit fork of the rgb matrix api but it does not work too

The other sample are working as expected

**Comment by hzeller** [comment]
If you have the Adafruit hat, you need to give the option [`--led-gpio-mapping=adafruit-hat`](https://github.com/hzeller/rpi-rgb-led-matrix#if-you-have-an-adafruit-hat).
