### ISSUE TITLE
Loking for some Info.

### ISSUE THREAD

**Issue by AG1023** [hzeller/rpi-rgb-led-matrix#535]
Hi Zeller / Hi Everybody!

I bought an RPI, a hat and an RGB led Matrix 32X32 (HUB75) from Adafruit, following the instructions for installation and configuration that appears on the website, I managed to run the library examples -D0 ...

Now I am interested in using the rpi-rgb-led-matrix / adapter / active-3 / (3 strings) because I would like to build 3 screens separately and get different images in each of them. I have tried to follow its instructions on github but I can not get an image so far ... it seems to me that it is something about configuration.

I would like to ask you some questions:
1- Is the matrix 32X32 of adafruit compatible with the rpi-rgb-led-matrix / adapter / active-3 / ???

2- Using the rpi-rgb-led-matrix / adapter / active-3 / I can master 3 screens (some 32x32 each) with different images on each screen ???
![32x32](https://user-images.githubusercontent.com/28967690/36829851-f5ccc294-1cee-11e8-8cbb-6f0d1ed59aeb.JPG)

3- Is there any information published for beginners where it explains the step by step for the configuration of the rpi-rgb-led-matrix / adapter / active-3 / (codes to write in the RPI included) ???

I include a photo of my hardware to facilitate the understanding of those explained above.

I thank you in advance !!!

AG

**Comment by hzeller** [comment]
1) I don't know that board as it seems to have come from some third party but if you are using the [standard wiring](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/wiring.md) like the [official boards that come with the project](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/adapter/active-3) it should just work. Note that the Adafruit description probably told you to use something like `--led-gpio-mapping=adafruit-hat`. Here, you don't need this option (or use it with `--led-gpio-mapping=regular`), as this is the official mapping

2) You can have different images on each screen, after all, it is just a canvas, _but_ you need to do that from one program. So write a program that puts different images on different sections of the screen.

3) Did you read the documentation and all the examples ? What is missing ?

**Comment by AG1023** [comment]
Thanks Zeller! 
I was actually using another board, anyway I bought the official board to be able to follow the material published by you. 

I look forward to the arrival of the new board. 

Keep in touch!

**Comment by AG1023** [comment]
Hi guys

Following the steps in running some demos, I have difficulties in continuing from here.

![image](https://user-images.githubusercontent.com/28967690/38165459-96b931a6-34e1-11e8-9fcf-f0de614a39c0.png)

**Comment by AG1023** [comment]
Got it!!!

![image](https://user-images.githubusercontent.com/28967690/38165619-697dfb1a-34e4-11e8-8fd8-3b1d20455001.png)

Thanks anyway!

**Comment by AG1023** [comment]
Hi guys!

Any advice to solve this problem shown in the video. The -D1 example starts ok but after a few seconds the image is affected. Maybe I need to place some extra flag or make some configuration ...???

Code used: $ sudo ./demo -t 20 --led-chain=2 -D 1 runtext.ppm

Video of the issue: https://www.youtube.com/watch?v=oa8pod8rOnU

Thanks in advance!

**Comment by hzeller** [comment]
Did you switch off the one-wire interface ? Please read the [troubleshooting section](https://github.com/hzeller/rpi-rgb-led-matrix#troubleshooting).

**Comment by AG1023** [comment]
You got it, Thanks Zeller!

Problem solved with this:

**I have also seen reports that on some Pis, the one-wire protocol is enabled (w1-gpio). This will also not work (disable by removing dtoverlay=w1-gpio in /boot/config.txt; or using raspi-config, Interface Options -> 1-Wire)**
