### ISSUE TITLE
Combine PPM and text input?

### ISSUE THREAD

**Issue by bmclain** [hzeller/rpi-rgb-led-matrix#540]
I'm planning on streaming text from an API but need to incorporate symbols in the form of images every so often. What's the best approach for this? Pull in the ImageScroller code from the demo and combine with the text scroller code in some way? Or is there an easier way to convert a handful of symbols into a custom font objects?

**Comment by hzeller** [comment]
I'd suggest to write a program from scratch - the demos are there to demonstrate things, but it mostly meant to help understand how things work.

Text is simply a bit of square image, that is drawn with the font library. Get yourself acquainted with that. Then you can also just draw other things by using regular dawing functionality.

If your pictograms are one-bit-single-color you might as well also create your own BDF font (which is simple, it is essentially the simplest format for fonts available, all font-editors should be able to deal with it).
