### ISSUE TITLE
[64x32 panel] 1st and 3rd quarter not showing

### ISSUE THREAD

**Issue by ct4711** [hzeller/rpi-rgb-led-matrix#546]
Hello!

**First at all thanks for this great project!**

I have a 64x32 panel from aliexpress (with some really bad soldered resistors) where the 1st and 3rd quarter of the display not showing anything.
The connections are double-checked and i think everything is connected correct.
I have also tried many combinations of the led-multiplexing and led-row-addr-type parameters without success.

Do i have a defective or unsupported panel?

Thanks in advance
ct4711

![screen1](https://user-images.githubusercontent.com/37120278/37052862-e4071736-217a-11e8-8786-e61d34b5f097.jpg)
![board](https://user-images.githubusercontent.com/37120278/37052886-f3ae9614-217a-11e8-84df-6e8fe1f63ae1.jpg)

**Comment by hzeller** [comment]
If you have everything connected, then this looks indeed like a defective panel unless they have some different multiplexing. You do have a different color mapping for some reason, but you can change that with `--led-rgb-sequence`.

Do you have a close-up picture of input connector and any markings it might have ?

**Comment by ct4711** [comment]
You are absolutly right, the right color mapping for this panel is RBG.

The connector doesn't have any markings, but now i'm 100% sure that the panel is defective:
If i bend the pcb a bit the 1st and 3rd quarter are flickering.

Thank you for your response and clearing out that it has to be a hardware problem.
