### ISSUE TITLE
Output Display blinks instead of having single manual physical gpio button for on & off 

### ISSUE THREAD

**Issue by henrylowzh** [hzeller/rpi-rgb-led-matrix#548]
Hi there,

I have created a manual trigger button(on/off) gpio button for my output. I took the "image-viewer.py" sample code as a reference. For your infomation I'm using a 64x128 display with a E line and had perform the pwm mod on the adafruit-hat.

When i launched the script, the gpio button automatics triggers both On & Off(getting a undesired Blink Display) without me pressing anything. I'm curious is there anything on the rgbmatrix module conflicting with the gpio? Or is there somewhere wrong in the code?

please find my code below:

```
import time     # Import sleep Library
import sys
import RPi.GPIO as GPIO    # Import GPIO Library
from rgbmatrix import RGBMatrix, RGBMatrixOptions
from PIL import Image

state = True
size = 64, 64

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)   # Use Physical Pin Numbering Scheme
button1=21                 # Button 1 is connected to physical pin 40

GPIO.setup(button1,GPIO.IN,pull_up_down=GPIO.PUD_UP) # Make button1 an input, Activate Pull UP Resistor

BS1=False                  # Set Flag BS1 to indicate Display is initially off

image_file1 = '/home/pi/rpi-rgb-led-matrix/danger.jpg'
image1 = Image.open(image_file1)
imageprop1 = image1.convert("RGB").rotate(180)

options = RGBMatrixOptions()
options.rows = 64
options.cols =128
options.chain_length = 1
options.parallel = 1
options.hardware_mapping = 'adafruit-hat-pwm'  # If you have an Adafruit HAT: 'adafruit-hat'

matrix = RGBMatrix(options = options)

while(1):                  # Create an infinite Loop
        if GPIO.input(button1)==0:            # Look for button to press
                if BS1==False:                # If the Display is off
                        print"Button was Pressed to Turn Display ON"
                        BS1=True              # Set Flag to show Display is now On
                        image1.thumbnail(size, Image.ANTIALIAS)
			image1.load()
			matrix.SetImage(imageprop1,32,0,)
			time.sleep(.5)             # Delay
                else:                         # If the Display is ON
                        print"Button Was Pressed to Turn Off"
                        matrix.Clear()
                        BS1=False               # Set Flag to show Display is now Off
                        time.sleep(.5)

```

**Comment by henrylowzh** [comment]
Hi @hzeller,

Thank You for your advice. For starters edited the GPIO setup after the matrix initialization
```
matrix = RGBMatrix(options = options)
GPIO.setup(button1,GPIO.IN,pull_up_down=GPIO.PUD_UP) 
```
However, i get a runtime error whereby
```
File "worktest4.py", line 27, in <module>
    GPIO.setup(button1,GPIO.IN,pull_up_down=GPIO.PUD_UP) # Make button1 an input, Activate Pull UP Resistor
RuntimeError: No access to /dev/mem.  Try running as root!
```
even though i had run the script on sudo(root)

I had also checked on the permission access for gpiomem
```
crw-rw---- 1 root gpio 244, 0 Mar  8 11:41 /dev/gpiomem
```
I might have a mistake somewhere. Could you advice?

**Comment by hzeller** [comment]
The default led matrix start drops the privileges. Can you set the drop_privileges value in the runtime options to false ?

**Comment by henrylowzh** [comment]
Hi @hzeller 

That totally works. The button is working as expected.
However the display image on the led matrix turn out wasn't good. The display color seem to be stretch and there were some slight flickering. Has this anything got to do with the refresh rate or pwm?
<a href="https://ibb.co/hNzA3S"><img src="https://preview.ibb.co/m6k6cn/28870272_10213108723407117_8273359128206770176_o.jpg" alt="28870272_10213108723407117_8273359128206770176_o" border="0"></a>

Compare to the earlier display which was good but was blinking
<a href="https://ibb.co/m5zoq7"><img src="https://preview.ibb.co/cx8Rcn/28870984_10213108723327115_2440045889511751680_o.jpg" alt="28870984_10213108723327115_2440045889511751680_o" border="0"></a>

**Comment by hzeller** [comment]
mmh, I don't know what the GPIO library in Python does to the rest of the system, hopefully it just reads the value, but it _looks_ like it messes with the data.
I can't really help here, as I usually do all my GPIO stuff in C++, but maybe someone else knows if there are weird interactions with the GPIO library in Python ?

**Comment by henrylowzh** [comment]
Alright Sure~
Thank You very much for your help though~

**Comment by hzeller** [comment]
Maybe the very fast polling in your endless-loop is creating too much memory bandwidth pressure on the GPIO. Try to sleep for 100ms between your loops. If this is for interactive input from users, this will be fast enough, but it will not mess with the GPIO subsystem tens of thousands of times a second.

**Comment by angelogoncalve** [comment]
Try this:

options = RGBMatrixOptions()
options.rows = 64
options.cols =128
options.chain_length = 1
options.parallel = 1
options.hardware_mapping = 'adafruit-hat-pwm'

options.gpio_slowdown = 4
options.pwm_lsb_nanoseconds = 130
options.pwm_bits = 1

**Comment by henrylowzh** [comment]
Hi @angelogoncalve Hi @hzeller 

I took your advice changed the delay to at least 100ms and added in the 
```
options.gpio_slowdown = 4
options.pwm_lsb_nanoseconds = 130
options.pwm_bits = 1
```
the modifications kinda improve the display quality. However, looks like i'm forced to change the 
```
options.hardware_mapping = 'adafruit-hat-pwm'
```
 to 'adafruit-hat' as with -pwm i'm getting distorted displays.

Thank you very much guys. Appreciate it.

**Comment by angelogoncalve** [comment]
Yes you are correct I forgot to tell you about this option to change also. Sorry my friend.

options.hardware_mapping = 'adafruit-hat'

**Comment by hzeller** [comment]
So looking at your first code again: you are using GPIO21 as input, but that is actually being used by the Adafruit HAT for strobe. So whatever you read there might indeed be wonky. Only GPIO inputs 2 3 7 8 9 10 11 14 15 19 24 25 are available.
