### ISSUE TITLE
Adafruit RGB Matrix HAT + RTC for Raspberry Pi

### ISSUE THREAD

**Issue by DebaGracias** [hzeller/rpi-rgb-led-matrix#550]
Hi All,
I purchased a Adafruit RGB Matrix HAT + RTC and mounted it on my Ras Pi 3 .I followed all the steps mentioned in the [link ](https://learn.adafruit.com/adafruit-rgb-matrix-plus-real-time-clock-hat-for-raspberry-pi).However when I try to run my code using this library ,I dont see the desired result.I just see few lines of leds lit.I dont know what i'm doing wrong.
I ordered the LED board from [AliExpress](https://www.aliexpress.com/item/40-inch-101cm-ios-And-Android-Wifi-wireless-remote-Programmable-Advertising-LED-Display-Board-Bright-Red/32752577115.html?spm=a2g0s.9042311.0.0.F3UzUv)
I have also attached an image of Input Pin diagram of LED board and an image showing the issue.
![led display result](https://user-images.githubusercontent.com/33568195/37138437-0cda34bc-22d0-11e8-9983-2104970461cd.PNG)
![ledboarddiagram](https://user-images.githubusercontent.com/33568195/37138439-0d0e3474-22d0-11e8-8273-68175e717201.PNG)

Could it be that the HAT is not compatible with this LED board?

**Comment by hzeller** [comment]
indeed, looks like you got a red/green panel with hub12 connector, not RGB with hub75. You might need to do some manual wiring and inversion of OE to get it to work with this library.

**Comment by hzeller** [comment]
We can probably combine this with the collecting bug for Hub12 requests #531 and close this one to keep things simple.
