### ISSUE TITLE
Raspberry Pi 3 Model B+

### ISSUE THREAD

**Issue by beikimajid** [hzeller/rpi-rgb-led-matrix#555]
Hi
How much does this new version affect in 
flicker and image enhancement?

The Raspberry Pi 3 Model B+ is the latest product in the Raspberry Pi 3 range.

    Broadcom BCM2837B0, Cortex-A53 (ARMv8) 64-bit SoC @ 1.4GHz
    1GB LPDDR2 SDRAM
    2.4GHz and 5GHz IEEE 802.11.b/g/n/ac wireless LAN, Bluetooth 4.2, BLE
    Gigabit Ethernet over USB 2.0 (maximum throughput 300 Mbps)
    Extended 40-pin GPIO header
    Full-size HDMI
    4 USB 2.0 ports
    CSI camera port for connecting a Raspberry Pi camera
    DSI display port for connecting a Raspberry Pi touchscreen display
    4-pole stereo output and composite video port
    Micro SD port for loading your operating system and storing data
    5V/2.5A DC power input
    Power-over-Ethernet (PoE) support (requires separate PoE HAT)

**Comment by hzeller** [comment]
Someone needs to try this

**Comment by hzeller** [comment]
Yes, looks like the B+ is working.
Given that it only got marginally faster, there is probably not much difference in potential flicker.
