### ISSUE TITLE
Problems with P5 32x32 1/8 scan display.

### ISSUE THREAD

**Issue by Lookandfind** [hzeller/rpi-rgb-led-matrix#559]
Hi guys thanks for work for this library. 

I read that other people had simular problems with first use, but with their solution i couldn't solve my problem.
I wired the display after the schematic on the first page and tryed a lot of different parameters like --led-multiplexing=0..5
But the best result is with multiplex =0
As you can see in the picture, i  belive that i have some lines double?
Can anybody give me a hint what i can do?

thanks for your time 

![photo_2018-03-18_00-49-24](https://user-images.githubusercontent.com/37489298/37561113-8eff3690-2a46-11e8-86ec-89adb21494c6.jpg)

**Comment by hzeller** [comment]
Do you have a picture of the connector on the board, that might indicate further details about the address mode ? Do you have a link or description of hte particular panel ?

The double lines indicate that it might be something like `--led-row-addr-type=2`, but then with an unusual case of 1:4 multiplexing ? Maybe it has a yet unknown address type format.

**Comment by angelogoncalve** [comment]
apply --led-multiplexing=6

or --led-multiplexing=4 --led-row-addr-type=2

or

MATRIX_ROWS = 32
MATRIX_COLUMNS = 32

    def chinese(x, y):
        scan_rate = MATRIX_ROWS / 4

            odd8_block = (((y % (.MATRIX_ROWS / 2)) / scan_rate) + 1) % 2
            num_mod_x = x / MATRIX_COLUMNS
            new_x = x + MATRIX_COLUMNS * (num_mod_x + odd8_block)
            new_y = (y % scan_rate) + scan_rate * (y / (MATRIX_ROWS / 2))

        return new_x, new_y

or

MATRIX_ROWS = 32
MATRIX_COLUMNS = 32

    def electrodragon(x, y):
            scan_rate = MATRIX_ROWS / 4
            new_x = ((x / (MATRIX_COLUMNS / 2)) * MATRIX_COLUMNS) + (x % (
                        MATRIX_COLUMNS / 2))
            if (y / scan_rate) % 2 == 1:
                new_x += MATRIX_COLUMNS / 2
            new_y = ((y / (MATRIX_ROWS / 2)) * (MATRIX_ROWS / 2)) + (y % scan_rate)
        return new_x, new_y

**Comment by Lookandfind** [comment]
Hi, 
I dont have further informations about the display i bought it over a yeahr ago on Aliexpress.
But here is a picture of the back


![photo_2018-03-19_17-43-31](https://user-images.githubusercontent.com/37489298/37609643-ec07269c-2b9d-11e8-8f2c-34594884b881.jpg)

This is a pic of using --led-multiplexing = 6

**Comment by rafayhayat** [comment]
I also have 32*32 panel with 1/8 scan rate, could you please suggest me any of the library as adafruit RGB Matrix Panel library is not working with the panel
