### ISSUE TITLE
[Large Screen] 64x64 Matrix

### ISSUE THREAD

**Issue by DnR-iData** [hzeller/rpi-rgb-led-matrix#563]
Hi mates,

I would like to know how I can in Python set the Large Screen Mode, like the "**-L**" argument with the demo command : 
```bash
sudo ./demo -D0 --led-rows=32 --led-cols=32 --led-chain=4 -L --led-brightness=30
```
![demo](https://user-images.githubusercontent.com/2852024/37594989-57a8dc28-2b77-11e8-9d68-c7e0d0b361c6.png)

The second part of the "O" is missing with Python :
![o](https://user-images.githubusercontent.com/2852024/37595098-c023841a-2b77-11e8-8bd6-181bd330a701.png)

I don't really understand how transformers works.

Can you give me a little help please.

Thank You in advance.

iData

**Comment by hzeller** [comment]
You need to update to the latest version of this library, then use the flags
  `--led-pixel-mapper="U-mapper" --led-chain=4`
This will work for this arrangement in both, C++ and Python programs.
If you are working with the options directly in your program, set the `pixel_mapper_config` value to `"U-mapper"`.

**Comment by DnR-iData** [comment]
Perfect :
![o](https://user-images.githubusercontent.com/2852024/37619938-2394194a-2bbb-11e8-8da1-6064a04a0eeb.jpg)

Thank you so mutch.

All ok :)

**Comment by DnR-iData** [comment]
I close the issu.

Thx
