### ISSUE TITLE
Maximum distance of signal cables

### ISSUE THREAD

**Issue by rkasperski** [hzeller/rpi-rgb-led-matrix#569]
I'm building a set of 6 timers for my curling rink and am trying, perhaps with false economy, to minimize the expense by minimizing the number controllers. Sharing a controller between two sheets would imply that the maximum signally cable distance, assuming equi-distance, would be about 2.5m. Better yet, would be to share the controller among all 6 sheets where the maximum distance would be about 15m. The cables I've come across are all quite short, all quite short of even 2.5m.  Is there a practical maximum length to the cables? thanks

**Comment by hzeller** [comment]
mmh. I would not really go longer than 50cm or so: the frequencies involved are in the order of 30+ Mhz so it would not work very well with long lines, in particular as the cables are not shielded. If you do experiments like that make sure to use the digital level converters and not drive the long cable directly from the Pi GPIO.

You might need to use the slowdown GPIO flag to arrive in a good working condition.

I have tried cables up to 50cm and it worked fine, but I don't know how much safety margin is left.
