### ISSUE TITLE
No output to 64x64 panel

### ISSUE THREAD

**Issue by fxmech** [hzeller/rpi-rgb-led-matrix#580]
I installed your library on a rapsberry pi3 but cant seem to get it to work with my 64x64 1/32 scan from adafruit.

The line I am using is:
sudo ./led-image-viewer /home/pi/Pictures/emo.jpg --led-rows=64 --led-cols=64

the reply is:
Size: 64x64. Hardware gpio mapping: regular
Loading 1 files...
Loading took 0.024s; now: Display

There is no output to the screen (completely dark)

Ive been able to display an image on the exact same hardware setup using the rpi-rgb-led-matrix library using:
sudo ./demo -D1 /home/pi/Pictures/emo.ppm --led-rows=64 --led-cols=64

**Comment by DonDalle** [comment]
Did you fix it? If yes, which settings did you use?
