### ISSUE TITLE
No LED being turned on

### ISSUE THREAD

**Issue by nictruong** [hzeller/rpi-rgb-led-matrix#597]
I bought a 16x32 matrix from Aliexpress: https://www.aliexpress.com/item/Freeshipping-outdoor-p10-smd-led-display-module-16x32-32x16-160x320-320x160-1-2-scan-high-brightenss/32669606028.html

I wired and rewired according to the README and I ran this command:

`sudo examples-api-use/demo -D0`

This is what I see: 

`FYI: Couldn't set affinity 0x8: Invalid argument`
`Size: 32x16. Hardware gpio mapping: regular`
`Press <CTRL-C> to exit and reset LEDs`

But not a single LED is being turned on. 

![image](https://user-images.githubusercontent.com/8978617/39089156-7dfb3a20-458e-11e8-9f34-2e77271d2523.png)

In the README, there is a 'c' pin, which I don't see. did I rightly assume it is the same as 'NC'? I have 3 wires not connected to anything: the 3 bottom GND pins of the right column.

This is an overview of what I have:

![image](https://user-images.githubusercontent.com/8978617/39089213-6664b0d4-458f-11e8-8983-9f88798e634e.png)

Can someone point me in the right direction? `FYI: Couldn't set affinity 0x8: Invalid argument` how can I fix this message? Is my matrix defective?

I am a JavaScript dev, I was going to play around with the NodeJS bindings for this, but that project is not maintained anymore.

**Comment by nictruong** [comment]
Thank you for your quick reply.

I was trying a bunch of commands with different values of --led-multiplexing and --led-row-addr-type, got frustrated because none of them worked, and decided to switch the 2.1mm plug jack adaptor connecting to the power supply, I now see a board with turned on LEDs!

I really appreciate you trying to help me. Cheers.

**Comment by hzeller** [comment]
Ha, yes, sometimes things as simple as the power supply can be the culprit :)

**Comment by angelogoncalve** [comment]
See the issue https://github.com/hzeller/rpi-rgb-led-matrix/issues/592.

Try the option:

sudo ./demo -D3 --led-rows=16 --led-cols=32 --led-multiplexing=7 --led-row-addr-type=0

**Comment by nictruong** [comment]
Hi angelogoncalve

I tried your command (after downloading and compiling the multiplex-mappers.cc file containing --led-plexing=7). I get a garbage image:

![image](https://user-images.githubusercontent.com/8978617/39097967-a1c2afbc-4631-11e8-9d14-fcc64fedc7a8.png)

I have tried every combinations of the following commands:

` sudo ./demo -D3 --led-rows=16 --led-cols=32 --led-multiplexing={0-7} --led-row-addr-type={0-2}`

Reading the README, since I have a A-B panel, it would seem I should be using `--led-row-addr-type=1`, but alas, it has not given me good results. `-D3` is supposed to give me a square right? Do you have any other advice for me?

**Comment by nictruong** [comment]
Just saw that there was a new PR probably merged after I cloned the project. Will try that and report back.
