### ISSUE TITLE
11 bit colorspace

### ISSUE THREAD

**Issue by meredithheskethfortescue** [hzeller/rpi-rgb-led-matrix#609]
Hi, 
I'm trying to get a very specific color value and would like to set the pwm manually (using Python).
The pwm has a 11 bit resolution, but via `matrix.SetPixel(...)` it's only possible to set an 8 bit colorspace.
I already found the `do_luminance_correct_` function in the `framebuffer.cc` and set it to `false`. 

I'm aware that the reduction of bit depth is necessary for the CIE luminance correction but since I don't need that, I would like to set the pwm with the `matrix.SetPixel(...)` command.
Is this somehow possible?

Best Regards,
Meredith

**Comment by hzeller** [comment]
So right now this is not exposed in the API somehow.
It should be fairly simple for you to add, but I am not sure how useful it would be for others, that I why I am careful if it should be considered for the mainline version.

What do you intend to use it for ?
