### ISSUE TITLE
Problem with  Pixel Mapping

### ISSUE THREAD

**Issue by hemanthkd** [hzeller/rpi-rgb-led-matrix#616]
Hi there!

I am trying to use 24 panels(P4 32*64 ) in 3 rows(8 panels in each row). Unfortunately, I am getting a distorted image which is different than what I have feeded. So please help me out 

sudo ./led-image-viewer  --led-multiplexing=3 --led-brightness=70  --led-cols=64 --led-rows=32 --led-chain=8  --led-parallel=3  --led-no-hardware-pulse nexus.jpg

![nexus](https://user-images.githubusercontent.com/38958852/39816713-a23b21be-53b9-11e8-93b1-0ed30eae8b81.jpg)
![observed image](https://user-images.githubusercontent.com/38958852/39816934-5d9c4e74-53ba-11e8-9619-dc61dc0b9679.jpeg)

**Comment by hzeller** [comment]
Maybe your panels need a different `--led-multiplexing` option ? Did you try all the available ones ?

**Comment by hemanthkd** [comment]
Yes, I have tried all the 3 available values. Even more, this is the best among other outputs

**Comment by hzeller** [comment]
There are 9 available values at this point; are you using the latest library ?

**Comment by hemanthkd** [comment]
Hi there, I am using the following library
git clone --recursive https://github.com/hzeller/rpi-matrix-pixelpusher.git

**Comment by hzeller** [comment]
In that project, update the matrix/ submodule to match the latest master.

**Comment by hemanthkd** [comment]
As of your suggestion, I have tried all the existing values. Unfortunately, the output with multiplexing=3,4,5,8 are somewhat better sliced
![mux_5](https://user-images.githubusercontent.com/38958852/40051933-1d8412e6-585a-11e8-9d2e-2c62a334db9f.jpeg)
![mux_8](https://user-images.githubusercontent.com/38958852/40051934-1db2a0f2-585a-11e8-8272-07db717ac7b5.jpeg)
![mux_3](https://user-images.githubusercontent.com/38958852/40051935-1de2b936-585a-11e8-8d19-b173105a3a0c.jpeg)
![mux_4](https://user-images.githubusercontent.com/38958852/40051936-1e0e3412-585a-11e8-9ab6-ac35a68abc7b.jpeg)

**Comment by hemanthkd** [comment]
Is it some addressing issue??

**Comment by hzeller** [comment]
It is a pixel-mapping issue. So you need to systematically determine what the pixel-mapping is of your boards (e.g. by sending one pixel at a time), then implement another [MultiplexMapper](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/multiplex-mappers.cc).

Please send a pull request with the result, because probably someone else has a similar panel and will be happy if that pixel mapping is already in the distribution.
