### ISSUE TITLE
Clarification about GND connections on wiring.md

### ISSUE THREAD

**Issue by onionsTasteGood** [hzeller/rpi-rgb-led-matrix#618]
First of all many thanks for the amazing library.

I'm not very experienced with hardware electronics. I'm trying to connect 3 chains of 64x32 panels. I wired up the rpi/panels as instructed in wiring.md. I noticed two GND connections are left disconnected. 

wiring.md mentions that "there are more GND pins on the Raspberry Pi, but they are left out for simplicity". Does that mean that the two GND connections should be left disconnected or should they be connected to a ground pin on the rpi?

Many thanks!

**Comment by hzeller** [comment]
You should connect the GND of the panels to the GND of the Pi. But since the Pi has many GND pins, only one is sufficient.
