### ISSUE TITLE
Limit to # of panels (32x32) that you can chain?

### ISSUE THREAD

**Issue by roykolak** [hzeller/rpi-rgb-led-matrix#62]
This is more of an exploratory question. I'm interested in making a 16:9-ish display. Using the 64x64 coordinate example code as a basis, is it reasonable to assume that you can scale up to 3x2 panels providing you have enough power?

Sidenote: thanks for all your work on this. Really cool stuff!

**Comment by roykolak** [comment]
errr... it's in the readme!

> On a Raspberry Pi 2, you can easily chain 12 panels in that chain (so 36 panels total)

closing...

**Comment by hzeller** [comment]
Note, I think I only ever tried 8 or so, but the 12 should be realistic. You probably need to set 
`-DRGB_SLOWDOWN_GPIO`
