### ISSUE TITLE
Looping playback on video-viewer?

### ISSUE THREAD

**Issue by gpvillamil** [hzeller/rpi-rgb-led-matrix#620]
Everything is working well with a 64x32 panel and the Adafruit Hat w PWM.

I'm just wondering, is it possible to loop playback on the video-viewer utility? I'd like to leave a short loop running continuously.

**Comment by hzeller** [comment]
You'll have to add that to the video viewer.
Alternatively, you can just create a stream out of the video (and write it out with `-O`), then use the image-viewer to loop that.

**Comment by ccoenen** [comment]
I'm running the video viewer in a endless loop in the shell (my video starts and ends in black, so there's no visible flicker).

```bash
#!/usr/bin/env bash
while :
do
  /path/to/video-viewer /path/to/video/pixelmatrix.mp4
done
```

**Comment by hzeller** [comment]
Added now in https://github.com/hzeller/rpi-rgb-led-matrix/commit/1c50740e773f5af356e60a2608f9bac47ee0d5f7 with a new command-line option `-f`.

However, I still would strongly suggest to create a pre-calculated uncompressed stream which then can be played with much less potential flicker on the Pi. Much less stress on the memory subsystem in the Pi.

 ```
  /path/to/video-viewer --led-chain=3 --led-parallel=3 myvideo.mp4 -O/tmp/myvideo.stream
  sudo /path/to/led-image-viewer --led-chain=3 --led-parallel=3 /tmp/myvideo.stream
```
