### ISSUE TITLE
Running out of memory after many frameCanvases

### ISSUE THREAD

**Issue by hacker6284** [hzeller/rpi-rgb-led-matrix#622]
First of all I wanted to say thanks for making this library. It has been very helpful for me. One issue I am having though is that I do most of my changes with frame canvases because it allows for a smoother transition, but after ~50,000 canvases (I know its a lot) the board glitches out, I assume because of memory problems. I can't figure out how to delete the frames because the only place your code allows for it is in the matrix deconstruction, but deleting my matrix is causing me other problems. I was wondering if you had a suggestion on what I should do?

**Comment by hzeller** [comment]
You only really should have few FrameCanvases (typically really only two) that you use in your system, and then fill them on demand. The size of a FrameCanvas is larger than just the image size, as it is preprocessed in a way that allows fast updates - so if you keep many of them in memory, you might run out of it quickly.

If you have large animations, consider putting them in an `rgb_matrix::SreamIO`. 
https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/include/content-streamer.h

There is an implementation that just keeps things in main-memory (but of course, that wouldn't buy you much), but also one that allows you to write the content to a file and then later retrieve.

The image viewer in the utils/ directory makes use of that. It only has a single additional FrameCanvas that it uses to swap, but the content can be read from a StreamIO.
