### ISSUE TITLE
--led-brightness does not work

### ISSUE THREAD

**Issue by mblue002** [hzeller/rpi-rgb-led-matrix#623]
Hello,
I have this *great* package driving a chain of 3 32x32 panels at 1/8 scan rate.
The default brightness level is quite bright and I have been trying to lower is by using the --led-brightness setting on the command line. Between --led-brightness=100 and --led-brightness=77, this is no visible change, it's still very bright. Once I reduce it to 76% with --led-brightness=76, and all settings below that, the display is blank. I only need the basic colors, so --led-pwm-bits=1.

I am using led-image-viewer in /utils as follows:
sudo ./led-image-viewer --led-rows=32 --led-cols=32 --led-chain=3 --led-multiplexing=6 --led-slowdown-gpio=3 --led-pwm-bits=1 --led-rgb-sequence=BRG  --led-brightness=100 filename

Thanks in advance,
Mike

**Comment by hzeller** [comment]
Well, if you only have one bit PWM, then they can either be on or off, so you can't control the brightness
So this works as intended.

Choose higher PWM settings if you want to modulate the brightness.
