### ISSUE TITLE
Problem with commands not found, and or no path

### ISSUE THREAD

**Issue by TheBlueNight360** [hzeller/rpi-rgb-led-matrix#627]
Hi I am having a problem, where the commands that I try and not working and it says that the command is unknown. 
![15274261577625029313232363311776](https://user-images.githubusercontent.com/37707364/40586188-0f2eb368-61bf-11e8-959b-e198079106ba.jpg)
![15274264142702328132605459626697](https://user-images.githubusercontent.com/37707364/40586217-be9b2318-61bf-11e8-8cf9-0707ba959612.jpg)

**Comment by hzeller** [comment]
read the error message - it says that you have to go to `examples-api-use/`

**Comment by TheBlueNight360** [comment]
Hi I am struggling to find how to add images and or Gif files and how to play them on the matrix. Could ypu please help and thanks for the help on the previous response

**Comment by angelogoncalve** [comment]
See this file the methods:

load_animation; load_animation1

[image_utils.zip](https://github.com/hzeller/rpi-rgb-led-matrix/files/2051375/image_utils.zip)
