### ISSUE TITLE
Large fonts

### ISSUE THREAD

**Issue by dzshanno** [hzeller/rpi-rgb-led-matrix#632]
HI, 
Amazing repo thanks - means I can see a way to create the scoreboard for my hockey team.

Is there a way to scale the fonts to make them bigger? Ideally id like to fill a single 16x32 panel with a single portrait oriented digit if that makes sense.

D

**Comment by angelogoncalve** [comment]
Use this:

def create_dir(file_path):
    """ Create a new dir, if not already exists """
    if not os.path.exists(file_path):  # check if file not exists
        #logging.error("The file does not exist, %s", file_path)
        loggers.error("The file does not exist, %s", file_path)
        raise IOError("The file path is not a file")
        #return 'File not found'
        os.makedirs(file_path)
    #logging.info("Loading file from %s", file_path)
    loggers.info("Loading file from %s", file_path)
    return file_path


def get_file(name_file):
    # Get the Current Dir
    #path = os.getcwd()
    path = os.path.dirname(__file__)
    file_path = os.path.join(path, name_file)

    file_path1 = create_dir(file_path)
    return file_path1


def load_font(font_text, font_size):
    """ Load the fonts file that will be used by the display """
    font_file = get_file('fonts/' + font_text)
    if os.path.isfile(font_file):
        if font_file.lower().endswith(".bdf"):
            font = graphics.Font()
            #font = font_file.format(font_size, font_size)
            font.LoadFont(font_file)
            font.CharacterWidth(font_size)
        elif font_file.lower().endswith(".ttf") or font_file.lower().endswith(".otf"):
            font = ImageFont.truetype(font_file, font_size)
        elif font_file.lower().endswith(".pil"):
            font = ImageFont.load(font_file)
    return font

**Comment by dzshanno** [comment]
Thanks for your quick response. So would font_size be the pixel width of the characters?

**Comment by angelogoncalve** [comment]
Yes if you use a bdf font file type, font_size be the pixel width of the characters.

If you use a ttf or otf font file type, font_size be the pixel height and width of the characters.

**Comment by dzshanno** [comment]
Does CharacterWidth(x) set the width or return what the width is?

**Comment by hzeller** [comment]
I usually use the
https://www.math.nmsu.edu/~mleisher/Software/otf2bdf/
converter to convert fonts from true-type to BDF in any size.  Then you can use the functions provided in this library to write text with that font and size.

**Comment by anandrajgupta** [comment]
Thank you for the info, how to check if font is loaded successfully?

**Comment by anandrajgupta** [comment]
Is there any way to check if the font .bdf file was found at the provided location or not?
