### ISSUE TITLE
led matrix lots of noise 

### ISSUE THREAD

**Issue by jasonv3** [hzeller/rpi-rgb-led-matrix#635]
i am sure i make right wiring,and use adaruit led 16x32 . but every demo i run,i found they have noise,blink situation,here is the secene https://www.youtube.com/watch?v=6wLBvYCgUoY .any body help me make out.

**Comment by hzeller** [comment]
First things first: Did you read the troubleshooting section https://github.com/hzeller/rpi-rgb-led-matrix#troubleshooting and followed all things mentioned there ?

**Comment by angelogoncalve** [comment]
Use this option when create the rgbmatrix:
options.gpio_slowdown = 4

**Comment by russdx** [comment]
May also need to add a buffer chip if your currently  talking directly to the raspberry gpio. Some boards need a clean 5v signals.
