### ISSUE TITLE
Multiple instances of RGBMatrix

### ISSUE THREAD

**Issue by werling** [hzeller/rpi-rgb-led-matrix#640]
Hello,

I have an a questions regarding the use of multiple python programs, which all use different instances of the RGBMatrix class.  

For example i use a tool to show an image and i start another program for generating some effects (e.g. sparkling particles). The two programs run independent from each other, but on the display they will be overlayed.
So far is everything as expected.

But if i close one program with "kill -15" signal the display will be black, even the other program is still running. Why is that? 

What I also found out is, that if I kill a program with "kill -1", the display is working like expected and is showing only the output of the other program.

Can somebody explain this behaviour? Is it problematic to use "kill -1", because some resources are not correctly released?

Thank you very much!

**Comment by hzeller** [comment]
You can't run multiple programs that all want to output something on the panel, the hardware only exists once. So you will see all kinds of artifacts if you try to do that.

Instead, write one program that receives new frames over the network (e.g. use a FlaschenTaschen server), then have various programs send over their image content.

**Comment by angelogoncalve** [comment]
class Singleton(type):
    """
    Singleton for Matrix initialization once
    """
    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
        return cls._instances[cls]


class Matrix(object):
    """
    Matrix Class initialization
    """
    __metaclass__ = Singleton

**Comment by werling** [comment]
Hello,
thanks for your responses. I thought maybe this would be a more common thing and like I wrote, it kind of works with the "kill -1" terminal command.
But nevertheless I will have a look at the FlaschenTaschen server.
