### ISSUE TITLE
Non issue - Question?

### ISSUE THREAD

**Issue by PhilDunphy** [hzeller/rpi-rgb-led-matrix#641]
Is it possible to prevent text from scrolling and to stay static on screen?

**Comment by danielhdzzz** [comment]
Remove any incrementing variables in the code. Like `pos += 1` or `pos -=1`.

**Comment by hzeller** [comment]
When you use the library to write your own programs you can display anything you want.
Don't use the demo program to display anything, it really is only meant to demo things.
