### ISSUE TITLE
Lower half of 4 panels doesn't display red channel

### ISSUE THREAD

**Issue by swalsch** [hzeller/rpi-rgb-led-matrix#649]
![redchannel](https://user-images.githubusercontent.com/40644782/41999674-9b72a458-7a5e-11e8-955f-d7af0cefa40a.jpg)
The lower half of all 4 of these 32x32 panels won't light up red leds. This worked properly before, when I was just following the outdated adafruit tutorial. I then did the pwm mod on the adafruit hat, setup a raspbian stretch lite with the pixelpusher implementation of this matrix and ran the demo to check, only to find this problem. I suspect wiring, since it's unlikely all 4 panels fail in the same channel in the lower half, right? Where would I start investigating? What could be the problem?

Some stats:
pi 3
adafruit hat with pwm wiring
adafruit sourced 32x32 matrix panels
raspbian stretch lite
cloned from pixelpusher git
4 panel chain using U-mapper

Thanks!
Stephan

**Comment by hzeller** [comment]
Did the same set-up work without the pixelpusher and just running the examples-api-use/demo ?
It does look like some wiring problem.

**Comment by hzeller** [comment]
I suppose you fixed the wiring issue ?

**Comment by swalsch** [comment]
So after checking and replacing some wiring and the problem persisting (yes, also in demo mode for the examples) I ordered new panels, which took a while. Sadly they show the same behaviour, which has led me to believe the adafruit hat might be faulty. So next step I'll solder the signal cable straight to the pi to rule that out.

**Comment by swalsch** [comment]
I did the above mentioned step of soldering the signal cable directly to the pi, skipping the adafruit HAT and now it works!! So the R2 signal path on the HAT is somehow broken. I only use the HAT for power distribution now and everything works fine.
