### ISSUE TITLE
Color Mapping Error

### ISSUE THREAD

**Issue by loewek3628** [hzeller/rpi-rgb-led-matrix#654]
Hi,

We currently have a display with 3 parallel chains of 6 matrices each.

Here is what the display shows:
![truck-matrix-1](https://user-images.githubusercontent.com/20243865/42386772-1065f320-8106-11e8-97f4-bcf91aea5610.jpg)

Here is the original image: 
![9-14-2017 series](https://user-images.githubusercontent.com/20243865/42386880-5d324730-8106-11e8-89a5-e945e9542ea7.jpg)

We think our issue is with our second chain of wiring. There are clearly color issues and some sort of duplication of the image.

As of now we have tested and have found no issues:
- Continuity of the wires
- Power
- Different ribbon wires
- Different matrix panels
- Multiple different images and text strings

Any other ideas to troubleshoot our problem?

**Comment by hzeller** [comment]
It looks like that in your middle chain the green and blue of the first and second half-panel are swapped. G1 and B2 or something along those lines. Double check that you have all R1,G1,B1 and R2,G2,B2 at the correct places. Did you double-check that there are no solder-bridges on the adapter board you soldered ?

So if you have a test-image that shows just red, green and blue patterns it might be easy to spot.

**Comment by loewek3628** [comment]
We tried showing a RGB only test image and there was no visible error which seemed odd.

Switching the pins around was also unfruitful because even though we could see the change in colors, it didn't change the strange splitting or doubling effect. 

Currently, the wiring is done with male-to-female jumper wires so the only soldered connections are for the A, B, C, D, Strobe, etc. pins and everything there shows connectivity via the multimeter.

Here is what scrolling text that is supposed to be white (and not doubled) looks like:

![hello-hzeller](https://user-images.githubusercontent.com/20243865/42389016-ff84fd24-810c-11e8-86b4-03950c7879c7.jpg)

**Comment by loewek3628** [comment]
Whoops! You were right - Green 1 and Green 2 were switched....

**Comment by hzeller** [comment]
in the above image, is the color for the top-text white or is it magenta ?
It sounds like for the middle chain, the greens G1 and G2 are switched.
