### ISSUE TITLE
video-viewer couldnt open output stream permission denied

### ISSUE THREAD

**Issue by mbates14** [hzeller/rpi-rgb-led-matrix#658]
I am trying to convert a video into a stream file, but the video file, and where I want to put the stream file is on a USB drive. its formatted as FAT32. 

I tried to run the utility to put the stream but I keep getting permission denied. So I ran it as sudo, same problem. 

hmmm.. any ideas?

**Comment by hzeller** [comment]
If the user you are running this does have write permissions, but the `daemon` user not,
try not to drop privileges to `daemon:daemon` by setting the `--led-no-drop-privs` flag.

**Comment by mbates14** [comment]
I will give it a shot. thanks.
