### ISSUE TITLE
(Python binding) "Pause" matrix object

### ISSUE THREAD

**Issue by fedus** [hzeller/rpi-rgb-led-matrix#659]
Hello,

I observed that as soon as the matrix object has been created in Python, there is a constant CPU load of around 70% minimum on a Raspberry Pi 3. I suppose this happens because the library starts drawing immediately and constantly to the screen (even if black). 

Is there a way to add a "pause" and "resume" functionality to the library, so that drawing can be stopped in order to keep the CPU load small during downtimes? Ideally, without deleting the matrix object from memory and recreating it.

What are people's opinion on this?

In any case, thanks for the great library.

**Comment by hzeller** [comment]
The constant load is needed, as the displays require constant pushing of pixels as they don't have a frame-buffer. Special-casing the 'all black' case is not really worthwhile as you have to anyway deal with the load as soon as a pixel is set to non-black and it also would mess up timing.

Note that the CPU load is only on a single core; you have four cores on a Pi3, so there is plenty to do other things. So, don't worry about that.

In the C++ API, you can selectively start the thread that does the update after you have created the matrix, but there is no mechanism exposed to pause/resume it.
