### ISSUE TITLE
Static Text with 4 lines

### ISSUE THREAD

**Issue by ostium** [hzeller/rpi-rgb-led-matrix#663]
Hello,

I need to show 4 lines of text, something like this:
--------------------------
|  XX:YY                   |
|  AAA BBBBBB ZZ  |
|  AAA BBBBBB ZZ  |
|  AAA BBBBBB ZZ  |
--------------------------
I'm using five displays, like this #552 , and its working with the examples in library.
 
But now, I don know how to start :-(

Thanks for your help.

**Comment by hzeller** [comment]
Start out with the [text-example.cc](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/examples-api-use/text-example.cc)

The interesting function is [`rgb_matrix::DrawText()`](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/include/graphics.h#L83), which allows you to draw a text with a given font at a poarticular position. So in your case you'd want to write the four lines in different y-positions.
