### ISSUE TITLE
RGB 32x32 Indoor 1/16 Missing half the lines

### ISSUE THREAD

**Issue by dididave** [hzeller/rpi-rgb-led-matrix#665]
![20180719_164656](https://user-images.githubusercontent.com/41451945/42969486-52b24292-8b74-11e8-9f75-e2e22d538045.jpg)
I tried a few different flag for multiplexing but Cant figure out if its an hardware or software issue

**Comment by hzeller** [comment]
Double check your address lines (A, B, C, C). There might be a swap or short somewhere.

**Comment by dididave** [comment]
I think I figured it out, the pi is defective, maybe a parameter or hardware. I did succeed to get all lines by changing the adapter for the adafruit but now bottom half has different colors. Thank you for your great project and time. Where can I make a donation
