### ISSUE TITLE
Extra GPIO Pins with the Adapter Board

### ISSUE THREAD

**Issue by puffycholo** [hzeller/rpi-rgb-led-matrix#666]
Good day. A noob question. Will i be able to use other GPIO Pins if I use the adapter board provided?

My project needs to daisy chain 6 panels and at the same time a GSM module connected to the Raspberry pi.

**Comment by puffycholo** [comment]
im only using 2 chains. where will i connect the gpio ports unused? i will be using this drive board 


[https://www.electrodragon.com/product/rgb-matrix-panel-drive-board-raspberry-pi/](url)

**Comment by hzeller** [comment]
Yes, if you only use two chains, you can use the remaining GPIOs.

You find the available GPOSs by  checking out the p2_XX values in https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/hardware-mapping.c

**Comment by puffycholo** [comment]
I will be using 64x32 panels. Do i need to tweak the adapters just like the 64x64 board config?

**Comment by hzeller** [comment]
No, 64x32 is essentially just a long 32. So no tweaking needed.
