### ISSUE TITLE
Adafruit 16x32 RGB not working

### ISSUE THREAD

**Issue by ace16vitamine** [hzeller/rpi-rgb-led-matrix#667]
Hi,

I have a simple question...

I started to use the Adafruit 16x32 RGB matrix panel with rpi-rgb-led-matrix, but I can not find a how to that is working. I wired the cable from this URL: https://learn.adafruit.com/16x32-rgb-display-with-raspberry-pi-part-2/wiring-the-displays to my pi3. 

I know that this is working, I am able to show thinks from a simple python script to the panel.

But every time I try ./demo -t 10 -D 1 runtext.ppm --led-no-hardware-pulse

it shows my nothing, black screen.

Any Ideas what is to do?

Thanks
Stefan

**Comment by ace16vitamine** [comment]
But now I see that the LEDs on the upper side are also glowing (see picture). Is that normal?

![display_1](https://user-images.githubusercontent.com/22064392/43146494-9be85190-8f61-11e8-8911-3f605e47e7f8.jpg)

**Comment by hzeller** [comment]
Make sure to use short cables and level converters for clean digital signal transitions.
