### ISSUE TITLE
LED P10 green wiith weird HUB12 without OE pin

### ISSUE THREAD

**Issue by yoeckoe** [hzeller/rpi-rgb-led-matrix#692]
Hi Hzeller,
i have a problem to access my LED P10 green with different HUB12  pin map
like this
1.F -------- 2.F
3.N -------- 2.F
5.N -------- 2.F
7.N -------- 2.F
9.N -------- 2.F
11.N -------- 2.D1
13.N -------- 2.D2
15.N -------- 2.F

i've try with the old hub12 pin connector (with OE Pin available) but didn't work. Maybe you can help me, thanks before.

**Comment by davemaster** [comment]
HUB12 Pictures please.
