### ISSUE TITLE
Character Width 

### ISSUE THREAD

**Issue by sleewis** [hzeller/rpi-rgb-led-matrix#694]
Font::CharacterWidth returns: g->width
Font::DrawGlyph returns: g->device_width

Is this intended?
By returning g->device_width from Font::CharacterWidth I am able to predict the correct length before displaying the text.

**Comment by hzeller** [comment]
This is an oversight (partially because in an early version of this code, it was only looking at the width, not device-width).
Fixed in latest commit.
