### ISSUE TITLE
libxml2 error

### ISSUE THREAD

**Issue by mbates14** [hzeller/rpi-rgb-led-matrix#696]
Something new sprang up when trying to use led-image-viewer. 

I keep getting this now:

sudo ./led-image-viewer --led-rows=16 --led-cols=32 --led-chain=3 --led-multiplexing=3 --led-parallel=2 --led-gpio-mapping=regular --led-pwm-lsb-nanoseconds=600 --led-slowdown-gpio=4 --led-brightness=100 -l1 flag96x32.str
./led-image-viewer: error while loading shared libraries: /usr/lib/arm-linux-gnueabihf/libxml2.so.2: invalid ELF header

any ideas how to fix this?

**Comment by mbates14** [comment]
Had to uninstall and reinstall all the libraries and now it works again. 

Must be SD card corruption?

**Comment by hzeller** [comment]
Maybe. Or you copied the led-image-viewer binary a while ago and it doesn't link anymore for whatever reason.
Good that you found a solution.

**Comment by mbates14** [comment]
it worked one day, powered down, and not the next. Nothing happened in between except a power cycle and time.
