### ISSUE TITLE
64x32 with Rpi 3 : missing half the image

### ISSUE THREAD

**Issue by bcholet** [hzeller/rpi-rgb-led-matrix#697]
Hi there, 

I'm struggling to find an answer to that issue : 
I have a 64x32 panel, which seems to be 2 32x32 panels chained. 
I'm using the matrix.cfg file to configure the display, but whenever I write that the display is 64 width and 32 height, set the WxH of each panels to 32x32, chain_length = 2, and parallel_count=1, I get the following message : Expected 2 panels in configuration but found 4! 
I have a display when I reset the settings to 64x64, chain_length=4, parallel_count=1, but my display being 64x32, I only get half the image on the display :'(
The strange thing is that everything works perfectly fine with the rpi-rgb-led-matrix code...
I've been trying to put a lot of different WxH settings but nothing cuts it :/ Does anyone already had this issue ? I'm using a Rasp Pi 3 with the Adafruit RGB Matrix HAT on. 

Thanks a lot for your time and help :)

**Comment by hzeller** [comment]
This library doesn't have a matrix.cfg, so seem to use a derived project that provides such a config. You should ask there.
