### ISSUE TITLE
video viewer to stream file conversion on PC?

### ISSUE THREAD

**Issue by mbates14** [hzeller/rpi-rgb-led-matrix#699]
Is it possible to make and use the video-viewer script on a PC installation of linux to convert video files over to stream files? 

I would like to use my PC to just convert all my shorts over to str files for use with the Pi without using the pi itself. 

is this possible under the current configuration? Just curious.

**Comment by hzeller** [comment]
Yes.
Just make sure to provide the same parameters that describe the LED layout, such as `--led-parallel` or `--led-chain`. 
Also, the converting machine needs to be little endian, but Intel PCs are, so no problem there.

You don't have to run as root, as the conversion functionality does not need to access any GPIO hardware (which wouldn't be available anyway in your PC)

**Comment by mbates14** [comment]
Perfect, thats what I needed to know ;-)
