### ISSUE TITLE
Interfacing with 80*40 Panels

### ISSUE THREAD

**Issue by hemanthkd** [hzeller/rpi-rgb-led-matrix#701]
I got the new release of Qiangli P4 80*40 panels, when tried interfacing, I faced a problem that rows from 16 to 20 as well as 36 to 40 are not turning on. Hope  you would help us

**Comment by hemanthkd** [comment]
Image, which I have given as input is download.jpg
![download.jpg](https://user-images.githubusercontent.com/38958852/46688813-f61bcb00-cc1b-11e8-90df-b9ff56983504.jpg)
And the result I got is Result.jpeg
![result](https://user-images.githubusercontent.com/38958852/46689557-d08fc100-cc1d-11e8-8f6a-056c45ff3b82.jpeg)

**Comment by hzeller** [comment]
You are not providing enough info. How did you connect it and what are the commandline options you provide to the program?

**Comment by hemanthkd** [comment]
We took total of  8 panels in two chains and arranged in U mapper in two chains with the Active-3. So in one chain we place 4 panels in U-shape so that first two will be normal and other 2 will be upside down. And the commands we followed are:
pi@raspberrypi:~/rpi-matrix-pixelpusher/matrix/utils $  sudo ./led-image-viewer   --led-rows=40 --led-cols=80 --led-pixel-mapper="U-mapper"  --led-chain=4  --led-parallel=2  --led-no-hardware-pulse download.jpg

**Comment by hzeller** [comment]
with 40 height, you need the E address line configured on the active3 adapter. did you?

**Comment by hemanthkd** [comment]
The panels which we got from Qiangli have only four address lines (A,B,C,D) and let us know how can we configure things on active-3 adapter

**Comment by hemanthkd** [comment]
I am extremely sorry that just now I have found the E pin on the 8th pin and have configured accordingly by connecting E pin and 8th, 4rth pin and GND on the active adapter but the result is the exact inverse of the previous output and is as follows:
![epin_8th_result](https://user-images.githubusercontent.com/38958852/46717714-85f65f00-cc86-11e8-8375-19dfc9bc6a9b.jpeg)
as follows

**Comment by hemanthkd** [comment]
When I am not connecting the E pin, I am getting the inital output(Result.jpeg). 
![result](https://user-images.githubusercontent.com/38958852/46809836-01dacf00-cd8d-11e8-8cfc-0f5afe6d929a.jpeg)

And when I have connected the Epin to the 8th pin on the adapter I found this output(UpdatedResult.jp
![updated_result](https://user-images.githubusercontent.com/38958852/46811721-ebcf0d80-cd90-11e8-9977-12de66a42401.jpg)
g).
It is something like if we merge both the outputs then its a complete output. Please help me out in resolving this issue

**Comment by hzeller** [comment]
It looks wierd as if the `E` pin is permanently high.
Can you double-check that you have your UART disabled, as the E-line is sharing a pin with that, and maybe that interferes.
Also double-check the soldering on the relevant pins of the active3 board.

**Comment by hemanthkd** [comment]
I have tried disabling UART using "sudo systemctl disable hciuart" but still the same result is taking place, but when I tried E pin connecting to GND physically, then the other  part of the screen is turning on as mentioned in the above pictures

**Comment by hemanthkd** [comment]
And I also checked the solderings on the adapter board, those are clear and perfect. i hope the main issue is only due the permanent state of GPIO 15. Please help me out

**Comment by hzeller** [comment]
did you disable the uart by putting `enable_uart=0` in `/boot/config.txt` ? Otherwise the system might attempt to write console messages to it.

**Comment by hemanthkd** [comment]
Yes it is already present.

**Comment by hzeller** [comment]
so your gpio15 is stuck, you have to get it unstuck. There is something going on with your hardware, either the breakout board or the Pi. Can't help remotely here, you have to systematically figure out where the problem is: measure the output while toggling it, replace hardware...

**Comment by hemanthkd** [comment]
Should i use a new pi

**Comment by hzeller** [comment]
depending if you find that the GPIO pin has a hardware fault

**Comment by hemanthkd** [comment]
can I use some other pins  instead of GPIO 15 as I was not using the 3rd chain in the adapter

**Comment by hemanthkd** [comment]
As discussed I have changed the GPIO 15 to GPIO 21 and also manually routes the adapter board, but this time the default state of GPIO21 is not getting changed and I am sure that both 15 and 21 are working fine for a simple blinking led code

**Comment by davemaster** [comment]
Can You please provide a picture of your panels and your RPi connection (good quality pictures) so we can figure it the solution to help You?

**Comment by hemanthkd** [comment]
I hope there is an issue with the command to enable the E line, while all the rest of the things are working fine. Here are some pictures of my panels and RPI connection.Link:https://drive.google.com/drive/folders/1dqstTAMj7qeeqWiZ4l9rJiKoGUE81TAL?usp=sharing

**Comment by davemaster** [comment]
> 
> 
> I hope there is an issue with the command to enable the E line, while all the rest of the things are working fine. Here are some pictures of my panels and RPI connection.Link:https://drive.google.com/drive/folders/1dqstTAMj7qeeqWiZ4l9rJiKoGUE81TAL?usp=sharing

According Your pictures, You may have a connection problem. Try this, always, the simple first then the complex; so, try rpi-rgb-led-matrix with only ONE panel; also, use  those cables link these [https://www.sparkfun.com/products/11026](url); without the HAT. Try this, FIRST. Pictures or videos of this try please.

**Comment by hemanthkd** [comment]
The same issue has taken place even I have directly interfaced the single panel with pi directly
Link for the pictures:https://drive.google.com/drive/folders/1u0MlPX2Oi_dZstOJsroZ5XfqVWDu4K12?usp=sharing

**Comment by hemanthkd** [comment]
When I have connected the single panel and when given the following command

**Comment by hzeller** [comment]
Alright, can you try again with a fresh checkout ? Hopefully that should make the 40 row panel working with `--led-rows=40`.

**Comment by hemanthkd** [comment]
Thank you so much for your full support. Finally, I got the perfect output
![successful_output](https://user-images.githubusercontent.com/38958852/47832894-0f004200-ddbe-11e8-94e5-1a380c2049ac.jpeg)

**Comment by muharramapri** [comment]
> Thank you so much for your full support. Finally, I got the perfect output
> ![successful_output](https://user-images.githubusercontent.com/38958852/47832894-0f004200-ddbe-11e8-94e5-1a380c2049ac.jpeg)

now i have problem like you before, can you help me? please
![IMG_20201211_151745](https://user-images.githubusercontent.com/75059964/102052695-0ee62380-3e19-11eb-9920-34adc9e8d30a.jpg)
