### ISSUE TITLE
WS2812B Support

### ISSUE THREAD

**Issue by freumichCH** [hzeller/rpi-rgb-led-matrix#705]
Hello Henner

First of all. Thanks for your Work and effort. I realized a lot of cool projects with your library. One of my favorites was a little cloud showing the numbers of Online Users on our Cloud infrastructure. :)

![img_1390](https://user-images.githubusercontent.com/22443781/47241213-2d903180-d3eb-11e8-97a3-5bd143edbf26.jpg)

So now to my question.
Is it possible to get WS2812 Support into your library? 😊
I know that RBP is not a realtime System. But can't imagine that there is no way realize this.
A matrix can have as well hundrets of thausends of Pixels. 

Thanks in advance!
Greetings

**Comment by hzeller** [comment]
So WS2812 is very different from this particular LED matrix, so it is not really possible.

You might be interested in another project of mine http://spixels.org/ which does exactly that: control a bunch of LED strips with the Raspberry Pi. However, only the SPI kind of LED strips (WS2801, APA102, ...), not the WS2812, which have an insane timing that I wanted to avoid implementing (and it is not really worthwhile as the WS2812 is really low quality and these days APA102 is the much better choice even though still a little bit more expensive).
