### ISSUE TITLE
Running the c# bindings with .net core

### ISSUE THREAD

**Issue by tincann** [hzeller/rpi-rgb-led-matrix#709]
Hi @hzeller ,

I'm trying to get the c# bindings working with .net core code base. Unfortunately, this doesn't work out of the box.

To understand what the problem is, I've tried to get the [minimal example](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/bindings/c%23/examples/minimal-example.cs) working. The `minimal-example.exe` works fine with mono. However, it doesn't work as expected if I try to compile my program with dotnet core doing the following:

1. On my machine I compile the code with the `linux-arm` target:
> dotnet publish -r linux-arm
2. Then, I `rsync` the published files to my raspberry pi.
3. I copy the `librgbmatrix.so` file to the same directory (I use the so file from the `bindings/c#` directory, because this one definitely works with `minimal-example.exe`)

When running the `linux-arm` binary with sudo rights, the program immediately quits without errors (I also tried adding a `while(true)` and also a `try-catch`, but it seems to break out of it). I've verified that the cross-compilation works by trying out a my c# program while avoiding the `librgbmatrix.so` bindings. This program runs as expected and writes output to stdout. 

Do you have any pointers on to how to proceed with debugging this? Is there a verbose mode I can turn on, where I could see the error message?

Thank you in advance.

**Comment by hzeller** [comment]
I have never programmed in C# so can't be of any help here.

The last C# binding contributions have been from @digital-synapse and @Michael-Richardson so they might be much more qualified to help with this.

**Comment by tincann** [comment]
Alright, thank you. I'll wait for their responses then. 

In the meantime I wanted to ask you if there exists an environmental variable that turns on verbose logging. I saw this once in an error message, but I'm not sure if it was coming from your library.

**Comment by hzeller** [comment]
The LED matrix itself does not have much logging, but if there is something wrong it will typically complain on stderr. Not sure if there is additional logging provided by mono w.r.t. internals.

**Comment by digital-synapse** [comment]
no reason why this shouldn't work (native interop might need some changes? not sure how .net core handles dllimports)
note: .net core doesn't yet support armv6 (raspberry pi zero) https://github.com/dotnet/coreclr/issues/10605

**Comment by wolfi-by** [comment]
With the new dotnet core 3.1 everything is running fine on RPi4 using Raspbian Lite. 
Under C# images are manipulated using System.Image.Bitmap. So its possible to use any TTF-Font to write Text. Copy images one into another is quite fast by using Bitlock. If i use a Matrix with 3 parallel lines and each 10 64x64 pixel my Image is updated in about 3 milliseconds. But after that it is problematic to copy that bitmap to canvas using SetPixel function. Copying data to canvas takes about 150 milliseconds... That is quit long.
So i was searching for a way to copy RGB-Data directly into canvas. From my Bitmap i get a byte array   in 24bpp-format holding color data in BGR-format. 

I am not firm in writing a wrapper for the library. So what would be the best way to make a call directly to the pixels of the canvas.

Maybe someone can explain it or ad a call to the c# wrapper class.

Greetings from Germany

**Comment by digital-synapse** [comment]
It may be possible to recompile the c# bindings under .netcore with no
changes needed.

The test setup I had was on a pi zero which sadly doesn't support it yet so
I haven't had a chance to try this myself.

**Comment by tincann** [comment]
@digital-synapse This is exactly how I eventually made it work on .net core 2.2.
