### ISSUE TITLE
Width of 1 board is always 20?

### ISSUE THREAD

**Issue by friedcpu** [hzeller/rpi-rgb-led-matrix#71]
Hi,
I am finding that the width of 1 board is always assumed to be 20, I have 3 chained displays and it always returns 60, instead of 96 as I am using 3 x 16x32 displays 

This can be reproduced and verified by adding the following line to demo-main.cc

printf("Canvas Width: %x \n", canvas()->width());

In the VolumeBars example 
./led-matrix -b 30 -c 3 -r 16 -D 9
Press <RETURN> to exit and reset LEDs
Canvas Width: 60

./led-matrix -b 30 -c 1 -r 16 -D 9
Press <RETURN> to exit and reset LEDs
Canvas Width: 20

Curiously, if specifying 5 it returns 'a0' and more than 5 it just returns '100' 
I have tried to find where in the led-matrix library it is specified that the default width of a board is assumed to be 20 but havn't had any success. Could you please explain how the chain interface works and hopefully I can modify it for my needs.

Thank you

**Comment by hzeller** [comment]
You are giving a hex formatting in your printf() statement: 32 decimal = 20 hex; and 96 decimal is 60 hex.

Default width is always assumed to be 32 - this is the only kind of boards I have seen so far.

So if you have a chain of 3 boards with 32 width each (96 total), then it all works as it should.
