### ISSUE TITLE
How the data is transferring from Raspberry Pi 3 to RGB led display

### ISSUE THREAD

**Issue by Abhimanyuabhi** [hzeller/rpi-rgb-led-matrix#719]
Hi sir.......
Good evening ........
Hope you have a good day............
Sir, We need the explanation how the data is transferring from raspberry pi to RGB-LED display.
We are using HUB-75 Interfacing so in that there are 16-pins.  Out of 16-pins there are 3 Ground-pins and the reaming pins are 13-pins . From  the 13-pins there are 6-pins for color(R1,G1,B1,R2,G2 and B2) and the reaming pins are 13-pins .We are requesting to you we need the reaming pin description and full explanation.We executed some demos on 32x16 RGB-LED matrix display with raspberry pi 3 model b+ but we don't know how the data was transferred from raspberry pi to display......

Thank you so much........

**Comment by hzeller** [comment]
The relevant part is in the [`DumpToMatrix()`](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/framebuffer.cc#L562) function, reading the code from there will tell you.

The Matrix essentially is a shift register that can show two lines at a time in the top and bottom half to which the two RGB sets are clocked into. Whenever a line is full, the strobe signal makes it visible at the given address and the output enable determines for how long. That is done rapidly to generate the Binary Code Modulation to get the grayscale.
