### ISSUE TITLE
10K pullup

### ISSUE THREAD

**Issue by ts4pi** [hzeller/rpi-rgb-led-matrix#72]
Hi,

a few days ago my boards from OSH Park. I think the sent me the older version without the 10k Pullup.
Do You have the actual schematic as PDF so I could change the boards ?

thanks in advance 
Thomas
thomas@schierz.de

**Comment by hzeller** [comment]
Uh, how did you get an older version ? I just checked the link on the active-3 readme and it points to https://oshpark.com/shared_projects/vIwlNEFd which does like the right version.

I don't have a PDF at hand, but the pull-up is between ~OE (output enable) and 3.3V. So Pin 12 on the GPIO header and Pin 1.

It is not super needed, but it helps in cases in which you see random bright LED lines light up when the program is not active.
