### ISSUE TITLE
Support for OTF or TTF font

### ISSUE THREAD

**Issue by ms-driveai** [hzeller/rpi-rgb-led-matrix#735]
Is there support for a font like OTF or TTF? 

Currently, the list of fonts are all BDF (https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/fonts).
BDF is outdated and hard to use. Ideally, we'd like to able to render text in a modern font that more easily supports design iterations. Thanks!

**Comment by hzeller** [comment]
The advantage of BDF is that it is easy to parse with a few lines of code without additional dependencies and that it is a bitmap format which is what you want for this low resolution screens.

You can of course link any library that reads other font formats and use that to render to the canvas.

The simple way: I suggest to use otf2bdf tool to convert any font to BDF as described in the readme.
