### ISSUE TITLE
RPi + LED Matrix + ImageScroller

### ISSUE THREAD

**Issue by fusionfoto** [hzeller/rpi-rgb-led-matrix#736]
First of all, thanks again for such an awesome project and the continuous support you provide. 

I'm trying to hybridize the RunText scroller and the ImageScroller. Where we can run text, run an image, run text, and so forth.

Runtext is doing fine.

When I run the demo Imagescroller,  with a command like: image:

sudo ./image-scroller.py -c 3 -i (my image)

I get a situation where the graphic appears in the middle of the three panels and scrolls to the left... and repeats. My image is about the size of the raspberry pi icon in the larger demo file.  I've tried monkeying with the xpos settings, but they all seem to start looping at weird places, even if they start at the correct place.

Is there a simple adjustment/fix I need to make to use a less wide image than the sample?

thanks in advance!

**Comment by hzeller** [comment]
you probably have set your offsets weirdly or don't take the width of the display into account. Sounds like a simple coding issue that you can solve by staring at the code for a while :)
