### ISSUE TITLE
rgbmatrix conflict with raspicam initialization

### ISSUE THREAD

**Issue by visansi** [hzeller/rpi-rgb-led-matrix#741]
@hzeller thanks for the coolest rgbmatrix codebase.

I got it working with the following 32X32 matrices 
    WH-K4016-V3.1 from adafruit (JXI5020GP chip?? ) with --led-multiplexing=0
and also 
    P6-8S-3535-3232A1 from china with [MBI5124 controller](http://belchip.by/sitedocs/00006155.pdf) with --led-multiplexing=1

But when I integrate this with an application that uses [raspicam ](https://github.com/cedricve/raspicam ) driver for a PI Camera it seems to conflict on mman resources.

Here is a minimal code that fails to open camera when RGBMatrix is initialized before the Camera::Open is called.

    #include "led-matrix.h"
    #include <unistd.h>
    #include <math.h>
    #include <stdio.h>
    #include <fstream>
    #include <iostream>
    #include <raspicam/raspicam.h>

    using namespace std;
    using namespace rgb_matrix;

    int main(int argc, char *argv[]) {
      RuntimeOptions runOpt;
      RGBMatrix::Options matOpt;
      matOpt.rows = 32;
      matOpt.chain_length = 1;
      matOpt.parallel = 1;

     //if(1) {       // test LED and PI CAMERA
     if(0) {       // skip LED test PI CAMERA
        RGBMatrix *matrix = CreateMatrixFromOptions(matOpt, runOpt);
        matrix->SetPixel(10, 10, 127, 127,  127);
        usleep(20 * 100 * 1000);
        matrix->Clear();
        delete matrix;
      }
    //------------------------------------------------------------------------
        raspicam::RaspiCam Camera; //Cmaera object
        if ( !Camera.open()) {cerr<<"Error opening camera"<<endl;return -1;}
        sleep(3);
        Camera.grab();
    //------------------------------------------------------------------------
      return 0;
    }

Opening the Camera::Open succeeds if done before RGBMatrix instantiation and does not impact LEDs operation. They also seem to work fine if run from different processes.

I can see both code bases using "sys/mman.h" and calling mman allocations but apparently on different resources.

Can anyone provide more insight and help me resolve this conflict ?

thanks

**Comment by hzeller** [comment]
make sure to set the runtime option to not drop privileges when initializing the rgb matrix (see header file). Otherwise, the process does not have root privileges anymore after the initialization, and the camera init fails.

**Comment by hzeller** [comment]
You have to parse the command line flags for `--led-no-drop-privs` to work using the parsing function.

Right now in your example you just call `CreateMatrixFromOptions()` and pass the option-structs you have set programmatically. So if you don't read the flags, you have to set the value `runOpt.drop_privileges` manually. This is probably the best if you want to have a fixed set-up and don't want the user to mess with any of the options via command-line flags.

If you want to be able to set command line flags, there is either `rgb_matrix::ParseOptionsFromFlags()` that fills in the options, or you can use the convenience wrapper function `rgb_marix::CreateMatrixFromFlags()`.

See documentation in the [header file](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/include/led-matrix.h#L428).

**Comment by visansi** [comment]
thanks @hzeller . I understand the flow better now and you also guessed right - I dont want the user to have any controls at startup.
