### ISSUE TITLE
Memory Problem 

### ISSUE THREAD

**Issue by tuan91** [hzeller/rpi-rgb-led-matrix#750]
Hi, first off all, i want to thank you for the library. I have a Memory Problem. After 2 days my program is killed. My panel gets weather data from a REST API.  This should be done continuously.  Every 40 minutes, the RAM memory increases by 1%. I'll leave you an example code in this mail.. I hope you can help me, thank you! 
![example code python](https://user-images.githubusercontent.com/46566423/50986364-f2436180-1506-11e9-952e-4a1136e9d56d.JPG)

**Comment by hzeller** [comment]
why are you creating a new frame canvas with every run_led_panel? you only need this once when creating the matrix. Otherwise you collect framecanvases in memory that you only use once.

**Comment by tuan91** [comment]
Thanks for the quick feedback!
I thought I had to do it that way. I once tried to write "createframecanvas" outside the run_LED-panel, but it didnt work. Can you give me an example of what you mean, many thanks!

**Comment by angelogoncalve** [comment]
Can you share the code how you fixed about the frame canvas?

Thank you for your help.

**Comment by tuan91** [comment]
![sample solution](https://user-images.githubusercontent.com/46566423/51470911-81f1d700-1d75-11e9-9696-98ea9ec8171d.JPG)

**Comment by hzeller** [comment]
how can you call `matrix.CreateFrameCanvas()` when only in the next line you define `matrix = RGBMatrix(options = options)` ? Shouldn't these lines be swapped ?

**Comment by tuan91** [comment]
Oh sorry, the two lines must be swapped.
Thank you for the Feedback!

**Comment by angelogoncalve** [comment]
Dea Sir. Thank you for sharing the code and I will change in the code the two lines swapping them creating the matrix first and the canvas after.
