### ISSUE TITLE
led-image-viewer

### ISSUE THREAD

**Issue by whatismyname185** [hzeller/rpi-rgb-led-matrix#751]
So, I did the sudo apt-get update
then I did sudo apt-get install libgraphicsmagick++-dev libwebp-dev -y
but when I do the make led-image-viewer, i'm getting make: *** No rule to make target 'led-image-viewer'.  Stop.

I'm using a raspian stretch fresh nothing installed in it.

Can you please help me..
![make](https://user-images.githubusercontent.com/28812414/51092384-9249f680-1764-11e9-9d25-f3b79c9bfc62.jpg)

**Comment by d3d9** [comment]
It seems like you didn't clone the repository (at least it isn't in your /home/pi directory), you need to ```git clone https://github.com/hzeller/rpi-rgb-led-matrix.git``` if you haven't already, then enter the rpi-rgb-led-matrix directory and run ```make all```.

**Comment by whatismyname185** [comment]
OMG!!!...I got it to work...Thanks so much!!!, God Bless
