### ISSUE TITLE
Active-3 adapter, i can sell it.

### ISSUE THREAD

**Issue by gioreva** [hzeller/rpi-rgb-led-matrix#763]
I could sell adapter active-3 to €30 + shipping.
Is there interest ?

**Comment by marcmerlin** [comment]
Yes, please.

**Comment by gioreva** [comment]
How Many ? Where ship ?

**Comment by marcmerlin** [comment]
sorry for the slow reply. I ended up finding some $3 one from HKG. can't believe they are so cheap, but they worked fine
If you'd like to add yourself for Europe, you can add yourself to a followup CL: https://github.com/hzeller/rpi-rgb-led-matrix/pull/799/files

**Comment by gioreva** [comment]
Tanks.
No, no, I give up
