### ISSUE TITLE
Problem with Chinese P5 192x64 (64x32, 3 cols, 2 rows)

### ISSUE THREAD

**Issue by uros-skopus** [hzeller/rpi-rgb-led-matrix#765]
Hi,

Thanks for both great project and community established!
I have the problem with Chinese P5 outdoor module 192x64 (64x32, 3 cols, 2 rows), 1:16, SM16207 LED, specification and image are attached.

![p5outdoor](https://user-images.githubusercontent.com/46559152/53378716-f9afb480-3966-11e9-947a-ec14ab481f89.jpg)

[16207s-badLED-chipset.pdf](https://github.com/hzeller/rpi-rgb-led-matrix/files/2903219/16207s-badLED-chipset.pdf)

It was connected with Raspberry Pi 3 B+ using GPIO pins and active hub. I have tested with both official:
https://www.electrodragon.com/product/rgb-matrix-panel-drive-board-raspberry-pi/
, and Chinese hub, but without success:

![hub75-6-v1 2-uros](https://user-images.githubusercontent.com/46559152/53378894-8b1f2680-3967-11e9-89eb-ffd01cc8c774.jpg)

Command I am running is:
**sudo ./led-image-viewer --led-rows=32 --led-cols=64 --led-chain=3 --led-parallel=2 {image_name}**

I have also tried all multiplexing options but without success (--led-multiplexing=3 is something closest to what should be expected). It's not the problem of correct puzzling of IDC inputs (bottom-middle-top), but the image doesn't even have proper parts scattered, more like it is blurred. Just to mention 3:1 images are used for testing.

My first question is whether this lib is compatible with these Chinese SM16207 LED modules over HUBs?
Also, is it a problem to use these 3-channel HUBS (bottom-middle-top) to display just 2 chains?
Or is it something else?

Thanks in advance!

**Comment by uros-skopus** [comment]
Adding some test images:
1) **sudo ./rotating-block-generator.py --led-rows=32 --led-cols=64 --led-chain=3 --led-parallel=2**

![cube-test-normal-64-32](https://user-images.githubusercontent.com/46559152/53404644-5f775d00-39b6-11e9-9342-74606f2bccb8.jpg)

2) **sudo ./rotating-block-generator.py --led-rows=64 --led-cols=128 --led-chain=3 --led-parallel=2**

![cube-test-128-64](https://user-images.githubusercontent.com/46559152/53404692-7c139500-39b6-11e9-8e6d-128aaedd6417.jpg)

3) **sudo ./rotating-block-generator.py --led-rows=32 --led-cols=64 --led-chain=3 --led-parallel=2 --led-multiplexing=4 --led-slowdown-gpio=2**

![cube-test-mux-4-slowdown-2](https://user-images.githubusercontent.com/46559152/53404760-9e0d1780-39b6-11e9-8ed0-4877b3e97e7b.jpg)

**Comment by uros-skopus** [comment]
Those were 32x32 modules, that was the problem.

**Comment by SanddrP** [comment]
Hi.
I have a matrix 64*32 SM16207 LED, 
Please tell me the parameters of the meters you chose for the matrix, thank you
