### ISSUE TITLE
Compile led-image-viewer

### ISSUE THREAD

**Issue by keredwink** [hzeller/rpi-rgb-led-matrix#784]
Came across this through adafruit.

Works great but led-image-viewer is not compiled by default.

When I do compile it it forces led-cpio-mapping to regular instead of adafruit-hat and requires the --led-no-hardware-pulse option to work properly.

Is there a way to compile so that it defaults to adafruit-hat and doesn't need --led-no-hardware-pulse?

**Comment by hzeller** [comment]
If you want to compile default options into the binary, see the Makefile in lib.

If you have an Adafruit hat, you also really should do the little hardware mod to make things run with pwm as described in the Readme.

**Comment by keredwink** [comment]
Thanks
