### ISSUE TITLE
issues with make and compile

### ISSUE THREAD

**Issue by Toootless** [hzeller/rpi-rgb-led-matrix#800]
I am using your libraries for to drive an RGB-LED 32x 16. I am also using some code from WiringPi to import data from an Arduino to the Raspberry Pi. I tried to use Greany to compile and build the file, but geany has an issue find the LED_matrix library. 

gcc -Wall -o "display3" "display3.c" -lwiringPi -lwiringPiDev -lrt -lm -lpthread (in directory: /home/pi/rpi-rgb-led-matrix-master/examples-api-use)
/tmp/ccmhKKhh.o: In function `main':
display3.c:(.text+0x708): undefined reference to `led_matrix_create_from_options'
display3.c:(.text+0x728): undefined reference to `led_matrix_create_offscreen_canvas'
display3.c:(.text+0x740): undefined reference to `led_canvas_get_size'
display3.c:(.text+0x950): undefined reference to `led_canvas_clear'
display3.c:(.text+0xab0): undefined reference to `led_canvas_set_pixel'
display3.c:(.text+0xc4c): undefined reference to `led_canvas_set_pixel'
display3.c:(.text+0xde8): undefined reference to `led_canvas_set_pixel'
display3.c:(.text+0xf84): undefined reference to `led_canvas_set_pixel'
display3.c:(.text+0xfcc): undefined reference to `led_matrix_swap_on_vsync'
display3.c:(.text+0xfd8): undefined reference to `led_matrix_delete'
collect2: error: ld returned 1 exit status
Compilation failed.

I then tried to use the make file to compile and build the file, but cannot find the correct part to add to the make file to find the library for the WiringPi.

pi@raspberrypi:~/rpi-rgb-led-matrix-master $ sudo make
make -C /home/pi/rpi-rgb-led-matrix-master/lib
make[1]: Entering directory '/home/pi/rpi-rgb-led-matrix-master/lib'
make[1]: Leaving directory '/home/pi/rpi-rgb-led-matrix-master/lib'
make -C examples-api-use
make[1]: Entering directory '/home/pi/rpi-rgb-led-matrix-master/examples-api-use'
make -C ../lib
make[2]: Entering directory '/home/pi/rpi-rgb-led-matrix-master/lib'
make[2]: Leaving directory '/home/pi/rpi-rgb-led-matrix-master/lib'
g++ display3.o -o display3 -L../lib -lrgbmatrix -lrt -lm -lpthread  -lstdc++ 
display3.o: In function `getData_convertData':
display3.c:(.text+0x2e4): undefined reference to `serialOpen'
display3.c:(.text+0x330): undefined reference to `wiringPiSetup'
display3.c:(.text+0x378): undefined reference to `millis'
display3.c:(.text+0x394): undefined reference to `millis'
display3.c:(.text+0x3d4): undefined reference to `serialPutchar'
display3.c:(.text+0x3f4): undefined reference to `delay'
display3.c:(.text+0x400): undefined reference to `serialGetchar'
display3.c:(.text+0x428): undefined reference to `serialDataAvail'
display3.c:(.text+0x454): undefined reference to `serialGetchar'
collect2: error: ld returned 1 exit status
Makefile:29: recipe for target 'display3' failed
make[1]: *** [display3] Error 1
make[1]: Leaving directory '/home/pi/rpi-rgb-led-matrix-master/examples-api-use'
Makefile:25: recipe for target '/home/pi/rpi-rgb-led-matrix-master/lib/librgbmatrix.a' failed
make: *** [/home/pi/rpi-rgb-led-matrix-master/lib/librgbmatrix.a] Error 2

Would you know what to add to the make file to add the WiringPi ?

Here is the code.

`/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 *
 * Using the C-API of this library.
 *
 */
// TCP Server
#include "led-matrix-c.h"

#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h> 
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <wiringPi.h>
#include <wiringSerial.h>
#include <termios.h>

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
struct BAR_TYPE {
	int mn_col;
	int mn_row;
};

struct CLR_TYPE {
	int mn_r;
	int mn_g;
	int mn_b;
};

int gan_data[3];

  struct termios options ;

#define gb_dbg 0
#define gb_data 0
const int baud = 112500;

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
int a2h(char lPc_MS, char lPc_LS) {
  
  int ln_MS = 0x00;
  int ln_LS = 0x00;

  switch (lPc_MS)
  {
    case 0x30 : {ln_MS = 0; break;}
    case 0x31 : {ln_MS = 1; break;}
    case 0x32 : {ln_MS = 2; break;}
    case 0x33 : {ln_MS = 3; break;}
    case 0x34 : {ln_MS = 4; break;}
    case 0x35 : {ln_MS = 5; break;}
    case 0x36 : {ln_MS = 6; break;}
    case 0x37 : {ln_MS = 7; break;}
    case 0x38 : {ln_MS = 8; break;}
    case 0x39 : {ln_MS = 9; break;}
    case 0x41 : {ln_MS = 10; break;}
    case 0x42 : {ln_MS = 11; break;}
    case 0x43 : {ln_MS = 12; break;}
    case 0x44 : {ln_MS = 13; break;}
    case 0x45 : {ln_MS = 14; break;}
    case 0x46 : {ln_MS = 15; break;}
  }

  switch (lPc_LS)
  {
    case 0x30 : {ln_LS = 0; break;}
    case 0x31 : {ln_LS = 1; break;}
    case 0x32 : {ln_LS = 2; break;}
    case 0x33 : {ln_LS = 3; break;}
    case 0x34 : {ln_LS = 4; break;}
    case 0x35 : {ln_LS = 5; break;}
    case 0x36 : {ln_LS = 6; break;}
    case 0x37 : {ln_LS = 7; break;}
    case 0x38 : {ln_LS = 8; break;}
    case 0x39 : {ln_LS = 9; break;}
    case 0x41 : {ln_LS = 10; break;}
    case 0x42 : {ln_LS = 11; break;}
    case 0x43 : {ln_LS = 12; break;}
    case 0x44 : {ln_LS = 13; break;}
    case 0x45 : {ln_LS = 14; break;}
    case 0x46 : {ln_LS = 15; break;}
  }

  return ((ln_MS << 4) + ln_LS);
}
 
	

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
int getData_convertData() {
  int fd;
  int ln_rc = -1;
  int ln_ctr = 0;
  char lac_buffer[32];
  int ln_bytesread = 0;
  int ln_ndx = 0;
  unsigned int nextTime;
  int count;

 if ((fd = serialOpen ("/dev/ttyACM0", 115200)) < 0)
  {
    fprintf (stderr, "Unable to open serial device: %s\n", strerror (errno)) ;
    return 1 ;
  }

  if (wiringPiSetup () == -1)
  {
    fprintf (stdout, "Unable to start wiringPi: %s\n", strerror (errno)) ;
    return 1 ;
  }

  nextTime = millis () + 300 ;

  for (count = 0 ; count < 256 ; )
  {
    if (millis () > nextTime)
    {
      printf ("\nOut: %3d: ", count) ;
      fflush (stdout) ;
      serialPutchar (fd, count) ;
      nextTime += 300 ;
      ++count ;
    }

    delay (3) ;

    while (serialDataAvail (fd))
    {
      printf (" -> %3d", serialGetchar (fd)) ;
      fflush (stdout) ;
    }
  }

/*
  while(1) {
	printf("Waiting for flag 'X' from Arduino");
	ln_char = serialGetchar(fd);
	if (88 == ln_char) {
		break; }
	if (1000 <= ln_ctr++) { // safety to exit if no "X" received
		printf(">> Flag not received, exiting");
		return (ln_rc);}
	}
*/
	// Example string received from Arduino = 1F2F4F8F

  for (ln_ctr = 0; ln_ctr < 8; ln_ctr++) {
	  lac_buffer[ln_ctr] = serialGetchar(fd);
	  ln_bytesread++;}

   if (8 > ln_bytesread) {
       ln_bytesread = 8;}

    ln_ndx = gan_data[0] = gan_data[1] = gan_data[2] = gan_data[3] = 0;
    while (ln_ndx < ln_bytesread) {
      switch(ln_ndx) {
        case 0 : {gan_data[0] = a2h(lac_buffer[0],lac_buffer[1]); break;}
        case 2 : {gan_data[1] = a2h(lac_buffer[2],lac_buffer[3]); break;}
        case 4 : {gan_data[2] = a2h(lac_buffer[4],lac_buffer[5]); break;}
        case 6 : {gan_data[3] = a2h(lac_buffer[6],lac_buffer[7]); break;}
      }
      ln_ndx += 2;
    }
    
    printf("Data = %d%d%d%d",gan_data[0],gan_data[1],gan_data[2],gan_data[3]);

  return (ln_rc = 0);

}

  
/*
//  if (lac_buffer[ln_bytesread] == "\0") {
//    printf("Bytes received = %s\n",lac_buffer); }
*/  

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/*
void sendData( int sockfd, int x ) {
  int n;

  char buffer[32];
  sprintf( buffer, "%d\n", x );
  if ( (n = write( sockfd, buffer, strlen(buffer) ) ) < 0 ) {
    printf("ERROR writing to socket");
  }
  buffer[n] = '\0';
}
*/

int main(int argc, char **argv) {
	
  struct RGBLedMatrixOptions options;
  struct RGBLedMatrix *matrix;
  struct LedCanvas *offscreen_canvas;
  int width, height;
  int i, j;
 // int sockfd, newsockfd, portno = 51717, clilen;
 //struct sockaddr_in serv_addr, cli_addr;
  struct BAR_TYPE lj_LL;
  struct BAR_TYPE lj_LM;
  struct BAR_TYPE lj_RM;
  struct BAR_TYPE lj_RR;
  struct CLR_TYPE lj_blu = {65,102,11};
  struct CLR_TYPE lj_grn = {0,255,0};
  struct CLR_TYPE lj_gyw = {211,247,54};
  struct CLR_TYPE lj_yel = {255,255,0};
  struct CLR_TYPE lj_org = {255,153,0};
  struct CLR_TYPE lj_lrd = {242,23,12};
  struct CLR_TYPE lj_red = {255,0,0};
  //struct CLR_TYPE lj_blk = {255,255,255};

  memset(&options, 0, sizeof(options));
  options.rows = 16;
  options.chain_length = 1;
	
  /* This supports all the led commandline options. Try --led-help */
  matrix = led_matrix_create_from_options(&options, &argc, &argv);
  if (matrix == NULL)
    return 1;

  /* Let's do an example with double-buffering. We create one extra
   * buffer onto which we draw, which is then swapped on each refresh.
   * This is typically a good aproach for animations and such.
   */
  offscreen_canvas = led_matrix_create_offscreen_canvas(matrix);
  
  led_canvas_get_size(offscreen_canvas, &width, &height);
  
  fprintf(stderr, "Size: %dx%d. Hardware gpio mapping: %s\n",
          width, height, options.hardware_mapping);
          
          // Code
  int ln_update = 0;
  int ln_r, ln_g, ln_b;
  
  ln_r = ln_g = ln_b =
  lj_LL.mn_col = lj_LL.mn_row =
  lj_LM.mn_col = lj_LM.mn_row =
  lj_RM.mn_col = lj_RM.mn_row =
  lj_RR.mn_col = lj_RR.mn_row = 0;
  
 /* 
  if ((fd = serialOpen ("/dev/ttyACM1", 115200)) < 0)
  {
    fprintf (stderr, "Unable to open serial device: %s\n", strerror (errno)) ;
    return 1 ;
  }

*/
/*  
	printf( "using port #%d\n", portno );
    
     sockfd = socket(AF_INET, SOCK_STREAM, 0);
     if (sockfd < 0) {
			printf( "ERROR opening socket");
		}

	bzero((char *) &serv_addr, sizeof(serv_addr));

     serv_addr.sin_family = AF_INET;
     serv_addr.sin_addr.s_addr = INADDR_ANY;
     serv_addr.sin_port = htons( portno );
     if (bind(sockfd, (struct sockaddr *) &serv_addr,
              sizeof(serv_addr)) < 0) {
				  printf("ERROR on binding" );
			  }
     listen(sockfd,5);
     clilen = sizeof(cli_addr);
     printf( "waiting for new client...\n" );
    if ( ( newsockfd = accept( sockfd, (struct sockaddr *) &cli_addr, (socklen_t*) &clilen) ) < 0 ){
			printf("ERROR on accept");
			}
        printf( "opened new communication with client\n" );
*/

while (1) {
	  
		  {
	
/*start of get data
 * infinite wait on a connection ---
 */   

    //---- wait for data from client ---
	if (0 == getData_convertData()) { 
	printf("Received : %d %d %d %d\n",
		   gan_data[0],gan_data[1],gan_data[2],gan_data[3]);
	}

	if (0x10 == (gan_data[0] & 0x10)) {
		if (lj_LL.mn_row != (0x0F & gan_data[0])) {
			ln_update = 1;
			lj_LL.mn_col = 31;
			lj_LL.mn_row = (0x0F & gan_data[0]);
			if (gb_dbg) {printf(">> LL.row=%d, LL.col=%d\n",lj_LL.mn_row,lj_LL.mn_col);}
		}
		else if (gb_dbg) {printf(">> LL received new data but no update required\n");}
	}

	if (0x20 == (gan_data[1] & 0x20)) {
		if (lj_LM.mn_row != (0x0F & gan_data[1])) {
			ln_update = 1;
			lj_LM.mn_col = 23;
			lj_LM.mn_row = (0x0F & gan_data[1]);
			if (gb_dbg) {printf(">> LM.row=%d, LM.col=%d\n",lj_LM.mn_row,lj_LM.mn_col);}
		}
		else if (gb_dbg) {printf(">> LM received new data but no update required\n");}
	}

	if (0x40 == (gan_data[2] & 0x40)) {
		if (lj_RM.mn_row != (0x0F & gan_data[2])) {
			ln_update = 1;
			lj_RM.mn_col = 15;
			lj_RM.mn_row = (0x0F & gan_data[2]);
			if (gb_dbg) {printf(">> RM.row=%d, RM.col=%d\n",lj_RM.mn_row,lj_RM.mn_col);}
		}
		else if (gb_dbg) {printf(">> RM received new data but no update required\n");}
	}

	if (0x80 == (gan_data[3] & 0x80)) {
		if (lj_RR.mn_row != (0x0F & gan_data[3])) {
			ln_update = 1;
			lj_RR.mn_col = 7;
			lj_RR.mn_row = (0x0F & gan_data[3]);
			if (gb_dbg) {printf(">> RR.row=%d, RR.col=%d\n",lj_RR.mn_row,lj_RR.mn_col);}
		}
		else if (gb_dbg) {printf(">> RR received new data but no update required\n");}
	}

	if (0 < ln_update) {

		ln_update = 0;

		led_canvas_clear(offscreen_canvas);

		for (i = lj_LL.mn_col; i > lj_LL.mn_col - 8; i--) {
			for (j = 0; j < lj_LL.mn_row; j++) {
				if (gb_dbg) {printf("LL.row=%d, LL.col=%d\n",j,i);}
				switch(j) {
					case 0 : // Blue
					ln_r = lj_blu.mn_r;
					ln_g = lj_blu.mn_g;
					ln_b = lj_blu.mn_b;
					break;

					case 1 :
					case 2 :
					case 3 : // Green 
					ln_r = lj_grn.mn_r;
					ln_g = lj_grn.mn_g;
					ln_b = lj_grn.mn_b;
					break;

					case 4 :
					case 5 : // Yellow Green
					ln_r = lj_gyw.mn_r;
					ln_g = lj_gyw.mn_g;
					ln_b = lj_gyw.mn_b;
					break;

					case 6 :
					case 7 :
					case 8 : // Yellow
					ln_r = lj_yel.mn_r;
					ln_g = lj_yel.mn_g;
					ln_b = lj_yel.mn_b;
					break;

					case 9 :
					case 10 :
					case 11 : // Orange
					ln_r = lj_org.mn_r;
					ln_g = lj_org.mn_g;
					ln_b = lj_org.mn_b;
					break;

					case 12 :
					case 13 : // Lt Red
					ln_r = lj_lrd.mn_r;
					ln_g = lj_lrd.mn_g;
					ln_b = lj_lrd.mn_b;
					break;

					case 14 :
					case 15 : // Red
					ln_r = lj_red.mn_r;
					ln_g = lj_red.mn_g;
					ln_b = lj_red.mn_b;
					break;
				}

				led_canvas_set_pixel(offscreen_canvas, i, j, ln_r, ln_g, ln_b);
			}
		}

		for (i = lj_LM.mn_col; i > lj_LM.mn_col - 8; i--) {
			for (j = 0; j < lj_LM.mn_row; j++) {
				if (gb_dbg) {printf("LM.row=%d, LM.col=%d\n",j,i);}
				switch(j) {
					case 0 : // Blue
					ln_r = lj_blu.mn_r;
					ln_g = lj_blu.mn_g;
					ln_b = lj_blu.mn_b;
					break;

					case 1 :
					case 2 :
					case 3 : // Green 
					ln_r = lj_grn.mn_r;
					ln_g = lj_grn.mn_g;
					ln_b = lj_grn.mn_b;
					break;

					case 4 :
					case 5 : // Yellow Green
					ln_r = lj_gyw.mn_r;
					ln_g = lj_gyw.mn_g;
					ln_b = lj_gyw.mn_b;
					break;

					case 6 :
					case 7 :
					case 8 : // Yellow
					ln_r = lj_yel.mn_r;
					ln_g = lj_yel.mn_g;
					ln_b = lj_yel.mn_b;
					break;

					case 9 :
					case 10 :
					case 11 : // Orange
					ln_r = lj_org.mn_r;
					ln_g = lj_org.mn_g;
					ln_b = lj_org.mn_b;
					break;

					case 12 :
					case 13 : // Lt Red
					ln_r = lj_lrd.mn_r;
					ln_g = lj_lrd.mn_g;
					ln_b = lj_lrd.mn_b;
					break;

					case 14 :
					case 15 : // Red
					ln_r = lj_red.mn_r;
					ln_g = lj_red.mn_g;
					ln_b = lj_red.mn_b;
					break;
				}

				led_canvas_set_pixel(offscreen_canvas, i, j, ln_r, ln_g, ln_b);
			}
		}

		for (i = lj_RM.mn_col; i > lj_RM.mn_col - 8; i--) {
			for (j = 0; j < lj_RM.mn_row; j++) {
				if (gb_dbg) {printf("RM.row=%d, RM.col=%d\n",j,i);}
				switch(j) {
					case 0 : // Blue
					ln_r = lj_blu.mn_r;
					ln_g = lj_blu.mn_g;
					ln_b = lj_blu.mn_b;
					break;

					case 1 :
					case 2 :
					case 3 : // Green 
					ln_r = lj_grn.mn_r;
					ln_g = lj_grn.mn_g;
					ln_b = lj_grn.mn_b;
					break;

					case 4 :
					case 5 : // Yellow Green
					ln_r = lj_gyw.mn_r;
					ln_g = lj_gyw.mn_g;
					ln_b = lj_gyw.mn_b;
					break;

					case 6 :
					case 7 :
					case 8 : // Yellow
					ln_r = lj_yel.mn_r;
					ln_g = lj_yel.mn_g;
					ln_b = lj_yel.mn_b;
					break;

					case 9 :
					case 10 :
					case 11 : // Orange
					ln_r = lj_org.mn_r;
					ln_g = lj_org.mn_g;
					ln_b = lj_org.mn_b;
					break;

					case 12 :
					case 13 : // Lt Red
					ln_r = lj_lrd.mn_r;
					ln_g = lj_lrd.mn_g;
					ln_b = lj_lrd.mn_b;
					break;

					case 14 :
					case 15 : // Red
					ln_r = lj_red.mn_r;
					ln_g = lj_red.mn_g;
					ln_b = lj_red.mn_b;
					break;
				}

				led_canvas_set_pixel(offscreen_canvas, i, j, ln_r, ln_g, ln_b);
			}
		}

		for (i = lj_RR.mn_col; i > lj_RR.mn_col - 8; i--) {
			for (j = 0; j < lj_RR.mn_row; j++) {
				if (gb_dbg) {printf("RR.row=%d, RR.col=%d\n",j,i);}
				switch(j) {
					case 0 : // Blue
					ln_r = lj_blu.mn_r;
					ln_g = lj_blu.mn_g;
					ln_b = lj_blu.mn_b;
					break;

					case 1 :
					case 2 :
					case 3 : // Green 
					ln_r = lj_grn.mn_r;
					ln_g = lj_grn.mn_g;
					ln_b = lj_grn.mn_b;
					break;

					case 4 :
					case 5 : // Yellow Green
					ln_r = lj_gyw.mn_r;
					ln_g = lj_gyw.mn_g;
					ln_b = lj_gyw.mn_b;
					break;

					case 6 :
					case 7 :
					case 8 : // Yellow
					ln_r = lj_yel.mn_r;
					ln_g = lj_yel.mn_g;
					ln_b = lj_yel.mn_b;
					break;

					case 9 :
					case 10 :
					case 11 : // Orange
					ln_r = lj_org.mn_r;
					ln_g = lj_org.mn_g;
					ln_b = lj_org.mn_b;
					break;

					case 12 :
					case 13 : // Lt Red
					ln_r = lj_lrd.mn_r;
					ln_g = lj_lrd.mn_g;
					ln_b = lj_lrd.mn_b;
					break;

					case 14 :
					case 15 : // Red
					ln_r = lj_red.mn_r;
					ln_g = lj_red.mn_g;
					ln_b = lj_red.mn_b;
					break;
				}

				led_canvas_set_pixel(offscreen_canvas, i, j, ln_r, ln_g, ln_b);
			}
		}

		offscreen_canvas = led_matrix_swap_on_vsync(matrix, offscreen_canvas);
	}
  } //close( newsockfd );

  /*
   * Make sure to always call led_matrix_delete() in the end to reset the
   * display. Installing signal handlers for defined exit is a good idea.
   */
  led_matrix_delete(matrix);

  return 0;
}
}
`

**Comment by hzeller** [comment]
Make sure to link all relevant libraries when you link your program.

Also: don't use wiringPi, it will intefere with the LED matrix as it also attempts to mess with the GPIO pins. It might work, but I'd just use the features already provided in rpi-rgb-led-matrix: If you want to read inputs, see [input-example.cc](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/examples-api-use/input-example.cc).

**Comment by Toootless** [comment]
Is there another way to read data from an Arduino over the USB on the Rasberry Pi?

**Comment by Toootless** [comment]
The part of WiringPi I am using is the serialTest.c I don't thing it does anything with the GPIO.

`/*
 * serialTest.c:
 *	Very simple program to test the serial port. Expects
 *	the port to be looped back to itself
 *
 * Copyright (c) 2012-2013 Gordon Henderson. <projects@drogon.net>
 ***********************************************************************
 * This file is part of wiringPi:
 *	https://projects.drogon.net/raspberry-pi/wiringpi/
 *
 *    wiringPi is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Lesser General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    wiringPi is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public License
 *    along with wiringPi.  If not, see <http://www.gnu.org/licenses/>.
 ***********************************************************************
 */

#include <stdio.h>
#include <string.h>
#include <errno.h>

#include <wiringPi.h>
#include <wiringSerial.h>

int main ()
{
  int fd ;
  int count ;
  unsigned int nextTime ;

  if ((fd = serialOpen ("/dev/ttyACM0", 115200)) < 0)
  {
    fprintf (stderr, "Unable to open serial device: %s\n", strerror (errno)) ;
    return 1 ;
  }

  if (wiringPiSetup () == -1)
  {
    fprintf (stdout, "Unable to start wiringPi: %s\n", strerror (errno)) ;
    return 1 ;
  }

  nextTime = millis () + 300 ;

  for (count = 0 ; count < 256 ; )
  {
    if (millis () > nextTime)
    {
      printf ("\nOut: %3d: ", count) ;
      fflush (stdout) ;
      serialPutchar (fd, count) ;
      nextTime += 300 ;
      ++count ;
    }

    delay (3) ;

    while (serialDataAvail (fd))
    {
      printf (" -> %3d", serialGetchar (fd)) ;
      fflush (stdout) ;
    }
  }

  printf ("\n") ;
  return 0 ;
}`

**Comment by hzeller** [comment]
ok, if you don't use GPIO, then wiringPi would be an option (However, in that case, I'd just use the regular Linux ways to configure the [serial interface via termios](https://en.wikibooks.org/wiki/Serial_Programming/termios), then simple open(); no need for wiringPi).

So if you _do_ want to use wiringPi: you're back to your original question making sure things link properly. I'd use the [description in the README how to create your own Makefile](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#integrating-in-your-own-application) as starting point, then just add the wiringPi library.

**Comment by Toootless** [comment]
I will go back and reread that link when I tried to "add the wiringPi " to the marker file, it would start and go into the library and then exit and stops or it still does not link to the wiringPi files.

`make[1]: Entering directory '/home/pi/rpi-rgb-led-matrix-master/lib'
make[1]: Leaving directory '/home/pi/rpi-rgb-led-matrix-master/lib'
g++ display3.o -o display3 -L/usr/local/lib -L../lib -lrgbmatrix -lrt -lm -lpthread  -lstdc++ 
display3.o: In function `getData_convertData':
display3.c:(.text+0x2e4): undefined reference to `serialOpen'
display3.c:(.text+0x330): undefined reference to `wiringPiSetup'
display3.c:(.text+0x378): undefined reference to `millis'
display3.c:(.text+0x394): undefined reference to `millis'
display3.c:(.text+0x3d4): undefined reference to `serialPutchar'
display3.c:(.text+0x3f4): undefined reference to `delay'
display3.c:(.text+0x400): undefined reference to `serialGetchar'
display3.c:(.text+0x428): undefined reference to `serialDataAvail'
display3.c:(.text+0x454): undefined reference to `serialGetchar'
collect2: error: ld returned 1 exit status
Makefile:33: recipe for target 'display3' failed
make: *** [display3] Error 1
`


`CFLAGS=-Wall -O3 -g -Wextra -Wno-unused-parameter $(INCLUDE) -Winline -pipe
CXXFLAGS=$(CFLAGS)
INCLUDE	= -I/usr/local/include
LDFLAGS	= -L/usr/local/lib
LDLIBS    = -lwiringPi -lwiringPiDev -lpthread -lm -lcrypt -lrt

OBJECTS=demo-main.o minimal-example.o c-example.o text-example.o clock.o display3.o
BINARIES=demo minimal-example c-example text-example clock display3

# Where our library resides. You mostly only need to change the
# RGB_LIB_DISTRIBUTION, this is where the library is checked out.
RGB_LIB_DISTRIBUTION=..
RGB_INCDIR=$(RGB_LIB_DISTRIBUTION)/include
RGB_LIBDIR=$(RGB_LIB_DISTRIBUTION)/lib
RGB_LIBRARY_NAME=rgbmatrix
RGB_LIBRARY=$(RGB_LIBDIR)/lib$(RGB_LIBRARY_NAME).a
LDFLAGS+=-L$(RGB_LIBDIR) -l$(RGB_LIBRARY_NAME) -lrt -lm -lpthread 


all : $(BINARIES)

$(RGB_LIBRARY): FORCE
	$(MAKE) -C $(RGB_LIBDIR)

demo : demo-main.o $(RGB_LIBRARY)
	$(CXX) $< -o $@ $(LDFLAGS)

minimal-example : minimal-example.o
text-example: text-example.o
clock : clock.o

display3 : display3.o $(RGB_LIBRARY)
	$(CXX) $< -o $@ $(LDFLAGS) -lstdc++ 

# All the binaries that have the same name as the object file.q
% : %.o $(RGB_LIBRARY)
	$(CXX) $< -o $@ $(LDFLAGS)


# Since the C example uses the C++ library underneath, which depends on C++
# runtime stuff, you still have to also link -lstdc++
c-example : c-example.o $(RGB_LIBRARY)
	$(CC) $< -o $@ $(LDFLAGS) -lstdc++

%.o : %.cc
	$(CXX) -I$(RGB_INCDIR) $(CXXFLAGS) -c -o $@ $<

%.o : %.c
	$(CC) -I$(RGB_INCDIR) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJECTS) $(BINARIES)

FORCE:
.PHONY: FORCE
`

**Comment by hzeller** [comment]
You need to add `-lwiringPi -lwiringPiDev` to your `LDFLAGS` variable.

**Comment by Toootless** [comment]
# Where our library resides. You mostly only need to change the
# RGB_LIB_DISTRIBUTION, this is where the library is checked out.
RGB_LIB_DISTRIBUTION=..
RGB_INCDIR=$(RGB_LIB_DISTRIBUTION)/include
RGB_LIBDIR=$(RGB_LIB_DISTRIBUTION)/lib
RGB_LIBRARY_NAME=rgbmatrix
RGB_LIBRARY=$(RGB_LIBDIR)/lib$(RGB_LIBRARY_NAME).a
LDFLAGS+=-L$(RGB_LIBDIR) -l$(RGB_LIBRARY_NAME) -lrt -lm -lpthread -lwiringPi -lwiringPiDev 

pi@raspberrypi:~/rpi-rgb-led-matrix-master/examples-api-use $ sudo make
make -C ../lib
make[1]: Entering directory '/home/pi/rpi-rgb-led-matrix-master/lib'
make[1]: Leaving directory '/home/pi/rpi-rgb-led-matrix-master/lib'
g++ display3.o -o display3 -L/usr/local/lib -L../lib -lrgbmatrix -lrt -lm -lpthread -lwiringPi -lwiringPiDev  -lstdc++ 
pi@raspberrypi:~/rpi-rgb-led-matrix-master/examples-api-use $

**Comment by hzeller** [comment]
Looks like you figured it out ?
