### ISSUE TITLE
Image distortion

### ISSUE THREAD

**Issue by ChristopherBadenhorst** [hzeller/rpi-rgb-led-matrix#804]
Hi,

Using the library on a combination with 2x3 panels, with a passive-3 I soldered. The hat works fine with a 32x32 p0.5 and the images are correct, but really distorted.

https://youtu.be/ZPRIRoxP86A

I already tried the gpio slowdown, and this is the best result. 

Wil it work better with the active-3?

Regards,

Chris

**Comment by ChristopherBadenhorst** [comment]
Found the solution in the other parameters. 
I only need the '--led-pwm-dither-bits' in python. Anyone who can help?

**Comment by ChristopherBadenhorst** [comment]
Got myself an Adafruit RGB + RTC. Works like a charm.

**Comment by hzeller** [comment]
PWM dither bits have been added in 4c9a4036f44f173b783a0ba701138605f8b7d95c
