### ISSUE TITLE
128x64 Error (looks like twice a 128x32 screen)

### ISSUE THREAD

**Issue by PHI34Halladay** [hzeller/rpi-rgb-led-matrix#805]
Hey guys,
I'm trying to connect four 64x32 LEDs to a scoreboard (MLB-LED-Scoreboard) to a screen of 128x64 but I somehow get a weird error.
I get the same things shown on LED 1,2 and on 3,4. In other words: It looks like the scoreboard is compressed, because Row 1 and 2 lay together and the 3 and 4 do the same.
I hope you guys know that I meant to say. If no, I can also post photos in here.

Please help me out here.

Regards,
Patrick

**Comment by marcmerlin** [comment]
yeah, a picture will likely help

**Comment by PHI34Halladay** [comment]
Hey Marc,

thanks for your answer. Here is a picture from the matrix
![IMG_5589](https://user-images.githubusercontent.com/46962608/57090716-b9bed200-6d07-11e9-8dad-2430ff15f075.jpeg)

![ezgif-4-9a95223ef956](https://user-images.githubusercontent.com/46962608/57090806-ed016100-6d07-11e9-942e-cd6b162af350.gif)

**Comment by trevor-viljoen** [comment]
What parameters are you passing to the script? You would need something like ```—led-rows=64 —led-cols=32 —led-chain=2 —led-parallel=2```

**Comment by PHI34Halladay** [comment]
Yes, I tried the exact same LED flags, but it says that my Pi is not able to habe two LEDs parallel. That's why I tried it like that:
--led-rows=64 --led-cols=128 --led-chains=2

I'm using the newest Raspberry Pi btw.

**Comment by Beersatron** [comment]
I can't quite see in the picture, but does your HAT have two outputs or just the one?

In other words, what way are the panels connected?

Pi -> HAT -> Panel1 -> Panel2 - Panel3 - Panel4
or
Pi -> HAT -> Panel1 -> Panel2
            \_> Panel3 -> Panel 4

**Comment by PHI34Halladay** [comment]
It has only one output.

**Comment by trevor-viljoen** [comment]
Are you able to get one panel to setup correctly? ```--led-rows=32 --led-cols=64``` You might try disconnecting them and then making sure a single panel works, then add another: ``` --led-rows=32 --led-cols=64 --led-chain=2```

**Comment by PHI34Halladay** [comment]
1 panel works perfectly and I also don't have any problem using two panels.

**Comment by Beersatron** [comment]
--led-pixel-mapper="U-mapper" --led-rows=32 --led-cols=64 --led-chain=4

**Comment by trevor-viljoen** [comment]
@PHI34Halladay, I have a feeling this may be mlb-led-scoreboard related. Can you run this command and post the output? ```sudo python main.py --led-rows=32 --led-cols=64 --led-pixel-mapper=U-mapper --led-chain=4```

I don't think mlb-led-scoreboard is able to determine the layout. If that is the case, let's close this issue and re-open one for that project.

**Comment by PHI34Halladay** [comment]
> @PHI34Halladay, I have a feeling this may be mlb-led-scoreboard related. Can you run this command and post the output? `sudo python main.py --led-rows=32 --led-cols=64 --led-pixel-mapper=U-mapper --led-chain=4`
> 
> I don't think mlb-led-scoreboard is able to determine the layout. If that is the case, let's close this issue and re-open one for that project.

I ran that command and nothing happened. The script loaded normally but the LEDs keep dark.

I've seen pictures from the mlb-led-scoreboard where guys are using 128x64 on 4 LEDs so it should work somehow.

**Comment by PHI34Halladay** [comment]
Guys, I got it done...
I played around with the LED flags for a little while and endet up with that command:

sudo python main.py --led-rows=32 --led-cols=64 --led-chain=4 --led-gpio-mapping="adafruit-hat" --led-pixel-mapper=U-mapper

Thanks for all the help and especially the U-mapper info :)

**Comment by angelogoncalve** [comment]
Yes you are correct:

bonnet hat - flag: --led-gpio-mapping="adafruit-hat"

one output that link 4 panels in serie - flag: --led-rows=32 --led-cols=64 --led-chain=4

you have 2 rows of panels that the message are equal for both - flag: --led-pixel-mapper=U-mapper
