### ISSUE TITLE
USB to audio conversion adapter with the API?

### ISSUE THREAD

**Issue by wakka0014** [hzeller/rpi-rgb-led-matrix#810]
Hello!
Thank you to a great API !!

I tried to play the LED and sound referring to the following URL, but it was useless.
https://github.com/hzeller/rpi-rgb-led-matrix/issues/158

I bought a converter for USB and audio, but can't I use a conversion adapter?
It will be the following.
https://www.biccamera.com/bc/item/1597625/

We look forward to your reply.
Thank you.

**Comment by hzeller** [comment]
This is somewhat outside the scope of this library; you need to figure out with your Linux distribution how well this adapter works.
