### ISSUE TITLE
Rectangle on Image

### ISSUE THREAD

**Issue by dbourdeveloper** [hzeller/rpi-rgb-led-matrix#811]
Using a Raspberry Pi 3 model v1.2 and Adafruit's Bonnet

Not sure if its my wiring, but every time I run any demo, I get a large white rectangle as shown in the image.

![Image (5)](https://user-images.githubusercontent.com/10367546/57576363-e9aa5b80-7412-11e9-8854-bfd746cfbd26.jpeg)
![Image-1 (1)](https://user-images.githubusercontent.com/10367546/57585746-068d7000-74a1-11e9-86f5-507297c03ffa.jpeg)

I have an external power source to the LED and it's using a DC adaptor with ranges of 3-12v. The bonnet ([from adafruit](https://learn.adafruit.com/adafruit-rgb-matrix-bonnet-for-raspberry-pi/overview)) is connected to the Raspberry Pi 3, but only for the purpose of connecting to the matrix or in other words, I didn't bother trying to power the matrix through it since I couldn't get that part to work either. The LED matrix is the [16x32 RGB](https://www.adafruit.com/product/420) from adafruit

**Comment by jaygarcia** [comment]
@dbourdeveloper Please post your matrix type, refresh rate, wiring and how you've connected it to the rpi, etc.. More input :D 

![image](https://user-images.githubusercontent.com/180031/57584976-99350b80-74af-11e9-928d-3decba922fe5.png)

**Comment by dbourdeveloper** [comment]
> @dbourdeveloper Please post your matrix type, refresh rate, wiring and how you've connected it to the rpi, etc.. More input :D
> 
> ![image](https://user-images.githubusercontent.com/180031/57584976-99350b80-74af-11e9-928d-3decba922fe5.png)

@jaygarcia , updated the OP. Thanks for getting back!

**Comment by hzeller** [comment]
This just looks lie your LED matrix is broken.

**Comment by dbourdeveloper** [comment]
> first 16 bit of the shift-register that supplies the bottom part is still working. So I suspect that there is a buffer or connection broken on the LED matrix that connects shift-registers chips between left and right with each other. Possibly just the clock line as it is harder to mess up 6 RGB lines in parallel. Inspect the leads on chips in the given quadrant closely and see if there is maybe a broken solder joint that might need a touch-up.

Thanks @hzeller , I was afraid that would be a case. I'll see what I can find but thank you for your amazing contribution with this library!
