### ISSUE TITLE
Rock 64 GPIO /de/mem mmap error: Operation not permitted

### ISSUE THREAD

**Issue by krishnasandeep10694** [hzeller/rpi-rgb-led-matrix#812]
Hi @hzeller  ,
I am planning to use this library with rock64. I have read in couple of sources that rock 64 and rpi has similar gpio pinout. But whem i am trying to run a runtext program which is in samples directory I am getting below error even though i am running as sudo.

```
rock64@rock64:~/Downloads/rpi-rgb-led-matrix-master/bindings/python/samples$ sudo python3 runtext.py --led-chain=1
mmap error: : Operation not permitted
RPi1: MMapping from base 0x20000000, offset 0x200000
Must run as root to be able to access /dev/mem
Prepend 'sudo' to the command
Press CTRL-C to stop sample
Segmentation fault
```
I am running Ubuntu_18.04_Bionic_LXDE_Desktop on rock 64. I dont have much idea about hardware memory mappings. I did a bit of google research on the above issue and people are mentioning to tweak some flags in kernel config and that would be dangerous. 

Any help would be appreciated.

Thanks.

**Comment by hzeller** [comment]
This library is for the Raspberry Pi, it will not work with any other SBC.

**Comment by krishnasandeep10694** [comment]
Ok thanks for quick reply.

**Comment by 7Ds7** [comment]
Kind of getting the same results on a Rpi3 B+ running arch

```
sudo examples-api-use/demo -D0                                                                                                                                                                                       
mmap error: : Operation not permitted
RPi1: MMapping from base 0x20000000, offset 0x200000
Must run as root to be able to access /dev/mem
Prepend 'sudo' to the command
```

Current arch version is ```Linux alarm 5.1.5-1-ARCH #1 SMP Sat May 25 13:23:49 MDT 2019 aarch64 GNU/Linux``` i know i had this running on a RPi a few years ago although the arch version might have been 32 instead of 64bits, wonder if that might be the problem ?

**Comment by hzeller** [comment]
Have a look, I think they changed things on recent kernels so that it is not possible to direcly mount /dev/mem. You have to figure out how to circumvent that.

**Comment by 7Ds7** [comment]
Thank you for the hing @hzeller yep seems that the only way to disable ```CONFIG_STRICT_DEVMEM``` would be building the kernel from source.

Changed to Raspbian Stretch Lite distribution and it works great

**Comment by quantenProjects** [comment]
I found a workaround for kernels with [`CONFIG_STRICT_DEVMEM` for my alpine linux on a raspberry pi](https://git.alpinelinux.org/aports/tree/main/linux-rpi/config-changes-rpi.armhf#n17):

The kernel parameter `iomem=relaxed` disables the address checking. Adding it to the `cmdline.txt` worked perfectly.

https://stackoverflow.com/a/49138256

btw: Alpine with its diskless mode is perfectly for display/presentation purposes, since the sd card is mounted read only and power losses doesn't corrupt the filesystem

**Comment by phongans** [comment]
> Thank you for the hing @hzeller yep seems that the only way to disable `CONFIG_STRICT_DEVMEM` would be building the kernel from source.
> 
> Changed to Raspbian Stretch Lite distribution and it works great

How to rebuild new OS?
