### ISSUE TITLE
Display date and time in two separate lines

### ISSUE THREAD

**Issue by jimmyspa** [hzeller/rpi-rgb-led-matrix#816]
Hello, 
I tried to use the time format of "%%d:%%H:%%M" but only 1 line is shown. Can it show in two lines, date in one line and time in the 2nd line?

Thanks.

**Comment by davemaster** [comment]
try using cr or lf sequences

**Comment by ChristopherBadenhorst** [comment]
Do you have the script lines you are using it in? In python it is easy:

`clock = datetime.datetime.now().strftime("%H:%M:")
 clock2 = datetime.datetime.now().strftime("%S")
 
graphics.DrawText(matrix, font, x, y, blue, clock)
graphics.DrawText(matrix, font, x, y, blue, clock2)`
