### ISSUE TITLE
Funky new P10 1/4 Scan (so the product description says)

### ISSUE THREAD

**Issue by grene78** [hzeller/rpi-rgb-led-matrix#820]
A little confused by all the various panel issues, but I think I have a new one not covered by any other issues.  What is the current method for handling these oddball displays?  Is there a tutorial on starting from scratch?  If not, I'll write one as I go.  My setup works perfectly with p6 indoor and p10 indoor but this p10 outdoor is a whole different beast.  Any pointers are appreciated.

2 x 16x32 P10 1/4 Scan Panels

sudo ./demo -D 3 --led-rows=16 --led-cols=32 --led-chain=2 --led-multiplexing=0
![0](https://user-images.githubusercontent.com/21082669/58205785-46c4cd80-7cad-11e9-8a8c-2ebc7624a7a6.jpg)

sudo ./demo -D 3 --led-rows=16 --led-cols=32 --led-chain=2 --led-multiplexing=1
![1](https://user-images.githubusercontent.com/21082669/58205780-42001980-7cad-11e9-9689-b1a99f681552.jpg)

sudo ./demo -D 3 --led-rows=16 --led-cols=32 --led-chain=2 --led-multiplexing=5
![5](https://user-images.githubusercontent.com/21082669/58205751-357bc100-7cad-11e9-9906-e91429c5c54b.jpg)

Configuring in the controller that we currently use for these panels (but trying to move away from dedicated controllers and use the system built on a pi.  I couldn't get the whole thing because of the nature of the crummy software, but this gives an idea.
![ugg](https://user-images.githubusercontent.com/21082669/58205880-855a8800-7cad-11e9-8118-2aa0cc580067.png)

Product Link: https://www.aliexpress.com/item/1634189398.html?spm=a2g0s.9042311.0.0.65b34c4dqJWAh1

**Comment by grene78** [comment]
Never mind, these panels are already supported.

For anyone else that comes across this, fresh eyes as I started to play around with the multiplex mapper classes led me to the discovery of --led-row-addr-type which I admit I somehow totally missed in my earlier endeavors.

sudo ./demo -D 3 --led-rows=16 --led-cols=32 --led-chain=2 **--led-row-addr-type=2** --led-multiplexing=5

![row-addr-type-2 mp5](https://user-images.githubusercontent.com/21082669/58270637-47666e00-7d58-11e9-9e44-1b257676a838.jpg)

**Comment by angelogoncalve** [comment]
Yes you can see in the readme to put the flag:

--led-row-addr-type=2

for 16x32 1/4 Scan Rate panel
