### ISSUE TITLE
Launching on Startup

### ISSUE THREAD

**Issue by natemac** [hzeller/rpi-rgb-led-matrix#83]
If I wanted to launch "sudo ./led-image-viewer LEDWallv2.gif -r 16 -c 4 -p 6" on startup, how might I go about doing that?
This might be a fundamental coding question, but I'm slightly new to this side of the programming. 

From the root location how do I tell the RPi to run that line of code inside the rpi-rgb-led-matrix folder?
Thanks.

**Comment by hzeller** [comment]
No coding question, just basic computer administration :)

 - To launch on startup, you want to write an init script (there is tons of documentation out there how to do that; essentially you want a script in `/etc/rc2.d/` or -- quick and dirty -- add the program invocation to `/etc/rc.local`)
 - the led-image-viewer supports the `-d` flag that allows you to run it as a daemon in the background.
 - For the image-file, it is best to actually give it the absolute path, e.g. /home/pi/LEDWallv2.gif or wherever your file resides.
