### ISSUE TITLE
Two 64x64 RGB Matrix as a Screen Display

### ISSUE THREAD

**Issue by sguzmanolmos** [hzeller/rpi-rgb-led-matrix#838]
Hi guys,

I'm trying to follow this Adafruit tutorial (https://cdn-learn.adafruit.com/downloads/pdf/raspberry-pi-led-matrix-display.pdf) but I can't manage to make it work. Mainly because I'm very new at this and I'm not using the same hardware as instructed. I'm running a Raspberry Pi 3B + Matrix Bonnet + Two 64x64 RGB LED Matrix 2.5mm Pitch + enough power supply

The goal is to make a 64x128 display that scales and crops part of the Pi's HDMI output. Could anyone help me? Thanks in advance! :)

**Comment by hzeller** [comment]
if you use the bonnet, you need to specify the [--led-gpio-mapping](https://github.com/hzeller/rpi-rgb-led-matrix#if-you-have-an-adafruit-hat-or-bonnet) flag as described in the README.

For HDMI replication, Adafruit wrote a program that does that ( https://github.com/adafruit/rpi-fb-matrix.git )
