### ISSUE TITLE
Matrix Bonnet not compatible with video-viewer?

### ISSUE THREAD

**Issue by sguzmanolmos** [hzeller/rpi-rgb-led-matrix#841]
Hi Guys, I've been trying to use the video viewer with my Raspberry Pi 3B, the Matrix Bonnet and two 64x64 2.5 mm pitch. But the video-viewer doesn't seem to work, only image-viewer and the demos are displaying, and in the GPIO options, the bonnet is not featured. Is this board not supported, or am I doing something wrong? Thanks for your time!

**Comment by hzeller** [comment]
the bonnet should be the same hardware mapping as the adafruit hat.

**Comment by sguzmanolmos** [comment]
Thanks! When the Bonnet is been modified to control 64x64 2.5mm pitch panels it uses the `hat-pwm` Problem solved :)

**Comment by sguzmanolmos** [comment]
Is it possible to mirror the Pi's HDMI output with the video-viewer?

**Comment by hzeller** [comment]
Adafruit built a program that uses this library and replicates the framebuffer content https://github.com/adafruit/rpi-fb-matrix.git
