### ISSUE TITLE
Gerber format

### ISSUE THREAD

**Issue by Sai5157** [hzeller/rpi-rgb-led-matrix#848]
While trying to give pcb and assembly manufacturing in pcbway they were saying they need a file format in RS-274X, can someone help in converting the existing gerber files to RS-274X format

**Comment by hzeller** [comment]
Maybe your board-house can't deal with the X2 attributes yet ? Anyway, I downgraded the gerber files to the old version, can you try again ?

**Comment by Sai5157** [comment]
Yes it is working now! I will update the order number here which will help the other fellows to get there active 3 board manufactured.Thanks a lot
