### ISSUE TITLE
Problem with FM6126A chipset

### ISSUE THREAD

**Issue by z26100** [hzeller/rpi-rgb-led-matrix#855]
Hi,
I bought some of [these](https://www.ebay.de/itm/4x-P4-RGB-LED-Matrix-Panels-Display-Austauschmodule-64x64-pixel-256-x-256-mm/303174069343?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649) panels and after I applied the [reset_active3.py.txt](https://github.com/hzeller/rpi-rgb-led-matrix/files/3139328/resetmatrix_active3.py.txt) I could at least see them working in general.
![IMG_2073](https://user-images.githubusercontent.com/4007385/61589093-ad7b4000-aba5-11e9-8d63-dc15deff2019.JPG)
![IMG_2074](https://user-images.githubusercontent.com/4007385/61589238-68580d80-aba7-11e9-9f9a-f9e2b03e0989.JPG)

![IMG_2072](https://user-images.githubusercontent.com/4007385/61589100-bd931f80-aba5-11e9-902e-62cd99192787.JPG)

However, the second half of the panel seems not to be addressed properly. 
After some investigations I think they consist out of 2x32 rows that are some chained together, so I also tried out
```
 sudo ./demo --led-no-hardware-pulse --led-gpio-mapping=regular --led-rows=64 --led-chain=2 -D 0
``` 
which leads to one single rotating cube but still the same LED rows remain blank/black.
![IMG_2075](https://user-images.githubusercontent.com/4007385/61589234-58d8c480-aba7-11e9-81aa-38e83a3b0a08.JPG)

Any suggestions?

**Comment by z26100** [comment]
After carefully reading the [documentation](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/adapter/active-3) of the active board in this repository it seems I've missed to solder the bridge for addressing the E line.

**Comment by sachasayan** [comment]
I've added a hardware compatibility table in the Wiki, could you add notes for this panel there with settings if you've confirmed it working? ^_^

https://github.com/hzeller/rpi-rgb-led-matrix/wiki

**Comment by hzeller** [comment]
Looks like you got it working with connecting the E line.

**Comment by marcmerlin** [comment]
Hi @hzeller , so it is mostly working, but not quite.
For a setup with more than 128 columns, the init sequence does not get sent deep enough. See https://github.com/hzeller/rpi-rgb-led-matrix/issues/947 for details

**Comment by marcmerlin** [comment]
whooops, ignore my comment on the wrong bug, I'll delete it.
