### ISSUE TITLE
garbage pixels although not constantly

### ISSUE THREAD

**Issue by flok99** [hzeller/rpi-rgb-led-matrix#863]

**Comment by flok99** [comment]
Situation:
- 8 panels, 32x16 each, adafruit 420
- brightness 50%
- --led-rows=16 --led-chain=8 --led-pixel-mapper="U-mapper"  --led-no-drop-privs
- adafruit hat, PWM patch applied, software compiled with HARDWARE_DESC?=adafruit-hat-pwm
- two powersupplies (gnd connected)
- raspberry pi 4 with 4.19.57-v7l+ kernel

With 4 panels (--led-chain=4) the background is black but scrolling text is noisy on the edges.
With 8 panels, the background is all noise, text shows fine altough with the same noise on the edges.
I went through the help-page (disabled all i/o like i2c, spi, serial, audio, etc).

Any ideas? Please see attached photos.

![noise-1](https://user-images.githubusercontent.com/3216056/62417614-2d001900-b654-11e9-9472-ec30a1a4319c.jpg)
![noise-2](https://user-images.githubusercontent.com/3216056/62417615-2d001900-b654-11e9-91bb-6eaa22fbb13b.jpg)

**Comment by hzeller** [comment]
The Pi4 is typically too fast for the panels. You typically want to set the gpio slowdown to a higher value.

**Comment by buzztiaan** [comment]
i just threw a pi3 at his desk, gonna try in a bit if that fixes it

**Comment by flok99** [comment]
I've tried --led-slowdown-gpio=4 and this helps dramatically; no noisy edges and it doesn't flicker anymore. The color-patterns stay though.

Next step is testing with the rpi3.

**Comment by flok99** [comment]
With the RPI-3b we have the same problem.

**Comment by hzeller** [comment]
Could also be high inductance in your power cables. Keep them as short as possible and consider adding capacitors directly to the power connection.

(Weird patterns often happen if 1-wire interface is switched on, but you said you already took care of disabling interfaces).

**Comment by flok99** [comment]
Ok, closing the ticket.
The problem was that the rpi4 was too fast and...a bug in our software :-(

**Comment by flok99** [comment]
thanks for your help by the way!
