### ISSUE TITLE
Led Matrix 32x16 Display issue

### ISSUE THREAD

**Issue by andriravoa** [hzeller/rpi-rgb-led-matrix#865]
Dear all,
I've a issue by displaying "forward scrolling an image" on my led matrix 32x16 with a RGB Matrix Panel Drive Board For Raspberry Pi (provided by electrodragon) using pi3 . 
During the test a use the following command: udo ./demo --led-rows=16 --led-chain=1 -D 9 runtext16.ppm and below is the screen i got. 
Could you guys please give an advise to fix it?
![DSC_0102](https://user-images.githubusercontent.com/53685186/62421535-3d87b200-b69b-11e9-95d7-0d0636c533fb.JPG)
![issue](https://user-images.githubusercontent.com/53685186/62421677-5a24e980-b69d-11e9-8974-5f88c739010e.gif)
And this is my setup:
![DSC_0100](https://user-images.githubusercontent.com/53685186/62421705-cef82380-b69d-11e9-83cf-3622e1ea2e75.JPG)

Thank you
A

**Comment by hzeller** [comment]
This looks like a 1:4 multiplexed LED panel. Use the flag for led multiplexing and find the option working for your panel.

**Comment by andriravoa** [comment]
Dear, after checking and using flag for led multiplexing. I found it and works with my panel. 
At the end, this is what i did: sudo ./demo --led-rows=16 --led-cols=32 --led-multiplexing=1 -D 3 runtext16.ppm
Thank you for your help. I appreciate your advise. 
Regards
A
