### ISSUE TITLE
Error when downloading files

### ISSUE THREAD

**Issue by greene36** [hzeller/rpi-rgb-led-matrix#873]
![PI Error](https://user-images.githubusercontent.com/54296325/63309542-26fd6f80-c2c5-11e9-8db6-bcec68ab8506.png)

Getting an error 404 for downloading the content files.  Have these files been replaced or sourced elsewhere?  Thank you.

**Comment by hzeller** [comment]
This is really a question for your distribution, not for rpi-rgb-led-matrix.

You have to do `sudo apt-get update` first before trying to apt install.
