### ISSUE TITLE
Display text and time using Pi3

### ISSUE THREAD

**Issue by andriravoa** [hzeller/rpi-rgb-led-matrix#877]
Hi all, 
Please assist me to display and alternate text and time using rgb led matrix with pi3. 
Thanks

**Comment by jaygarcia** [comment]
Hi @andriravoa, what is your exact question? It seems like you're asking us to do the work for you.

**Comment by andriravoa** [comment]
Hi @jaygarcia, this is just to ask to have an idea; but I did it already at home. 
Thank you.

**Comment by hzeller** [comment]
So please, if you're done with a quesiton @andriravoa make sure to close the issue.

**Comment by jaygarcia** [comment]
Great to hear @andriravoa  :). Please close this issue.

**Comment by jaygarcia** [comment]
Henner beat me to it :D
