### ISSUE TITLE
Autoplay all images arranged by date and time?

### ISSUE THREAD

**Issue by rijotech** [hzeller/rpi-rgb-led-matrix#881]
Hi Mr Zeller i was wondering if there is a way to arrange what to display first when executing 
sudo ./led-image-viewer -f -w3 *.png.
Meaning let say play all images acording to created date and time accending or decending instead of image names, is that posible?

**Comment by hzeller** [comment]
Instead of `*.png`, which globs the names alphabetically, you could use the sorted output of `ls -t`

```
sudo ./led-image-viewer -f -w3 $(ls -t *.png)
```

**Comment by rijotech** [comment]
Thanks Mr. Zeller
