### ISSUE TITLE
30px height Fonts

### ISSUE THREAD

**Issue by Wikiz05** [hzeller/rpi-rgb-led-matrix#882]
I having issue how to use otf2bdf. I'm a newbie here and I never use raspberry before, this is my 1st project with it. Could someone help me how to use the otf2bdf converter like a step by step tutorial. Or if someone be so kind to make me a 30px height bold bdf fonts?  I tried  bitfronter 3 but when I saved the file to bdf and run a text-example the fonts  not recognizable.

**Comment by hzeller** [comment]
You first have to choose the font you'd like to display. Find a TTF font you like and that is bold. Typically the fonts have that in their name. The typical resolution of fonts is 72 dpi, so in order to get a 30 pixel font, you'd do something like

```
otf2bdf -v -o myfont.bdf -r 72 -p 30 /path/to/font-Bold.ttf
```
