### ISSUE TITLE
Problem executing script with php page

### ISSUE THREAD

**Issue by eSenKaa** [hzeller/rpi-rgb-led-matrix#884]
Hi ! First of all, thanks for your awesome library.

I'm here because I have an issue, I made my own buildroot without sudo and I would like to execute a .sh from a php page. (The .sh works pretty well without sudo on my raspberry to execute things on my led screen) but when I try on my php page I got this in the logs :

Must run as root to be able to access /dev/mem
Prepend 'sudo' to the command

How can I manage to have it works without sudo.

Thanks in advance if you have an answer.

This is my script.sh : 

#!/bin/sh
echo $(ls)
./demo -D0 --led-daemon --led-no-drop-privs

echo $(ls) works well but then nothing on the php with the demo.

The index.php : 

![image](https://user-images.githubusercontent.com/28647764/64446144-57704680-d0d8-11e9-9108-3e71041d1640.png)

**Comment by hzeller** [comment]
you can set `demo` SUID root.

**Comment by eSenKaa** [comment]
thanks for your fast answer, could you be more specific with more details because i'm just a beginner so that don't talk much to me :/

**Comment by hzeller** [comment]
use chmod to set this flag; use Google to understand more of the concept if you haven't encountered it before (sorry, on phone, can't easily write)

**Comment by eSenKaa** [comment]
ok I found something and it actually works, thanks a lot :)
