### ISSUE TITLE
Using led matrix and SPI simultaneous 

### ISSUE THREAD

**Issue by bob00105** [hzeller/rpi-rgb-led-matrix#89]
Firstly, thank you for your amazing library.
However I would like to use a SPI device at the same time as the led matrix.
So is there a way to only use the second panel in a chain?
I tried to just change the pins, but I could not find where they are defined.

Bob Tillemans

P.S.  
I could not find how to add a question label to this post, is there a way to do that?

**Comment by hzeller** [comment]
Right now, there is not simple option to not use the first chain, but it is on my list to make that configurable.

As a quick hack, you could try to comment out the two lines
  b.bits.p0_r1 = b.bits.p0_g1 = b.bits.p0_b1 = 1;
  b.bits.p0_r2 = b.bits.p0_g2 = b.bits.p0_b2 = 1;

Around line 89 in this file
https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/framebuffer.cc#L89

This will not set these pins for use by the library then (you might need to re-boot the Pi to make sure that these are clear to use with SPI).

Now you can use the library with `-P2` to say that you have two parallel chains, but the first will actually not work in that case.

It will not be the full solution though:  the remaining chain now still 'thinks' it is the second in the chains, so only shows 32..63 y-coordinates; so still some fiddeling is needed in SetPixel() to remove that; or, better yet, to write a transformer (see include/canvas.h, include/transformer.h) to mask these out. 

These things will be more smooth once I've made that more easily configurable, but this might help you get started to hack it to work for now.
