### ISSUE TITLE
Upgrading from Adafruit's Tutorial

### ISSUE THREAD

**Issue by GantMan** [hzeller/rpi-rgb-led-matrix#9]
Hi, I'm new to the Raspberry Pi, and I've recently implemented the display using Adafruit's tutorial, which can be found here:  https://learn.adafruit.com/connecting-a-16x32-rgb-led-matrix-panel-to-a-raspberry-pi/overview

This code is based off an old fork of your code:  https://github.com/Boomerific/rpi-rgb-led-matrix

I've successfully built a nice display, and even made a nice Sinatra website that powers the board's images.  I'm looking to upgrade to a 32x32 display and consider using text for my next one, which is how I tracked down the original, here.   Unfortunately, switching to your code, everything is upside-down!  

I'm going to be working with some people in a local Maker space, and I'm wondering if there's a simple way to flip the output, so that people who complete the Adafruit tutorial, can upgrade to your constantly evolving repo, over being stuck on the other?

**Comment by hzeller** [comment]
Closing this issue, as the original thing has been resolved.
