### ISSUE TITLE
crash on Pi 3 Model A+

### ISSUE THREAD

**Issue by TonivdW** [hzeller/rpi-rgb-led-matrix#900]
Sparkling new model 3A+, freshly installed Raspian Lite, fully updated.
Right after starting ft-server the screen is getting overwritten with green or purple blurbs and sometimes kernel panics are reported. 

Is FT supported on model 3A+?

![DSC_0291](https://user-images.githubusercontent.com/2771748/65838380-cb31f780-e302-11e9-9d93-22a7811caaa7.JPG)

**Comment by hzeller** [comment]
If with FT, you mean https://github.com/hzeller/flaschen-taschen , then you probably have to update the submodule (it is in a version before the automatic A+ conversion). I'll fix that there.

**Comment by hzeller** [comment]
I've updated the version now, can you do a submodule update or a fresh recursive update with FlaschenTaschen to see ?

**Comment by TonivdW** [comment]
Yes, that fixed it! Many thanks.
