### ISSUE TITLE
RGBLedMatrixOptions.GpioSlowdown property has no effect (C# binding)

### ISSUE THREAD

**Issue by daniel-richter** [hzeller/rpi-rgb-led-matrix#906]
Setting the `RGBLedMatrixOptions.GpioSlowdown` property has no effect. It always has the default value of 1.

In my opinion, this should never have worked before. While options like rows, cols, chain length, etc are part of `RGBMatrix::Options`, gpio-slowdown is part of `RuntimeOptions` (and is never passed to `led_matrix_create_from_options`).

My current workaround is to hardcode set `DRGB_SLOWDOWN_GPIO` in `lib/MAKEFILE`

**Comment by hzeller** [comment]
can you provide a pull request that makes it work?

**Comment by daniel-richter** [comment]
I'll try, but I'm not sure what the best way to do this is, though. Adding a `led_matrix_create_from_options_2` that takes RuntimeOptions as a parameter? RuntimeOptions seem to be read directly from the command line at the moment...

**Comment by hzeller** [comment]
As a quick workaround for now, could you just pass the command-line option to your program ? Or pass it to the argc/argv manually when invoking `led_matrix_create_from_options`

**Comment by wibbleboy** [comment]
I'm glad that I found this thread; I hit the same issue yesterday where the Python examples were working on my Pi4, but I was getting ghosting of the pixels on my third panel whenn using the c# library, regardless of the slowdown property.

Building Daniels's workaround branch allows me to fix this by setting the slowdown to 5 via RGBLedMatrixOptions. Thanks.
