### ISSUE TITLE
3 chains using FM6126A - top chain colors wrong on half of panel

### ISSUE THREAD

**Issue by epdmc** [hzeller/rpi-rgb-led-matrix#912]
This almost works with three chains, really appreciate adding the 6126A code. 

So when I run something like ./demo -D 0 --led-cols=64 --led-parallel=3 --led-panel-type=FM6126A the last board in the chain seems to have an issue where half the colors are wrong. In this example the square is just always red (plus artifacts). 

Using this gem as well: https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/adapter

![IMG_3151](https://user-images.githubusercontent.com/53667180/67171948-fc8c6900-f37e-11e9-9cbc-dd40aaba618e.JPG)

**Comment by OllmGrb** [comment]
Hi, have the same issue but didnt try the adapter board out. Any luck??
