### ISSUE TITLE
Volume bars with noise from mic?

### ISSUE THREAD

**Issue by rijotech** [hzeller/rpi-rgb-led-matrix#914]
Hi Mr Hzeller, I was wondering if there is a way to get the Volume bars to work with mic noise?

**Comment by hzeller** [comment]
The volume bars are of course only a demo without any data.

If you want to display real audio, you need an audio input (the Raspberry Pi doesn't have any, so you need to add a USB soundcard), then read the data, do a fourier transformation and display it. Should only be a few lines of code if you are using an existing FFT library.
