### ISSUE TITLE
64x64 LED Matrix missing lines

### ISSUE THREAD

**Issue by iYCloud** [hzeller/rpi-rgb-led-matrix#919]
Hello!

First of all, thank you for the great library.

Like mentioned in the title, I have a 64x64 panel that has missing lines after every 8x64. I have included a picture down below.

Does anyone have any suggestions about how to get it to work or do I really have a defective panel?

![73084700_737414130111399_5147504160928694272_n](https://user-images.githubusercontent.com/57157074/67811465-84702280-faa5-11e9-97d3-e1e9ce238208.jpg)

**Comment by hzeller** [comment]
what multiplexing options did you try?

**Comment by iYCloud** [comment]
> what multiplexing options did you try?

I have tried all of them `--led-multiplexing=<0..10>` from 0 to 10. And the best result is with 0. Most of them will give the outcome shown on the picture down below.

![73142083_2469412809960088_2900731658003021824_n](https://user-images.githubusercontent.com/57157074/67833299-f15adb00-faec-11e9-8572-8e7c443c038d.jpg)

**Comment by hzeller** [comment]
And it is also not a `--led-panel-type=FM6126A` ?

**Comment by iYCloud** [comment]
> And it is also not a `--led-panel-type=FM6126A` ?

From my testing, adding the aforementioned line does not affect the outcome.

**Comment by iYCloud** [comment]
I have found a solution to my problem, by connecting the sixth line `GND` to GPIO pin 22 on my Raspberry Pi 3 B+ (following still the wiring diagram [url](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/wiring.md#wiring-diagram)).

My led matrix has a pin layout as follows (picture down below):
`R1 G1`
`B1 GND`
`R2 G2`
`B2 E`
`A B`
`C GND` (I used `GND` as `D`)
`CLK LAT`
`OE GND`

![74505870_424159915174916_5846579456369491968_n](https://user-images.githubusercontent.com/57157074/67971472-80fba900-fc15-11e9-82cd-9d735b2f0fa6.jpg)

**Comment by akingscote** [comment]
Thanks @iYCloud! i had the exact same problem!! cheers
