### ISSUE TITLE
Problem with full brightness of pannell

### ISSUE THREAD

**Issue by Danijel777** [hzeller/rpi-rgb-led-matrix#925]
When RGB matrix is populated with most of "white" LED diodes, picture is pulsating (about 12 Hz). RGB  matrix display is from Coreman (p4 64*32 rgb led matrix panel indoor smd2121 MBI led diplay screen p4 led video wall module p2p3p5p6).
Tho solution of problem is probably in power supply. Voltage droped down for about more then 2 Volts in frequency of about 12 Hz.
In the next days I will take power supplay with posibility of more current. Now I use PC Lenovo power supplay with 5V an max 14 A which is not enough for the peak of current RGB matrix needs.

Here is the link what happend [(https://youtu.be/y4Xf2xjoTL0)]
![IMG_20191110_141345](https://user-images.githubusercontent.com/57591178/68544549-8f3f8700-03c4-11ea-815e-7ac870c99857.jpg)
![IMG_20191110_141511](https://user-images.githubusercontent.com/57591178/68544550-8f3f8700-03c4-11ea-9d61-02bace4d7dd6.jpg)

**Comment by KentWalker** [comment]
The problem may not be that your power supply cannot deliver enough current but there is not enough current draw from the other supply rails.
PC power supplies expect to see a minimum current draw on both the 5VDC and 12VDC supplies and can become unstable if the load isn't enough.

Try adding some load resistance to the unused supplies.  The LED panel wouldn't draw more than 5A peak so the power supply should be adequate.

**Comment by hzeller** [comment]
Sometimes, the spikes in current can also bring the power-supply into some sort of oscillation. I also see that the power cables are pretty long which possibly creates some inductive load (the current pulses needed by the panel are pretty short.

I have seen a 60A power supply oscillate on a panel that only draws 45A average. This was fixed by having local capacitors at the connectors.

I'd try to add some 3300uF low-esr capacitor directly at the power connector on the panel. Here is a good starting point
https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/wiring.md#a-word-about-power

**Comment by Danijel777** [comment]
First, I tried what Mr. Hzeller has said.
The pulsating is smaller but is still there. 
Connection of capacitors is not nice but for evalution purpose is good enough.
Tomorrow I wil try with another PC power supply and consider what KentWalker said.
Thanks to both!
![IMG_20191111_235137](https://user-images.githubusercontent.com/57591178/68628033-ad4dda00-04df-11ea-82f7-e7da345b2d90.jpg)
![IMG_20191111_235304](https://user-images.githubusercontent.com/57591178/68628068-cb1b3f00-04df-11ea-82f1-5024f73683c5.jpg)

**Comment by Danijel777** [comment]
Well, with another PC power supplay (connected paralell), everything works fine. 
I have tried with max brightness of whole panel and pulsatings is gone.
With ampermeter I mesaured and white screen, current is about 2,60 A. This is power consumption of 13 W.
I thing that the problem what occur before was in PC power supply what KentWalker said in previous comment.
Possibly, the best solution is to build "classic" rectifier with transformer and 4 diodes in bridge (Graetz) and capacitor (and electronic circuit for stabiliesed voltage). 
PC rectifiers consist of power electronics elements, which sometimes produce unexpected results in case of diferent type of aplication, which was showed in this aplication with RGB LED display.
![IMG_20191112_221825](https://user-images.githubusercontent.com/57591178/68714798-e1d59a80-05a0-11ea-8c59-c005e38f09ef.jpg)

**Comment by Danijel777** [comment]
One question:
Is the rgb led display I used a good choice or would someone suggest a better manufacturer or product. The purpose is to build a video wall in 3 rows and 4 columns inside or outside the school. So the video wall should be for educational and informational needs. Thank you.
