### ISSUE TITLE
How to view an image without scrolling

### ISSUE THREAD

**Issue by Haidar93** [hzeller/rpi-rgb-led-matrix#930]
Hello everyone,

I would like to say thank you again for Mr. Henner Zeller for the amazing library.

I am a beginner to write code. Therefore, I looking for python code about how to display an image without move on the RGB led matrix.

I am thankful to those who will help me.

**Comment by hzeller** [comment]
For just showing an image, you might consider the existing utility for it:
https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/utils#image-viewer

For python examples, there is the [`imager-viewer.py`](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/bindings/python/samples/image-viewer.py).

(But, I would also strongly encourage you to start with C++ to learn programming)
