### ISSUE TITLE
Issue with output on 64x32 outdoor P5 8S (scan 1:8) panel

### ISSUE THREAD

**Issue by KorneevVitaly** [hzeller/rpi-rgb-led-matrix#934]
Hello,
I have a problem with output on 64x32 P5 8S RGB panel:

Configuration:
![Screenshot_10](https://user-images.githubusercontent.com/47393025/70386894-1887b080-19a7-11ea-9fdf-4f7b91776625.png)
Output:
![Screenshot_9](https://user-images.githubusercontent.com/47393025/70387191-90a3a580-19aa-11ea-8f5d-d67949058b12.png)

Then I tried demo, and what I've got:
1 Configuration:
./demo -D3  --led-rows=32 --led-cols=16 --led-chain=4 --led-brightness=20 --led-multiplexin g=5 --led-slowdown-gpio=2
![Screenshot_11](https://user-images.githubusercontent.com/47393025/70387158-2db20e80-19aa-11ea-8b60-f07fec8d2109.png)

2 Configuration
sudo ./demo -D3
--led-rows=32 --led-cols=16 --led-chain=4 --led-brightness=20 --led-multiplexing= 3 --led-slowdown-gpio=2
![Screenshot_12](https://user-images.githubusercontent.com/47393025/70387169-5b975300-19aa-11ea-8521-eec53ea6ae37.png)

The output always get shifted. Don't know what is wrong with settings.
Please, can you help me?

I use this board: https://www.electrodragon.com/product/rgb-matrix-panel-drive-board-raspberry-pi/
Panels, that are used:
![photo_2019-12-07_17-52-42](https://user-images.githubusercontent.com/47393025/70386726-d2315200-19a4-11ea-84a0-4184a5e608e3.jpg)
![photo_2019-12-07_18-20-18](https://user-images.githubusercontent.com/47393025/70386737-dc535080-19a4-11ea-9fed-b170d9a517fe.jpg)

**Comment by KorneevVitaly** [comment]
With this configuration is more close, but there ara a lot of errors with it:
 sudo ./demo -D3
--led-rows=32 --led-cols=16 --led-chain=4 --led-brightness=20 --led-multiplexing= 10 --led-slowdown-gpio=2
![Screenshot_13](https://user-images.githubusercontent.com/47393025/70387281-02c8ba00-19ac-11ea-9019-c2647c2438b5.png)
![Screenshot_14](https://user-images.githubusercontent.com/47393025/70387289-25f36980-19ac-11ea-9cd7-6a3c53f38195.png)

**Comment by Dtsoft** [comment]
I am also very interested in solving a similar problem. Thanks.

**Comment by KorneevVitaly** [comment]
Tried to write own mapper, but still stuck on wrong output, like it has it's own mapping, that don't match any mapper from this library:
sudo ./demo -D3 -- led-rows=32 --led-cols=64 --led-chain=1 --led-brightness=20 --led-slowdown-gpio=2 --led-multiplexing=9
![Screenshot_15](https://user-images.githubusercontent.com/47393025/70395980-10faf280-1a0d-11ea-8795-09458719c834.png)
Here how mapper now look:
```
 class P10MapperZ : public MultiplexMapperBase {
 public:
   P10MapperZ() : MultiplexMapperBase("P10-128x4-Z", 1) {}
   void MapSinglePanel(int x, int y, int *matrix_x, int *matrix_y) const {
    int A_x[64] = {0,1,2,3,8,9,10,11,16,17,18,19,24,25,26,27,32,33,34,35,40,41,4
    2,43,48,49,50,51,56,57,58,59,64,65,66,67,72,73,74,75,80,81,82,83,88,89,90,91,96,
    97,98,99,104,105,106,107,112,113,114,115,120,121,122,123};
   int B_x[64] = {4,5,6,7,12,13,14,15,20,21,22,23,28,29,30,31,36,37,38,39,44,45
    ,46,47,52,53,54,55,60,61,62,63,68,69,70,71,76,77,78,79,84,85,86,87,92,93,94,95,1
    00,101,102,103,108,109,110,111,116,117,118,119,124,125,126,127};

     if (y < 8) {
         *matrix_x = B_x[x];
         *matrix_y = y;
     }
    if ((y>=8) && (y<=15)) {
         *matrix_x = A_x[x];
         *matrix_y = y - 8;
     }
     if ((y>15) && (y<23)) {
         *matrix_y = y + 8;
         *matrix_x = B_x[x];
     }
     if (y>=23) {
         *matrix_y = y;
         *matrix_x = A_x[x];
     }
}
};
```

**Comment by KorneevVitaly** [comment]
So, I've edited existing P10MapperZ to look like this:
```
class P10MapperZ : public MultiplexMapperBase {
public:
  P10MapperZ() : MultiplexMapperBase("P10-128x4-Z", 1) {}
  void MapSinglePanel(int x, int y, int *matrix_x, int *matrix_y) const {
   
    if (y < 8) {
        *matrix_x = x + (4+(4*int(x/4)));
        *matrix_y = y;
    }
    if ((y>=8) && (y<=15)) {
        *matrix_x = x + (4+(4*int(x/4))) - 4;
        *matrix_y = y - 8;
    }
    if ((y>15) && (y<23)) {
        *matrix_y = y + 8;
        *matrix_x = x + (4+(4*int(x/4)));
    }
    if (y>=23) {
        *matrix_y = y;
        *matrix_x = x + (4+(4*int(x/4))) - 4;
    }
   
    panel_cols_ = 256;
    panel_rows_ = 16;    
  }
};
```
I used this options:
![снимок_1](https://user-images.githubusercontent.com/47393025/70432505-1c3f3400-1a88-11ea-9afd-cb8f503ec2cc.png)

And the output now look normal:
![снимок](https://user-images.githubusercontent.com/47393025/70432533-2a8d5000-1a88-11ea-97e6-83c74e4f5a86.png)

Hope this would be helpfull.

**Comment by KorneevVitaly** [comment]
But there is a noise problem. What can be done with it?

**Comment by KorneevVitaly** [comment]
But there is a noise problem. What can be done with it?

**Comment by KorneevVitaly** [comment]
Well, the problem with adressing is still present on longer chains:
![photo_2019-12-18_11-58-09](https://user-images.githubusercontent.com/47393025/71076123-db34d700-218d-11ea-97e7-0a60f0f633fe.jpg)

**Comment by KorneevVitaly** [comment]
So, after some tries and errors, I've come up with this solution for those matrix multiplexor (for now, only for 2 parallel):
```
class WavyCrp : public MultiplexMapperBase {
 public:
  WavyCrp() : MultiplexMapperBase("WawyCrp", 2) {}

  void MapSinglePanel(int x, int y, int *matrix_x, int *matrix_y) const {

    if (y < 8) {
      *matrix_x = x + (4+(4*int(x/4)));
      *matrix_y = y;
    }
    if ((y>=8) && (y<=15)) {
      *matrix_x = x + (4+(4*int(x/4))) - 4;
      *matrix_y = y - 8;
    }
    if ((y>15) && (y<=23)) {
      *matrix_x = x + (4+(4*int(x/4)));
      *matrix_y = y - 8;
    }
    if (y>23) {
      *matrix_x = x + (4+(4*int(x/4))) - 4;
      *matrix_y = y - 8*2;
    }
  }  
};
```
