### ISSUE TITLE
64x64 P3 1:16 scanrate --led-chain is not working in FM6126

### ISSUE THREAD

**Issue by gauravoffice96** [hzeller/rpi-rgb-led-matrix#935]

**Comment by hzeller** [comment]
Did you get it to work ?

**Comment by gauravoffice96** [comment]
No it doesn't work,When ever I am passing --led-chain=2 that second panel is not work

![IMG_20191211_112002](https://user-images.githubusercontent.com/56100276/70881724-83faff00-1ff3-11ea-88dc-f81865c50e33.jpg)

**Comment by gauravoffice96** [comment]
i am doing without hat or bonnet.

**Comment by davemaster** [comment]
power on second panel?

**Comment by gauravoffice96** [comment]
Power is given to second panel even though is not working but
if i increase the --led-cols=128 it is working

![128X64](https://user-images.githubusercontent.com/56100276/70966300-cc302500-20b8-11ea-9ea5-a8aa0d241f88.jpg)

my aim is to make 192x64 panel if i increase the --led-cols=192 this is happening... no multiplexing is supporting
thnx in advance 

![192X64](https://user-images.githubusercontent.com/56100276/70966363-000b4a80-20b9-11ea-9a9a-48cf28567c0a.jpg)
