### ISSUE TITLE
Backward text

### ISSUE THREAD

**Issue by FelipeSarche** [hzeller/rpi-rgb-led-matrix#939]
Awesome job, I configured the pins to fit my pcb, it works great but the text is backaward, I see this issue in clock and scrolling text 

./scrolling-text-example --led-rows=16 --led-cols=32 -f ../fonts/helvR12.bdf "FELIPE"

![felipeback](https://user-images.githubusercontent.com/58898620/70858453-4e112a00-1ed0-11ea-84cc-40c9f6b05731.jpg)

**Comment by FelipeSarche** [comment]
I made the pcb with the driver mbi5026

**Comment by hzeller** [comment]
Looks like you have an unusual Matrix that has the pixels reversed.

I've just added a 'Mirror' pixel mapper that should fix your situation, see
https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#mirror

Do a ``git pull`, recompile everything, and then you should be able to set the option `--led-pixel-mapper=Mirror:H` to flip your screen horizontally.

**Comment by hzeller** [comment]
did you get it to work ?

**Comment by FelipeSarche** [comment]
I work great job!!!!!!!!!!!!!!!!!!!

**Comment by hzeller** [comment]
Cool!
