### ISSUE TITLE
led-image-viewer not working on pi3 buster w/adafruit RGB matrix bonnet

### ISSUE THREAD

**Issue by jvc203** [hzeller/rpi-rgb-led-matrix#949]
Hello,

As described in title I can't get the led-image-viewer to run an animated gif on a standard 32x32 matrix. It's a Pi3 Buster w/Adafruit RGB Matrix Bonnet.

Everything seems installed and wired correctly because I can get a demo running.
![IMG_20191220_173207](https://user-images.githubusercontent.com/59266255/71491709-399e2d00-2800-11ea-8f16-b2780a952a4d.jpg)

But when I run the led-image-viewer nothing shows.  From the command line it looks like it's reading the gif correctly?
![IMG_20191220_173345](https://user-images.githubusercontent.com/59266255/71491719-56d2fb80-2800-11ea-9dec-c9b9731451b8.jpg)

Any help is greatly appreciated.  Thanks!

**Comment by hzeller** [comment]
The terminal shows what's up: you are using the regular hardware mapping. But since you use a non-standard hardware, in this case the adafruit hat, you need to give `--led-gpio-mapping=adafruit-hat` mapping. Not sure why it worked in your demo, it looks like you compiled it in there ?

**Comment by jvc203** [comment]
It works!   Yeah, not sure why the demo was working.  I didn't compile the gpio-mapping line in there..  Anyways, thanks for the help and the quick response!  Great library.

**Comment by jabulonboaz** [comment]
> 
> 
> The terminal shows what's up: you are using the regular hardware mapping. But since you use a non-standard hardware, in this case the adafruit hat, you need to give `--led-gpio-mapping=adafruit-hat` mapping. Not sure why it worked in your demo, it looks like you compiled it in there ?

you just saved my life HZeller i had the same issue just had to use hat-pwm so its stable. this issue has nothing to do with buster just the Adafruit bonet or hat. I use the bonet. thanks again
