### ISSUE TITLE
128x64 black bar through image

### ISSUE THREAD

**Issue by Jacksteel777** [hzeller/rpi-rgb-led-matrix#961]
`sudo ./led-image-viewer --led-no-hardware-pulse --led-rows=64 --led-cols=128 --led-multiplexing=1 --led-row-addr-type=0 Ponny2.gif`
![IMG_2484](https://user-images.githubusercontent.com/40410997/72312773-250ec100-3657-11ea-879c-563f24ad5e04.jpeg)
![IMG_2486](https://user-images.githubusercontent.com/40410997/72312782-2e982900-3657-11ea-971a-bf9cdfa99aed.jpeg)
![IMG_2485](https://user-images.githubusercontent.com/40410997/72312789-3526a080-3657-11ea-840b-4f6145cb7055.jpeg)
Configuration works great with P5, but with a P2.5 best image I can get is one with a black bar through the middle. Any help with how to edit is greatly appreciated...I am still very new to this.

**Comment by hzeller** [comment]
That is the symptom of a panel with E-line but only controlled with ABCD. Check out the instructions in the readme.

**Comment by Jacksteel777** [comment]
I see, thank you, it was fixed by joining the E line to to the 8 on the back of the bonnet.

**Comment by hzeller** [comment]
Cool! Have fun with your panel!
